/**
 * NPM Compatibility Test Runner for Otter
 * Runs all package compatibility tests and generates a report
 */

import { spawn } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';

interface TestResult {
  package: string;
  passed: number;
  failed: number;
  total: number;
  errors: string[];
  duration: number;
}

const testFiles = [
  'lodash.test.ts',
  'date-fns.test.ts',
  'zod.test.ts',
  'uuid.test.ts',
];

async function runTest(file: string): Promise<TestResult> {
  const packageName = file.replace('.test.ts', '');
  const startTime = Date.now();

  return new Promise((resolve) => {
    const proc = spawn('otter', ['run', file, '--allow-read'], {
      cwd: import.meta.dirname,
      stdio: ['pipe', 'pipe', 'pipe'],
    });

    let stdout = '';
    let stderr = '';

    proc.stdout.on('data', (data) => {
      stdout += data.toString();
      process.stdout.write(data);
    });

    proc.stderr.on('data', (data) => {
      stderr += data.toString();
      process.stderr.write(data);
    });

    proc.on('close', (code) => {
      const duration = Date.now() - startTime;

      // Parse results from output
      const passedMatch = stdout.match(/Passed:\s*(\d+)\/(\d+)/);
      const failedMatch = stdout.match(/Failed:\s*(\d+)\/(\d+)/);

      const passed = passedMatch ? parseInt(passedMatch[1], 10) : 0;
      const total = passedMatch ? parseInt(passedMatch[2], 10) : 0;
      const failed = failedMatch ? parseInt(failedMatch[1], 10) : 0;

      // Extract error messages
      const errors: string[] = [];
      const errorLines = stdout.split('\n').filter(
        (line) => line.startsWith('ERROR:') || line.startsWith('FAIL:')
      );
      errors.push(...errorLines);

      if (stderr.trim()) {
        errors.push(`stderr: ${stderr.trim()}`);
      }

      resolve({
        package: packageName,
        passed,
        failed,
        total,
        errors,
        duration,
      });
    });

    proc.on('error', (err) => {
      resolve({
        package: packageName,
        passed: 0,
        failed: 1,
        total: 1,
        errors: [`Failed to run: ${err.message}`],
        duration: Date.now() - startTime,
      });
    });
  });
}

function generateReport(results: TestResult[]): string {
  const lines: string[] = [];

  lines.push('# Otter NPM Compatibility Report');
  lines.push('');
  lines.push(`Generated: ${new Date().toISOString()}`);
  lines.push('');

  // Summary table
  lines.push('## Summary');
  lines.push('');
  lines.push('| Package | Passed | Failed | Total | Coverage | Duration |');
  lines.push('|---------|--------|--------|-------|----------|----------|');

  let totalPassed = 0;
  let totalFailed = 0;
  let totalTests = 0;

  for (const r of results) {
    const coverage = r.total > 0 ? ((r.passed / r.total) * 100).toFixed(1) : '0.0';
    const status = r.failed === 0 ? '✅' : '⚠️';
    lines.push(
      `| ${status} ${r.package} | ${r.passed} | ${r.failed} | ${r.total} | ${coverage}% | ${r.duration}ms |`
    );
    totalPassed += r.passed;
    totalFailed += r.failed;
    totalTests += r.total;
  }

  const totalCoverage = totalTests > 0 ? ((totalPassed / totalTests) * 100).toFixed(1) : '0.0';
  lines.push(
    `| **Total** | **${totalPassed}** | **${totalFailed}** | **${totalTests}** | **${totalCoverage}%** | - |`
  );
  lines.push('');

  // Detailed errors
  const packagesWithErrors = results.filter((r) => r.errors.length > 0);
  if (packagesWithErrors.length > 0) {
    lines.push('## Errors');
    lines.push('');

    for (const r of packagesWithErrors) {
      if (r.errors.length > 0) {
        lines.push(`### ${r.package}`);
        lines.push('');
        for (const err of r.errors) {
          lines.push(`- ${err}`);
        }
        lines.push('');
      }
    }
  }

  // Recommendations
  lines.push('## Recommendations');
  lines.push('');

  if (totalFailed === 0) {
    lines.push('All tests passed! No immediate action required.');
  } else {
    lines.push('The following gaps were identified:');
    lines.push('');

    for (const r of results) {
      if (r.failed > 0) {
        lines.push(`- **${r.package}**: ${r.failed} failing tests need investigation`);
      }
    }
  }

  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('*Report generated by Otter NPM Compatibility Test Suite*');

  return lines.join('\n');
}

async function main() {
  console.log('='.repeat(60));
  console.log('Otter NPM Compatibility Test Suite');
  console.log('='.repeat(60));
  console.log('');

  const results: TestResult[] = [];

  for (const file of testFiles) {
    console.log(`\n${'='.repeat(60)}`);
    console.log(`Running: ${file}`);
    console.log('='.repeat(60));
    console.log('');

    const result = await runTest(file);
    results.push(result);
  }

  console.log('\n' + '='.repeat(60));
  console.log('FINAL SUMMARY');
  console.log('='.repeat(60));
  console.log('');

  // Print summary
  for (const r of results) {
    const status = r.failed === 0 ? '✅' : '❌';
    console.log(`${status} ${r.package}: ${r.passed}/${r.total} passed (${r.duration}ms)`);
  }

  // Generate and save report
  const report = generateReport(results);
  const reportPath = path.join(import.meta.dirname, 'compat-report.md');
  fs.writeFileSync(reportPath, report);
  console.log(`\nReport saved to: ${reportPath}`);

  // Exit with error if any tests failed
  const totalFailed = results.reduce((sum, r) => sum + r.failed, 0);
  if (totalFailed > 0) {
    console.log(`\n❌ ${totalFailed} tests failed`);
    process.exit(1);
  } else {
    console.log('\n✅ All tests passed!');
  }
}

main().catch((err) => {
  console.error('Fatal error:', err);
  process.exit(1);
});
