//! ECMA-262 §25.4 `Atomics` namespace.
//!
//! Ships every spec method on the integer-typed subset of
//! TypedArrays. Wait / notify variants use the shared wait registry
//! so Test262 agents and runtime workers can block, wake, timeout,
//! and be cancelled by host watchdog interrupts.
//!
//! # Contents
//! - `ATOMICS_SPEC` / `ATOMICS_METHODS` — namespace registration.
//! - `validate_integer_typed_array` — §25.4.3.1
//!   ValidateIntegerTypedArray / ValidateSharedIntegerTypedArray.
//! - `validate_atomic_access` — §25.4.3.2 ValidateAtomicAccess.
//! - `validate_atomic_access_on_int_or_bigint_typed_array` —
//!   §25.4.3.3 ValidateAtomicAccessOnIntegerTypedArray (waitable
//!   subset).
//! - per-method native handlers using [`NativeCtx`] for spec-faithful
//!   coercion of `index` and `value` arguments.
//! - legacy `call()` opcode entry kept for the AtomicsCall fast
//!   path that older bytecode files may still carry.
//!
//! # Invariants
//! - `Uint8ClampedArray`, `Float32Array`, `Float64Array` are never
//!   accepted as a `typedArray` argument to any atomic op.
//! - Detached TypedArray buffers are rejected before `index` or
//!   value coercion.
//! - `wait` / `waitAsync` require a `SharedArrayBuffer`-backed view
//!   of `Int32Array` or `BigInt64Array`.
//! - Out-of-range indices surface as `RangeError`, **not**
//!   `TypeError`.
//! - View kind is validated before any other argument is coerced
//!   (validate-arraytype-before-value-coercion).
//! - `waitAsync` result labels, promises, and result objects remain in one
//!   handle scope until both `async` and `value` have been published.
//!
//! # See also
//! - <https://tc39.es/ecma262/#sec-atomics-object>
//! - <https://tc39.es/ecma262/#sec-validateintegertypedarray>
//! - <https://tc39.es/ecma262/#sec-validateatomicaccess>

use crate::abstract_ops::{self, ToPrimitiveHint};
use crate::atomics_wait::{self, WaitOutcome};
use crate::bigint::BigIntValue;
use crate::binary::{JsTypedArray, TypedArrayKind};
use crate::number::NumberValue;
use crate::number::parse::to_integer_or_infinity;
use crate::string::JsString;
use crate::{NativeCtx, NativeError, Value, VmError};
use std::sync::{LazyLock, Mutex};
use std::time::{Duration, Instant};

static ATOMICS_RMW_LOCK: LazyLock<Mutex<()>> = LazyLock::new(|| Mutex::new(()));
const WAIT_ASYNC_INLINE_TIMEOUT_LIMIT_MS: u64 = 500;
const WAIT_ASYNC_TIMEOUT_POLL_INTERVAL: Duration = Duration::from_millis(10);

// `ATOMICS_SPEC` + `Intrinsic` generated by `holt!`. §25.4 — links
// to `%Object.prototype%` (`link_object_prototype = true`).
otter_macros::holt! {
    name = "Atomics",
    feature = CORE,
    link_object_prototype = true,
    methods = {
        "add"             / 3 => native_add,
        "and"             / 3 => native_and,
        "compareExchange" / 4 => native_compare_exchange,
        "exchange"        / 3 => native_exchange,
        "isLockFree"      / 1 => native_is_lock_free,
        "load"            / 2 => native_load,
        "notify"          / 3 => native_notify,
        "or"              / 3 => native_or,
        "pause"           / 0 => native_pause,
        "store"           / 3 => native_store,
        "sub"             / 3 => native_sub,
        "wait"            / 4 => native_wait,
        "waitAsync"       / 4 => native_wait_async,
        "xor"             / 3 => native_xor,
    },
}

/// Whether `Atomics.add` / `sub` / `and` / `or` / `xor` / `exchange`
/// / `compareExchange` accept this kind. §25.4.3.1 step 2-3.
fn accepts_atomic_kind(kind: TypedArrayKind) -> bool {
    !matches!(
        kind,
        TypedArrayKind::Float16
            | TypedArrayKind::Float32
            | TypedArrayKind::Float64
            | TypedArrayKind::Uint8Clamped
    )
}

/// §25.4.3.1 ValidateIntegerTypedArray ( typedArray, waitable ).
/// `waitable=true` restricts the kind to Int32Array / BigInt64Array.
fn validate_integer_typed_array(
    value: &Value,
    heap: &otter_gc::GcHeap,
    waitable: bool,
    shared_required: bool,
    method_name: &'static str,
) -> Result<JsTypedArray, NativeError> {
    let ta = value
        .as_typed_array(heap)
        .ok_or_else(|| type_err(method_name, "argument is not a TypedArray".to_string()))?;
    let kind = ta.kind();
    if !accepts_atomic_kind(kind) {
        return Err(type_err(
            method_name,
            format!("{} is not an integer-element TypedArray", kind.name()),
        ));
    }
    if waitable && !matches!(kind, TypedArrayKind::Int32 | TypedArrayKind::BigInt64) {
        return Err(type_err(
            method_name,
            format!(
                "{} is not a waitable TypedArray (Int32Array or BigInt64Array)",
                kind.name()
            ),
        ));
    }
    if ta.buffer(heap).is_detached(heap) {
        return Err(type_err(
            method_name,
            "TypedArray buffer is detached".to_string(),
        ));
    }
    if shared_required && !ta.buffer(heap).is_shared() {
        return Err(type_err(
            method_name,
            "expected a SharedArrayBuffer-backed TypedArray".to_string(),
        ));
    }
    Ok(ta)
}

/// §25.4.3.4 ValidateAtomicAccess ( typedArray, requestIndex ).
/// Captures `typedArray.length`, coerces `request_index` through
/// ToIndex, then bounds-checks against the captured length.
/// Out-of-range → `RangeError`.
fn validate_atomic_access(
    ctx: &mut NativeCtx<'_>,
    ta: &JsTypedArray,
    request_index: &Value,
    method_name: &'static str,
) -> Result<usize, NativeError> {
    let len = ta.length(ctx.heap());
    let idx = coerce_to_index(ctx, request_index, method_name)?;
    if idx >= len {
        return Err(range_err(
            method_name,
            format!(
                "index {idx} is out of range for {} of length {}",
                ta.kind().name(),
                len
            ),
        ));
    }
    Ok(idx)
}

/// §7.1.22 ToIndex with full coercion (Object → primitive →
/// integer). Returns `RangeError` for negative / non-integer /
/// non-finite values, `TypeError` for `Symbol` or `BigInt` input
/// (since `ToNumber` on those throws).
fn coerce_to_index(
    ctx: &mut NativeCtx<'_>,
    value: &Value,
    method_name: &'static str,
) -> Result<usize, NativeError> {
    let primitive = to_primitive_number(ctx, value, method_name)?;
    if primitive.is_symbol() {
        return Err(type_err(
            method_name,
            "cannot convert Symbol to a number".to_string(),
        ));
    }
    if primitive.is_big_int() {
        return Err(type_err(
            method_name,
            "cannot convert BigInt to a number".to_string(),
        ));
    }
    let n = to_integer_or_infinity(&primitive, ctx.heap());
    if !n.is_finite() {
        return Err(range_err(method_name, "index is not finite".to_string()));
    }
    if n < 0.0 {
        return Err(range_err(method_name, "index is negative".to_string()));
    }
    if n > 9_007_199_254_740_991.0 {
        return Err(range_err(method_name, "index exceeds 2^53 - 1".to_string()));
    }
    Ok(n as usize)
}

/// §7.1.1 ToPrimitive(value, "number"). Plain primitive values
/// pass through unchanged; Objects route through
/// `Interpreter::evaluate_to_primitive` so `Symbol.toPrimitive` /
/// `valueOf` / `toString` are observable. User-thrown exceptions
/// during coercion propagate as `NativeError::Thrown` so the
/// runtime mapper hands the original payload back to JS (this is
/// required by tests like
/// `Atomics/notify/symbol-for-index-throws.js` that assert on a
/// `Test262Error` thrown from a poisoned `valueOf`).
fn to_primitive_number(
    ctx: &mut NativeCtx<'_>,
    value: &Value,
    method_name: &'static str,
) -> Result<Value, NativeError> {
    if abstract_ops::is_primitive(value) {
        return Ok(*value);
    }
    let exec = ctx.execution_context().cloned().ok_or_else(|| {
        type_err(
            method_name,
            "missing execution context for ToPrimitive".to_string(),
        )
    })?;
    ctx.with_turn_parts(|interp, stack| {
        interp
            .evaluate_to_primitive(stack, &exec, value, ToPrimitiveHint::Number)
            .map_err(|e| vm_error_to_native(interp, method_name, e))
    })
}

/// Convert a [`VmError`] surfaced from re-entering the interpreter
/// into the matching [`NativeError`]. Crucially, `VmError::Uncaught`
/// maps to `NativeError::Thrown` so the original user-thrown value
/// rides through (the runtime mapper at `lib.rs:15616` reconstructs
/// the JS exception from the `message` field).
fn vm_error_to_native(
    interp: &crate::Interpreter,
    method_name: &'static str,
    err: VmError,
) -> NativeError {
    match err {
        VmError::Uncaught => {
            let value = match interp.take_error_detail() {
                Some(crate::run_control::ErrorDetail::Uncaught(m)) => m,
                _ => Default::default(),
            };
            NativeError::Thrown {
                name: spec_name(method_name),
                message: value.into(),
            }
        }
        other => type_err(method_name, other.to_string()),
    }
}

/// Coerce the third / fourth argument of a read-modify-write op to
/// the element representation. Numeric kinds use `ToIntegerOrInfinity`;
/// BigInt kinds use `ToBigInt`.
fn coerce_element_value(
    ctx: &mut NativeCtx<'_>,
    kind: TypedArrayKind,
    value: &Value,
    method_name: &'static str,
) -> Result<Value, NativeError> {
    let primitive = to_primitive_number(ctx, value, method_name)?;
    if kind.is_bigint() {
        let oom_to_err = |err: otter_gc::OutOfMemory| {
            type_err(
                method_name,
                format!(
                    "out of memory: requested {} bytes, heap limit {}",
                    err.requested_bytes(),
                    err.heap_limit_bytes(),
                ),
            )
        };
        let s_opt = primitive.as_string(ctx.heap());
        let heap = ctx.interp_mut().gc_heap_mut();
        if let Some(b) = primitive.as_big_int() {
            Ok(Value::big_int(b))
        } else if let Some(b) = primitive.as_boolean() {
            let handle = BigIntValue::from_inner(heap, num_bigint::BigInt::from(i64::from(b)))
                .map_err(oom_to_err)?;
            Ok(Value::big_int(handle))
        } else if let Some(s) = s_opt {
            let txt = s.to_lossy_string(heap);
            let trimmed = txt.trim();
            let parsed = trimmed.parse::<num_bigint::BigInt>().map_err(|_| {
                type_err(method_name, format!("cannot convert {trimmed:?} to BigInt"))
            })?;
            let handle = BigIntValue::from_inner(heap, parsed).map_err(oom_to_err)?;
            Ok(Value::big_int(handle))
        } else if primitive.is_number() {
            Err(type_err(
                method_name,
                "cannot mix BigInt and Number".to_string(),
            ))
        } else {
            Err(type_err(
                method_name,
                "cannot convert value to BigInt".to_string(),
            ))
        }
    } else if primitive.is_big_int() {
        Err(type_err(
            method_name,
            "cannot mix BigInt and Number".to_string(),
        ))
    } else if primitive.is_symbol() {
        Err(type_err(
            method_name,
            "cannot convert Symbol to a number".to_string(),
        ))
    } else {
        let mut n = to_integer_or_infinity(&primitive, ctx.heap());
        // §7.1.5 step 2 — collapse `+0` / `-0` / `NaN` to `0`.
        if n == 0.0 {
            n = 0.0;
        }
        Ok(Value::number(NumberValue::from_f64(n)))
    }
}

fn type_err(name: &'static str, reason: String) -> NativeError {
    NativeError::TypeError {
        name: spec_name(name),
        reason,
    }
}

fn range_err(name: &'static str, reason: String) -> NativeError {
    NativeError::RangeError {
        name: spec_name(name),
        reason,
    }
}

/// Map "add" → "Atomics.add" etc. for diagnostic strings.
const fn spec_name(method: &'static str) -> &'static str {
    // Static strings; the runtime mapper only reads `.name` for
    // diagnostics so a plain method name is acceptable.
    method
}

// =====================================================================
// Native method handlers — primary entry points after the property
// lookup path resolves `Atomics.<method>` to a native function.
// =====================================================================

fn native_load(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    let ta = validate_integer_typed_array(
        args.first().unwrap_or(&Value::UNDEFINED),
        ctx.heap(),
        false,
        false,
        "Atomics.load",
    )?;
    let idx = validate_atomic_access(
        ctx,
        &ta,
        args.get(1).unwrap_or(&Value::UNDEFINED),
        "Atomics.load",
    )?;
    let heap = ctx.interp_mut().gc_heap_mut();
    ta.get(heap, idx).map_err(|e| {
        type_err(
            "Atomics.load",
            format!(
                "out of memory: {} requested, limit {}",
                e.requested_bytes(),
                e.heap_limit_bytes()
            ),
        )
    })
}

fn native_store(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    let ta = validate_integer_typed_array(
        args.first().unwrap_or(&Value::UNDEFINED),
        ctx.heap(),
        false,
        false,
        "Atomics.store",
    )?;
    let idx = validate_atomic_access(
        ctx,
        &ta,
        args.get(1).unwrap_or(&Value::UNDEFINED),
        "Atomics.store",
    )?;
    let value = coerce_element_value(
        ctx,
        ta.kind(),
        args.get(2).unwrap_or(&Value::UNDEFINED),
        "Atomics.store",
    )?;
    ta.set(ctx.interp_mut().gc_heap_mut(), idx, &value);
    Ok(value)
}

fn modify_op(
    ctx: &mut NativeCtx<'_>,
    args: &[Value],
    method_name: &'static str,
    op: fn(i64, i64) -> i64,
    op_big: fn(&num_bigint::BigInt, &num_bigint::BigInt) -> num_bigint::BigInt,
) -> Result<Value, NativeError> {
    let ta = validate_integer_typed_array(
        args.first().unwrap_or(&Value::UNDEFINED),
        ctx.heap(),
        false,
        false,
        method_name,
    )?;
    let idx = validate_atomic_access(
        ctx,
        &ta,
        args.get(1).unwrap_or(&Value::UNDEFINED),
        method_name,
    )?;
    let coerced = coerce_element_value(
        ctx,
        ta.kind(),
        args.get(2).unwrap_or(&Value::UNDEFINED),
        method_name,
    )?;
    let heap = ctx.interp_mut().gc_heap_mut();
    let oom_to_err = |err: otter_gc::OutOfMemory| {
        type_err(
            method_name,
            format!(
                "out of memory: requested {} bytes, heap limit {}",
                err.requested_bytes(),
                err.heap_limit_bytes(),
            ),
        )
    };
    let _atomic_guard = ATOMICS_RMW_LOCK
        .lock()
        .expect("Atomics read-modify-write mutex poisoned");
    let prev = ta.get(heap, idx).map_err(oom_to_err)?;
    if ta.kind().is_bigint() {
        let prev_b = prev
            .as_big_int()
            .map(|b| b.clone_inner(heap))
            .unwrap_or_else(|| num_bigint::BigInt::from(0));
        let v_b = coerced
            .as_big_int()
            .map(|b| b.clone_inner(heap))
            .unwrap_or_else(|| num_bigint::BigInt::from(0));
        let new_b = op_big(&prev_b, &v_b);
        let handle = BigIntValue::from_inner(heap, new_b).map_err(oom_to_err)?;
        ta.set(heap, idx, &Value::big_int(handle));
    } else {
        let prev_n = prev.as_number().map(|n| n.as_f64() as i64).unwrap_or(0);
        let v_n = coerced.as_number().map(|n| n.as_f64() as i64).unwrap_or(0);
        let new_n = op(prev_n, v_n);
        ta.set(
            heap,
            idx,
            &Value::number(NumberValue::from_f64(new_n as f64)),
        );
    }
    Ok(prev)
}

fn native_add(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    modify_op(
        ctx,
        args,
        "Atomics.add",
        |a, b| a.wrapping_add(b),
        |a, b| a + b,
    )
}

fn native_sub(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    modify_op(
        ctx,
        args,
        "Atomics.sub",
        |a, b| a.wrapping_sub(b),
        |a, b| a - b,
    )
}

fn native_and(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    modify_op(ctx, args, "Atomics.and", |a, b| a & b, |a, b| a & b)
}

fn native_or(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    modify_op(ctx, args, "Atomics.or", |a, b| a | b, |a, b| a | b)
}

fn native_xor(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    modify_op(ctx, args, "Atomics.xor", |a, b| a ^ b, |a, b| a ^ b)
}

fn native_exchange(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    let ta = validate_integer_typed_array(
        args.first().unwrap_or(&Value::UNDEFINED),
        ctx.heap(),
        false,
        false,
        "Atomics.exchange",
    )?;
    let idx = validate_atomic_access(
        ctx,
        &ta,
        args.get(1).unwrap_or(&Value::UNDEFINED),
        "Atomics.exchange",
    )?;
    let value = coerce_element_value(
        ctx,
        ta.kind(),
        args.get(2).unwrap_or(&Value::UNDEFINED),
        "Atomics.exchange",
    )?;
    let heap = ctx.interp_mut().gc_heap_mut();
    let _atomic_guard = ATOMICS_RMW_LOCK
        .lock()
        .expect("Atomics read-modify-write mutex poisoned");
    let prev = ta.get(heap, idx).map_err(|e| {
        type_err(
            "Atomics.exchange",
            format!(
                "out of memory: requested {} bytes, heap limit {}",
                e.requested_bytes(),
                e.heap_limit_bytes(),
            ),
        )
    })?;
    ta.set(heap, idx, &value);
    Ok(prev)
}

fn native_compare_exchange(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    let ta = validate_integer_typed_array(
        args.first().unwrap_or(&Value::UNDEFINED),
        ctx.heap(),
        false,
        false,
        "Atomics.compareExchange",
    )?;
    let idx = validate_atomic_access(
        ctx,
        &ta,
        args.get(1).unwrap_or(&Value::UNDEFINED),
        "Atomics.compareExchange",
    )?;
    let expected = coerce_element_value(
        ctx,
        ta.kind(),
        args.get(2).unwrap_or(&Value::UNDEFINED),
        "Atomics.compareExchange",
    )?;
    let replacement = coerce_element_value(
        ctx,
        ta.kind(),
        args.get(3).unwrap_or(&Value::UNDEFINED),
        "Atomics.compareExchange",
    )?;
    // §25.4.3.5 step 8 — expected must be narrowed through the
    // element-type's RawBytes round-trip before the comparison
    // against the raw current value (e.g. an Int16 view stores
    // `123456789` as `-13035`, so expected `123456789` must compare
    // against `-13035`, not the original Number).
    let heap = ctx.interp_mut().gc_heap_mut();
    let oom_to_err = |err: otter_gc::OutOfMemory| {
        type_err(
            "Atomics.compareExchange",
            format!(
                "out of memory: requested {} bytes, heap limit {}",
                err.requested_bytes(),
                err.heap_limit_bytes(),
            ),
        )
    };
    let _atomic_guard = ATOMICS_RMW_LOCK
        .lock()
        .expect("Atomics read-modify-write mutex poisoned");
    let expected_narrow = narrow_through_kind(heap, ta.kind(), &expected).map_err(oom_to_err)?;
    let current = ta.get(heap, idx).map_err(oom_to_err)?;
    if values_equal_strict(&current, &expected_narrow, heap) {
        ta.set(heap, idx, &replacement);
    }
    Ok(current)
}

/// Round-trip `value` through the element type so the result matches
/// what the buffer would read back after a store. Used by
/// `compareExchange` to spec-equate `expected` with `current` per
/// §25.4.3.5.
fn narrow_through_kind(
    heap: &mut otter_gc::GcHeap,
    kind: TypedArrayKind,
    value: &Value,
) -> Result<Value, otter_gc::OutOfMemory> {
    let mut scratch = [0u8; 8];
    kind.write(heap, &mut scratch, 0, value);
    kind.read(heap, &scratch, 0)
}

fn native_is_lock_free(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    // Spec §25.4.13 — argument is coerced via ToIntegerOrInfinity
    // (no ToIndex), so negative / non-integer / NaN map to `false`
    // by failing the `matches!(.., 1|2|4|8)` filter.
    let arg = args.first().cloned().unwrap_or(Value::undefined());
    let primitive = to_primitive_number(ctx, &arg, "Atomics.isLockFree")?;
    if primitive.is_symbol() {
        return Err(type_err(
            "Atomics.isLockFree",
            "cannot convert Symbol to a number".to_string(),
        ));
    }
    let n = to_integer_or_infinity(&primitive, ctx.heap());
    let supported = n.is_finite() && matches!(n as i64, 1 | 2 | 4 | 8) && (n as i64 as f64) == n;
    Ok(Value::boolean(supported))
}

fn native_pause(_ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    // §25.4.14 Atomics.pause ( iterationNumber )
    // <https://tc39.es/ecma262/#sec-atomics.pause>
    //
    // The argument, if present, must be an integral Number (not a
    // string or object coerced to one). The spec calls this
    // "integral Number" — Number whose ToIntegerOrInfinity equals
    // itself. Anything else throws TypeError. A single-threaded VM
    // can simply yield; we choose the trivial no-op.
    if let Some(v) = args.first()
        && !v.is_undefined()
    {
        let Some(n) = v.as_number() else {
            return Err(type_err(
                "Atomics.pause",
                "iterationNumber must be an integral Number".to_string(),
            ));
        };
        let f = n.as_f64();
        if !f.is_finite() || f.trunc() != f {
            return Err(type_err(
                "Atomics.pause",
                "iterationNumber must be an integral Number".to_string(),
            ));
        }
    }
    Ok(Value::undefined())
}

fn native_wait(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    do_wait(ctx, args, /* is_async */ false)
}

fn native_wait_async(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    do_wait(ctx, args, /* is_async */ true)
}

fn do_wait(ctx: &mut NativeCtx<'_>, args: &[Value], is_async: bool) -> Result<Value, NativeError> {
    let method_name = if is_async {
        "Atomics.waitAsync"
    } else {
        "Atomics.wait"
    };
    let ta = validate_integer_typed_array(
        args.first().unwrap_or(&Value::UNDEFINED),
        ctx.heap(),
        true,
        true,
        method_name,
    )?;
    let buf_id = ta
        .buffer(ctx.heap())
        .shared_id(ctx.heap())
        .expect("is_shared() guards shared_id");
    let idx = validate_atomic_access(
        ctx,
        &ta,
        args.get(1).unwrap_or(&Value::UNDEFINED),
        method_name,
    )?;
    // Coerce expected `value` before timeout for spec-faithful order.
    let expected = coerce_element_value(
        ctx,
        ta.kind(),
        args.get(2).unwrap_or(&Value::UNDEFINED),
        method_name,
    )?;
    // §25.4.3.13 step 11 — timeout is `ToNumber(q)`; NaN → +∞;
    // observable side-effects fire even on a single-threaded VM.
    let timeout = match args.get(3) {
        None => f64::INFINITY,
        Some(v) if v.is_undefined() => f64::INFINITY,
        Some(v) => {
            let primitive = to_primitive_number(ctx, v, method_name)?;
            if primitive.is_symbol() {
                return Err(type_err(
                    method_name,
                    "cannot convert Symbol to a number".to_string(),
                ));
            }
            let n = crate::number::parse::to_number_value(&primitive, ctx.heap());
            if n.is_nan() {
                f64::INFINITY
            } else {
                n.max(0.0)
            }
        }
    };
    if !is_async && !ctx.interp_mut().allow_blocking_atomics_wait() {
        return Err(type_err(
            method_name,
            "Atomics.wait cannot block on this runtime".to_string(),
        ));
    }
    let heap = ctx.interp_mut().gc_heap_mut();
    let current = ta.get(heap, idx).map_err(|e| {
        type_err(
            method_name,
            format!(
                "out of memory: requested {} bytes, heap limit {}",
                e.requested_bytes(),
                e.heap_limit_bytes(),
            ),
        )
    })?;
    if is_async {
        if !values_equal_strict(&current, &expected, heap) {
            return wait_async_result(ctx, method_name, false, "not-equal");
        }
        if timeout == 0.0 {
            return wait_async_result(ctx, method_name, false, "timed-out");
        }
        if timeout.is_finite() {
            let ms = timeout.min(u64::MAX as f64) as u64;
            if ms <= WAIT_ASYNC_INLINE_TIMEOUT_LIMIT_MS {
                wait_async_sleep_for_timeout(ctx, ms)?;
                return wait_async_result(ctx, method_name, true, "timed-out");
            }
        }
        atomics_wait::register_async_waiter(buf_id, idx);
        return wait_async_result(ctx, method_name, true, "ok");
    }

    let label = if !values_equal_strict(&current, &expected, heap) {
        "not-equal"
    } else {
        // §25.4.3.13 — block the calling thread on the shared-buffer
        // wait registry until either a notify or the timeout fires.
        let dur = if timeout.is_infinite() {
            None
        } else {
            // Clamp to u64::MAX milliseconds (~584 million years) to
            // stay inside `Duration::from_millis` range.
            let ms = timeout.min(u64::MAX as f64) as u64;
            Some(Duration::from_millis(ms))
        };
        let interrupt = ctx.interp_mut().interrupt_handle();
        match atomics_wait::park_until_notified(buf_id, idx, dur, Some(&interrupt)) {
            WaitOutcome::Ok => "ok",
            WaitOutcome::TimedOut => "timed-out",
            WaitOutcome::Interrupted | WaitOutcome::Cancelled => {
                return Err(NativeError::Interrupted);
            }
        }
    };
    string_value(ctx, method_name, label)
}

fn wait_async_sleep_for_timeout(ctx: &mut NativeCtx<'_>, ms: u64) -> Result<(), NativeError> {
    let deadline = Instant::now()
        .checked_add(Duration::from_millis(ms))
        .unwrap_or_else(Instant::now);
    let interrupt = ctx.interp_mut().interrupt_handle();
    while Instant::now() < deadline {
        if interrupt.is_set() {
            return Err(NativeError::Interrupted);
        }
        let remaining = deadline
            .checked_duration_since(Instant::now())
            .unwrap_or(Duration::ZERO);
        std::thread::sleep(remaining.min(WAIT_ASYNC_TIMEOUT_POLL_INTERVAL));
    }
    if interrupt.is_set() {
        return Err(NativeError::Interrupted);
    }
    Ok(())
}

fn wait_async_result(
    ctx: &mut NativeCtx<'_>,
    method_name: &'static str,
    is_async: bool,
    label: &str,
) -> Result<Value, NativeError> {
    ctx.scope(|mut scope| {
        let label = scope
            .string(label)
            .map_err(|error| type_err(method_name, format!("string allocation failed: {error}")))?;
        let value = if is_async {
            scope.promise_fulfilled(label).map_err(|error| {
                type_err(method_name, format!("promise allocation failed: {error}"))
            })?
        } else {
            label
        };
        let result = scope
            .object()
            .map_err(|error| type_err(method_name, format!("object allocation failed: {error}")))?;
        let is_async = scope.boolean(is_async);
        scope
            .set(result, "async", is_async)
            .map_err(|error| type_err(method_name, error.to_string()))?;
        scope
            .set(result, "value", value)
            .map_err(|error| type_err(method_name, error.to_string()))?;
        Ok(scope.finish(result))
    })
}

fn string_value(
    ctx: &mut NativeCtx<'_>,
    method_name: &'static str,
    value: &str,
) -> Result<Value, NativeError> {
    let label_str = JsString::from_str(value, ctx.heap_mut())
        .map_err(|e| type_err(method_name, format!("string allocation failed: {e}")))?;
    Ok(Value::string(label_str))
}

fn native_notify(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    // §25.4.3.12 Atomics.notify ( typedArray, index, count ).
    // Allows Int32Array / BigInt64Array; no SharedArrayBuffer
    // requirement — the spec returns 0 for a non-shared buffer
    // because no thread can be waiting on a non-shared backing.
    let ta = validate_integer_typed_array(
        args.first().unwrap_or(&Value::UNDEFINED),
        ctx.heap(),
        true,
        false,
        "Atomics.notify",
    )?;
    let idx = validate_atomic_access(
        ctx,
        &ta,
        args.get(1).unwrap_or(&Value::UNDEFINED),
        "Atomics.notify",
    )?;
    // count: ToIntegerOrInfinity with negative clamped to 0 per
    // §25.4.3.12 step 5; +Infinity means "wake every waiter".
    let count = match args.get(2) {
        None => usize::MAX,
        Some(v) if v.is_undefined() => usize::MAX,
        Some(v) => {
            let primitive = to_primitive_number(ctx, v, "Atomics.notify")?;
            if primitive.is_symbol() {
                return Err(type_err(
                    "Atomics.notify",
                    "cannot convert Symbol to a number".to_string(),
                ));
            }
            let n = to_integer_or_infinity(&primitive, ctx.heap());
            if n.is_infinite() && n.is_sign_positive() {
                usize::MAX
            } else if n.is_nan() || n.is_sign_negative() {
                0
            } else if n >= usize::MAX as f64 {
                usize::MAX
            } else {
                n as usize
            }
        }
    };
    let woken = match ta.buffer(ctx.heap()).shared_id(ctx.heap()) {
        Some(buf_id) => {
            let sync_woken = atomics_wait::notify_waiters(buf_id, idx, count);
            let async_woken =
                atomics_wait::notify_async_waiters(buf_id, idx, count.saturating_sub(sync_woken));
            sync_woken + async_woken
        }
        None => 0,
    };
    Ok(Value::number(NumberValue::from_f64(woken as f64)))
}

fn values_equal_strict(a: &Value, b: &Value, heap: &otter_gc::GcHeap) -> bool {
    if let (Some(x), Some(y)) = (a.as_number(), b.as_number()) {
        crate::number::equals(x, y)
    } else if let (Some(x), Some(y)) = (a.as_big_int(), b.as_big_int()) {
        x.numeric_eq(y, heap)
    } else {
        false
    }
}
