//! ECMA-262 §26.1 / §26.2 bootstrap installers for `WeakRef` and
//! `FinalizationRegistry`.
//!
//! Each global gets a real callable + constructible
//! [`crate::native_function::NativeFunction`] with the spec
//! prototype attached, replacing the bootstrap placeholders.
//!
//! # Contents
//! - [`install_weak_ref`] — bootstrap entry for `WeakRef`.
//! - [`install_finalization_registry`] — bootstrap entry for
//!   `FinalizationRegistry`.
//! - [`install_weak_well_knowns_post_bootstrap`] —
//!   `@@toStringTag` fixup driven by the post-bootstrap hook.
//!
//! # Invariants
//! - `new WeakRef(target)` requires `target` to be an Object (any
//!   heap-allocated value kind). Calling without `new` or with a
//!   primitive target throws `TypeError`.
//! - `new FinalizationRegistry(cleanup)` requires `cleanup` to be
//!   callable; otherwise `TypeError`.
//! - `.deref()` / `.register()` / `.unregister()` are real own
//!   data properties on the prototype.
//!
//! # See also
//! - <https://tc39.es/ecma262/#sec-weak-ref-constructor>
//! - <https://tc39.es/ecma262/#sec-finalization-registry-constructor>

use crate::weak_refs::{self, JsFinalizationRegistry, JsWeakRef};
use crate::{NativeCtx, NativeError, Value};

// `WEAKREF_SPEC` + `WeakRefIntrinsic` generated by `couch!`. §26.1
// — prototype links to %Object.prototype% via couch! default; the
// constructor back-pointer is auto-installed.
otter_macros::couch! {
    name = "WeakRef",
    string_tag = "WeakRef",
    feature = CORE,
    intrinsic = WeakRefIntrinsic,
    constructor = (length = 1, call = weak_ref_ctor_call),
    prototype = {
        methods = {
            "deref" / 0 => weak_ref_proto_deref,
        },
    },
}

// `FINALIZATIONREGISTRY_SPEC` + `FinalizationRegistryIntrinsic`
// generated by `couch!`. §26.2 — same shape as WeakRef.
otter_macros::couch! {
    name = "FinalizationRegistry",
    string_tag = "FinalizationRegistry",
    feature = CORE,
    intrinsic = FinalizationRegistryIntrinsic,
    constructor = (length = 1, call = fr_ctor_call),
    prototype = {
        methods = {
            "register"   / 2 => fr_proto_register,
            "unregister" / 1 => fr_proto_unregister,
        },
    },
}

// ---------------------------------------------------------------
// Constructor bodies
// ---------------------------------------------------------------

fn weak_ref_ctor_call(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    if !ctx.is_construct_call() {
        return Err(NativeError::TypeError {
            name: "WeakRef",
            reason: "constructor requires 'new'".to_string(),
        });
    }
    let target = args.first().cloned().unwrap_or(Value::undefined());
    if !target_can_be_weak(&target, ctx.heap()) {
        return Err(NativeError::TypeError {
            name: "WeakRef",
            reason: "target cannot be held weakly".to_string(),
        });
    }
    let weak_ref = ctx
        .alloc_weak_ref(&target, &[], &[args])
        .map_err(|_| oom("WeakRef"))?;
    if let Some(proto) = crate::bootstrap::native_new_target_prototype(ctx, "WeakRef")? {
        weak_refs::set_weak_ref_prototype_override(weak_ref, ctx.heap_mut(), Some(proto));
    }
    Ok(Value::weak_ref(weak_ref))
}

fn fr_ctor_call(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    if !ctx.is_construct_call() {
        return Err(NativeError::TypeError {
            name: "FinalizationRegistry",
            reason: "constructor requires 'new'".to_string(),
        });
    }
    let cleanup = args.first().cloned().unwrap_or(Value::undefined());
    if !ctx.interp_mut().is_callable_runtime(&cleanup) {
        return Err(NativeError::TypeError {
            name: "FinalizationRegistry",
            reason: "cleanup must be a function".to_string(),
        });
    }
    let context = ctx.execution_context().cloned();
    let registry = ctx
        .alloc_finalization_registry(cleanup, context, &[], &[args])
        .map_err(|_| oom("FinalizationRegistry"))?;
    if let Some(proto) = crate::bootstrap::native_new_target_prototype(ctx, "FinalizationRegistry")?
    {
        weak_refs::set_finalization_registry_prototype_override(
            registry,
            ctx.heap_mut(),
            Some(proto),
        );
    }
    Ok(Value::finalization_registry(registry))
}

// ---------------------------------------------------------------
// Prototype method bodies
// ---------------------------------------------------------------

fn weak_ref_proto_deref(ctx: &mut NativeCtx<'_>, _args: &[Value]) -> Result<Value, NativeError> {
    let weak_ref = receiver_weak_ref(ctx, "WeakRef.prototype.deref")?;
    Ok(weak_refs::weak_ref_deref(weak_ref, ctx.heap()))
}

fn fr_proto_register(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    let registry = receiver_finalization_registry(ctx, "FinalizationRegistry.prototype.register")?;
    let target = args.first().cloned().unwrap_or(Value::undefined());
    let held_value = args.get(1).cloned().unwrap_or(Value::undefined());
    let unregister_token = args.get(2).cloned();
    if !target_can_be_weak(&target, ctx.heap()) {
        return Err(NativeError::TypeError {
            name: "FinalizationRegistry.prototype.register",
            reason: "target cannot be held weakly".to_string(),
        });
    }
    // §26.1.3.2 step 6 — a present, non-undefined unregisterToken must
    // itself be able to be held weakly.
    if let Some(token) = unregister_token.as_ref()
        && !token.is_undefined()
        && !target_can_be_weak(token, ctx.heap())
    {
        return Err(NativeError::TypeError {
            name: "FinalizationRegistry.prototype.register",
            reason: "unregisterToken cannot be held weakly".to_string(),
        });
    }
    weak_refs::finalization_registry_register(
        registry,
        ctx.heap_mut(),
        &target,
        held_value,
        unregister_token.as_ref(),
    )
    .map_err(|e| vm_to_native(e, "FinalizationRegistry.prototype.register"))?;
    Ok(Value::undefined())
}

fn fr_proto_unregister(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    let registry =
        receiver_finalization_registry(ctx, "FinalizationRegistry.prototype.unregister")?;
    let token = args.first().cloned().unwrap_or(Value::undefined());
    // §26.1.3.4 step 3 — the unregisterToken must be able to be held weakly.
    if !target_can_be_weak(&token, ctx.heap()) {
        return Err(NativeError::TypeError {
            name: "FinalizationRegistry.prototype.unregister",
            reason: "unregisterToken cannot be held weakly".to_string(),
        });
    }
    let removed = weak_refs::finalization_registry_unregister(registry, ctx.heap_mut(), &token)
        .map_err(|e| vm_to_native(e, "FinalizationRegistry.prototype.unregister"))?;
    Ok(Value::boolean(removed))
}

// ---------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------

fn receiver_weak_ref(ctx: &NativeCtx<'_>, name: &'static str) -> Result<JsWeakRef, NativeError> {
    ctx.this_value()
        .as_weak_ref()
        .ok_or_else(|| NativeError::TypeError {
            name,
            reason: "this is not a WeakRef".to_string(),
        })
}

fn receiver_finalization_registry(
    ctx: &NativeCtx<'_>,
    name: &'static str,
) -> Result<JsFinalizationRegistry, NativeError> {
    ctx.this_value()
        .as_finalization_registry()
        .ok_or_else(|| NativeError::TypeError {
            name,
            reason: "this is not a FinalizationRegistry".to_string(),
        })
}

fn target_can_be_weak(v: &Value, heap: &otter_gc::GcHeap) -> bool {
    // ECMA-262 §6.1.7.4 CanBeHeldWeakly — any Object, or a Symbol that
    // is NOT in the global registry (`Symbol.for` results cannot be
    // held weakly because they are never collected). `is_object_type`
    // covers callables / arrays / proxies / exotics, not just plain
    // `TAG_PTR_OBJECT`.
    if v.is_symbol() {
        return v.as_symbol(heap).is_some_and(|s| !s.is_registered());
    }
    v.is_object_type()
}

fn oom(name: &'static str) -> NativeError {
    NativeError::TypeError {
        name,
        reason: "out of memory".to_string(),
    }
}

fn vm_to_native(err: crate::VmError, name: &'static str) -> NativeError {
    match err {
        crate::VmError::TypeError { message } => NativeError::TypeError {
            name,
            reason: message,
        },
        crate::VmError::NotCallable => NativeError::TypeError {
            name,
            reason: "value is not callable".to_string(),
        },
        crate::VmError::Uncaught { value } => NativeError::Thrown {
            name,
            message: value,
        },
        other => NativeError::TypeError {
            name,
            reason: other.to_string(),
        },
    }
}
