//! ECMA-262 §25.3 DataView bootstrap installer.
//!
//! Real callable + constructible `NativeFunction` for `DataView`
//! plus a prototype carrying every spec-listed method and the
//! `buffer` / `byteLength` / `byteOffset` accessors.
//!
//! # Contents
//! - [`install_data_view`] — bootstrap entry.
//! - [`install_data_view_well_knowns_post_bootstrap`] — `@@toStringTag`.
//!
//! # Invariants
//! - `new DataView(buffer, byteOffset?, byteLength?)` runs §25.3.2.1.
//! - Bare `DataView(...)` (without `new`) throws `TypeError`.
//! - 20 prototype methods + 3 read-only accessors live as own
//!   properties on `DataView.prototype`.
//!
//! # See also
//! - <https://tc39.es/ecma262/#sec-dataview-constructor>
//! - <https://tc39.es/ecma262/#sec-properties-of-the-dataview-prototype-object>

use crate::binary::data_view_prototype;
use crate::js_surface::JsSurfaceError;
use crate::object::{self, JsObject, PartialPropertyDescriptor};
use crate::{NativeCtx, NativeError, Value};

// `DATAVIEW_SPEC` + `Intrinsic` generated by `couch!`. §25.3 — 20
// view get/set methods + 3 byte-* accessors. Prototype chains to
// %Object.prototype% by couch! default; constructor back-pointer
// auto-installed.
otter_macros::couch! {
    name = "DataView",
    feature = CORE,
    constructor = (length = 1, call = data_view_ctor_call),
    prototype = {
        methods = {
            "getInt8"      / 1 => data_view_prototype::dv_get_int8,
            "getUint8"     / 1 => data_view_prototype::dv_get_uint8,
            "getInt16"     / 1 => data_view_prototype::dv_get_int16,
            "getUint16"    / 1 => data_view_prototype::dv_get_uint16,
            "getInt32"     / 1 => data_view_prototype::dv_get_int32,
            "getUint32"    / 1 => data_view_prototype::dv_get_uint32,
            "getFloat16"   / 1 => data_view_prototype::dv_get_float16,
            "getFloat32"   / 1 => data_view_prototype::dv_get_float32,
            "getFloat64"   / 1 => data_view_prototype::dv_get_float64,
            "getBigInt64"  / 1 => data_view_prototype::dv_get_bigint64,
            "getBigUint64" / 1 => data_view_prototype::dv_get_biguint64,
            "setInt8"      / 2 => data_view_prototype::dv_set_int8,
            "setUint8"     / 2 => data_view_prototype::dv_set_uint8,
            "setInt16"     / 2 => data_view_prototype::dv_set_int16,
            "setUint16"    / 2 => data_view_prototype::dv_set_uint16,
            "setInt32"     / 2 => data_view_prototype::dv_set_int32,
            "setUint32"    / 2 => data_view_prototype::dv_set_uint32,
            "setFloat16"   / 2 => data_view_prototype::dv_set_float16,
            "setFloat32"   / 2 => data_view_prototype::dv_set_float32,
            "setFloat64"   / 2 => data_view_prototype::dv_set_float64,
            "setBigInt64"  / 2 => data_view_prototype::dv_set_bigint64,
            "setBigUint64" / 2 => data_view_prototype::dv_set_biguint64,
        },
        accessors = [
            ("buffer",     get = dv_get_buffer),
            ("byteLength", get = dv_get_byte_length),
            ("byteOffset", get = dv_get_byte_offset),
        ],
    },
}

/// Install `DataView.prototype[@@toStringTag] = "DataView"`.
pub fn install_data_view_well_knowns_post_bootstrap(
    heap: &mut otter_gc::GcHeap,
    global: JsObject,
    well_known: &crate::symbol::WellKnownSymbols,
) -> Result<(), JsSurfaceError> {
    use crate::symbol::WellKnown;

    let Some(ctor) = object::get(global, heap, "DataView").and_then(|v| v.as_native_function())
    else {
        return Ok(());
    };
    let descriptor = ctor
        .own_property_descriptor(heap, "prototype")
        .map_err(|_| JsSurfaceError::OutOfMemory)?;
    let prototype = match descriptor.and_then(|d| match d.kind {
        crate::object::DescriptorKind::Data { value } => value.as_object(),
        _ => None,
    }) {
        Some(p) => p,
        None => return Ok(()),
    };
    let tag = crate::string::JsString::from_str("DataView", heap)
        .map_err(|_| JsSurfaceError::OutOfMemory)?;
    object::define_own_symbol_property_partial(
        prototype,
        heap,
        well_known.get(WellKnown::ToStringTag),
        PartialPropertyDescriptor {
            value: Some(Value::string(tag)),
            writable: Some(false),
            enumerable: Some(false),
            configurable: Some(true),
            ..Default::default()
        },
    );
    Ok(())
}

// ---------------------------------------------------------------
// Constructor
// ---------------------------------------------------------------

/// §25.3.2.1 step 4 / step 8 — `ToIndex(value)` for the constructor's
/// `byteOffset` / `byteLength`. Runs `ToNumber` through the interpreter
/// so a `valueOf` / `@@toPrimitive` hook fires (and can detach the
/// buffer mid-construction), propagates its thrown value verbatim, and
/// rejects a negative or `> 2**53 - 1` integer with a `RangeError`.
fn ctor_to_index(ctx: &mut NativeCtx<'_>, value: Option<&Value>) -> Result<usize, NativeError> {
    let undefined = Value::undefined();
    let value = value.unwrap_or(&undefined);
    let exec = ctx
        .execution_context()
        .cloned()
        .ok_or(NativeError::TypeError {
            name: "DataView",
            reason: "missing execution context".to_string(),
        })?;
    let number = crate::coerce::to_number_or_throw(ctx.interp_mut(), &exec, value)
        .map_err(|e| crate::native_function::vm_to_native_error(e, "DataView"))?;
    let n = number.as_f64();
    let integer = if n.is_nan() { 0.0 } else { n.trunc() };
    if !(0.0..=9_007_199_254_740_991.0).contains(&integer) {
        return Err(NativeError::RangeError {
            name: "DataView",
            reason: "Invalid DataView length".to_string(),
        });
    }
    Ok(integer as usize)
}

fn data_view_ctor_call(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    if !ctx.is_construct_call() {
        return Err(NativeError::TypeError {
            name: "DataView",
            reason: "constructor requires 'new'".to_string(),
        });
    }
    // §25.3.2.1 in spec order: require an ArrayBuffer argument, ToIndex
    // the byteOffset (whose coercion may detach the buffer), only then
    // check the detached state, the offset bound, and finally ToIndex
    // the byteLength against the offset.
    let buffer = args
        .first()
        .and_then(|v| v.as_array_buffer())
        .ok_or(NativeError::TypeError {
            name: "DataView",
            reason: "First argument to DataView constructor must be an ArrayBuffer".to_string(),
        })?;
    let byte_offset = ctor_to_index(ctx, args.get(1))?;
    if buffer.is_detached(ctx.heap()) {
        return Err(NativeError::TypeError {
            name: "DataView",
            reason: "Cannot construct a DataView with a detached ArrayBuffer".to_string(),
        });
    }
    let buffer_byte_length = buffer.byte_length(ctx.heap());
    if byte_offset > buffer_byte_length {
        return Err(NativeError::RangeError {
            name: "DataView",
            reason: "Start offset is outside the bounds of the buffer".to_string(),
        });
    }
    let byte_length = match args.get(2) {
        None => buffer_byte_length - byte_offset,
        Some(v) if v.is_undefined() => buffer_byte_length - byte_offset,
        Some(_) => {
            let requested = ctor_to_index(ctx, args.get(2))?;
            if byte_offset + requested > buffer_byte_length {
                return Err(NativeError::RangeError {
                    name: "DataView",
                    reason: "Invalid DataView length".to_string(),
                });
            }
            requested
        }
    };
    let view =
        crate::binary::data_view::JsDataView::new(ctx.heap_mut(), buffer, byte_offset, byte_length)
            .map_err(|_| NativeError::TypeError {
                name: "DataView",
                reason: "out of memory".to_string(),
            })?;
    let value = Value::data_view(view);
    // §10.1.13 GetPrototypeFromConstructor — derived `super()`
    // construction forwards `new.target`, so the allocated exotic
    // receives `Subclass.prototype` as its observable [[Prototype]].
    // <https://tc39.es/ecma262/#sec-getprototypefromconstructor>
    let needs_proto_override = ctx.new_target().is_none_or(|v| !v.is_native_function());
    if needs_proto_override
        && let Some(proto) = crate::bootstrap::native_new_target_prototype(ctx, "DataView")?
    {
        ctx.interp_mut()
            .set_non_gc_exotic_prototype_override(&value, Some(proto));
    }
    Ok(value)
}

// ---------------------------------------------------------------
// Accessors
// ---------------------------------------------------------------

fn dv_get_buffer(ctx: &mut NativeCtx<'_>, _args: &[Value]) -> Result<Value, NativeError> {
    let view = receiver_dv(ctx, "get DataView.prototype.buffer")?;
    Ok(Value::array_buffer(view.buffer(ctx.heap())))
}

fn dv_get_byte_length(ctx: &mut NativeCtx<'_>, _args: &[Value]) -> Result<Value, NativeError> {
    let view = receiver_dv(ctx, "get DataView.prototype.byteLength")?;
    // §25.3.4.1 — a detached (out-of-bounds) view has no byte length;
    // the getter throws a TypeError rather than reporting zero.
    if view.buffer(ctx.heap()).is_detached(ctx.heap()) {
        return Err(NativeError::TypeError {
            name: "get DataView.prototype.byteLength",
            reason: "Cannot read byteLength of a DataView with a detached buffer".to_string(),
        });
    }
    Ok(Value::number(crate::number::NumberValue::from_i32(
        view.byte_length(ctx.heap()) as i32,
    )))
}

fn dv_get_byte_offset(ctx: &mut NativeCtx<'_>, _args: &[Value]) -> Result<Value, NativeError> {
    let view = receiver_dv(ctx, "get DataView.prototype.byteOffset")?;
    // §25.3.4.2 — likewise a detached view's byteOffset getter throws.
    if view.buffer(ctx.heap()).is_detached(ctx.heap()) {
        return Err(NativeError::TypeError {
            name: "get DataView.prototype.byteOffset",
            reason: "Cannot read byteOffset of a DataView with a detached buffer".to_string(),
        });
    }
    Ok(Value::number(crate::number::NumberValue::from_i32(
        view.byte_offset(ctx.heap()) as i32,
    )))
}

fn receiver_dv(
    ctx: &NativeCtx<'_>,
    name: &'static str,
) -> Result<crate::binary::data_view::JsDataView, NativeError> {
    if let Some(v) = ctx.this_value().as_data_view() {
        Ok(v)
    } else {
        Err(NativeError::TypeError {
            name,
            reason: "this is not a DataView".to_string(),
        })
    }
}
