//! ECMA-262 §21.2 BigInt bootstrap installer.
//!
//! `BigInt` is a callable-only NativeFunction (no `[[Construct]]`).
//! The prototype carries `toString` / `valueOf` as own data
//! properties; the constructor carries `asIntN` / `asUintN`
//! statics. `@@toStringTag = "BigInt"` is installed in the
//! post-bootstrap hook.
//!
//! # Contents
//! - [`install_bigint`] — bootstrap entry.
//! - [`install_bigint_well_knowns_post_bootstrap`] — `@@toStringTag`.
//!
//! # Invariants
//! - `new BigInt(x)` throws `TypeError` per §21.2.1.1 step 1.
//! - `BigInt(x)` callable returns a BigInt via
//!   [`crate::bigint::dispatch::call`].
//! - `asIntN` / `asUintN` flow through the same dispatcher.
//!
//! # See also
//! - <https://tc39.es/ecma262/#sec-bigint-constructor>

use otter_bytecode::method_id::BigIntMethod;

use crate::bigint;
use crate::{NativeCtx, NativeError, Value, VmError};

// `BIGINT_SPEC` + `Intrinsic` generated by `couch!`. §21.2 — BigInt
// IS a constructor (it has a `[[Construct]]` slot, so
// `IsConstructor(BigInt)` is true and it may appear as an `extends`
// target), but `new BigInt(x)` throws because step 1 rejects a defined
// NewTarget — `bigint_ctor_call` enforces that via `is_construct_call`.
// Prototype links to `%Object.prototype%` by couch! default;
// constructor back-pointer auto-installed.
otter_macros::couch! {
    name = "BigInt",
    string_tag = "BigInt",
    feature = CORE,
    constructor = (length = 1, call = bigint_ctor_call),
    statics = {
        "asIntN"  / 2 => bigint_static_as_int_n,
        "asUintN" / 2 => bigint_static_as_uint_n,
    },
    prototype = {
        methods = {
            "toString"       / 0 => bigint_proto_to_string,
            "toLocaleString" / 0 => bigint_proto_to_locale_string,
            "valueOf"        / 0 => bigint_proto_value_of,
        },
    },
}

// ---------------------------------------------------------------
// Constructor + statics
// ---------------------------------------------------------------

fn bigint_ctor_call(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    if ctx.is_construct_call() {
        return Err(NativeError::TypeError {
            name: "BigInt",
            reason: "BigInt is not a constructor".to_string(),
        });
    }
    let coerced = coerce_bigint_call_args(ctx, args, "BigInt")?;
    bigint::dispatch::call(ctx.interp_mut(), BigIntMethod::Construct, &coerced)
        .map_err(|e| vm_to_native(ctx.interp_mut(), e, "BigInt"))
}

fn bigint_static_as_int_n(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    let coerced = coerce_bigint_call_args(ctx, args, "BigInt.asIntN")?;
    bigint::dispatch::call(ctx.interp_mut(), BigIntMethod::AsIntN, &coerced)
        .map_err(|e| vm_to_native(ctx.interp_mut(), e, "BigInt.asIntN"))
}

fn bigint_static_as_uint_n(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    let coerced = coerce_bigint_call_args(ctx, args, "BigInt.asUintN")?;
    bigint::dispatch::call(ctx.interp_mut(), BigIntMethod::AsUintN, &coerced)
        .map_err(|e| vm_to_native(ctx.interp_mut(), e, "BigInt.asUintN"))
}

/// §7.1.13 ToBigInt step 4 — Array operands flow through
/// `ToPrimitive(hint: number)` which routes through
/// `Array.prototype.toString` = `.join(",")`. The free
/// `bigint::dispatch::call` has no GC access, so we pre-coerce
/// Array arguments to their joined-string form before dispatch.
fn coerce_bigint_call_args(
    ctx: &mut NativeCtx<'_>,
    args: &[Value],
    name: &'static str,
) -> Result<smallvec::SmallVec<[Value; 4]>, NativeError> {
    ctx.scope(|mut scope| {
        let inputs: smallvec::SmallVec<[crate::Local<'_>; 4]> =
            args.iter().map(|value| scope.value(*value)).collect();
        let mut outputs: smallvec::SmallVec<[crate::Local<'_>; 4]> =
            smallvec::SmallVec::with_capacity(inputs.len());
        for input in inputs {
            let value = scope.raw(input);
            if let Some(arr) = value.as_array() {
                let parts: Vec<String> = {
                    let heap = scope.context().heap();
                    crate::array::with_elements(arr, heap, |elements| {
                        elements
                            .iter()
                            .map(|value| {
                                if value.is_undefined() || value.is_null() || value.is_hole() {
                                    String::new()
                                } else {
                                    value.display_string(heap)
                                }
                            })
                            .collect()
                    })
                };
                outputs.push(scope.string(&parts.join(",")).map_err(|_| {
                    NativeError::TypeError {
                        name,
                        reason: "out of memory".to_string(),
                    }
                })?);
            } else if value.is_object()
                || value.is_function()
                || value.is_closure()
                || value.is_native_function()
                || value.is_bound_function()
                || value.is_class_constructor()
                || value.is_proxy()
                || value.is_regexp()
                || value.is_map()
                || value.is_set()
            {
                // §7.1.1 ToPrimitive ladder for object-like operands.
                let exec = scope
                    .context()
                    .execution_context()
                    .cloned()
                    .ok_or_else(|| NativeError::TypeError {
                        name,
                        reason: "missing execution context".to_string(),
                    })?;
                let primitive = scope.with_turn_parts(|interp, stack| {
                    interp
                        .evaluate_to_primitive(
                            stack,
                            &exec,
                            &value,
                            crate::abstract_ops::ToPrimitiveHint::Number,
                        )
                        .map_err(|error| vm_to_native(interp, error, name))
                })?;
                outputs.push(scope.value(primitive));
            } else {
                outputs.push(input);
            }
        }
        Ok(outputs.iter().map(|value| scope.raw(*value)).collect())
    })
}

// ---------------------------------------------------------------
// Prototype methods
// ---------------------------------------------------------------

fn bigint_proto_to_string(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    ctx.scope(|mut scope| {
        let this = scope.this();
        let this_value = scope.raw(this);
        if this_value.as_big_int().is_none()
            && this_value
                .as_object()
                .and_then(|obj| crate::object::bigint_data(obj, scope.context().heap()))
                .is_none()
        {
            return Err(NativeError::TypeError {
                name: "BigInt.prototype.toString",
                reason: "this is not a BigInt".to_string(),
            });
        }

        // §21.2.3.4 step 2 — `radix` defaults to 10 when `undefined`,
        // otherwise routes through `ToIntegerOrInfinity`. The spec
        // raises RangeError for `< 2` / `> 36`; non-coercible operands
        // raise TypeError.
        let radix_value = scope.argument(args, 0);
        let radix = if scope.raw(radix_value).is_undefined() {
            10u32
        } else {
            // §21.2.3.3 step 4 — radixNumber = ToIntegerOrInfinity(radix),
            // whose ToNumber runs a `valueOf` / `@@toPrimitive` (poisoned
            // ones throw) and rejects Symbol / BigInt; an object operand
            // must not be silently dropped to NaN.
            let value = scope.raw(radix_value);
            let exec = scope
                .context()
                .execution_context()
                .cloned()
                .ok_or_else(|| NativeError::TypeError {
                    name: "BigInt.prototype.toString",
                    reason: "missing execution context".to_string(),
                })?;
            let number = scope.with_turn_parts(|interp, stack| {
                crate::coerce::to_number_or_throw(interp, stack, &exec, &value)
                    .map_err(|err| vm_to_native(interp, err, "BigInt.prototype.toString"))
            })?;
            let f = number.as_f64();
            let trunc = if f.is_nan() { 0.0 } else { f.trunc() };
            if !trunc.is_finite() || !(2.0..=36.0).contains(&trunc) {
                return Err(NativeError::RangeError {
                    name: "BigInt.prototype.toString",
                    reason: "radix must be an integer in [2, 36]".to_string(),
                });
            }
            trunc as u32
        };

        let this_value = scope.raw(this);
        let b = if let Some(b) = this_value.as_big_int() {
            b
        } else if let Some(obj) = this_value.as_object() {
            crate::object::bigint_data(obj, scope.context().heap()).ok_or_else(|| {
                NativeError::TypeError {
                    name: "BigInt.prototype.toString",
                    reason: "this is not a BigInt".to_string(),
                }
            })?
        } else {
            return Err(NativeError::TypeError {
                name: "BigInt.prototype.toString",
                reason: "this is not a BigInt".to_string(),
            });
        };
        let rendered = b.with_inner(scope.context().heap(), |bi| bi.to_str_radix(radix));
        let rendered = scope
            .string(&rendered)
            .map_err(|_| oom("BigInt.prototype.toString"))?;
        Ok(scope.finish(rendered))
    })
}

/// §BigInt.prototype.toLocaleString — brand-check `this`, then format
/// through a freshly constructed Intl.NumberFormat so the output matches
/// `new Intl.NumberFormat(locales, options).format(this)`.
fn bigint_proto_to_locale_string(
    ctx: &mut NativeCtx<'_>,
    args: &[Value],
) -> Result<Value, NativeError> {
    let this = ctx.this_value();
    let name = "BigInt.prototype.toLocaleString";
    let b = if let Some(b) = this.as_big_int() {
        b
    } else if let Some(obj) = this.as_object() {
        crate::object::bigint_data(obj, ctx.heap()).ok_or_else(|| NativeError::TypeError {
            name,
            reason: "this is not a BigInt".to_string(),
        })?
    } else {
        return Err(NativeError::TypeError {
            name,
            reason: "this is not a BigInt".to_string(),
        });
    };
    let value = b
        .with_inner(ctx.heap(), num_traits::ToPrimitive::to_f64)
        .unwrap_or(f64::NAN);
    let locales = args.first().copied().unwrap_or_else(Value::undefined);
    let options = args.get(1).copied().unwrap_or_else(Value::undefined);
    crate::intl::number_format::to_locale_string(ctx, value, locales, options)
}

fn bigint_proto_value_of(ctx: &mut NativeCtx<'_>, _args: &[Value]) -> Result<Value, NativeError> {
    let this = ctx.this_value();
    if let Some(b) = this.as_big_int() {
        Ok(Value::big_int(b))
    } else if let Some(obj) = this.as_object() {
        crate::object::bigint_data(obj, ctx.heap())
            .map(Value::big_int)
            .ok_or_else(|| NativeError::TypeError {
                name: "BigInt.prototype.valueOf",
                reason: "this is not a BigInt".to_string(),
            })
    } else {
        Err(NativeError::TypeError {
            name: "BigInt.prototype.valueOf",
            reason: "this is not a BigInt".to_string(),
        })
    }
}

// ---------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------

fn oom(name: &'static str) -> NativeError {
    NativeError::TypeError {
        name,
        reason: "out of memory".to_string(),
    }
}

fn vm_to_native(interp: &crate::Interpreter, err: VmError, name: &'static str) -> NativeError {
    match err {
        VmError::TypeError => {
            let message = match interp.take_error_detail() {
                Some(crate::run_control::ErrorDetail::Message(m)) => m,
                _ => Default::default(),
            };
            NativeError::TypeError {
                name,
                reason: message.into(),
            }
        }
        VmError::TypeMismatch => NativeError::TypeError {
            name,
            reason: "type mismatch".to_string(),
        },
        VmError::RangeError => {
            let message = match interp.take_error_detail() {
                Some(crate::run_control::ErrorDetail::Message(m)) => m,
                _ => Default::default(),
            };
            NativeError::RangeError {
                name,
                reason: message.into(),
            }
        }
        VmError::SyntaxError => {
            let message = match interp.take_error_detail() {
                Some(crate::run_control::ErrorDetail::Message(m)) => m,
                _ => Default::default(),
            };
            NativeError::SyntaxError {
                name,
                reason: message.into(),
            }
        }
        VmError::Uncaught => {
            let value = match interp.take_error_detail() {
                Some(crate::run_control::ErrorDetail::Uncaught(m)) => m,
                _ => Default::default(),
            };
            NativeError::Thrown {
                name,
                message: value.into(),
            }
        }
        other => NativeError::TypeError {
            name,
            reason: other.to_string(),
        },
    }
}
