//! ECMA-262 §25.3 DataView bootstrap installer.
//!
//! Real callable + constructible `NativeFunction` for `DataView`
//! plus a prototype carrying every spec-listed method and the
//! `buffer` / `byteLength` / `byteOffset` accessors.
//!
//! # Contents
//! - [`install_data_view`] — bootstrap entry.
//! - [`install_data_view_well_knowns_post_bootstrap`] — `@@toStringTag`.
//!
//! # Invariants
//! - `new DataView(buffer, byteOffset?, byteLength?)` runs §25.3.2.1.
//! - Bare `DataView(...)` (without `new`) throws `TypeError`.
//! - 20 prototype methods + 3 read-only accessors live as own
//!   properties on `DataView.prototype`.
//!
//! # See also
//! - <https://tc39.es/ecma262/#sec-dataview-constructor>
//! - <https://tc39.es/ecma262/#sec-properties-of-the-dataview-prototype-object>

use crate::binary::data_view_prototype;
use crate::{NativeCtx, NativeError, Value};

// `DATAVIEW_SPEC` + `Intrinsic` generated by `couch!`. §25.3 — 20
// view get/set methods + 3 byte-* accessors. Prototype chains to
// %Object.prototype% by couch! default; constructor back-pointer
// auto-installed.
otter_macros::couch! {
    name = "DataView",
    string_tag = "DataView",
    feature = CORE,
    constructor = (length = 1, call = data_view_ctor_call),
    prototype = {
        methods = {
            "getInt8"      / 1 => data_view_prototype::dv_get_int8,
            "getUint8"     / 1 => data_view_prototype::dv_get_uint8,
            "getInt16"     / 1 => data_view_prototype::dv_get_int16,
            "getUint16"    / 1 => data_view_prototype::dv_get_uint16,
            "getInt32"     / 1 => data_view_prototype::dv_get_int32,
            "getUint32"    / 1 => data_view_prototype::dv_get_uint32,
            "getFloat16"   / 1 => data_view_prototype::dv_get_float16,
            "getFloat32"   / 1 => data_view_prototype::dv_get_float32,
            "getFloat64"   / 1 => data_view_prototype::dv_get_float64,
            "getBigInt64"  / 1 => data_view_prototype::dv_get_bigint64,
            "getBigUint64" / 1 => data_view_prototype::dv_get_biguint64,
            "setInt8"      / 2 => data_view_prototype::dv_set_int8,
            "setUint8"     / 2 => data_view_prototype::dv_set_uint8,
            "setInt16"     / 2 => data_view_prototype::dv_set_int16,
            "setUint16"    / 2 => data_view_prototype::dv_set_uint16,
            "setInt32"     / 2 => data_view_prototype::dv_set_int32,
            "setUint32"    / 2 => data_view_prototype::dv_set_uint32,
            "setFloat16"   / 2 => data_view_prototype::dv_set_float16,
            "setFloat32"   / 2 => data_view_prototype::dv_set_float32,
            "setFloat64"   / 2 => data_view_prototype::dv_set_float64,
            "setBigInt64"  / 2 => data_view_prototype::dv_set_bigint64,
            "setBigUint64" / 2 => data_view_prototype::dv_set_biguint64,
        },
        accessors = [
            ("buffer",     get = dv_get_buffer),
            ("byteLength", get = dv_get_byte_length),
            ("byteOffset", get = dv_get_byte_offset),
        ],
    },
}

// ---------------------------------------------------------------
// Constructor
// ---------------------------------------------------------------

/// §25.3.2.1 step 4 / step 8 — `ToIndex(value)` for the constructor's
/// `byteOffset` / `byteLength`. Runs `ToNumber` through the interpreter
/// so a `valueOf` / `@@toPrimitive` hook fires (and can detach the
/// buffer mid-construction), propagates its thrown value verbatim, and
/// rejects a negative or `> 2**53 - 1` integer with a `RangeError`.
fn ctor_to_index(ctx: &mut NativeCtx<'_>, value: Option<&Value>) -> Result<usize, NativeError> {
    let undefined = Value::undefined();
    let value = value.unwrap_or(&undefined);
    let exec = ctx
        .execution_context()
        .cloned()
        .ok_or_else(|| NativeError::TypeError {
            name: "DataView",
            reason: "missing execution context".to_string(),
        })?;
    let number = ctx.with_turn_parts(|interp, stack| {
        crate::coerce::to_number_or_throw(interp, stack, &exec, value)
            .map_err(|e| crate::native_function::vm_to_native_error(interp, e, "DataView"))
    })?;
    let n = number.as_f64();
    let integer = if n.is_nan() { 0.0 } else { n.trunc() };
    if !(0.0..=9_007_199_254_740_991.0).contains(&integer) {
        return Err(NativeError::RangeError {
            name: "DataView",
            reason: "Invalid DataView length".to_string(),
        });
    }
    Ok(integer as usize)
}

fn data_view_ctor_call(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    if !ctx.is_construct_call() {
        return Err(NativeError::TypeError {
            name: "DataView",
            reason: "constructor requires 'new'".to_string(),
        });
    }
    ctx.scope(|mut scope| {
        // §25.3.2.1 in spec order: require an ArrayBuffer argument, ToIndex
        // the byteOffset (whose coercion may detach the buffer), only then
        // check the detached state, the offset bound, and finally ToIndex
        // the byteLength against the offset.
        let buffer_value = scope.argument(args, 0);
        if scope.raw(buffer_value).as_array_buffer().is_none() {
            return Err(NativeError::TypeError {
                name: "DataView",
                reason: "First argument to DataView constructor must be an ArrayBuffer".to_string(),
            });
        }
        let offset_value = scope.argument(args, 1);
        let byte_offset = {
            let offset = scope.raw(offset_value);
            ctor_to_index(scope.context(), Some(&offset))?
        };
        let buffer =
            scope
                .raw(buffer_value)
                .as_array_buffer()
                .ok_or_else(|| NativeError::TypeError {
                    name: "DataView",
                    reason: "ArrayBuffer root changed kind during construction".to_string(),
                })?;
        if buffer.is_detached(scope.context().heap()) {
            return Err(NativeError::TypeError {
                name: "DataView",
                reason: "Cannot construct a DataView with a detached ArrayBuffer".to_string(),
            });
        }
        let buffer_byte_length = buffer.byte_length(scope.context().heap());
        if byte_offset > buffer_byte_length {
            return Err(NativeError::RangeError {
                name: "DataView",
                reason: "Start offset is outside the bounds of the buffer".to_string(),
            });
        }
        let length_value = scope.argument(args, 2);
        let length_absent = scope.raw(length_value).is_undefined();
        let byte_length = if length_absent {
            buffer_byte_length - byte_offset
        } else {
            let length = scope.raw(length_value);
            let requested = ctor_to_index(scope.context(), Some(&length))?;
            if byte_offset + requested > buffer_byte_length {
                return Err(NativeError::RangeError {
                    name: "DataView",
                    reason: "Invalid DataView length".to_string(),
                });
            }
            requested
        };

        // §25.3.2.1 step 10 — GetPrototypeFromConstructor may run user code.
        // Re-read every rooted value after it before installing the view.
        let needs_proto_override = scope
            .context()
            .new_target()
            .is_none_or(|value| !value.is_native_function());
        let proto_override = if needs_proto_override {
            crate::bootstrap::native_new_target_prototype(scope.context(), "DataView")?
                .map(|value| scope.value(value))
        } else {
            None
        };
        let buffer =
            scope
                .raw(buffer_value)
                .as_array_buffer()
                .ok_or_else(|| NativeError::TypeError {
                    name: "DataView",
                    reason: "ArrayBuffer root changed kind during construction".to_string(),
                })?;
        if buffer.is_detached(scope.context().heap()) {
            return Err(NativeError::TypeError {
                name: "DataView",
                reason: "Cannot construct a DataView with a detached ArrayBuffer".to_string(),
            });
        }
        let current_buffer_byte_length = buffer.byte_length(scope.context().heap());
        if byte_offset > current_buffer_byte_length
            || (!length_absent && byte_offset + byte_length > current_buffer_byte_length)
        {
            return Err(NativeError::RangeError {
                name: "DataView",
                reason: "Invalid DataView length".to_string(),
            });
        }
        let view = crate::binary::data_view::JsDataView::new(
            scope.context().heap_mut(),
            buffer,
            byte_offset,
            byte_length,
        )
        .map_err(|_| NativeError::TypeError {
            name: "DataView",
            reason: "out of memory".to_string(),
        })?;
        let view_value = scope.value(Value::data_view(view));

        // §25.3.2.1 — an absent byteLength over a length-resizable buffer
        // (resizable ArrayBuffer or growable SharedArrayBuffer) makes the
        // view length-tracking (AUTO byte length).
        let buffer =
            scope
                .raw(buffer_value)
                .as_array_buffer()
                .ok_or_else(|| NativeError::TypeError {
                    name: "DataView",
                    reason: "ArrayBuffer root changed kind during construction".to_string(),
                })?;
        if length_absent
            && (buffer.is_resizable(scope.context().heap())
                || buffer.is_growable(scope.context().heap()))
        {
            let view =
                scope
                    .raw(view_value)
                    .as_data_view()
                    .ok_or_else(|| NativeError::TypeError {
                        name: "DataView",
                        reason: "DataView root changed kind during construction".to_string(),
                    })?;
            view.set_length_tracking(scope.context().heap_mut());
        }
        if let Some(proto) = proto_override {
            let value = scope.raw(view_value);
            let proto = scope.raw(proto);
            scope
                .context()
                .interp_mut()
                .set_non_gc_exotic_prototype_override(&value, Some(proto));
        }
        Ok(scope.finish(view_value))
    })
}

// ---------------------------------------------------------------
// Accessors
// ---------------------------------------------------------------

fn dv_get_buffer(ctx: &mut NativeCtx<'_>, _args: &[Value]) -> Result<Value, NativeError> {
    let view = receiver_dv(ctx, "get DataView.prototype.buffer")?;
    Ok(Value::array_buffer(view.buffer(ctx.heap())))
}

fn dv_get_byte_length(ctx: &mut NativeCtx<'_>, _args: &[Value]) -> Result<Value, NativeError> {
    let view = receiver_dv(ctx, "get DataView.prototype.byteLength")?;
    // §25.3.4.1 — a detached or out-of-bounds view (fixed view past a
    // shrunk resizable buffer) has no byte length; the getter throws a
    // TypeError. A length-tracking view reports its live size.
    if view.is_out_of_bounds(ctx.heap()) {
        return Err(NativeError::TypeError {
            name: "get DataView.prototype.byteLength",
            reason: "Cannot read byteLength of an out-of-bounds DataView".to_string(),
        });
    }
    Ok(Value::number(crate::number::NumberValue::from_i32(
        view.current_byte_length(ctx.heap()) as i32,
    )))
}

fn dv_get_byte_offset(ctx: &mut NativeCtx<'_>, _args: &[Value]) -> Result<Value, NativeError> {
    let view = receiver_dv(ctx, "get DataView.prototype.byteOffset")?;
    // §25.3.4.2 — likewise a detached or out-of-bounds view's
    // byteOffset getter throws.
    if view.is_out_of_bounds(ctx.heap()) {
        return Err(NativeError::TypeError {
            name: "get DataView.prototype.byteOffset",
            reason: "Cannot read byteOffset of an out-of-bounds DataView".to_string(),
        });
    }
    Ok(Value::number(crate::number::NumberValue::from_i32(
        view.byte_offset(ctx.heap()) as i32,
    )))
}

fn receiver_dv(
    ctx: &NativeCtx<'_>,
    name: &'static str,
) -> Result<crate::binary::data_view::JsDataView, NativeError> {
    if let Some(v) = ctx.this_value().as_data_view() {
        Ok(v)
    } else {
        Err(NativeError::TypeError {
            name,
            reason: "this is not a DataView".to_string(),
        })
    }
}
