//! ECMA-262 §26.1 / §26.2 bootstrap installers for `WeakRef` and
//! `FinalizationRegistry`.
//!
//! Each global gets a real callable + constructible
//! [`crate::native_function::NativeFunction`] with the spec
//! prototype attached, replacing the bootstrap placeholders.
//!
//! # Contents
//! - [`install_weak_ref`] — bootstrap entry for `WeakRef`.
//! - [`install_finalization_registry`] — bootstrap entry for
//!   `FinalizationRegistry`.
//! - [`install_weak_well_knowns_post_bootstrap`] —
//!   `@@toStringTag` fixup driven by the post-bootstrap hook.
//!
//! # Invariants
//! - `new WeakRef(target)` requires `target` to be an Object (any
//!   heap-allocated value kind). Calling without `new` or with a
//!   primitive target throws `TypeError`.
//! - `new FinalizationRegistry(cleanup)` requires `cleanup` to be
//!   callable; otherwise `TypeError`.
//! - `.deref()` / `.register()` / `.unregister()` are real own
//!   data properties on the prototype.
//!
//! # See also
//! - <https://tc39.es/ecma262/#sec-weak-ref-constructor>
//! - <https://tc39.es/ecma262/#sec-finalization-registry-constructor>

use crate::js_surface::JsSurfaceError;
use crate::object::{self, JsObject, PartialPropertyDescriptor};
use crate::weak_refs::{self, JsFinalizationRegistry, JsWeakRef};
use crate::{NativeCtx, NativeError, Value};

// `WEAKREF_SPEC` + `WeakRefIntrinsic` generated by `couch!`. §26.1
// — prototype links to %Object.prototype% via couch! default; the
// constructor back-pointer is auto-installed.
otter_macros::couch! {
    name = "WeakRef",
    feature = CORE,
    intrinsic = WeakRefIntrinsic,
    constructor = (length = 1, call = weak_ref_ctor_call),
    prototype = {
        methods = {
            "deref" / 0 => weak_ref_proto_deref,
        },
    },
}

// `FINALIZATIONREGISTRY_SPEC` + `FinalizationRegistryIntrinsic`
// generated by `couch!`. §26.2 — same shape as WeakRef.
otter_macros::couch! {
    name = "FinalizationRegistry",
    feature = CORE,
    intrinsic = FinalizationRegistryIntrinsic,
    constructor = (length = 1, call = fr_ctor_call),
    prototype = {
        methods = {
            "register"   / 2 => fr_proto_register,
            "unregister" / 1 => fr_proto_unregister,
        },
    },
}

/// Install `@@toStringTag` on both prototypes once the per-realm
/// well-known table exists.
pub fn install_weak_well_knowns_post_bootstrap(
    heap: &mut otter_gc::GcHeap,
    global: JsObject,
    well_known: &crate::symbol::WellKnownSymbols,
) -> Result<(), JsSurfaceError> {
    use crate::symbol::WellKnown;

    let tag_sym = well_known.get(WellKnown::ToStringTag);
    for (ctor_name, tag_value) in [
        ("WeakRef", "WeakRef"),
        ("FinalizationRegistry", "FinalizationRegistry"),
    ] {
        let Some(prototype) = ctor_prototype(global, heap, ctor_name) else {
            continue;
        };
        let tag = crate::string::JsString::from_str(tag_value, heap)
            .map_err(|_| JsSurfaceError::OutOfMemory)?;
        object::define_own_symbol_property_partial(
            prototype,
            heap,
            tag_sym,
            PartialPropertyDescriptor {
                value: Some(Value::string(tag)),
                writable: Some(false),
                enumerable: Some(false),
                configurable: Some(true),
                ..Default::default()
            },
        );
    }
    Ok(())
}

// ---------------------------------------------------------------
// Constructor bodies
// ---------------------------------------------------------------

fn weak_ref_ctor_call(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    if !ctx.is_construct_call() {
        return Err(NativeError::TypeError {
            name: "WeakRef",
            reason: "constructor requires 'new'".to_string(),
        });
    }
    let target = args.first().cloned().unwrap_or(Value::undefined());
    if !target_can_be_weak(&target) {
        return Err(NativeError::TypeError {
            name: "WeakRef",
            reason: "target must be an object".to_string(),
        });
    }
    let weak_ref = ctx
        .alloc_weak_ref(&target, &[], &[args])
        .map_err(|_| oom("WeakRef"))?;
    if let Some(proto) = crate::bootstrap::native_new_target_prototype(ctx, "WeakRef")? {
        weak_refs::set_weak_ref_prototype_override(weak_ref, ctx.heap_mut(), Some(proto));
    }
    Ok(Value::weak_ref(weak_ref))
}

fn fr_ctor_call(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    if !ctx.is_construct_call() {
        return Err(NativeError::TypeError {
            name: "FinalizationRegistry",
            reason: "constructor requires 'new'".to_string(),
        });
    }
    let cleanup = args.first().cloned().unwrap_or(Value::undefined());
    if !ctx.interp_mut().is_callable_runtime(&cleanup) {
        return Err(NativeError::TypeError {
            name: "FinalizationRegistry",
            reason: "cleanup must be a function".to_string(),
        });
    }
    let context = ctx.execution_context().cloned();
    let registry = ctx
        .alloc_finalization_registry(cleanup, context, &[], &[args])
        .map_err(|_| oom("FinalizationRegistry"))?;
    if let Some(proto) = crate::bootstrap::native_new_target_prototype(ctx, "FinalizationRegistry")?
    {
        weak_refs::set_finalization_registry_prototype_override(
            registry,
            ctx.heap_mut(),
            Some(proto),
        );
    }
    Ok(Value::finalization_registry(registry))
}

// ---------------------------------------------------------------
// Prototype method bodies
// ---------------------------------------------------------------

fn weak_ref_proto_deref(ctx: &mut NativeCtx<'_>, _args: &[Value]) -> Result<Value, NativeError> {
    let weak_ref = receiver_weak_ref(ctx, "WeakRef.prototype.deref")?;
    Ok(weak_refs::weak_ref_deref(weak_ref, ctx.heap()))
}

fn fr_proto_register(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    let registry = receiver_finalization_registry(ctx, "FinalizationRegistry.prototype.register")?;
    let target = args.first().cloned().unwrap_or(Value::undefined());
    let held_value = args.get(1).cloned().unwrap_or(Value::undefined());
    let unregister_token = args.get(2).cloned();
    if !target_can_be_weak(&target) {
        return Err(NativeError::TypeError {
            name: "FinalizationRegistry.prototype.register",
            reason: "target must be an object".to_string(),
        });
    }
    weak_refs::finalization_registry_register(
        registry,
        ctx.heap_mut(),
        &target,
        held_value,
        unregister_token.as_ref(),
    )
    .map_err(|e| vm_to_native(e, "FinalizationRegistry.prototype.register"))?;
    Ok(Value::undefined())
}

fn fr_proto_unregister(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    let registry =
        receiver_finalization_registry(ctx, "FinalizationRegistry.prototype.unregister")?;
    let token = args.first().cloned().unwrap_or(Value::undefined());
    let removed = weak_refs::finalization_registry_unregister(registry, ctx.heap_mut(), &token)
        .map_err(|e| vm_to_native(e, "FinalizationRegistry.prototype.unregister"))?;
    Ok(Value::boolean(removed))
}

// ---------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------

fn ctor_prototype(
    global: JsObject,
    heap: &mut otter_gc::GcHeap,
    ctor_name: &str,
) -> Option<JsObject> {
    let f = object::get(global, heap, ctor_name).and_then(|v| v.as_native_function())?;
    let descriptor = f
        .own_property_descriptor(&mut *heap, "prototype")
        .ok()
        .flatten()?;
    match descriptor.kind {
        crate::object::DescriptorKind::Data { value } => value.as_object(),
        _ => None,
    }
}

fn receiver_weak_ref(ctx: &NativeCtx<'_>, name: &'static str) -> Result<JsWeakRef, NativeError> {
    ctx.this_value()
        .as_weak_ref()
        .ok_or_else(|| NativeError::TypeError {
            name,
            reason: "this is not a WeakRef".to_string(),
        })
}

fn receiver_finalization_registry(
    ctx: &NativeCtx<'_>,
    name: &'static str,
) -> Result<JsFinalizationRegistry, NativeError> {
    ctx.this_value()
        .as_finalization_registry()
        .ok_or_else(|| NativeError::TypeError {
            name,
            reason: "this is not a FinalizationRegistry".to_string(),
        })
}

fn target_can_be_weak(v: &Value) -> bool {
    // ECMA-262 §6.1.7.4 CanBeHeldWeakly — `Object` includes any
    // heap-backed reference (callable / array / proxy / exotic), not
    // just `TAG_PTR_OBJECT`. `Value::is_object_like` is narrower
    // than the spec definition and rejects functions, breaking
    // `new WeakRef(function () {})`.
    v.is_object_type() || v.is_symbol()
}

fn oom(name: &'static str) -> NativeError {
    NativeError::TypeError {
        name,
        reason: "out of memory".to_string(),
    }
}

fn vm_to_native(err: crate::VmError, name: &'static str) -> NativeError {
    match err {
        crate::VmError::TypeError { message } => NativeError::TypeError {
            name,
            reason: message,
        },
        crate::VmError::NotCallable => NativeError::TypeError {
            name,
            reason: "value is not callable".to_string(),
        },
        crate::VmError::Uncaught { value } => NativeError::Thrown {
            name,
            message: value,
        },
        other => NativeError::TypeError {
            name,
            reason: other.to_string(),
        },
    }
}
