//! ECMA-262 §27.2 Promise bootstrap installer.
//!
//! Installs the JS-visible `Promise` constructor with all 7 static
//! methods (`resolve` / `reject` / `all` / `race` / `allSettled` /
//! `any` / `withResolvers`) and a prototype carrying `then` /
//! `catch` / `finally`. The constructor delegates to the existing
//! [`crate::promise_dispatch`] dispatcher; the prototype is linked
//! to `%Object.prototype%` and gets `@@toStringTag = "Promise"`
//! installed in
//! [`install_promise_well_knowns_post_bootstrap`].
//!
//! # Contents
//! - [`install_promise`] — bootstrap entry point.
//! - [`install_promise_well_knowns_post_bootstrap`] — `@@toStringTag`
//!   fixup that runs once the per-realm `WellKnownSymbols` table
//!   exists.
//!
//! # Invariants
//! - `new Promise(executor)` runs the executor synchronously with
//!   the realm's `resolve` / `reject` natives. If the executor
//!   throws, the captured rejection reason settles the promise.
//! - `Promise()` (no `new`) throws a `TypeError` per §27.2.3.1.
//! - All statics + prototype methods reuse
//!   [`crate::promise_dispatch::statics_call`] /
//!   [`crate::promise_dispatch::prototype_call`] so the
//!   microtask queue semantics stay identical to the dedicated
//!   `Op::PromiseCall` opcode path.
//!
//! # See also
//! - <https://tc39.es/ecma262/#sec-promise-constructor>
//! - <https://tc39.es/ecma262/#sec-properties-of-the-promise-prototype-object>

use otter_bytecode::method_id::PromiseMethod;
use smallvec::SmallVec;

use crate::js_surface::JsSurfaceError;
use crate::object::{self, JsObject, PartialPropertyDescriptor};
use crate::promise_dispatch::{self, PromiseBuilder};
use crate::{NativeCtx, NativeError, Value, VmError};

// `PROMISE_SPEC` + `Intrinsic` generated by `couch!`. §27.2 — the
// `couch!` install body chains the prototype to `%Object.prototype%`
// (default behaviour when the prototype block is non-empty),
// installs the static methods on the constructor, attaches the
// prototype methods, and pins the `constructor` back-pointer per
// §27.2.5.2.
otter_macros::couch! {
    name = "Promise",
    string_tag = "Promise",
    feature = CORE,
    constructor = (length = 1, call = promise_ctor_call),
    statics = {
        "resolve"          / 1 => promise_static_resolve,
        "reject"           / 1 => promise_static_reject,
        "all"              / 1 => promise_static_all,
        "race"             / 1 => promise_static_race,
        "allSettled"       / 1 => promise_static_all_settled,
        "any"              / 1 => promise_static_any,
        "withResolvers"    / 0 => promise_static_with_resolvers,
        "try"              / 1 => promise_static_try,
        "allKeyed"         / 1 => promise_static_all_keyed,
        "allSettledKeyed"  / 1 => promise_static_all_settled_keyed,
    },
    prototype = {
        methods = {
            "then"    / 2 => promise_proto_then,
            "catch"   / 1 => promise_proto_catch,
            "finally" / 1 => promise_proto_finally,
        },
    },
}

/// Install Promise well-known symbol properties.
///
/// # See also
/// - <https://tc39.es/ecma262/#sec-promise.prototype-@@tostringtag>
/// - <https://tc39.es/ecma262/#sec-get-promise-@@species>
pub fn install_promise_well_knowns_post_bootstrap(
    heap: &mut otter_gc::GcHeap,
    global: JsObject,
    well_known: &crate::symbol::WellKnownSymbols,
) -> Result<(), JsSurfaceError> {
    use crate::symbol::WellKnown;

    let Some(ctor) = object::get(global, heap, "Promise").and_then(|v| v.as_native_function())
    else {
        return Ok(());
    };
    let global_root = Value::object(global);
    let ctor_root = Value::native_function(ctor);
    let species_getter = crate::bootstrap::native_static_with_value_roots(
        heap,
        "get [Symbol.species]",
        0,
        promise_species_get,
        &[&global_root, &ctor_root],
    )
    .map_err(|_| JsSurfaceError::OutOfMemory)?;
    if !ctor.define_own_symbol_property(
        heap,
        well_known.get(WellKnown::Species),
        PartialPropertyDescriptor {
            get: Some(Value::native_function(species_getter)),
            enumerable: Some(false),
            configurable: Some(true),
            ..Default::default()
        },
    ) {
        return Err(JsSurfaceError::DefinePropertyFailed(
            "Promise[Symbol.species]",
        ));
    }

    Ok(())
}

/// §27.2.4.10 `get Promise[@@species]`.
///
/// # See also
/// - <https://tc39.es/ecma262/#sec-get-promise-@@species>
fn promise_species_get(ctx: &mut NativeCtx<'_>, _args: &[Value]) -> Result<Value, NativeError> {
    Ok(*ctx.this_value())
}

// ---------------------------------------------------------------
// Constructor body
// ---------------------------------------------------------------

/// §27.2.3.1 `Promise(executor)`.
///
/// 1. If NewTarget is undefined, throw a TypeError.
/// 2. If IsCallable(executor) is false, throw a TypeError.
/// 3. Allocate a fresh pending promise + native resolve/reject.
/// 4. Invoke executor with `[resolve, reject]` synchronously.
///    If the executor throws, settle the promise via the captured
///    `reject` (idempotent — if the executor already resolved
///    before throwing, the reject is a spec-mandated no-op).
fn promise_ctor_call(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    if !ctx.is_construct_call() {
        return Err(NativeError::TypeError {
            name: "Promise",
            reason: "Promise constructor requires 'new'".to_string(),
        });
    }
    let executor = args.first().cloned().unwrap_or(Value::undefined());
    if !ctx.interp_mut().is_callable_runtime(&executor) {
        return Err(NativeError::TypeError {
            name: "Promise",
            reason: "Promise executor is not callable".to_string(),
        });
    }
    let context = ctx
        .execution_context()
        .cloned()
        .ok_or_else(|| NativeError::TypeError {
            name: "Promise",
            reason: "no active execution context".to_string(),
        })?;
    let (handle, resolve, reject) = PromiseBuilder::with_context(context.clone())
        .construct_native_rooted(ctx, &[&executor], &[args])
        .map_err(|_| oom("Promise"))?;
    if let Some(proto) = crate::bootstrap::native_new_target_prototype(ctx, "Promise")? {
        handle.set_prototype_override(ctx.heap_mut(), Some(proto));
    }
    let promise_value = Value::promise(handle);
    let invoke_args: SmallVec<[Value; 8]> = smallvec::smallvec![resolve, reject];
    let invoke_result =
        ctx.interp_mut()
            .run_callable_sync(&context, &executor, Value::undefined(), invoke_args);
    if let Err(err) = invoke_result {
        // §27.2.1.4 step 3 — wrap the abrupt completion's value,
        // route it through the captured native `reject`. The
        // resolve / reject natives are idempotent once the
        // promise is settled.
        let reason = vm_err_to_value(&err, ctx.heap_mut());
        let _ = ctx.interp_mut().run_callable_sync(
            &context,
            &reject,
            Value::undefined(),
            smallvec::smallvec![reason],
        );
    }
    Ok(promise_value)
}

// ---------------------------------------------------------------
// Static method bodies
// ---------------------------------------------------------------

fn promise_static_resolve(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    invoke_static(ctx, PromiseMethod::Resolve, args)
}

fn promise_static_reject(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    invoke_static(ctx, PromiseMethod::Reject, args)
}

fn promise_static_all(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    invoke_static(ctx, PromiseMethod::All, args)
}

fn promise_static_race(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    invoke_static(ctx, PromiseMethod::Race, args)
}

fn promise_static_all_settled(
    ctx: &mut NativeCtx<'_>,
    args: &[Value],
) -> Result<Value, NativeError> {
    invoke_static(ctx, PromiseMethod::AllSettled, args)
}

fn promise_static_all_keyed(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    invoke_static(ctx, PromiseMethod::AllKeyed, args)
}

fn promise_static_all_settled_keyed(
    ctx: &mut NativeCtx<'_>,
    args: &[Value],
) -> Result<Value, NativeError> {
    invoke_static(ctx, PromiseMethod::AllSettledKeyed, args)
}

fn promise_static_any(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    invoke_static(ctx, PromiseMethod::Any, args)
}

fn promise_static_with_resolvers(
    ctx: &mut NativeCtx<'_>,
    args: &[Value],
) -> Result<Value, NativeError> {
    invoke_static(ctx, PromiseMethod::WithResolvers, args)
}

fn promise_static_try(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    invoke_static(ctx, PromiseMethod::Try, args)
}

fn invoke_static(
    ctx: &mut NativeCtx<'_>,
    method: PromiseMethod,
    args: &[Value],
) -> Result<Value, NativeError> {
    let context = ctx.execution_context().cloned();
    let constructor = Some(*ctx.this_value());
    let (interp, _ignored_ctx) = ctx.interp_mut_and_context();
    promise_dispatch::statics_call(interp, context, constructor, method, args)
}

// ---------------------------------------------------------------
// Prototype method bodies
// ---------------------------------------------------------------

fn promise_proto_then(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    let promise = match ctx.this_value().as_promise() {
        Some(p) => p,
        None => {
            return Err(NativeError::TypeError {
                name: "Promise.prototype.then",
                reason: "`this` is not a Promise".to_string(),
            });
        }
    };
    let context = ctx.execution_context().cloned();
    let (interp, _ignored) = ctx.interp_mut_and_context();
    promise_dispatch::prototype_call(interp, context, &promise, "then", args)
}

/// §27.2.5.1 `Promise.prototype.catch(onRejected)`.
///
/// 1. Let promise be the this value.
/// 2. Return ? Invoke(promise, "then", « undefined, onRejected »).
///
/// No IsPromise check: catch is observably implemented in terms of
/// `.then` and works on any thenable.
///
/// # See also
/// - <https://tc39.es/ecma262/#sec-promise.prototype.catch>
fn promise_proto_catch(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    let this_value = *ctx.this_value();
    let on_rejected = args.first().cloned().unwrap_or(Value::undefined());
    promise_dispatch::invoke_then(ctx, this_value, Value::undefined(), on_rejected)
}

fn promise_proto_finally(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    let this_value = *ctx.this_value();
    let on_finally = args.first().cloned().unwrap_or(Value::undefined());
    promise_dispatch::method_finally_invoke(ctx, this_value, on_finally)
}

// ---------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------

fn oom(name: &'static str) -> NativeError {
    NativeError::TypeError {
        name,
        reason: "out of memory".to_string(),
    }
}

fn vm_err_to_value(err: &VmError, heap: &mut otter_gc::GcHeap) -> Value {
    Value::string(
        crate::JsString::from_str(&err.to_string(), heap).unwrap_or_else(|_| {
            crate::JsString::from_str("", heap).expect("empty string allocates")
        }),
    )
}
