//! ECMA-262 §22.2 RegExp bootstrap installer.
//!
//! Installs the JS-visible `RegExp` constructor + prototype via
//! `couch!`. The prototype carries `exec` / `test` / `toString` /
//! `compile` as own data properties and the spec-mandated accessor
//! getters for `source` / `flags` / `global` / `ignoreCase` /
//! `multiline` / `dotAll` / `unicode` / `sticky` / `hasIndices` /
//! `unicodeSets`. `@@toStringTag` + symbol-keyed protocol methods
//! land in [`install_regexp_well_knowns_post_bootstrap`]. The B.2.4
//! legacy static accessors (`RegExp.input`, `$1`..`$9`, …) run via
//! the `post_install` hook because they capture the ctor identity.
//!
//! # Contents
//! - `Intrinsic` — generated by `couch!`.
//! - [`install_regexp_well_knowns_post_bootstrap`] — symbol fixup.
//!
//! # Invariants
//! - `new RegExp(pattern, flags)` and bare `RegExp(...)` both
//!   produce a fresh RegExp value. Per §22.2.3.1 step 1, when
//!   `pattern` is itself a RegExp and `flags` is `undefined` and
//!   the new-target is the active `RegExp` constructor, the
//!   incoming RegExp is returned unchanged.
//! - Prototype accessor getters throw `TypeError` when `this` is
//!   not a RegExp (exception: `RegExp.prototype` itself returns
//!   `"(?:)"` for `source` and `""` for `flags`).
//! - Legacy static accessor constructors, captures, getters, and setters stay
//!   in one canonical root scope across every paired native allocation.
//!
//! # See also
//! - <https://tc39.es/ecma262/#sec-regexp-constructor>
//! - <https://tc39.es/ecma262/#sec-properties-of-the-regexp-prototype-object>

use crate::js_surface::JsSurfaceError;
use crate::object::{self, JsObject, PropertyDescriptor};
use crate::regexp::{JsRegExp, RegExpFlags};
use crate::rooting::RootScopeExt;
use crate::string::JsString;
use crate::{NativeCtx, NativeError, Value};

otter_macros::couch! {
    name = "RegExp",
    feature = CORE,
    constructor = (length = 2, call = regexp_ctor_call),
    statics = {
        "escape" / 1 => regexp_escape,
    },
    prototype = {
        methods = {
            "exec"     / 1 => proto_exec,
            "test"     / 1 => proto_test,
            "toString" / 0 => proto_to_string,
            "compile"  / 2 => proto_compile,
        },
        accessors = [
            ("source",      get = accessor_source),
            ("flags",       get = accessor_flags),
            ("global",      get = accessor_global),
            ("ignoreCase",  get = accessor_ignore_case),
            ("multiline",   get = accessor_multiline),
            ("dotAll",      get = accessor_dot_all),
            ("unicode",     get = accessor_unicode),
            ("sticky",      get = accessor_sticky),
            ("hasIndices",  get = accessor_has_indices),
            ("unicodeSets", get = accessor_unicode_sets),
        ],
    },
    post_install = install_regexp_legacy_accessors,
}

/// §B.2.4 RegExp legacy static accessors — `RegExp.input`, `$_`,
/// `lastMatch`, `$&`, `lastParen`, `$+`, `leftContext`, `` $` ``,
/// `rightContext`, `$'`, plus `$1`..`$9`. Each is an accessor
/// pair installed on the `%RegExp%` constructor with `[[Enumerable]]
/// = false`, `[[Configurable]] = true`. The getters / setters
/// validate that `this` is `%RegExp%` per `GetLegacyRegExpStaticProperty`
/// / `SetLegacyRegExpStaticProperty` and otherwise return empty
/// strings (we don't yet track per-realm last-match state).
///
/// # See also
/// - <https://tc39.es/ecma262/#sec-additional-properties-of-the-regexp.prototype-object>
fn install_regexp_legacy_accessors(
    heap: &mut otter_gc::GcHeap,
    _global: JsObject,
    ctor: crate::native_function::NativeFunction,
) -> Result<(), JsSurfaceError> {
    use crate::native_function::NativeFunction;

    fn install_get_only(
        heap: &mut otter_gc::GcHeap,
        ctor: Value,
        name: &'static str,
        getter_name: &'static str,
    ) -> Result<(), JsSurfaceError> {
        let mut ctor_root = ctor;
        let mut getter_root = Value::undefined();
        let mut roots = otter_gc::RootScope::new(heap);
        // SAFETY: both canonical slots precede the scope and are reloaded
        // after the getter allocation before descriptor installation.
        unsafe {
            roots.add_value(&mut ctor_root);
            roots.add_value(&mut getter_root);
        }
        let captures: smallvec::SmallVec<[Value; 4]> = smallvec::smallvec![ctor_root];
        getter_root = Value::native_function(
            NativeFunction::with_length_and_captures(
                heap,
                getter_name,
                0,
                legacy_accessor_getter,
                captures,
            )
            .map_err(|_| JsSurfaceError::OutOfMemory)?,
        );
        let ctor = ctor_root
            .as_native_function()
            .expect("RegExp constructor remains rooted");
        let desc = PropertyDescriptor::accessor(Some(getter_root), None, false, true);
        if !ctor.define_own_property(heap, name, desc) {
            return Err(JsSurfaceError::DefinePropertyFailed(name));
        }
        Ok(())
    }

    fn install_get_set(
        heap: &mut otter_gc::GcHeap,
        ctor: Value,
        name: &'static str,
        getter_name: &'static str,
        setter_name: &'static str,
    ) -> Result<(), JsSurfaceError> {
        let mut ctor_root = ctor;
        let mut getter_root = Value::undefined();
        let mut setter_root = Value::undefined();
        let mut roots = otter_gc::RootScope::new(heap);
        // SAFETY: the canonical slots precede the scope and no references to
        // them are retained across the getter/setter allocation safepoints.
        unsafe {
            roots.add_value(&mut ctor_root);
            roots.add_value(&mut getter_root);
            roots.add_value(&mut setter_root);
        }
        let g_captures: smallvec::SmallVec<[Value; 4]> = smallvec::smallvec![ctor_root];
        getter_root = Value::native_function(
            NativeFunction::with_length_and_captures(
                heap,
                getter_name,
                0,
                legacy_accessor_getter,
                g_captures,
            )
            .map_err(|_| JsSurfaceError::OutOfMemory)?,
        );
        let s_captures: smallvec::SmallVec<[Value; 4]> = smallvec::smallvec![ctor_root];
        setter_root = Value::native_function(
            NativeFunction::with_length_and_captures(
                heap,
                setter_name,
                1,
                legacy_accessor_setter,
                s_captures,
            )
            .map_err(|_| JsSurfaceError::OutOfMemory)?,
        );
        let ctor = ctor_root
            .as_native_function()
            .expect("RegExp constructor remains rooted");
        let desc = PropertyDescriptor::accessor(Some(getter_root), Some(setter_root), false, true);
        if !ctor.define_own_property(heap, name, desc) {
            return Err(JsSurfaceError::DefinePropertyFailed(name));
        }
        Ok(())
    }

    let mut ctor_root = Value::native_function(ctor);
    let mut roots = otter_gc::RootScope::new(heap);
    // SAFETY: the constructor slot precedes the scope and stays live until all
    // legacy accessor pairs have been installed.
    unsafe { roots.add_value(&mut ctor_root) };
    install_get_set(heap, ctor_root, "input", "get input", "set input")?;
    install_get_set(heap, ctor_root, "$_", "get $_", "set $_")?;
    install_get_only(heap, ctor_root, "lastMatch", "get lastMatch")?;
    install_get_only(heap, ctor_root, "$&", "get $&")?;
    install_get_only(heap, ctor_root, "lastParen", "get lastParen")?;
    install_get_only(heap, ctor_root, "$+", "get $+")?;
    install_get_only(heap, ctor_root, "leftContext", "get leftContext")?;
    install_get_only(heap, ctor_root, "$`", "get $`")?;
    install_get_only(heap, ctor_root, "rightContext", "get rightContext")?;
    install_get_only(heap, ctor_root, "$'", "get $'")?;
    install_get_only(heap, ctor_root, "$1", "get $1")?;
    install_get_only(heap, ctor_root, "$2", "get $2")?;
    install_get_only(heap, ctor_root, "$3", "get $3")?;
    install_get_only(heap, ctor_root, "$4", "get $4")?;
    install_get_only(heap, ctor_root, "$5", "get $5")?;
    install_get_only(heap, ctor_root, "$6", "get $6")?;
    install_get_only(heap, ctor_root, "$7", "get $7")?;
    install_get_only(heap, ctor_root, "$8", "get $8")?;
    install_get_only(heap, ctor_root, "$9", "get $9")?;
    Ok(())
}

/// §B.2.4.1 `GetLegacyRegExpStaticProperty` — verify `this` is the
/// `%RegExp%` constructor, otherwise raise `TypeError`. We don't yet
/// maintain per-realm last-match state, so the getter returns the
/// empty string (spec-permitted "no prior match" sentinel).
fn legacy_accessor_getter(
    ctx: &mut NativeCtx<'_>,
    _args: &[Value],
    captures: &[Value],
) -> Result<Value, NativeError> {
    let this_value = *ctx.this_value();
    let ctor = captures.first().cloned().unwrap_or(Value::undefined());
    if !values_strict_equal(&this_value, &ctor) {
        return Err(NativeError::TypeError {
            name: "RegExp legacy accessor",
            reason: "Method called on incompatible receiver".to_string(),
        });
    }
    Ok(Value::string(
        JsString::from_str("", ctx.heap_mut()).map_err(|_| NativeError::TypeError {
            name: "RegExp legacy accessor",
            reason: "out of memory".to_string(),
        })?,
    ))
}

/// §B.2.4.2 `SetLegacyRegExpStaticProperty` — accepts the assignment
/// only when `this` is `%RegExp%`, otherwise raises `TypeError`. We
/// drop the value because per-realm last-match storage isn't yet
/// implemented; this satisfies the spec-mandated receiver check and
/// the prop-desc tests that observe the setter shape.
fn legacy_accessor_setter(
    ctx: &mut NativeCtx<'_>,
    _args: &[Value],
    captures: &[Value],
) -> Result<Value, NativeError> {
    let this_value = *ctx.this_value();
    let ctor = captures.first().cloned().unwrap_or(Value::undefined());
    if !values_strict_equal(&this_value, &ctor) {
        return Err(NativeError::TypeError {
            name: "RegExp legacy accessor",
            reason: "Method called on incompatible receiver".to_string(),
        });
    }
    Ok(Value::undefined())
}

fn values_strict_equal(a: &Value, b: &Value) -> bool {
    match (a.as_native_function(), b.as_native_function()) {
        (Some(x), Some(y)) => x.ptr_eq(&y),
        _ => false,
    }
}

/// Install `@@toStringTag` (no longer set on every RegExp — it
/// lives on the prototype) and the Symbol-keyed methods
/// (`@@match`, `@@replace`, `@@search`, `@@split`, `@@matchAll`).
pub fn install_regexp_well_knowns_post_bootstrap(
    heap: &mut otter_gc::GcHeap,
    global: JsObject,
    well_known: &crate::symbol::WellKnownSymbols,
) -> Result<(), JsSurfaceError> {
    use crate::symbol::WellKnown;

    let Some(ctor) = object::get(global, heap, "RegExp").and_then(|v| v.as_native_function())
    else {
        return Ok(());
    };
    let descriptor = ctor
        .own_property_descriptor(heap, "prototype")
        .map_err(|_| JsSurfaceError::OutOfMemory)?;
    let prototype = match descriptor.and_then(|d| match d.kind {
        crate::object::DescriptorKind::Data { value } => value.as_object(),
        _ => None,
    }) {
        Some(p) => p,
        None => return Ok(()),
    };
    // §22.2.6.{8,10,11} `RegExp.prototype[@@match]` /
    // `RegExp.prototype[@@search]` / `RegExp.prototype[@@replace]` —
    // install native functions so user calls like
    // `re[Symbol.match]("…")` resolve through the spec-mandated
    // algorithm.
    let mut prototype_root = Value::object(prototype);
    let mut match_root = Value::undefined();
    let mut search_root = Value::undefined();
    let mut replace_root = Value::undefined();
    let mut split_root = Value::undefined();
    let mut match_all_root = Value::undefined();
    let mut roots = otter_gc::RootScope::new(heap);
    // SAFETY: all canonical slots precede the scope and remain stationary until
    // every native is allocated and installed on the prototype.
    unsafe {
        roots.add_value(&mut prototype_root);
        roots.add_value(&mut match_root);
        roots.add_value(&mut search_root);
        roots.add_value(&mut replace_root);
        roots.add_value(&mut split_root);
        roots.add_value(&mut match_all_root);
    }
    let match_sym = well_known.get(WellKnown::Match);
    let search_sym = well_known.get(WellKnown::Search);
    let replace_sym = well_known.get(WellKnown::Replace);
    let split_sym = well_known.get(WellKnown::Split);
    let match_all_sym = well_known.get(WellKnown::MatchAll);
    match_root = Value::native_function(
        crate::bootstrap::native_static_with_value_roots(
            heap,
            "[Symbol.match]",
            1,
            crate::regexp_prototype::native_regexp_symbol_match,
            &[],
        )
        .map_err(|_| JsSurfaceError::OutOfMemory)?,
    );
    search_root = Value::native_function(
        crate::bootstrap::native_static_with_value_roots(
            heap,
            "[Symbol.search]",
            1,
            crate::regexp_prototype::native_regexp_symbol_search,
            &[],
        )
        .map_err(|_| JsSurfaceError::OutOfMemory)?,
    );
    replace_root = Value::native_function(
        crate::bootstrap::native_static_with_value_roots(
            heap,
            "[Symbol.replace]",
            2,
            crate::regexp_prototype::native_regexp_symbol_replace,
            &[],
        )
        .map_err(|_| JsSurfaceError::OutOfMemory)?,
    );
    split_root = Value::native_function(
        crate::bootstrap::native_static_with_value_roots(
            heap,
            "[Symbol.split]",
            2,
            crate::regexp_prototype::native_regexp_symbol_split,
            &[],
        )
        .map_err(|_| JsSurfaceError::OutOfMemory)?,
    );
    match_all_root = Value::native_function(
        crate::bootstrap::native_static_with_value_roots(
            heap,
            "[Symbol.matchAll]",
            1,
            crate::regexp_prototype::native_regexp_symbol_match_all,
            &[],
        )
        .map_err(|_| JsSurfaceError::OutOfMemory)?,
    );
    let prototype = prototype_root
        .as_object()
        .expect("RegExp.prototype remains rooted during symbol bootstrap");
    object::define_own_symbol_property_partial(
        prototype,
        heap,
        match_sym,
        crate::object::PartialPropertyDescriptor {
            value: Some(match_root),
            writable: Some(true),
            enumerable: Some(false),
            configurable: Some(true),
            ..Default::default()
        },
    );
    object::define_own_symbol_property_partial(
        prototype,
        heap,
        search_sym,
        crate::object::PartialPropertyDescriptor {
            value: Some(search_root),
            writable: Some(true),
            enumerable: Some(false),
            configurable: Some(true),
            ..Default::default()
        },
    );
    object::define_own_symbol_property_partial(
        prototype,
        heap,
        replace_sym,
        crate::object::PartialPropertyDescriptor {
            value: Some(replace_root),
            writable: Some(true),
            enumerable: Some(false),
            configurable: Some(true),
            ..Default::default()
        },
    );
    object::define_own_symbol_property_partial(
        prototype,
        heap,
        split_sym,
        crate::object::PartialPropertyDescriptor {
            value: Some(split_root),
            writable: Some(true),
            enumerable: Some(false),
            configurable: Some(true),
            ..Default::default()
        },
    );
    object::define_own_symbol_property_partial(
        prototype,
        heap,
        match_all_sym,
        crate::object::PartialPropertyDescriptor {
            value: Some(match_all_root),
            writable: Some(true),
            enumerable: Some(false),
            configurable: Some(true),
            ..Default::default()
        },
    );
    Ok(())
}

// ---------------------------------------------------------------
// RegExp.escape (sec-regexp.escape)
// ---------------------------------------------------------------

/// `c` is one of the RegExp `SyntaxCharacter`s (`^ $ \ . * + ? ( ) [ ] { } |`).
fn is_regexp_syntax_character(c: u32) -> bool {
    matches!(
        c,
        0x5E | 0x24
            | 0x5C
            | 0x2E
            | 0x2A
            | 0x2B
            | 0x3F
            | 0x28
            | 0x29
            | 0x5B
            | 0x5D
            | 0x7B
            | 0x7D
            | 0x7C
    )
}

/// `c` is in the `RegExp.escape` "other punctuators" set
/// `,-=<>#&!%:;@~'`` plus U+0022 QUOTATION MARK.
fn is_regexp_escape_other_punctuator(c: u32) -> bool {
    matches!(
        c,
        0x2C | 0x2D
            | 0x3D
            | 0x3C
            | 0x3E
            | 0x23
            | 0x26
            | 0x21
            | 0x25
            | 0x3A
            | 0x3B
            | 0x40
            | 0x7E
            | 0x27
            | 0x60
            | 0x22
    )
}

/// `c` is matched by `WhiteSpace` or `LineTerminator` (§12.2 / §12.3),
/// excluding the entries already covered by the `ControlEscape` table
/// (`\t \n \v \f \r`).
fn is_regexp_escape_space(c: u32) -> bool {
    matches!(
        c,
        0x20 | 0xA0 | 0xFEFF              // SPACE, NBSP, ZWNBSP
        | 0x1680                          // OGHAM SPACE MARK
        | 0x2000
            ..=0x200A                 // EN QUAD .. HAIR SPACE
        | 0x2028 | 0x2029                 // LINE / PARAGRAPH SEPARATOR
        | 0x202F | 0x205F | 0x3000 // NNBSP, MMSP, IDEOGRAPHIC SPACE
    )
}

/// EncodeForRegExpEscape(c) — append the escape (or the code point
/// verbatim) for a single code point.
fn encode_for_regexp_escape(c: u32, out: &mut String) {
    if is_regexp_syntax_character(c) || c == 0x2F {
        out.push('\\');
        if let Some(ch) = char::from_u32(c) {
            out.push(ch);
        }
        return;
    }
    match c {
        0x09 => out.push_str("\\t"),
        0x0A => out.push_str("\\n"),
        0x0B => out.push_str("\\v"),
        0x0C => out.push_str("\\f"),
        0x0D => out.push_str("\\r"),
        _ if is_regexp_escape_other_punctuator(c)
            || is_regexp_escape_space(c)
            || (0xD800..=0xDFFF).contains(&c) =>
        {
            // Hex escape: `\xHH` for ≤ 0xFF, `\uHHHH` otherwise (all
            // such code points are in the BMP).
            if c <= 0xFF {
                out.push_str(&format!("\\x{c:02x}"));
            } else {
                out.push_str(&format!("\\u{c:04x}"));
            }
        }
        _ => {
            // Verbatim. Lone surrogates are handled above, so every
            // code point reaching here is a Unicode scalar value.
            if let Some(ch) = char::from_u32(c) {
                out.push(ch);
            }
        }
    }
}

/// §22.2.5.2 `RegExp.escape(S)` — escape `S` so it matches itself
/// literally when used as a RegExp pattern.
fn regexp_escape(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    let arg = args.first().copied().unwrap_or_else(Value::undefined);
    // step 1 — S must be a String (no coercion).
    let Some(s) = (if arg.is_string() {
        arg.as_string(ctx.heap())
    } else {
        None
    }) else {
        return Err(NativeError::TypeError {
            name: "RegExp.escape",
            reason: "argument must be a string".to_string(),
        });
    };
    let units = s.to_utf16_vec(ctx.heap());
    let mut escaped = String::with_capacity(units.len());
    let mut first = true;
    let mut i = 0usize;
    while i < units.len() {
        // StringToCodePoints — combine a valid surrogate pair, else
        // take the lone code unit as its own code point.
        let unit = units[i];
        let code_point = if (0xD800..=0xDBFF).contains(&unit)
            && i + 1 < units.len()
            && (0xDC00..=0xDFFF).contains(&units[i + 1])
        {
            let cp = 0x10000 + (((unit as u32 - 0xD800) << 10) | (units[i + 1] as u32 - 0xDC00));
            i += 2;
            cp
        } else {
            i += 1;
            unit as u32
        };
        if first && matches!(code_point, 0x30..=0x39 | 0x41..=0x5A | 0x61..=0x7A) {
            // step 4.a — a leading ASCII letter or digit is hex-escaped
            // so the output cannot extend a preceding `\0` / `\1` /
            // `\c` escape in concatenated patterns.
            escaped.push_str(&format!("\\x{code_point:02x}"));
        } else {
            encode_for_regexp_escape(code_point, &mut escaped);
        }
        first = false;
    }
    let result =
        JsString::from_str(&escaped, ctx.heap_mut()).map_err(|err| NativeError::TypeError {
            name: "RegExp.escape",
            reason: err.to_string(),
        })?;
    Ok(Value::string(result))
}

// ---------------------------------------------------------------
// Constructor body
// ---------------------------------------------------------------

/// §22.2.3.1 RegExp(pattern, flags).
fn regexp_ctor_call(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    ctx.scope(|mut scope| {
        let pattern = scope.argument(args, 0);
        let flags = scope.argument(args, 1);
        let pattern_value = scope.raw(pattern);
        let pattern_is_regexp = is_regexp_runtime(scope.context(), &pattern_value, "RegExp")?;

        // §22.2.3.1 steps 3-4 — every observable IsRegExp/constructor
        // lookup runs with both arguments parked in the handle arena.
        if pattern_is_regexp && scope.is_undefined(flags) && !scope.context().is_construct_call() {
            let pattern_value = scope.raw(pattern);
            if regexp_constructor_matches(scope.context(), &pattern_value)? {
                return Ok(scope.finish(pattern));
            }
        }

        let pattern_source = if pattern_is_regexp {
            let pattern_value = scope.raw(pattern);
            let source = crate::regexp_prototype::get_property_runtime(
                scope.context(),
                &pattern_value,
                "source",
                "RegExp",
            )?;
            scope.value(source)
        } else {
            pattern
        };
        let flags_value = if pattern_is_regexp && scope.is_undefined(flags) {
            let pattern_value = scope.raw(pattern);
            let flags = crate::regexp_prototype::get_property_runtime(
                scope.context(),
                &pattern_value,
                "flags",
                "RegExp",
            )?;
            scope.value(flags)
        } else {
            flags
        };

        // Coercing flags can run arbitrary JS after source coercion. Keep the
        // source string as a Local and copy its units only after both ladders
        // complete.
        let pattern_string = if scope.is_undefined(pattern_source) {
            None
        } else {
            let source = scope.raw(pattern_source);
            let source = crate::regexp_prototype::coerce_to_jsstring_runtime(
                scope.context(),
                &source,
                "RegExp",
            )?;
            Some(scope.value(Value::string(source)))
        };
        let flags_string = if scope.is_undefined(flags_value) {
            None
        } else {
            let flags = scope.raw(flags_value);
            let flags = crate::regexp_prototype::coerce_to_jsstring_runtime(
                scope.context(),
                &flags,
                "RegExp",
            )?;
            Some(scope.value(Value::string(flags)))
        };
        let pattern_utf16 = match pattern_string {
            Some(pattern) => scope
                .raw(pattern)
                .as_string(scope.context().heap())
                .ok_or_else(|| oom("RegExp"))?
                .to_utf16_vec(scope.context().heap()),
            None => Vec::new(),
        };
        let flags_text = match flags_string {
            Some(flags) => scope
                .raw(flags)
                .as_string(scope.context().heap())
                .ok_or_else(|| oom("RegExp"))?
                .to_lossy_string(scope.context().heap()),
            None => String::new(),
        };

        let re = scope
            .with_turn_parts(|interp, _| {
                JsRegExp::compile_cached(
                    &mut interp.gc_heap,
                    &mut interp.regex_compile_cache,
                    &pattern_utf16,
                    &flags_text,
                )
            })
            .map_err(|error| NativeError::SyntaxError {
                name: "RegExp",
                reason: format!("{error}"),
            })?;
        let re = scope.value(Value::regexp(re));

        // `GetPrototypeFromConstructor(newTarget, ...)` is observable for a
        // Proxy new.target. Root the freshly compiled RegExp before entering
        // that lookup and resolve both handles again afterwards.
        if let Some(prototype) =
            crate::bootstrap::native_new_target_prototype(scope.context(), "RegExp")?
        {
            let prototype = scope.value(prototype);
            let re_value = scope.raw(re);
            let re_handle = re_value.as_regexp().ok_or_else(|| oom("RegExp"))?;
            let prototype = scope.raw(prototype);
            re_handle.set_prototype_override(scope.context().heap_mut(), Some(prototype));
        }
        Ok(scope.finish(re))
    })
}

fn is_regexp_runtime(
    ctx: &mut NativeCtx<'_>,
    value: &Value,
    name: &'static str,
) -> Result<bool, NativeError> {
    if !value.is_object_type() {
        return Ok(false);
    }
    let match_sym = ctx
        .cx
        .interp
        .well_known_symbols()
        .get(crate::symbol::WellKnown::Match);
    let matcher =
        crate::regexp_prototype::get_symbol_property_runtime(ctx, value, match_sym, name)?;
    if !matcher.is_undefined() {
        return Ok(matcher.to_boolean(ctx.heap()));
    }
    Ok(value.is_regexp())
}

fn regexp_constructor_matches(
    ctx: &mut NativeCtx<'_>,
    pattern: &Value,
) -> Result<bool, NativeError> {
    let pattern_ctor =
        crate::regexp_prototype::get_property_runtime(ctx, pattern, "constructor", "RegExp")?;
    let regexp_ctor = object::get(*ctx.cx.interp.global_this(), ctx.heap(), "RegExp")
        .unwrap_or(Value::undefined());
    Ok(values_strict_equal(&pattern_ctor, &regexp_ctor))
}

// ---------------------------------------------------------------
// Prototype method bodies (delegate to existing intrinsic impls)
// ---------------------------------------------------------------

pub(crate) fn proto_exec(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    ctx.scope(|mut scope| {
        let receiver = scope.this();
        if scope.raw(receiver).as_regexp().is_none() {
            return Err(NativeError::TypeError {
                name: "RegExp.prototype.exec",
                reason: "this is not a RegExp".to_string(),
            });
        }
        let input = scope.argument(args, 0);
        let input_value = scope.raw(input);
        let input = coerce_to_string(scope.context(), &input_value, "RegExp.prototype.exec")?;
        let input = scope.value(Value::string(input));
        let receiver_value = scope.raw(receiver);
        let input_value = scope.raw(input);
        let input = input_value
            .as_string(scope.context().heap())
            .ok_or_else(|| oom("RegExp.prototype.exec"))?;
        let result =
            crate::regexp_prototype::exec_once_native(&receiver_value, input, scope.context())?;
        let result = scope.value(result);
        Ok(scope.finish(result))
    })
}

fn proto_test(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    // §22.2.6.16 — `this` need only be an Object; the match runs through
    // the abstract RegExpExec, which dispatches on the `exec` property,
    // so a non-RegExp object carrying its own `exec` is honoured.
    ctx.scope(|mut scope| {
        let receiver = scope.this();
        if !scope.raw(receiver).is_object_type() {
            return Err(NativeError::TypeError {
                name: "RegExp.prototype.test",
                reason: "receiver is not an object".to_string(),
            });
        }
        let input = scope.argument(args, 0);
        let input_value = scope.raw(input);
        let input = coerce_to_string(scope.context(), &input_value, "RegExp.prototype.test")?;
        let input = scope.value(Value::string(input));
        let receiver_value = scope.raw(receiver);
        let input_value = scope.raw(input);
        let input = input_value
            .as_string(scope.context().heap())
            .ok_or_else(|| oom("RegExp.prototype.test"))?;
        let result = crate::regexp_prototype::regexp_exec_runtime(
            scope.context(),
            &receiver_value,
            input,
            "RegExp.prototype.test",
        )?;
        Ok(Value::boolean(!result.is_null()))
    })
}

/// §B.2.4.1 `RegExp.prototype.compile(pattern, flags)` — native
/// surface shared by direct calls, `Function.prototype.call`, and
/// property reads.
fn proto_compile(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    ctx.scope(|mut scope| {
        const NAME: &str = "RegExp.prototype.compile";
        let receiver = scope.this();
        let re = scope
            .raw(receiver)
            .as_regexp()
            .ok_or_else(|| NativeError::TypeError {
                name: NAME,
                reason: "this is not a RegExp".to_string(),
            })?;
        // §B.2.4.1 — `compile` only rejects a subclass instance.
        let default_proto = scope
            .context()
            .interp_mut()
            .realm_intrinsics()
            .regexp_prototype;
        if let Some(prototype) = re.prototype_override(scope.context().heap())
            && prototype.as_object() != default_proto
        {
            return Err(NativeError::TypeError {
                name: NAME,
                reason: "cannot compile a RegExp subclass instance".to_string(),
            });
        }

        let pattern = scope.argument(args, 0);
        let flags = scope.argument(args, 1);
        let (pattern_units, flags_text) = if let Some(other) = scope.raw(pattern).as_regexp() {
            if !scope.is_undefined(flags) {
                return Err(NativeError::TypeError {
                    name: NAME,
                    reason: "Cannot supply flags when constructing one RegExp from another"
                        .to_string(),
                });
            }
            let heap = scope.context().heap();
            (other.pattern_utf16(heap), other.flags(heap).to_js_string())
        } else if scope.is_undefined(pattern) {
            let flags_value = scope.raw(flags);
            (
                Vec::<u16>::new(),
                compile_flags_to_string(scope.context(), &flags_value)?,
            )
        } else {
            let pattern_value = scope.raw(pattern);
            let pattern_string = crate::regexp_prototype::coerce_to_jsstring_runtime(
                scope.context(),
                &pattern_value,
                NAME,
            )?;
            let pattern_string = scope.value(Value::string(pattern_string));
            let flags_value = scope.raw(flags);
            let flags_text = compile_flags_to_string(scope.context(), &flags_value)?;
            let pattern_value = scope.raw(pattern_string);
            let pattern = pattern_value
                .as_string(scope.context().heap())
                .ok_or_else(|| oom(NAME))?;
            (pattern.to_utf16_vec(scope.context().heap()), flags_text)
        };

        // Re-read the receiver after both user coercions. Preserve an arbitrary
        // object-valued lastIndex in a Local across the reinitialization
        // allocation, then restore that relocated value on the non-writable
        // failure path.
        let re = scope.raw(receiver).as_regexp().ok_or_else(|| oom(NAME))?;
        let old_last_index = re.last_index_value(scope.context().heap());
        let old_last_index = scope.value(old_last_index);
        re.reinitialize(scope.context().heap_mut(), &pattern_units, &flags_text)
            .map_err(regexp_error_to_syntax_error)?;
        let re = scope.raw(receiver).as_regexp().ok_or_else(|| oom(NAME))?;
        if !re.last_index_writable(scope.context().heap()) {
            let old_last_index = scope.raw(old_last_index);
            re.set_last_index_value(scope.context().heap_mut(), old_last_index);
            return Err(NativeError::TypeError {
                name: NAME,
                reason: "Cannot assign to read only property 'lastIndex'".to_string(),
            });
        }
        Ok(scope.finish(receiver))
    })
}

fn compile_flags_to_string(ctx: &mut NativeCtx<'_>, value: &Value) -> Result<String, NativeError> {
    if value.is_undefined() {
        return Ok(String::new());
    }
    Ok(
        crate::regexp_prototype::coerce_to_jsstring_runtime(
            ctx,
            value,
            "RegExp.prototype.compile",
        )?
        .to_lossy_string(ctx.heap()),
    )
}

fn regexp_error_to_syntax_error(err: crate::regexp::RegExpError) -> NativeError {
    NativeError::SyntaxError {
        name: "RegExp.prototype.compile",
        reason: match err {
            crate::regexp::RegExpError::InvalidPattern { message } => {
                format!("invalid regular expression: {message}")
            }
            crate::regexp::RegExpError::InvalidFlag { flag } => {
                format!("invalid regular expression flag `{flag}`")
            }
            crate::regexp::RegExpError::DuplicateFlag { flag } => {
                format!("duplicate regular expression flag `{flag}`")
            }
            crate::regexp::RegExpError::OutOfMemory => "out of memory".to_string(),
        },
    }
}

fn proto_to_string(ctx: &mut NativeCtx<'_>, _args: &[Value]) -> Result<Value, NativeError> {
    // §22.2.6.13 — generic over any object receiver: read `source` and
    // `flags` through `[[Get]]` (firing accessors / Proxy traps) and
    // `ToString` each, rather than requiring a real RegExp. A real
    // RegExp resolves its own `source` / `flags` accessor getters, and
    // `%RegExp.prototype%` yields the `"(?:)"` / `""` sentinels.
    const NAME: &str = "RegExp.prototype.toString";
    ctx.scope(|mut scope| {
        let receiver = scope.this();
        if !scope.raw(receiver).is_object_type() {
            return Err(NativeError::TypeError {
                name: NAME,
                reason: "this value must be an Object".to_string(),
            });
        }
        let receiver_value = scope.raw(receiver);
        let source = crate::regexp_prototype::get_property_runtime(
            scope.context(),
            &receiver_value,
            "source",
            NAME,
        )?;
        let source = scope.value(source);
        let source_value = scope.raw(source);
        let pattern = crate::regexp_prototype::coerce_to_jsstring_runtime(
            scope.context(),
            &source_value,
            NAME,
        )?;
        let pattern = scope.value(Value::string(pattern));

        let receiver_value = scope.raw(receiver);
        let flags = crate::regexp_prototype::get_property_runtime(
            scope.context(),
            &receiver_value,
            "flags",
            NAME,
        )?;
        let flags = scope.value(flags);
        let flags_value = scope.raw(flags);
        let flags = crate::regexp_prototype::coerce_to_jsstring_runtime(
            scope.context(),
            &flags_value,
            NAME,
        )?;
        let flags = scope.value(Value::string(flags));

        // Copy from the relocated Local slots only after both observable
        // ladders complete.
        let pattern_value = scope.raw(pattern);
        let pattern = pattern_value
            .as_string(scope.context().heap())
            .ok_or_else(|| oom(NAME))?;
        let pattern_units = pattern.to_utf16_vec(scope.context().heap());
        let flags_value = scope.raw(flags);
        let flags = flags_value
            .as_string(scope.context().heap())
            .ok_or_else(|| oom(NAME))?;
        let flag_units = flags.to_utf16_vec(scope.context().heap());
        let mut rendered = Vec::with_capacity(pattern_units.len() + flag_units.len() + 2);
        rendered.push(b'/' as u16);
        rendered.extend_from_slice(&pattern_units);
        rendered.push(b'/' as u16);
        rendered.extend_from_slice(&flag_units);

        let rendered = JsString::from_utf16_units(&rendered, scope.context().heap_mut())
            .map_err(|_| oom(NAME))?;
        let rendered = scope.value(Value::string(rendered));
        Ok(scope.finish(rendered))
    })
}

// ---------------------------------------------------------------
// Prototype accessors
// ---------------------------------------------------------------

/// §22.2.6.10 `get RegExp.prototype.source`. When `this` is the
/// realm's `%RegExp.prototype%` (no `[[OriginalSource]]` slot)
/// returns the sentinel `"(?:)"`; non-RegExp non-prototype
/// receivers throw `TypeError`. Otherwise emits the spec's
/// `EscapeRegExpPattern(src, flags)`.
fn accessor_source(ctx: &mut NativeCtx<'_>, _args: &[Value]) -> Result<Value, NativeError> {
    let receiver = *ctx.this_value();

    let raw_units = if let Some(re) = receiver.as_regexp() {
        re.pattern_utf16(ctx.heap())
    } else if let Some(obj) = receiver.as_object() {
        let is_proto = ctx
            .interp_mut()
            .constructor_prototype_value("RegExp")
            .ok()
            .and_then(|p| p.as_object())
            .is_some_and(|p| p == obj);
        if !is_proto {
            return Err(NativeError::TypeError {
                name: "get RegExp.prototype.source",
                reason: "this is not a RegExp".to_string(),
            });
        }
        return Ok(Value::string(
            JsString::from_str("(?:)", ctx.heap_mut()).map_err(|_| oom("source"))?,
        ));
    } else {
        return Err(NativeError::TypeError {
            name: "get RegExp.prototype.source",
            reason: "this is not a RegExp".to_string(),
        });
    };
    let escaped = crate::regexp_prototype::escape_regexp_pattern_utf16(&raw_units);
    Ok(Value::string(
        JsString::from_utf16_units(&escaped, ctx.heap_mut()).map_err(|_| oom("source"))?,
    ))
}

/// §22.2.6.4 `get RegExp.prototype.flags`. Generic over any
/// receiver: reads each flag property via `[[Get]]`, applies
/// `ToBoolean`, and concatenates the flag letter when truthy.
/// Spec order is `d g i m s u v y`.
fn accessor_flags(ctx: &mut NativeCtx<'_>, _args: &[Value]) -> Result<Value, NativeError> {
    const NAME: &str = "get RegExp.prototype.flags";
    ctx.scope(|mut scope| {
        let receiver = scope.this();
        if !scope.raw(receiver).is_object_type() {
            return Err(NativeError::TypeError {
                name: NAME,
                reason: "this value must be an Object".to_string(),
            });
        }
        let mut out = String::with_capacity(8);
        for &(property, letter) in &[
            ("hasIndices", 'd'),
            ("global", 'g'),
            ("ignoreCase", 'i'),
            ("multiline", 'm'),
            ("dotAll", 's'),
            ("unicode", 'u'),
            ("unicodeSets", 'v'),
            ("sticky", 'y'),
        ] {
            let receiver_value = scope.raw(receiver);
            let value = crate::regexp_prototype::get_property_runtime(
                scope.context(),
                &receiver_value,
                property,
                NAME,
            )?;
            let value = scope.value(value);
            if scope.raw(value).to_boolean(scope.context().heap()) {
                out.push(letter);
            }
        }
        let flags = JsString::from_str(&out, scope.context().heap_mut()).map_err(|_| oom(NAME))?;
        let flags = scope.value(Value::string(flags));
        Ok(scope.finish(flags))
    })
}

fn accessor_global(ctx: &mut NativeCtx<'_>, _args: &[Value]) -> Result<Value, NativeError> {
    flag_bool(ctx, "get RegExp.prototype.global", |f| f.global)
}

fn accessor_ignore_case(ctx: &mut NativeCtx<'_>, _args: &[Value]) -> Result<Value, NativeError> {
    flag_bool(ctx, "get RegExp.prototype.ignoreCase", |f| f.ignore_case)
}

fn accessor_multiline(ctx: &mut NativeCtx<'_>, _args: &[Value]) -> Result<Value, NativeError> {
    flag_bool(ctx, "get RegExp.prototype.multiline", |f| f.multiline)
}

fn accessor_dot_all(ctx: &mut NativeCtx<'_>, _args: &[Value]) -> Result<Value, NativeError> {
    flag_bool(ctx, "get RegExp.prototype.dotAll", |f| f.dot_all)
}

fn accessor_unicode(ctx: &mut NativeCtx<'_>, _args: &[Value]) -> Result<Value, NativeError> {
    flag_bool(ctx, "get RegExp.prototype.unicode", |f| f.unicode)
}

fn accessor_sticky(ctx: &mut NativeCtx<'_>, _args: &[Value]) -> Result<Value, NativeError> {
    flag_bool(ctx, "get RegExp.prototype.sticky", |f| f.sticky)
}

fn accessor_has_indices(ctx: &mut NativeCtx<'_>, _args: &[Value]) -> Result<Value, NativeError> {
    flag_bool(ctx, "get RegExp.prototype.hasIndices", |f| f.has_indices)
}

fn accessor_unicode_sets(ctx: &mut NativeCtx<'_>, _args: &[Value]) -> Result<Value, NativeError> {
    flag_bool(ctx, "get RegExp.prototype.unicodeSets", |f| f.unicode_sets)
}

fn flag_bool(
    ctx: &mut NativeCtx<'_>,
    name: &'static str,
    f: impl FnOnce(&RegExpFlags) -> bool,
) -> Result<Value, NativeError> {
    // §22.2.6.x step 3a: a non-RegExp `this` that is the prototype object
    // itself yields `undefined` (so `RegExp.prototype.flags` reads ""), only
    // any other object without an [[OriginalFlags]] slot throws.
    let Some(re) = ctx.this_value().as_regexp() else {
        if this_is_regexp_prototype(ctx) {
            return Ok(Value::undefined());
        }
        return Err(NativeError::TypeError {
            name,
            reason: "this is not a RegExp".to_string(),
        });
    };
    let flags = re.flags(ctx.heap());
    Ok(Value::boolean(f(&flags)))
}

/// SameValue(this, %RegExp.prototype%) — used by the flag accessors to
/// distinguish the prototype object from an arbitrary non-RegExp receiver.
fn this_is_regexp_prototype(ctx: &mut NativeCtx<'_>) -> bool {
    let Some(this_obj) = ctx.this_value().as_object() else {
        return false;
    };
    matches!(
        ctx.interp_mut().realm_intrinsics().regexp_prototype,
        Some(proto) if proto == this_obj
    )
}

// ---------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------

fn coerce_to_string(
    ctx: &mut NativeCtx<'_>,
    v: &Value,
    name: &'static str,
) -> Result<JsString, NativeError> {
    crate::regexp_prototype::coerce_to_jsstring_runtime(ctx, v, name)
}

fn oom(name: &'static str) -> NativeError {
    NativeError::TypeError {
        name,
        reason: "out of memory".to_string(),
    }
}
