//! ECMA-262 §25.1 ArrayBuffer bootstrap installer.
//!
//! Replaces the placeholder with a real callable + constructible
//! `NativeFunction`. Statics: `isView`. Prototype: `slice` +
//! `resize` + `transfer` + `transferToFixedLength`, plus accessor
//! getters for `byteLength`, `maxByteLength`, `resizable`,
//! `detached`.
//!
//! Prototype methods delegate to
//! [`crate::binary::array_buffer_prototype`] native helpers.
//!
//! # See also
//! - <https://tc39.es/ecma262/#sec-arraybuffer-constructor>
//! - <https://tc39.es/ecma262/#sec-properties-of-the-arraybuffer-prototype-object>

use otter_bytecode::method_id::{ArrayBufferMethod, SharedArrayBufferMethod};

use crate::abstract_ops::{self, ToPrimitiveHint};
use crate::binary::dispatch;
use crate::js_surface::JsSurfaceError;
use crate::object::{self, JsObject, PartialPropertyDescriptor};
use crate::{NativeCtx, NativeError, Value, VmError};

/// §7.1.5 `ToIntegerOrInfinity(value)` with an observable
/// `ToPrimitive` (number hint): object arguments route through
/// `valueOf` / `toString` / `@@toPrimitive` so user callbacks fire,
/// and `Symbol` / `BigInt` surface a `TypeError` per §7.1.4 ToNumber.
/// `resize` / `grow` apply their own `RangeError` bounds afterwards.
fn coerce_length_integer(
    ctx: &mut NativeCtx<'_>,
    value: &Value,
    name: &'static str,
) -> Result<f64, NativeError> {
    let primitive = if abstract_ops::is_primitive(value) {
        *value
    } else {
        let (interp, exec) = ctx.interp_mut_and_context();
        let exec = exec.ok_or(NativeError::TypeError {
            name,
            reason: "missing execution context for ToPrimitive".to_string(),
        })?;
        interp
            .evaluate_to_primitive(&exec, value, ToPrimitiveHint::Number)
            .map_err(|e| match e {
                VmError::Uncaught { value } => NativeError::Thrown {
                    name,
                    message: value,
                },
                other => NativeError::TypeError {
                    name,
                    reason: other.to_string(),
                },
            })?
    };
    if primitive.is_symbol() {
        return Err(NativeError::TypeError {
            name,
            reason: "cannot convert a Symbol to a number".to_string(),
        });
    }
    if primitive.is_big_int() {
        return Err(NativeError::TypeError {
            name,
            reason: "cannot convert a BigInt to a number".to_string(),
        });
    }
    Ok(crate::number::parse::to_integer_or_infinity(
        &primitive,
        ctx.heap(),
    ))
}

/// §7.1.22 `ToIndex(value)` with an observable `ToPrimitive`. Out-of-range
/// (negative or `> 2^53 - 1`, including `±∞`) surfaces a `RangeError`,
/// matching `transfer` / `transferToFixedLength`'s clamping semantics.
fn coerce_index(
    ctx: &mut NativeCtx<'_>,
    value: &Value,
    name: &'static str,
) -> Result<usize, NativeError> {
    let n = coerce_length_integer(ctx, value, name)?;
    if !(0.0..=9_007_199_254_740_991.0).contains(&n) {
        return Err(NativeError::RangeError {
            name,
            reason: "length out of range [0, 2^53 - 1]".to_string(),
        });
    }
    Ok(n as usize)
}

// `ARRAYBUFFER_SPEC` + `ArrayBufferIntrinsic` generated by `couch!`.
// §25.1 — prototype chains to %Object.prototype% by couch! default;
// constructor back-pointer auto-installed.
otter_macros::couch! {
    name = "ArrayBuffer",
    feature = CORE,
    intrinsic = ArrayBufferIntrinsic,
    constructor = (length = 1, call = ab_ctor_call),
    statics = {
        "isView" / 1 => ab_is_view,
    },
    prototype = {
        methods = {
            "slice"                 / 2 => ab_slice,
            "resize"                / 1 => ab_resize,
            "transfer"              / 0 => ab_transfer,
            "transferToFixedLength" / 0 => ab_transfer_to_fixed_length,
        },
        accessors = [
            ("byteLength",    get = ab_byte_length),
            ("maxByteLength", get = ab_max_byte_length),
            ("resizable",     get = ab_resizable),
            ("detached",      get = ab_detached),
        ],
    },
}

// `SHAREDARRAYBUFFER_SPEC` + `SharedArrayBufferIntrinsic` generated
// by `couch!`. §25.2 — shares the `JsArrayBuffer` substrate with
// `ArrayBuffer`; `is_shared` distinguishes the two value-side.
// `transfer` / `transferToFixedLength` belong to ArrayBuffer only.
otter_macros::couch! {
    name = "SharedArrayBuffer",
    feature = CORE,
    intrinsic = SharedArrayBufferIntrinsic,
    constructor = (length = 1, call = sab_ctor_call),
    prototype = {
        methods = {
            "slice" / 2 => sab_slice,
            "grow"  / 1 => sab_grow,
        },
        accessors = [
            ("byteLength",    get = sab_byte_length),
            ("maxByteLength", get = sab_max_byte_length),
            ("growable",      get = sab_growable),
        ],
    },
}

fn sab_ctor_call(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    if !ctx.is_construct_call() {
        return Err(NativeError::TypeError {
            name: "SharedArrayBuffer",
            reason: "constructor requires 'new'".to_string(),
        });
    }
    // §25.2.3.1 step 2 — ToIndex(length) observable coercion.
    let length = observable_to_index_arg(ctx, args.first(), "SharedArrayBuffer")?;
    let mut coerced_args: smallvec::SmallVec<[Value; 4]> = smallvec::SmallVec::new();
    coerced_args.push(length);
    coerced_args.extend(args.iter().skip(1).copied());
    let args = coerced_args.as_slice();
    let roots = ctx.collect_native_roots();
    let this_value = *ctx.this_value();
    let new_target = ctx.new_target().cloned();
    let mut external_visit = |visitor: &mut dyn FnMut(*mut otter_gc::raw::RawGc)| {
        crate::runtime_cx::visit_native_roots(
            visitor,
            &roots,
            &this_value,
            new_target.as_ref(),
            &[],
            &[args],
        );
    };
    let value = dispatch::shared_array_buffer_call_with_roots(
        SharedArrayBufferMethod::Construct,
        args,
        ctx.heap_mut(),
        &mut external_visit,
    )
    .map_err(|e| vm_to_native(e, "SharedArrayBuffer"))?;
    // §10.1.13 GetPrototypeFromConstructor — newTarget.prototype is
    // always consulted; only %SharedArrayBuffer% itself keeps the
    // intrinsic default without an override record.
    let is_self_target = ctx.new_target().is_some_and(|nt| {
        crate::object::get(
            ctx.cx.interp.global_this,
            &ctx.cx.interp.gc_heap,
            "SharedArrayBuffer",
        )
        .is_some_and(|sab| *nt == sab)
    });
    if !is_self_target
        && let Some(proto) =
            crate::bootstrap::native_new_target_prototype(ctx, "SharedArrayBuffer")?
        && proto.is_object_type()
    {
        ctx.interp_mut()
            .set_non_gc_exotic_prototype_override(&value, Some(proto));
    }
    Ok(value)
}

/// §25.2.5.4 — `SharedArrayBuffer.prototype.grow(newByteLength)`.
fn sab_grow(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    const NAME: &str = "SharedArrayBuffer.prototype.grow";
    // §25.2.5.4 steps 2-3 — RequireInternalSlot + IsSharedArrayBuffer.
    let buf = receiver_sab(ctx, NAME)?;
    // Step 2 — RequireInternalSlot([[ArrayBufferMaxByteLength]]): a
    // non-growable shared buffer lacks the slot.
    if !buf.is_growable(ctx.heap()) {
        return Err(NativeError::TypeError {
            name: NAME,
            reason: "receiver is not a growable SharedArrayBuffer".to_string(),
        });
    }
    // Step 4 — ToIntegerOrInfinity (observable valueOf / toString).
    let new_len_f = coerce_length_integer(ctx, args.first().unwrap_or(&Value::undefined()), NAME)?;
    // Step 5 — RangeError when out of [0, maxByteLength].
    if new_len_f < 0.0 || new_len_f > buf.max_byte_length(ctx.heap()) as f64 {
        return Err(NativeError::RangeError {
            name: NAME,
            reason: "newLength is out of bounds [0, maxByteLength]".to_string(),
        });
    }
    if !buf.grow(ctx.heap_mut(), new_len_f as usize) {
        return Err(NativeError::RangeError {
            name: NAME,
            reason: "newLength is smaller than the current byteLength".to_string(),
        });
    }
    Ok(Value::undefined())
}

fn sab_growable(ctx: &mut NativeCtx<'_>, _args: &[Value]) -> Result<Value, NativeError> {
    let b = receiver_sab(ctx, "get SharedArrayBuffer.prototype.growable")?;
    Ok(Value::boolean(b.is_growable(ctx.heap())))
}

/// §25.2.4.x `get SharedArrayBuffer.prototype.maxByteLength` — shared
/// receiver brand check (the `ArrayBuffer` accessor rejects shared).
fn sab_max_byte_length(ctx: &mut NativeCtx<'_>, _args: &[Value]) -> Result<Value, NativeError> {
    let b = receiver_sab(ctx, "get SharedArrayBuffer.prototype.maxByteLength")?;
    Ok(Value::number_i32(b.max_byte_length(ctx.heap()) as i32))
}

/// Install `SharedArrayBuffer.prototype[@@toStringTag] = "SharedArrayBuffer"`.
pub fn install_shared_array_buffer_well_knowns_post_bootstrap(
    heap: &mut otter_gc::GcHeap,
    global: JsObject,
    well_known: &crate::symbol::WellKnownSymbols,
) -> Result<(), JsSurfaceError> {
    use crate::symbol::WellKnown;

    let Some(ctor) =
        object::get(global, heap, "SharedArrayBuffer").and_then(|v| v.as_native_function())
    else {
        return Ok(());
    };
    let descriptor = ctor
        .own_property_descriptor(heap, "prototype")
        .map_err(|_| JsSurfaceError::OutOfMemory)?;
    let prototype = match descriptor.and_then(|d| match d.kind {
        crate::object::DescriptorKind::Data { value } => value.as_object(),
        _ => None,
    }) {
        Some(p) => p,
        None => return Ok(()),
    };
    let tag = crate::string::JsString::from_str("SharedArrayBuffer", heap)
        .map_err(|_| JsSurfaceError::OutOfMemory)?;
    object::define_own_symbol_property_partial(
        prototype,
        heap,
        well_known.get(WellKnown::ToStringTag),
        PartialPropertyDescriptor {
            value: Some(Value::string(tag)),
            writable: Some(false),
            enumerable: Some(false),
            configurable: Some(true),
            ..Default::default()
        },
    );
    Ok(())
}

/// Install `ArrayBuffer.prototype[@@toStringTag] = "ArrayBuffer"`.
pub fn install_array_buffer_well_knowns_post_bootstrap(
    heap: &mut otter_gc::GcHeap,
    global: JsObject,
    well_known: &crate::symbol::WellKnownSymbols,
) -> Result<(), JsSurfaceError> {
    use crate::symbol::WellKnown;

    let Some(ctor) = object::get(global, heap, "ArrayBuffer").and_then(|v| v.as_native_function())
    else {
        return Ok(());
    };
    let descriptor = ctor
        .own_property_descriptor(heap, "prototype")
        .map_err(|_| JsSurfaceError::OutOfMemory)?;
    let prototype = match descriptor.and_then(|d| match d.kind {
        crate::object::DescriptorKind::Data { value } => value.as_object(),
        _ => None,
    }) {
        Some(p) => p,
        None => return Ok(()),
    };
    let tag = crate::string::JsString::from_str("ArrayBuffer", heap)
        .map_err(|_| JsSurfaceError::OutOfMemory)?;
    object::define_own_symbol_property_partial(
        prototype,
        heap,
        well_known.get(WellKnown::ToStringTag),
        PartialPropertyDescriptor {
            value: Some(Value::string(tag)),
            writable: Some(false),
            enumerable: Some(false),
            configurable: Some(true),
            ..Default::default()
        },
    );
    Ok(())
}

// ---------------------------------------------------------------
// Constructor + statics
// ---------------------------------------------------------------

/// §7.1.22 ToIndex with the OBSERVABLE ToNumber ladder — fires user
/// `valueOf` / `@@toPrimitive` and propagates their abrupt
/// completions before the truncation / range checks.
fn observable_to_index_arg(
    ctx: &mut NativeCtx<'_>,
    arg: Option<&Value>,
    name: &'static str,
) -> Result<Value, NativeError> {
    let Some(v) = arg else {
        return Ok(Value::undefined());
    };
    if v.is_undefined() || v.as_number().is_some() {
        return Ok(*v);
    }
    let exec_ctx = ctx
        .execution_context()
        .cloned()
        .ok_or_else(|| NativeError::TypeError {
            name,
            reason: "missing execution context".to_string(),
        })?;
    let n = ctx
        .cx
        .interp
        .coerce_to_number(&exec_ctx, v)
        .map_err(|e| crate::native_function::vm_to_native_error(e, name))?;
    Ok(Value::number(n))
}

fn ab_ctor_call(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    if !ctx.is_construct_call() {
        return Err(NativeError::TypeError {
            name: "ArrayBuffer",
            reason: "constructor requires 'new'".to_string(),
        });
    }
    // §25.1.4.1 step 2 — ToIndex(length) runs the observable
    // ToNumber ladder before allocation.
    let length = observable_to_index_arg(ctx, args.first(), "ArrayBuffer")?;
    let mut coerced_args: smallvec::SmallVec<[Value; 4]> = smallvec::SmallVec::new();
    coerced_args.push(length);
    coerced_args.extend(args.iter().skip(1).copied());
    let args = coerced_args.as_slice();
    let roots = ctx.collect_native_roots();
    let this_value = *ctx.this_value();
    let new_target = ctx.new_target().cloned();
    let mut external_visit = |visitor: &mut dyn FnMut(*mut otter_gc::raw::RawGc)| {
        crate::runtime_cx::visit_native_roots(
            visitor,
            &roots,
            &this_value,
            new_target.as_ref(),
            &[],
            &[args],
        );
    };
    let value = dispatch::array_buffer_call_with_roots(
        ArrayBufferMethod::Construct,
        args,
        ctx.heap_mut(),
        &mut external_visit,
    )
    .map_err(|e| vm_to_native(e, "ArrayBuffer"))?;
    // §10.1.13 GetPrototypeFromConstructor — newTarget.prototype is
    // ALWAYS consulted (Reflect.construct with a foreign newTarget,
    // accessor-defined prototypes, derived super()); only a
    // newTarget that IS %ArrayBuffer% itself keeps the intrinsic
    // default without an override record.
    let is_self_target = ctx.new_target().is_some_and(|nt| {
        crate::object::get(
            ctx.cx.interp.global_this,
            &ctx.cx.interp.gc_heap,
            "ArrayBuffer",
        )
        .is_some_and(|ab| *nt == ab)
    });
    if !is_self_target
        && let Some(proto) = crate::bootstrap::native_new_target_prototype(ctx, "ArrayBuffer")?
        && proto.is_object_type()
    {
        ctx.interp_mut()
            .set_non_gc_exotic_prototype_override(&value, Some(proto));
    }
    Ok(value)
}

fn ab_is_view(_ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    dispatch::array_buffer_call(ArrayBufferMethod::IsView, args, _ctx.heap())
        .map_err(|e| vm_to_native(e, "ArrayBuffer.isView"))
}

// ---------------------------------------------------------------
// Prototype methods
// ---------------------------------------------------------------

/// §25.1.5.4 `slice(start, end)` — half-open range, clamps to
/// `[0, byteLength]`, returns a fresh fixed-length buffer.
fn ab_slice(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    const NAME: &str = "ArrayBuffer.prototype.slice";
    let this_value = *ctx.this_value();
    let buf = receiver_ab(ctx, NAME)?;
    if buf.is_detached(ctx.heap()) {
        return Err(NativeError::TypeError {
            name: NAME,
            reason: "buffer is detached".to_string(),
        });
    }
    let exec_ctx = ctx
        .execution_context()
        .cloned()
        .ok_or_else(|| NativeError::TypeError {
            name: NAME,
            reason: "missing execution context".to_string(),
        })?;
    // §25.1.6.16 steps 6-13 — ToIntegerOrInfinity coercion fires
    // user valueOf for both operands.
    let len = buf.byte_length(ctx.heap()) as i64;
    let start_f = ctx
        .cx
        .interp
        .integer_or_infinity_for_arg(&exec_ctx, args.first())
        .map_err(|e| vm_to_native(e, NAME))?;
    let first = relative_clamp_f(start_f, len);
    let end_f = match args.get(1) {
        None => len as f64,
        Some(v) if v.is_undefined() => len as f64,
        Some(_) => ctx
            .cx
            .interp
            .integer_or_infinity_for_arg(&exec_ctx, args.get(1))
            .map_err(|e| vm_to_native(e, NAME))?,
    };
    let final_end = relative_clamp_f(end_f, len);
    let new_len = (final_end - first).max(0) as usize;
    // §25.1.6.16 step 14 — SpeciesConstructor(O, %ArrayBuffer%).
    let default_ctor = crate::object::get(ctx.cx.interp.global_this, ctx.heap(), "ArrayBuffer")
        .ok_or_else(|| NativeError::TypeError {
            name: NAME,
            reason: "%ArrayBuffer% intrinsic is missing".to_string(),
        })?;
    let ctor = ctx
        .cx
        .interp
        .species_constructor_value(&exec_ctx, &this_value, &default_ctor)
        .map_err(|e| vm_to_native(e, NAME))?;
    let mut argv: smallvec::SmallVec<[Value; 8]> = smallvec::SmallVec::new();
    argv.push(Value::number(crate::number::NumberValue::from_f64(
        new_len as f64,
    )));
    let new_value = ctx
        .cx
        .interp
        .run_construct_sync(&exec_ctx, &ctor, ctor, argv)
        .map_err(|e| vm_to_native(e, NAME))?;
    // Steps 16-21 — result-shape checks.
    let Some(new_buf) = new_value.as_array_buffer() else {
        return Err(NativeError::TypeError {
            name: NAME,
            reason: "species constructor did not return an ArrayBuffer".to_string(),
        });
    };
    if new_buf.is_shared() {
        return Err(NativeError::TypeError {
            name: NAME,
            reason: "species constructor returned a SharedArrayBuffer".to_string(),
        });
    }
    if new_buf.is_detached(ctx.heap()) {
        return Err(NativeError::TypeError {
            name: NAME,
            reason: "species constructor returned a detached ArrayBuffer".to_string(),
        });
    }
    if new_buf.ptr_eq(buf) {
        return Err(NativeError::TypeError {
            name: NAME,
            reason: "species constructor returned the source ArrayBuffer".to_string(),
        });
    }
    if new_buf.byte_length(ctx.heap()) < new_len {
        return Err(NativeError::TypeError {
            name: NAME,
            reason: "species constructor returned a too-small ArrayBuffer".to_string(),
        });
    }
    // Step 22 — the constructor may have detached the source.
    if buf.is_detached(ctx.heap()) {
        return Err(NativeError::TypeError {
            name: NAME,
            reason: "buffer was detached by the species constructor".to_string(),
        });
    }
    if new_len > 0 {
        let first = first as usize;
        let copy: Vec<u8> = buf.with_bytes(ctx.heap(), |b| b[first..first + new_len].to_vec());
        new_buf.with_bytes_mut(ctx.heap_mut(), |dst| {
            dst[..copy.len()].copy_from_slice(&copy)
        });
    }
    Ok(new_value)
}

/// Resolve a ToIntegerOrInfinity result against `len` with relative
/// (negative-from-end) semantics, clamped to `[0, len]`.
fn relative_clamp_f(n: f64, len: i64) -> i64 {
    if n.is_nan() {
        return 0;
    }
    if n == f64::NEG_INFINITY {
        return 0;
    }
    if n == f64::INFINITY {
        return len;
    }
    let i = n as i64;
    if i < 0 { (len + i).max(0) } else { i.min(len) }
}

/// §25.2.5.6 SharedArrayBuffer.prototype.slice — shared-brand
/// receiver, plain copy (species kept default).
fn sab_slice(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    const NAME: &str = "SharedArrayBuffer.prototype.slice";
    let this_value = *ctx.this_value();
    let buf = receiver_sab(ctx, NAME)?;
    let exec_ctx = ctx
        .execution_context()
        .cloned()
        .ok_or(NativeError::TypeError {
            name: NAME,
            reason: "missing execution context".to_string(),
        })?;
    // §25.2.5.6 steps 4-9 — ToIntegerOrInfinity coercion fires user
    // valueOf for both operands, in source order.
    let len = buf.byte_length(ctx.heap()) as i64;
    let start_f = ctx
        .cx
        .interp
        .integer_or_infinity_for_arg(&exec_ctx, args.first())
        .map_err(|e| vm_to_native(e, NAME))?;
    let first = relative_clamp_f(start_f, len);
    let end_f = match args.get(1) {
        None => len as f64,
        Some(v) if v.is_undefined() => len as f64,
        Some(_) => ctx
            .cx
            .interp
            .integer_or_infinity_for_arg(&exec_ctx, args.get(1))
            .map_err(|e| vm_to_native(e, NAME))?,
    };
    let final_end = relative_clamp_f(end_f, len);
    let new_len = (final_end - first).max(0) as usize;
    // Step 11 — SpeciesConstructor(O, %SharedArrayBuffer%).
    let default_ctor =
        crate::object::get(ctx.cx.interp.global_this, ctx.heap(), "SharedArrayBuffer").ok_or(
            NativeError::TypeError {
                name: NAME,
                reason: "%SharedArrayBuffer% intrinsic is missing".to_string(),
            },
        )?;
    let ctor = ctx
        .cx
        .interp
        .species_constructor_value(&exec_ctx, &this_value, &default_ctor)
        .map_err(|e| vm_to_native(e, NAME))?;
    let mut argv: smallvec::SmallVec<[Value; 8]> = smallvec::SmallVec::new();
    argv.push(Value::number(crate::number::NumberValue::from_f64(
        new_len as f64,
    )));
    let new_value = ctx
        .cx
        .interp
        .run_construct_sync(&exec_ctx, &ctor, ctor, argv)
        .map_err(|e| vm_to_native(e, NAME))?;
    // Steps 13-16 — result must be a SharedArrayBuffer, distinct from
    // the source, and at least `new_len` bytes long.
    let Some(new_buf) = new_value.as_array_buffer().filter(|b| b.is_shared()) else {
        return Err(NativeError::TypeError {
            name: NAME,
            reason: "species constructor did not return a SharedArrayBuffer".to_string(),
        });
    };
    if new_buf.ptr_eq(buf) {
        return Err(NativeError::TypeError {
            name: NAME,
            reason: "species constructor returned the source SharedArrayBuffer".to_string(),
        });
    }
    if new_buf.byte_length(ctx.heap()) < new_len {
        return Err(NativeError::TypeError {
            name: NAME,
            reason: "species constructor returned a too-small SharedArrayBuffer".to_string(),
        });
    }
    if new_len > 0 {
        let first = first as usize;
        let copy: Vec<u8> = buf.with_bytes(ctx.heap(), |b| b[first..first + new_len].to_vec());
        new_buf.with_bytes_mut(ctx.heap_mut(), |dst| {
            dst[..copy.len()].copy_from_slice(&copy)
        });
    }
    Ok(new_value)
}

/// §25.2.4.2 — shared-brand byteLength getter.
fn sab_byte_length(ctx: &mut NativeCtx<'_>, _args: &[Value]) -> Result<Value, NativeError> {
    let b = receiver_sab(ctx, "get SharedArrayBuffer.prototype.byteLength")?;
    Ok(Value::number_i32(b.byte_length(ctx.heap()) as i32))
}

/// §25.1.5.6 `resize(newByteLength)` — only valid for resizable,
/// non-detached buffers.
fn ab_resize(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    const NAME: &str = "ArrayBuffer.prototype.resize";
    let buf = receiver_ab(ctx, NAME)?;
    // §25.1.5.6 step 2 — RequireInternalSlot([[ArrayBufferMaxByteLength]]):
    // fixed-length buffers lack the slot. Shared buffers use `grow`.
    if !buf.is_resizable(ctx.heap()) || buf.is_shared() {
        return Err(NativeError::TypeError {
            name: NAME,
            reason: "receiver is not a resizable ArrayBuffer".to_string(),
        });
    }
    // Step 4 — ToIntegerOrInfinity runs *before* the detach check, so a
    // poisoned `valueOf` that detaches the buffer still throws here.
    let new_len_f = coerce_length_integer(ctx, args.first().unwrap_or(&Value::undefined()), NAME)?;
    // Step 5 — bounds check is a RangeError (±∞ and overflow included).
    if new_len_f < 0.0 || new_len_f > buf.max_byte_length(ctx.heap()) as f64 {
        return Err(NativeError::RangeError {
            name: NAME,
            reason: "newLength is out of bounds [0, maxByteLength]".to_string(),
        });
    }
    // Step 6 — detach check after coercion.
    if buf.is_detached(ctx.heap()) {
        return Err(NativeError::TypeError {
            name: NAME,
            reason: "buffer is detached".to_string(),
        });
    }
    if !buf.resize(ctx.heap_mut(), new_len_f as usize) {
        return Err(NativeError::RangeError {
            name: NAME,
            reason: "newLength exceeds maxByteLength".to_string(),
        });
    }
    Ok(Value::undefined())
}

/// §25.1.5.8 `transfer(newLength?)` — copy + detach; the new buffer is
/// resizable iff this one was.
fn ab_transfer(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    ab_transfer_inner(ctx, args, false, "ArrayBuffer.prototype.transfer")
}

/// §25.1.5.9 `transferToFixedLength(newLength?)` — as `transfer` but the
/// result is fixed-length.
fn ab_transfer_to_fixed_length(
    ctx: &mut NativeCtx<'_>,
    args: &[Value],
) -> Result<Value, NativeError> {
    ab_transfer_inner(
        ctx,
        args,
        true,
        "ArrayBuffer.prototype.transferToFixedLength",
    )
}

fn ab_transfer_inner(
    ctx: &mut NativeCtx<'_>,
    args: &[Value],
    fixed: bool,
    name: &'static str,
) -> Result<Value, NativeError> {
    let buf = receiver_ab(ctx, name)?;
    // §25.1.5.8 step 4 — ToIndex(newLength) runs before the detach
    // check, so a poisoned `valueOf` is observable even on a detached
    // buffer.
    let new_len = match args.first() {
        None => buf.byte_length(ctx.heap()),
        Some(v) if v.is_undefined() => buf.byte_length(ctx.heap()),
        Some(v) => coerce_index(ctx, v, name)?,
    };
    if buf.is_detached(ctx.heap()) {
        return Err(NativeError::TypeError {
            name,
            reason: "buffer is detached".to_string(),
        });
    }
    let cur_len = buf.byte_length(ctx.heap());
    let mut new_bytes = vec![0u8; new_len];
    let copy_len = new_len.min(cur_len);
    buf.with_bytes(ctx.heap(), |src| {
        new_bytes[..copy_len].copy_from_slice(&src[..copy_len]);
    });
    let resizable = buf.is_resizable(ctx.heap());
    let max = if resizable {
        buf.max_byte_length(ctx.heap()).max(new_len)
    } else {
        0
    };
    let new_buffer = if fixed {
        ctx.array_buffer_from_bytes_rooted(new_bytes, &[], &[args])?
    } else if resizable {
        let result = ctx
            .array_buffer_resizable_rooted(new_len, max, &[], &[args])?
            .ok_or(NativeError::TypeError {
                name,
                reason: "allocation failed".to_string(),
            })?;
        result.with_bytes_mut(ctx.heap_mut(), |dst| dst.copy_from_slice(&new_bytes));
        result
    } else {
        ctx.array_buffer_from_bytes_rooted(new_bytes, &[], &[args])?
    };
    buf.detach(ctx.heap_mut());
    Ok(Value::array_buffer(new_buffer))
}

// ---------------------------------------------------------------
// Accessors
// ---------------------------------------------------------------

fn ab_byte_length(ctx: &mut NativeCtx<'_>, _args: &[Value]) -> Result<Value, NativeError> {
    let b = receiver_ab(ctx, "get ArrayBuffer.prototype.byteLength")?;
    if b.is_detached(ctx.heap()) {
        return Ok(Value::number_i32(0));
    }
    Ok(Value::number_i32(b.byte_length(ctx.heap()) as i32))
}

fn ab_max_byte_length(ctx: &mut NativeCtx<'_>, _args: &[Value]) -> Result<Value, NativeError> {
    let b = receiver_ab(ctx, "get ArrayBuffer.prototype.maxByteLength")?;
    Ok(Value::number_i32(b.max_byte_length(ctx.heap()) as i32))
}

fn ab_resizable(ctx: &mut NativeCtx<'_>, _args: &[Value]) -> Result<Value, NativeError> {
    let b = receiver_ab(ctx, "get ArrayBuffer.prototype.resizable")?;
    Ok(Value::boolean(b.is_resizable(ctx.heap())))
}

fn ab_detached(ctx: &mut NativeCtx<'_>, _args: &[Value]) -> Result<Value, NativeError> {
    let b = receiver_ab(ctx, "get ArrayBuffer.prototype.detached")?;
    Ok(Value::boolean(b.is_detached(ctx.heap())))
}

fn receiver_ab(
    ctx: &NativeCtx<'_>,
    name: &'static str,
) -> Result<crate::binary::array_buffer::JsArrayBuffer, NativeError> {
    match ctx.this_value().as_array_buffer() {
        // §25.1.5 — every ArrayBuffer.prototype member brand-checks
        // [[ArrayBufferData]] WITHOUT [[ArrayBufferByteLengthData]]
        // being shared; a SharedArrayBuffer receiver is a TypeError.
        Some(b) if !b.is_shared() => Ok(b),
        _ => Err(NativeError::TypeError {
            name,
            reason: "this is not an ArrayBuffer".to_string(),
        }),
    }
}

/// §25.2.4 SharedArrayBuffer.prototype brand check — shared only.
fn receiver_sab(
    ctx: &NativeCtx<'_>,
    name: &'static str,
) -> Result<crate::binary::array_buffer::JsArrayBuffer, NativeError> {
    match ctx.this_value().as_array_buffer() {
        Some(b) if b.is_shared() => Ok(b),
        _ => Err(NativeError::TypeError {
            name,
            reason: "this is not a SharedArrayBuffer".to_string(),
        }),
    }
}

fn vm_to_native(err: VmError, name: &'static str) -> NativeError {
    match err {
        VmError::TypeError { message } => NativeError::TypeError {
            name,
            reason: message,
        },
        VmError::TypeMismatch => NativeError::TypeError {
            name,
            reason: "type mismatch".to_string(),
        },
        VmError::RangeError { message } => NativeError::RangeError {
            name,
            reason: message,
        },
        VmError::OutOfMemory { .. } => NativeError::RangeError {
            name,
            reason: err.to_string(),
        },
        other => NativeError::TypeError {
            name,
            reason: other.to_string(),
        },
    }
}
