//! ECMA-262 §21.2 BigInt bootstrap installer.
//!
//! `BigInt` is a callable-only NativeFunction (no `[[Construct]]`).
//! The prototype carries `toString` / `valueOf` as own data
//! properties; the constructor carries `asIntN` / `asUintN`
//! statics. `@@toStringTag = "BigInt"` is installed in the
//! post-bootstrap hook.
//!
//! # Contents
//! - [`install_bigint`] — bootstrap entry.
//! - [`install_bigint_well_knowns_post_bootstrap`] — `@@toStringTag`.
//!
//! # Invariants
//! - `new BigInt(x)` throws `TypeError` per §21.2.1.1 step 1.
//! - `BigInt(x)` callable returns a BigInt via
//!   [`crate::bigint::dispatch::call`].
//! - `asIntN` / `asUintN` flow through the same dispatcher.
//!
//! # See also
//! - <https://tc39.es/ecma262/#sec-bigint-constructor>

use otter_bytecode::method_id::BigIntMethod;

use crate::bigint;
use crate::js_surface::JsSurfaceError;
use crate::object::{self, JsObject, PartialPropertyDescriptor};
use crate::{NativeCtx, NativeError, Value, VmError};

// `BIGINT_SPEC` + `Intrinsic` generated by `couch!`. §21.2 — BigInt
// is callable-only (no [[Construct]] slot; `new BigInt(x)` throws
// via §10.1.10), so `callable_only = true` switches the install
// path from `native_constructor_static_with_value_roots` to
// `native_static_with_value_roots`. Prototype links to
// `%Object.prototype%` by couch! default; constructor back-pointer
// auto-installed.
otter_macros::couch! {
    name = "BigInt",
    feature = CORE,
    constructor = (length = 1, call = bigint_ctor_call, callable_only = true),
    statics = {
        "asIntN"  / 2 => bigint_static_as_int_n,
        "asUintN" / 2 => bigint_static_as_uint_n,
    },
    prototype = {
        methods = {
            "toString" / 0 => bigint_proto_to_string,
            "valueOf"  / 0 => bigint_proto_value_of,
        },
    },
}

/// Install `BigInt.prototype[@@toStringTag] = "BigInt"`.
pub fn install_bigint_well_knowns_post_bootstrap(
    heap: &mut otter_gc::GcHeap,
    global: JsObject,
    well_known: &crate::symbol::WellKnownSymbols,
) -> Result<(), JsSurfaceError> {
    use crate::symbol::WellKnown;

    let Some(ctor) = object::get(global, heap, "BigInt").and_then(|v| v.as_native_function())
    else {
        return Ok(());
    };
    let descriptor = ctor
        .own_property_descriptor(heap, "prototype")
        .map_err(|_| JsSurfaceError::OutOfMemory)?;
    let prototype = match descriptor.and_then(|d| match d.kind {
        crate::object::DescriptorKind::Data { value } => value.as_object(),
        _ => None,
    }) {
        Some(p) => p,
        None => return Ok(()),
    };
    let tag = crate::string::JsString::from_str("BigInt", heap)
        .map_err(|_| JsSurfaceError::OutOfMemory)?;
    object::define_own_symbol_property_partial(
        prototype,
        heap,
        well_known.get(WellKnown::ToStringTag),
        PartialPropertyDescriptor {
            value: Some(Value::string(tag)),
            writable: Some(false),
            enumerable: Some(false),
            configurable: Some(true),
            ..Default::default()
        },
    );
    Ok(())
}

// ---------------------------------------------------------------
// Constructor + statics
// ---------------------------------------------------------------

fn bigint_ctor_call(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    if ctx.is_construct_call() {
        return Err(NativeError::TypeError {
            name: "BigInt",
            reason: "BigInt is not a constructor".to_string(),
        });
    }
    let coerced = coerce_bigint_call_args(ctx, args, "BigInt")?;
    bigint::dispatch::call(
        ctx.interp_mut().gc_heap_mut(),
        BigIntMethod::Construct,
        &coerced,
    )
    .map_err(|e| vm_to_native(e, "BigInt"))
}

fn bigint_static_as_int_n(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    let coerced = coerce_bigint_call_args(ctx, args, "BigInt.asIntN")?;
    bigint::dispatch::call(
        ctx.interp_mut().gc_heap_mut(),
        BigIntMethod::AsIntN,
        &coerced,
    )
    .map_err(|e| vm_to_native(e, "BigInt.asIntN"))
}

fn bigint_static_as_uint_n(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    let coerced = coerce_bigint_call_args(ctx, args, "BigInt.asUintN")?;
    bigint::dispatch::call(
        ctx.interp_mut().gc_heap_mut(),
        BigIntMethod::AsUintN,
        &coerced,
    )
    .map_err(|e| vm_to_native(e, "BigInt.asUintN"))
}

/// §7.1.13 ToBigInt step 4 — Array operands flow through
/// `ToPrimitive(hint: number)` which routes through
/// `Array.prototype.toString` = `.join(",")`. The free
/// `bigint::dispatch::call` has no GC access, so we pre-coerce
/// Array arguments to their joined-string form before dispatch.
fn coerce_bigint_call_args(
    ctx: &mut NativeCtx<'_>,
    args: &[Value],
    name: &'static str,
) -> Result<smallvec::SmallVec<[Value; 4]>, NativeError> {
    let mut out: smallvec::SmallVec<[Value; 4]> = args.iter().cloned().collect();
    for slot in out.iter_mut() {
        if let Some(arr) = slot.as_array() {
            let parts: Vec<String> = {
                let heap = ctx.heap();
                crate::array::with_elements(arr, heap, |elements| {
                    elements
                        .iter()
                        .map(|v| {
                            if v.is_undefined() || v.is_null() || v.is_hole() {
                                String::new()
                            } else {
                                v.display_string(heap)
                            }
                        })
                        .collect()
                })
            };
            let joined = parts.join(",");
            *slot = Value::string(
                crate::string::JsString::from_str(&joined, ctx.heap_mut()).map_err(|_| {
                    NativeError::TypeError {
                        name,
                        reason: "out of memory".to_string(),
                    }
                })?,
            );
        } else if slot.is_object()
            || slot.is_function()
            || slot.is_closure()
            || slot.is_native_function()
            || slot.is_bound_function()
            || slot.is_class_constructor()
            || slot.is_proxy()
            || slot.is_regexp()
            || slot.is_map()
            || slot.is_set()
        {
            // §7.1.1 ToPrimitive ladder for object-like operands.
            let (interp, exec) = ctx.interp_mut_and_context();
            let exec = exec.ok_or_else(|| NativeError::TypeError {
                name,
                reason: "missing execution context".to_string(),
            })?;
            let primitive = interp
                .evaluate_to_primitive(&exec, slot, crate::abstract_ops::ToPrimitiveHint::Number)
                .map_err(|e| vm_to_native(e, name))?;
            *slot = primitive;
        }
    }
    Ok(out)
}

// ---------------------------------------------------------------
// Prototype methods
// ---------------------------------------------------------------

fn bigint_proto_to_string(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    let this = ctx.this_value();
    let b = if let Some(b) = this.as_big_int() {
        b
    } else if let Some(obj) = this.as_object() {
        crate::object::bigint_data(obj, ctx.heap()).ok_or_else(|| NativeError::TypeError {
            name: "BigInt.prototype.toString",
            reason: "this is not a BigInt".to_string(),
        })?
    } else {
        return Err(NativeError::TypeError {
            name: "BigInt.prototype.toString",
            reason: "this is not a BigInt".to_string(),
        });
    };
    // §21.2.3.4 step 2 — `radix` defaults to 10 when `undefined`,
    // otherwise routes through `ToIntegerOrInfinity`. The spec
    // raises RangeError for `< 2` / `> 36`; non-coercible operands
    // raise TypeError.
    let radix = if let Some(v) = args.first() {
        if v.is_undefined() {
            10u32
        } else if v.is_symbol() {
            return Err(NativeError::TypeError {
                name: "BigInt.prototype.toString",
                reason: "Cannot convert a Symbol value to a number".to_string(),
            });
        } else if v.is_big_int() {
            return Err(NativeError::TypeError {
                name: "BigInt.prototype.toString",
                reason: "Cannot convert a BigInt value to a number".to_string(),
            });
        } else {
            let f = if let Some(n) = v.as_number() {
                n.as_f64()
            } else if let Some(b) = v.as_boolean() {
                if b { 1.0 } else { 0.0 }
            } else if v.is_null() {
                0.0
            } else if let Some(s) = v.as_string(ctx.heap()) {
                crate::number::parse::to_number_from_string(&s.to_lossy_string(ctx.heap())).as_f64()
            } else {
                f64::NAN
            };
            let trunc = if f.is_nan() { 0.0 } else { f.trunc() };
            if !trunc.is_finite() || !(2.0..=36.0).contains(&trunc) {
                return Err(NativeError::RangeError {
                    name: "BigInt.prototype.toString",
                    reason: "radix must be an integer in [2, 36]".to_string(),
                });
            }
            trunc as u32
        }
    } else {
        10u32
    };
    let rendered = b.with_inner(ctx.heap(), |bi| bi.to_str_radix(radix));

    let s = crate::string::JsString::from_str(&rendered, ctx.heap_mut())
        .map_err(|_| oom("BigInt.prototype.toString"))?;
    Ok(Value::string(s))
}

fn bigint_proto_value_of(ctx: &mut NativeCtx<'_>, _args: &[Value]) -> Result<Value, NativeError> {
    let this = ctx.this_value();
    if let Some(b) = this.as_big_int() {
        Ok(Value::big_int(b))
    } else if let Some(obj) = this.as_object() {
        crate::object::bigint_data(obj, ctx.heap())
            .map(Value::big_int)
            .ok_or_else(|| NativeError::TypeError {
                name: "BigInt.prototype.valueOf",
                reason: "this is not a BigInt".to_string(),
            })
    } else {
        Err(NativeError::TypeError {
            name: "BigInt.prototype.valueOf",
            reason: "this is not a BigInt".to_string(),
        })
    }
}

// ---------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------

fn oom(name: &'static str) -> NativeError {
    NativeError::TypeError {
        name,
        reason: "out of memory".to_string(),
    }
}

fn vm_to_native(err: VmError, name: &'static str) -> NativeError {
    match err {
        VmError::TypeError { message } => NativeError::TypeError {
            name,
            reason: message,
        },
        VmError::TypeMismatch => NativeError::TypeError {
            name,
            reason: "type mismatch".to_string(),
        },
        VmError::RangeError { message } => NativeError::RangeError {
            name,
            reason: message,
        },
        VmError::SyntaxError { message } => NativeError::SyntaxError {
            name,
            reason: message,
        },
        VmError::Uncaught { value } => NativeError::Thrown {
            name,
            message: value,
        },
        other => NativeError::TypeError {
            name,
            reason: other.to_string(),
        },
    }
}
