//! ECMA-262 §25.3 DataView bootstrap installer.
//!
//! Real callable + constructible `NativeFunction` for `DataView`
//! plus a prototype carrying every spec-listed method and the
//! `buffer` / `byteLength` / `byteOffset` accessors.
//!
//! # Contents
//! - [`install_data_view`] — bootstrap entry.
//! - [`install_data_view_well_knowns_post_bootstrap`] — `@@toStringTag`.
//!
//! # Invariants
//! - `new DataView(buffer, byteOffset?, byteLength?)` runs §25.3.2.1.
//! - Bare `DataView(...)` (without `new`) throws `TypeError`.
//! - 20 prototype methods + 3 read-only accessors live as own
//!   properties on `DataView.prototype`.
//!
//! # See also
//! - <https://tc39.es/ecma262/#sec-dataview-constructor>
//! - <https://tc39.es/ecma262/#sec-properties-of-the-dataview-prototype-object>

use otter_bytecode::method_id::DataViewMethod;

use crate::binary::data_view_prototype;
use crate::js_surface::JsSurfaceError;
use crate::object::{self, JsObject, PartialPropertyDescriptor};
use crate::{NativeCtx, NativeError, Value, VmError};

// `DATAVIEW_SPEC` + `Intrinsic` generated by `couch!`. §25.3 — 20
// view get/set methods + 3 byte-* accessors. Prototype chains to
// %Object.prototype% by couch! default; constructor back-pointer
// auto-installed.
otter_macros::couch! {
    name = "DataView",
    feature = CORE,
    constructor = (length = 1, call = data_view_ctor_call),
    prototype = {
        methods = {
            "getInt8"      / 1 => data_view_prototype::dv_get_int8,
            "getUint8"     / 1 => data_view_prototype::dv_get_uint8,
            "getInt16"     / 1 => data_view_prototype::dv_get_int16,
            "getUint16"    / 1 => data_view_prototype::dv_get_uint16,
            "getInt32"     / 1 => data_view_prototype::dv_get_int32,
            "getUint32"    / 1 => data_view_prototype::dv_get_uint32,
            "getFloat32"   / 1 => data_view_prototype::dv_get_float32,
            "getFloat64"   / 1 => data_view_prototype::dv_get_float64,
            "getBigInt64"  / 1 => data_view_prototype::dv_get_bigint64,
            "getBigUint64" / 1 => data_view_prototype::dv_get_biguint64,
            "setInt8"      / 2 => data_view_prototype::dv_set_int8,
            "setUint8"     / 2 => data_view_prototype::dv_set_uint8,
            "setInt16"     / 2 => data_view_prototype::dv_set_int16,
            "setUint16"    / 2 => data_view_prototype::dv_set_uint16,
            "setInt32"     / 2 => data_view_prototype::dv_set_int32,
            "setUint32"    / 2 => data_view_prototype::dv_set_uint32,
            "setFloat32"   / 2 => data_view_prototype::dv_set_float32,
            "setFloat64"   / 2 => data_view_prototype::dv_set_float64,
            "setBigInt64"  / 2 => data_view_prototype::dv_set_bigint64,
            "setBigUint64" / 2 => data_view_prototype::dv_set_biguint64,
        },
        accessors = [
            ("buffer",     get = dv_get_buffer),
            ("byteLength", get = dv_get_byte_length),
            ("byteOffset", get = dv_get_byte_offset),
        ],
    },
}

/// Install `DataView.prototype[@@toStringTag] = "DataView"`.
pub fn install_data_view_well_knowns_post_bootstrap(
    heap: &mut otter_gc::GcHeap,
    global: JsObject,
    well_known: &crate::symbol::WellKnownSymbols,
) -> Result<(), JsSurfaceError> {
    use crate::symbol::WellKnown;

    let Some(ctor) = object::get(global, heap, "DataView").and_then(|v| v.as_native_function())
    else {
        return Ok(());
    };
    let descriptor = ctor
        .own_property_descriptor(heap, "prototype")
        .map_err(|_| JsSurfaceError::OutOfMemory)?;
    let prototype = match descriptor.and_then(|d| match d.kind {
        crate::object::DescriptorKind::Data { value } => value.as_object(),
        _ => None,
    }) {
        Some(p) => p,
        None => return Ok(()),
    };
    let tag = crate::string::JsString::from_str("DataView", heap)
        .map_err(|_| JsSurfaceError::OutOfMemory)?;
    object::define_own_symbol_property_partial(
        prototype,
        heap,
        well_known.get(WellKnown::ToStringTag),
        PartialPropertyDescriptor {
            value: Some(Value::string(tag)),
            writable: Some(false),
            enumerable: Some(false),
            configurable: Some(true),
            ..Default::default()
        },
    );
    Ok(())
}

// ---------------------------------------------------------------
// Constructor
// ---------------------------------------------------------------

fn data_view_ctor_call(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    if !ctx.is_construct_call() {
        return Err(NativeError::TypeError {
            name: "DataView",
            reason: "constructor requires 'new'".to_string(),
        });
    }
    let value =
        crate::binary::dispatch::data_view_call(DataViewMethod::Construct, args, ctx.heap_mut())
            .map_err(|e| vm_to_native(e, "DataView"))?;
    // §10.1.13 GetPrototypeFromConstructor — derived `super()`
    // construction forwards `new.target`, so the allocated exotic
    // receives `Subclass.prototype` as its observable [[Prototype]].
    // <https://tc39.es/ecma262/#sec-getprototypefromconstructor>
    let needs_proto_override = ctx.new_target().is_none_or(|v| !v.is_native_function());
    if needs_proto_override
        && let Some(proto) = crate::bootstrap::native_new_target_prototype(ctx, "DataView")?
    {
        ctx.interp_mut()
            .set_non_gc_exotic_prototype_override(&value, Some(proto));
    }
    Ok(value)
}

// ---------------------------------------------------------------
// Accessors
// ---------------------------------------------------------------

fn dv_get_buffer(ctx: &mut NativeCtx<'_>, _args: &[Value]) -> Result<Value, NativeError> {
    let view = receiver_dv(ctx, "get DataView.prototype.buffer")?;
    Ok(Value::array_buffer(view.buffer(ctx.heap())))
}

fn dv_get_byte_length(ctx: &mut NativeCtx<'_>, _args: &[Value]) -> Result<Value, NativeError> {
    let view = receiver_dv(ctx, "get DataView.prototype.byteLength")?;
    if view.buffer(ctx.heap()).is_detached(ctx.heap()) {
        return Ok(Value::number(crate::number::NumberValue::from_i32(0)));
    }
    Ok(Value::number(crate::number::NumberValue::from_i32(
        view.byte_length(ctx.heap()) as i32,
    )))
}

fn dv_get_byte_offset(ctx: &mut NativeCtx<'_>, _args: &[Value]) -> Result<Value, NativeError> {
    let view = receiver_dv(ctx, "get DataView.prototype.byteOffset")?;
    if view.buffer(ctx.heap()).is_detached(ctx.heap()) {
        return Ok(Value::number(crate::number::NumberValue::from_i32(0)));
    }
    Ok(Value::number(crate::number::NumberValue::from_i32(
        view.byte_offset(ctx.heap()) as i32,
    )))
}

fn receiver_dv(
    ctx: &NativeCtx<'_>,
    name: &'static str,
) -> Result<crate::binary::data_view::JsDataView, NativeError> {
    if let Some(v) = ctx.this_value().as_data_view() {
        Ok(v)
    } else {
        Err(NativeError::TypeError {
            name,
            reason: "this is not a DataView".to_string(),
        })
    }
}

fn vm_to_native(err: VmError, name: &'static str) -> NativeError {
    match err {
        VmError::TypeError { message } => NativeError::TypeError {
            name,
            reason: message,
        },
        VmError::TypeMismatch => NativeError::TypeError {
            name,
            reason: "type mismatch".to_string(),
        },
        VmError::RangeError { message } => NativeError::RangeError {
            name,
            reason: message,
        },
        other => NativeError::TypeError {
            name,
            reason: other.to_string(),
        },
    }
}
