//! `JSON` namespace — hand-rolled `stringify` and `parse`.
//!
//! The byte-cursor parser and iterative serializers own their buffers and
//! preserve deterministic property order. Native entry points run observable
//! coercion, reviver, replacer and accessor work through the live VM context.
//!
//! # Contents
//! - [`JSON_SPEC`] — static namespace spec used by bootstrap.
//! - [`call`] — internal heap-only parser/serializer dispatcher.
//! - Native parse/stringify/rawJSON entries and their canonical error projection.
//! - [`stringify`] / [`parse`] — public entry points.
//! - [`stringify_with_options`] — programmable `space` + `replacer`.
//! - [`JsonError`] / [`ParseError`] — typed syntax and allocation failures.
//!
//! # Invariants
//! - **No recursion.** Both serializer and parser walk an explicit
//!   stack capped at `MAX_NESTING_DEPTH` (1024) so adversarial
//!   nested input cannot blow the host stack.
//! - **Cycle detection.** Stringify carries an identity visit set;
//!   revisiting an active node raises `JsonError::Cyclic`.
//! - **Deterministic key order.** Object properties enumerate in
//!   shape insertion order (`JsObject::borrow_props`).
//! - **NaN / ±Infinity / -0 → `null`** per spec §25.5.2.4.
//! - Allocator refusals retain their original typed cause and project to native
//!   OutOfMemory; only malformed input projects to SyntaxError. Reviver
//!   failures use the single canonical VM-to-native completion projection.
//! - **BigInt → `TypeError`-equivalent** ([`JsonError::BigInt`]).
//! - **Strict parse.** Trailing commas, comments, single quotes,
//!   leading zeros, leading `+`, NaN/Infinity literals — all
//!   rejected. The parser walks `&[u8]` for the ASCII fast path
//!   and falls back to WTF-16 unescape only inside string literals.
//!
//! # See also
//! - <https://tc39.es/ecma262/#sec-json-object>

mod parse;
pub mod scan;
mod serialize;
mod stringify;

pub use parse::{ParseError, parse};
pub use stringify::{StringifyOptions, stringify, stringify_with_options};

use crate::string::JsString;
use crate::{NativeCtx, NativeError, Value, VmError};
use otter_gc::heap::RootSlotVisitor;
use otter_gc::raw::RawGc;

// `JSON_SPEC` + `Intrinsic` are generated by `holt!`. The static
// spec name + intrinsic adapter name match the previous hand-written
// surface byte-for-byte (`JSON_SPEC: NamespaceSpec`, `pub struct
// Intrinsic;` implementing `BuiltinIntrinsic` with NAME = "JSON",
// FEATURE = CORE, and the same `NamespaceBuilder`-driven install
// body). First production consumer of the otter-themed macro family
// (Phase 4.2a pathfinder).
otter_macros::holt! {
    name = "JSON",
    feature = CORE,
    methods = {
        "parse"     / 2 => native_parse,
        "stringify" / 3 => native_stringify,
        "rawJSON"   / 1 => native_raw_json,
        "isRawJSON" / 1 => native_is_raw_json,
    },
}

/// Hard cap on nesting depth. Both stringify and parse abort with
/// `JsonError::TooDeep` once exceeded — keeps adversarial input
/// from blowing the host stack and matches V8's `JSON.stringify`
/// behaviour for very deep objects.
pub const MAX_NESTING_DEPTH: usize = 1024;

/// Failure modes for [`call`].
#[derive(Debug, Clone, thiserror::Error)]
#[non_exhaustive]
pub enum JsonError {
    /// `JSON.<name>` is not a registered function.
    #[error("JSON.{0} is not defined")]
    UnknownMember(String),
    /// Argument failed type / value coercion.
    #[error("JSON.{name} argument {index} {reason}")]
    BadArgument {
        /// Function name.
        name: &'static str,
        /// Argument index (0-based).
        index: u16,
        /// Short reason.
        reason: &'static str,
    },
    /// Cycle detected while serialising.
    #[error("JSON.stringify cannot serialize cyclic structures.")]
    Cyclic,
    /// Nesting exceeded [`MAX_NESTING_DEPTH`].
    #[error("JSON nesting exceeded {limit} levels.")]
    TooDeep {
        /// Configured cap.
        limit: usize,
    },
    /// `BigInt` cannot be serialised per spec §25.5.2.4.
    #[error("JSON.stringify cannot serialize BigInt values.")]
    BigInt,
    /// Original collector allocation failure during parse or stringify.
    #[error(transparent)]
    OutOfMemory(#[from] otter_gc::OutOfMemory),
    /// Strict-mode parse failure.
    #[error("JSON.parse: {message} at byte {position}")]
    ParseFailed {
        /// Diagnostic body.
        message: String,
        /// 0-based byte offset.
        position: usize,
    },
}

impl From<ParseError> for JsonError {
    fn from(err: ParseError) -> Self {
        match err {
            ParseError::Syntax { message, position } => Self::ParseFailed { message, position },
            ParseError::OutOfMemory(error) => Self::OutOfMemory(error),
        }
    }
}

fn native_json_error(error: JsonError, name: &'static str) -> NativeError {
    match error {
        JsonError::ParseFailed { message, position } => NativeError::SyntaxError {
            name,
            reason: format!("JSON Parse error: {message} at byte {position}"),
        },
        JsonError::OutOfMemory(error) => NativeError::OutOfMemory {
            name,
            requested_bytes: error.requested_bytes(),
            heap_limit_bytes: error.heap_limit_bytes(),
        },
        error @ (JsonError::UnknownMember(_)
        | JsonError::BadArgument { .. }
        | JsonError::Cyclic
        | JsonError::TooDeep { .. }
        | JsonError::BigInt) => NativeError::TypeError {
            name,
            reason: error.to_string(),
        },
    }
}

/// Dispatch a `JSON.<method>(args...)` call. Routes via the
/// typed method id emitted by the compiler — no string-table
/// indirection or per-call name match.
pub fn call(
    method: otter_bytecode::method_id::JsonMethod,
    args: &[Value],
    gc_heap: &mut otter_gc::GcHeap,
) -> Result<Value, JsonError> {
    use otter_bytecode::method_id::JsonMethod;
    match method {
        JsonMethod::Stringify => json_stringify(args, gc_heap),
        JsonMethod::Parse => json_parse(args, gc_heap),
    }
}

/// Dispatch a `JSON.<method>` call with an explicit root visitor for callers
/// that have a live VM stack or native root set.
pub(crate) fn call_with_roots(
    method: otter_bytecode::method_id::JsonMethod,
    args: &[Value],
    gc_heap: &mut otter_gc::GcHeap,
    external_visit: &mut RootSlotVisitor<'_>,
    object_proto: Option<Value>,
) -> Result<Value, JsonError> {
    use otter_bytecode::method_id::JsonMethod;
    match method {
        JsonMethod::Stringify => json_stringify(args, gc_heap),
        JsonMethod::Parse => json_parse_with_roots(args, gc_heap, external_visit, object_proto),
    }
}

fn native_parse(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    // One native handle scope owns the observable coercion input, the reviver,
    // the resulting source string and parsed result through Internalize. A
    // ToString hook can collect before parsing has even started.
    ctx.scope(|mut scope| {
        let input = scope.value(args.first().copied().unwrap_or_else(Value::undefined));
        let reviver = scope.value(args.get(1).copied().unwrap_or_else(Value::undefined));
        // §25.5.1 step 1 also coerces a missing argument: undefined becomes
        // "undefined", then the strict parser reports a syntax failure.
        let input_value = scope.raw(input);
        let text = coerce_text_to_string(scope.context(), input_value, "parse")?;
        let text = scope.value(Value::string(text));
        let object_proto = scope
            .context()
            .interp_mut()
            .object_prototype_object_opt()
            .map(Value::object);
        let source = [scope.raw(text)];
        let unfiltered = native_json_call(
            scope.context(),
            otter_bytecode::method_id::JsonMethod::Parse,
            &source,
            object_proto,
        )?;
        let unfiltered = scope.value(unfiltered);

        // §25.5.1 steps 7–9 — a callable reviver drives InternalizeJSONProperty.
        if !scope.raw(reviver).is_callable() {
            return Ok(scope.raw(unfiltered));
        }
        let context = match scope.context().execution_context().cloned() {
            Some(context) => context,
            None => {
                return Err(crate::native_function::vm_to_native_error(
                    scope.context().interp_mut(),
                    VmError::InvalidOperand,
                    "parse",
                ));
            }
        };
        // The source-span tree is owned Rust data. Read the current source
        // handle after parsing, which may have relocated its input.
        let source_tree = scope
            .raw(text)
            .as_string(scope.context().heap())
            .map(|text| text.to_lossy_string(scope.context().heap()))
            .and_then(|text| parse::parse_source_tree(&text));
        let unfiltered = scope.raw(unfiltered);
        let reviver = scope.raw(reviver);
        let result = scope.context().with_turn_parts(|interp, stack| {
            interp.json_internalize_root(stack, &context, unfiltered, reviver, source_tree.as_ref())
        });
        result.map_err(|error| error.into_native(scope.context().interp_mut(), "parse"))
    })
}

/// §7.1.17 `ToString(text)` for JSON text inputs. Strings pass
/// through; other primitives use their display form; objects run the
/// ToPrimitive(hint:string) + ToString ladder so a user `toString` /
/// `valueOf` is observable. Symbols throw a `TypeError`. User
/// exceptions propagate verbatim.
fn coerce_text_to_string(
    ctx: &mut NativeCtx<'_>,
    value: Value,
    name: &'static str,
) -> Result<JsString, NativeError> {
    let exec = match ctx.execution_context().cloned() {
        Some(context) => context,
        None => {
            return Err(crate::native_function::vm_to_native_error(
                ctx.interp_mut(),
                VmError::InvalidOperand,
                name,
            ));
        }
    };
    let result = ctx.with_turn_parts(|interp, stack| {
        crate::coerce::to_js_string_or_throw(interp, stack, &exec, &value)
    });
    result.map_err(|error| error.into_native(ctx.interp_mut(), name))
}

/// §25.5.3 `JSON.rawJSON(text)`.
fn native_raw_json(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    let value = args.first().copied().unwrap_or_else(Value::undefined);
    let json_string = coerce_text_to_string(ctx, value, "rawJSON")?;
    let text = json_string.to_lossy_string(ctx.heap());

    // §25.5.3 step 2 — reject empty input or leading/trailing JSON
    // whitespace.
    let bytes = text.as_bytes();
    let bad_edge = bytes.is_empty()
        || matches!(bytes.first(), Some(0x09 | 0x0A | 0x0D | 0x20))
        || matches!(bytes.last(), Some(0x09 | 0x0A | 0x0D | 0x20));
    if bad_edge {
        return Err(NativeError::SyntaxError {
            name: "rawJSON",
            reason: "invalid rawJSON text".to_string(),
        });
    }

    ctx.scope(|mut scope| {
        let raw_value = scope.value(Value::string(json_string));

        // §25.5.3 steps 3–4 — must be a valid JSON primitive (not an
        // object or array). `raw_value` remains rooted while parsing allocates.
        match parse::parse(&text, scope.context().heap_mut()) {
            Ok(parsed) if parsed.as_object().is_some() || parsed.as_array().is_some() => {
                return Err(NativeError::SyntaxError {
                    name: "rawJSON",
                    reason: "rawJSON text must be a primitive JSON value".to_string(),
                });
            }
            Ok(_) => {}
            Err(err) => return Err(native_json_error(err.into(), "rawJSON")),
        }

        // §25.5.3 steps 5–7 — null-proto object, own "rawJSON" data
        // property, [[IsRawJSON]] slot, then frozen.
        let obj = scope.bare_object()?;
        scope.define(
            obj,
            "rawJSON",
            raw_value,
            crate::object::PropertyFlags::data_default(),
        )?;
        let obj_value = scope.raw(obj);
        let mut obj_handle = obj_value.as_object().expect("bare object handle");
        crate::object::set_is_raw_json(&mut obj_handle, scope.context().heap_mut(), true)?;
        scope.freeze(obj)?;
        Ok(scope.finish(obj))
    })
}

/// §25.5.4 `JSON.isRawJSON(O)`.
fn native_is_raw_json(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    let is_raw = args
        .first()
        .and_then(|v| v.as_object())
        .is_some_and(|obj| crate::object::is_raw_json(obj, ctx.heap()));
    Ok(Value::boolean(is_raw))
}

fn native_stringify(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    // §25.5.2.1 — the full algorithm needs a live execution context so
    // `toJSON`, the replacer, and accessor `[[Get]]` are observable.
    let context = match ctx.execution_context().cloned() {
        Some(context) => context,
        None => {
            return Err(crate::native_function::vm_to_native_error(
                ctx.interp_mut(),
                VmError::InvalidOperand,
                "stringify",
            ));
        }
    };
    let result =
        ctx.with_turn_parts(|interp, stack| interp.json_stringify_spec(stack, &context, args));
    match result {
        Ok(v) => Ok(v),
        Err(err) => Err(err.into_native(ctx.interp_mut(), "stringify")),
    }
}

fn native_json_call(
    ctx: &mut NativeCtx<'_>,
    method: otter_bytecode::method_id::JsonMethod,
    args: &[Value],
    object_proto: Option<Value>,
) -> Result<Value, NativeError> {
    let mut external_visit = |visitor: &mut dyn FnMut(*mut RawGc)| {
        for value in args {
            value.trace_value_slots(visitor);
        }
        if let Some(value) = object_proto.as_ref() {
            value.trace_value_slots(visitor);
        }
    };
    call_with_roots(
        method,
        args,
        ctx.heap_mut(),
        &mut external_visit,
        object_proto,
    )
    .map_err(|error| native_json_error(error, method.name()))
}

fn json_stringify(args: &[Value], gc_heap: &mut otter_gc::GcHeap) -> Result<Value, JsonError> {
    let value = args.first().cloned().unwrap_or(Value::undefined());
    let space = args.get(2).cloned().unwrap_or(Value::undefined());
    let opts = StringifyOptions::from_space_with_heap(&space, Some(gc_heap))?;
    match stringify_with_options(&value, &opts, gc_heap)? {
        Some(text) => Ok(Value::string(JsString::from_str(&text, gc_heap)?)),
        None => Ok(Value::undefined()),
    }
}

fn json_parse(args: &[Value], gc_heap: &mut otter_gc::GcHeap) -> Result<Value, JsonError> {
    let Some(s) = args.first().and_then(|v| v.as_string(gc_heap)) else {
        return Err(JsonError::BadArgument {
            name: "parse",
            index: 0,
            reason: "must be a string",
        });
    };
    let text = s.to_lossy_string(gc_heap);
    let value = parse(&text, gc_heap)?;
    Ok(value)
}

fn json_parse_with_roots(
    args: &[Value],
    gc_heap: &mut otter_gc::GcHeap,
    external_visit: &mut RootSlotVisitor<'_>,
    object_proto: Option<Value>,
) -> Result<Value, JsonError> {
    let Some(s) = args.first().and_then(|v| v.as_string(gc_heap)) else {
        return Err(JsonError::BadArgument {
            name: "parse",
            index: 0,
            reason: "must be a string",
        });
    };
    let text = s.to_lossy_string(gc_heap);
    let value = parse::parse_with_roots(&text, gc_heap, external_visit, object_proto)?;
    Ok(value)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn n(v: i32) -> Value {
        Value::number_i32(v)
    }

    fn make_heap() -> otter_gc::GcHeap {
        crate::object::fixture_heap()
    }

    #[test]
    fn stringify_primitives() {
        let mut heap = make_heap();
        assert_eq!(
            stringify(&Value::null(), &mut heap).unwrap().unwrap(),
            "null"
        );
        assert_eq!(
            stringify(&Value::boolean(true), &mut heap)
                .unwrap()
                .unwrap(),
            "true"
        );
        assert_eq!(stringify(&n(42), &mut heap).unwrap().unwrap(), "42");
        // Undefined → omitted (returns None).
        assert!(stringify(&Value::undefined(), &mut heap).unwrap().is_none());
    }

    #[test]
    fn stringify_nan_and_infinity_become_null() {
        let mut heap = make_heap();
        let nan = Value::number_f64(f64::NAN);
        let inf = Value::number_f64(f64::INFINITY);
        assert_eq!(stringify(&nan, &mut heap).unwrap().unwrap(), "null");
        assert_eq!(stringify(&inf, &mut heap).unwrap().unwrap(), "null");
    }

    #[test]
    fn stringify_object_preserves_insertion_order() {
        let mut heap = make_heap();
        let mut obj = crate::object::alloc_object_old_for_fixture(&mut heap).unwrap();
        assert!(
            crate::object::define_own_property_in_place(
                &mut obj,
                &mut heap,
                "b",
                crate::object::PropertyDescriptor::data(n(1), true, true, true)
            )
            .expect("fixture property allocation")
        );
        assert!(
            crate::object::define_own_property_in_place(
                &mut obj,
                &mut heap,
                "a",
                crate::object::PropertyDescriptor::data(n(2), true, true, true)
            )
            .expect("fixture property allocation")
        );
        let s = stringify(&Value::object(obj), &mut heap).unwrap().unwrap();
        assert_eq!(s, "{\"b\":1,\"a\":2}");
    }

    #[test]
    fn stringify_rejects_bigint() {
        let mut heap = make_heap();
        let bi = Value::big_int(
            crate::bigint::BigIntValue::from_decimal(&mut heap, "1")
                .unwrap()
                .unwrap(),
        );
        assert!(matches!(stringify(&bi, &mut heap), Err(JsonError::BigInt)));
    }

    #[test]
    fn stringify_uses_source_bytes_for_unmutated_parsed_array() {
        let mut heap = make_heap();
        let parsed = parse("[1,2,3,4]", &mut heap).unwrap();
        // Re-stringify should reproduce the input verbatim.
        let s = stringify(&parsed, &mut heap).unwrap().unwrap();
        assert_eq!(s, "[1,2,3,4]");
    }

    #[test]
    fn stringify_observably_equivalent_when_fast_path_disqualified() {
        let mut heap = make_heap();
        let Some(arr) = parse("[1,2,3]", &mut heap).unwrap().as_array() else {
            panic!("parsed value should be an array")
        };
        // Mutating the array invalidates source_bytes; stringify must
        // still produce a correct (though re-rendered) result.
        crate::array::set(arr, &mut heap, 0, Value::number_i32(99)).unwrap();
        let s = stringify(&Value::array(arr), &mut heap).unwrap().unwrap();
        assert_eq!(s, "[99,2,3]");
    }

    #[test]
    fn stringify_pretty_disables_source_bytes_fast_path() {
        let mut heap = make_heap();
        let parsed = parse("[1,2,3]", &mut heap).unwrap();
        let opts = StringifyOptions::from_space(&Value::number_i32(2)).unwrap();
        let s = stringify_with_options(&parsed, &opts, &mut heap)
            .unwrap()
            .unwrap();
        // Pretty output must reflect the indent setting, proving we
        // did not short-circuit through the captured raw bytes.
        assert_eq!(s, "[\n  1,\n  2,\n  3\n]");
    }

    #[test]
    fn parse_round_trip() {
        let mut heap = make_heap();
        let v = parse("{\"x\":[1,2,3]}", &mut heap).unwrap();
        if let Some(o) = v.as_object() {
            if let Some(arr) = crate::object::get(o, &heap, "x").and_then(|v| v.as_array()) {
                assert_eq!(crate::array::len(arr, &heap), 3);
                assert_eq!(crate::array::get(arr, &heap, 1).display_string(&heap), "2");
            } else {
                panic!("expected x: array");
            }
        } else {
            panic!("expected object");
        }
    }

    #[test]
    fn error_messages_are_specific() {
        // Cyclic — no path walk (cheap identity-pointer set on the
        // hot path; full path tracking can layer on later).
        let mut heap = make_heap();
        let mut obj = crate::object::alloc_object_old_for_fixture(&mut heap).unwrap();
        let self_ref = Value::object(obj);
        assert!(
            crate::object::define_own_property_in_place(
                &mut obj,
                &mut heap,
                "self",
                crate::object::PropertyDescriptor::data(self_ref, true, true, true)
            )
            .expect("fixture property allocation")
        );
        let err = stringify(&Value::object(obj), &mut heap).unwrap_err();
        assert!(matches!(err, JsonError::Cyclic));
        assert_eq!(
            err.to_string(),
            "JSON.stringify cannot serialize cyclic structures.",
        );

        // BigInt.
        let bi = Value::big_int(
            crate::bigint::BigIntValue::from_decimal(&mut heap, "1")
                .unwrap()
                .unwrap(),
        );
        let err = stringify(&bi, &mut heap).unwrap_err();
        assert_eq!(
            err.to_string(),
            "JSON.stringify cannot serialize BigInt values.",
        );

        // Parse with byte position.
        let mut gc_heap = make_heap();
        let err = parse("[1, 2,]", &mut gc_heap).unwrap_err();
        assert!(matches!(err, ParseError::Syntax { position: 6, message }
            if message == "trailing comma"));
    }
}

#[cfg(test)]
mod allocation_error_tests;

#[cfg(test)]
mod reviver_error_tests;
