//! `JSON` namespace — hand-rolled `stringify` and `parse`.
//!
//! Slice 32 picks the hot-path implementation deliberately: we
//! **do not** depend on `serde_json`. Serde's parser is general-
//! purpose and ~3–5× slower than a focused byte-cursor parser on
//! the JS shapes we actually serialize. Stringify and parse both
//! own their own buffer/cursor so we can keep them branch-free on
//! the common case (ASCII strings, small integers, dense arrays).
//!
//! # Contents
//! - [`JSON_SPEC`] — static namespace spec used by bootstrap.
//! - [`call`] — internal dispatcher shared by the `JSON.parse` and
//!   `JSON.stringify` native function entry points.
//! - [`stringify`] / [`parse`] — public entry points.
//! - [`stringify_with_options`] — programmable `space` + `replacer`.
//! - [`JsonError`] — failure mode the dispatcher converts to
//!   `VmError`.
//!
//! # Invariants
//! - **No recursion.** Both serializer and parser walk an explicit
//!   stack capped at `MAX_NESTING_DEPTH` (1024) so adversarial
//!   nested input cannot blow the host stack.
//! - **Cycle detection.** Stringify carries an identity visit set;
//!   revisiting an active node raises `JsonError::Cyclic`.
//! - **Deterministic key order.** Object properties enumerate in
//!   shape insertion order (`JsObject::borrow_props`).
//! - **NaN / ±Infinity / -0 → `null`** per spec §25.5.2.4.
//! - **BigInt → `TypeError`-equivalent** ([`JsonError::BigInt`]).
//! - **Strict parse.** Trailing commas, comments, single quotes,
//!   leading zeros, leading `+`, NaN/Infinity literals — all
//!   rejected. The parser walks `&[u8]` for the ASCII fast path
//!   and falls back to WTF-16 unescape only inside string literals.
//!
//! # See also
//! - <https://tc39.es/ecma262/#sec-json-object>

mod parse;
pub mod scan;
mod serialize;
mod stringify;

pub use parse::{ParseError, parse};
pub use stringify::{StringifyOptions, stringify, stringify_with_options};

use crate::string::JsString;
use crate::{NativeCtx, NativeError, Value, VmError};
use otter_gc::heap::RootSlotVisitor;
use otter_gc::raw::RawGc;

// `JSON_SPEC` + `Intrinsic` are generated by `holt!`. The static
// spec name + intrinsic adapter name match the previous hand-written
// surface byte-for-byte (`JSON_SPEC: NamespaceSpec`, `pub struct
// Intrinsic;` implementing `BuiltinIntrinsic` with NAME = "JSON",
// FEATURE = CORE, and the same `NamespaceBuilder`-driven install
// body). First production consumer of the otter-themed macro family
// (Phase 4.2a pathfinder).
otter_macros::holt! {
    name = "JSON",
    feature = CORE,
    methods = {
        "parse"     / 2 => native_parse,
        "stringify" / 3 => native_stringify,
        "rawJSON"   / 1 => native_raw_json,
        "isRawJSON" / 1 => native_is_raw_json,
    },
}

/// Hard cap on nesting depth. Both stringify and parse abort with
/// `JsonError::TooDeep` once exceeded — keeps adversarial input
/// from blowing the host stack and matches V8's `JSON.stringify`
/// behaviour for very deep objects.
pub const MAX_NESTING_DEPTH: usize = 1024;

/// Failure modes for [`call`].
#[derive(Debug, Clone, thiserror::Error)]
#[non_exhaustive]
pub enum JsonError {
    /// `JSON.<name>` is not a registered function.
    #[error("JSON.{0} is not defined")]
    UnknownMember(String),
    /// Argument failed type / value coercion.
    #[error("JSON.{name} argument {index} {reason}")]
    BadArgument {
        /// Function name.
        name: &'static str,
        /// Argument index (0-based).
        index: u16,
        /// Short reason.
        reason: &'static str,
    },
    /// Cycle detected while serialising.
    #[error("JSON.stringify cannot serialize cyclic structures.")]
    Cyclic,
    /// Nesting exceeded [`MAX_NESTING_DEPTH`].
    #[error("JSON nesting exceeded {limit} levels.")]
    TooDeep {
        /// Configured cap.
        limit: usize,
    },
    /// `BigInt` cannot be serialised per spec §25.5.2.4.
    #[error("JSON.stringify cannot serialize BigInt values.")]
    BigInt,
    /// Underlying string-heap allocation failed.
    #[error("out of memory: requested {requested_bytes} bytes, heap limit {heap_limit_bytes}")]
    OutOfMemory {
        /// Bytes requested.
        requested_bytes: u64,
        /// Heap cap (`0` = unlimited).
        heap_limit_bytes: u64,
    },
    /// Strict-mode parse failure.
    #[error("JSON.parse: {message} at byte {position}")]
    ParseFailed {
        /// Diagnostic body.
        message: String,
        /// 0-based byte offset.
        position: usize,
    },
}

impl From<otter_gc::OutOfMemory> for JsonError {
    fn from(err: otter_gc::OutOfMemory) -> Self {
        Self::OutOfMemory {
            requested_bytes: err.requested_bytes(),
            heap_limit_bytes: err.heap_limit_bytes(),
        }
    }
}

impl From<ParseError> for JsonError {
    fn from(err: ParseError) -> Self {
        Self::ParseFailed {
            message: err.message,
            position: err.position,
        }
    }
}

/// Dispatch a `JSON.<method>(args...)` call. Routes via the
/// typed method id emitted by the compiler — no string-table
/// indirection or per-call name match.
pub fn call(
    method: otter_bytecode::method_id::JsonMethod,
    args: &[Value],
    gc_heap: &mut otter_gc::GcHeap,
) -> Result<Value, JsonError> {
    use otter_bytecode::method_id::JsonMethod;
    match method {
        JsonMethod::Stringify => json_stringify(args, gc_heap),
        JsonMethod::Parse => json_parse(args, gc_heap),
    }
}

/// Dispatch a `JSON.<method>` call with an explicit root visitor for callers
/// that have a live VM stack or native root set.
pub(crate) fn call_with_roots(
    method: otter_bytecode::method_id::JsonMethod,
    args: &[Value],
    gc_heap: &mut otter_gc::GcHeap,
    external_visit: &mut RootSlotVisitor<'_>,
    object_proto: Option<Value>,
) -> Result<Value, JsonError> {
    use otter_bytecode::method_id::JsonMethod;
    match method {
        JsonMethod::Stringify => json_stringify(args, gc_heap),
        JsonMethod::Parse => json_parse_with_roots(args, gc_heap, external_visit, object_proto),
    }
}

fn native_parse(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    let coerced = coerce_json_parse_args(ctx, args)?;
    // §25.5.1 results expose the realm `%Object.prototype%`. Hand it to the
    // parser so each object is constructed with that prototype in place, instead
    // of walking the whole result tree afterwards to install it.
    let object_proto = ctx
        .interp_mut()
        .object_prototype_object_opt()
        .map(Value::object);
    let unfiltered = native_json_call(
        ctx,
        otter_bytecode::method_id::JsonMethod::Parse,
        &coerced,
        object_proto,
    )?;

    // §25.5.1 steps 7–9 — a callable reviver drives InternalizeJSONProperty.
    let reviver = args.get(1).copied().unwrap_or_else(Value::undefined);
    if !reviver.is_callable() {
        return Ok(unfiltered);
    }
    let context = ctx
        .execution_context()
        .cloned()
        .ok_or_else(|| NativeError::TypeError {
            name: "parse",
            reason: "missing execution context".to_string(),
        })?;
    // §25.5.1 `json-parse-with-source` — record the source-span tree so
    // the reviver's `context.source` argument is populated for leaves.
    let source_tree = coerced
        .first()
        .and_then(|v| v.as_string(ctx.heap()))
        .map(|s| s.to_lossy_string(ctx.heap()))
        .and_then(|text| parse::parse_source_tree(&text));
    let result = ctx.with_turn_parts(|interp, stack| {
        interp.json_internalize_root(stack, &context, unfiltered, reviver, source_tree.as_ref())
    });
    match result {
        Ok(v) => Ok(v),
        Err(err) => Err(vm_to_native_parse(ctx.interp_mut(), err)),
    }
}

/// Map a reviver-path [`VmError`] onto the native surface, preserving
/// user exceptions (`Uncaught` → `Thrown`).
fn vm_to_native_parse(interp: &crate::Interpreter, err: VmError) -> NativeError {
    match err {
        VmError::Uncaught => {
            let value = match interp.take_error_detail() {
                Some(crate::run_control::ErrorDetail::Uncaught(m)) => m,
                _ => Default::default(),
            };
            NativeError::Thrown {
                name: "parse",
                message: value.into(),
            }
        }
        VmError::RangeError => {
            let message = match interp.take_error_detail() {
                Some(crate::run_control::ErrorDetail::Message(m)) => m,
                _ => Default::default(),
            };
            NativeError::RangeError {
                name: "parse",
                reason: message.into(),
            }
        }
        VmError::Exit { code } => NativeError::Exit { code },
        VmError::TypeError => {
            let message = match interp.take_error_detail() {
                Some(crate::run_control::ErrorDetail::Message(m)) => m,
                _ => Default::default(),
            };
            NativeError::TypeError {
                name: "parse",
                reason: message.into(),
            }
        }
        other => NativeError::TypeError {
            name: "parse",
            reason: other.to_string(),
        },
    }
}

/// §25.5.1 step 1 — `JText = ? ToString(text)`. Non-string `text`
/// arguments coerce through the spec ToPrimitive (hint:string) +
/// ToString ladder so a `JSON.parse({ toString(){ return '...' } })`
/// observes the user hook.
fn coerce_json_parse_args(
    ctx: &mut NativeCtx<'_>,
    args: &[Value],
) -> Result<smallvec::SmallVec<[Value; 4]>, NativeError> {
    let mut out: smallvec::SmallVec<[Value; 4]> = args.iter().cloned().collect();
    // §25.5.1 step 1 runs `ToString(text)` even for a missing argument:
    // `JSON.parse()` coerces `undefined` → `"undefined"` and parses it
    // (yielding a SyntaxError), rather than a TypeError on a bad arg.
    if out.is_empty() {
        out.push(Value::undefined());
    }
    if let Some(slot) = out.first_mut() {
        let s = coerce_text_to_string(ctx, *slot, "parse")?;
        *slot = Value::string(s);
    }
    Ok(out)
}

/// §7.1.17 `ToString(text)` for JSON text inputs. Strings pass
/// through; other primitives use their display form; objects run the
/// ToPrimitive(hint:string) + ToString ladder so a user `toString` /
/// `valueOf` is observable. Symbols throw a `TypeError`. User
/// exceptions propagate verbatim.
fn coerce_text_to_string(
    ctx: &mut NativeCtx<'_>,
    value: Value,
    name: &'static str,
) -> Result<JsString, NativeError> {
    let exec = ctx
        .execution_context()
        .cloned()
        .ok_or_else(|| NativeError::TypeError {
            name,
            reason: "missing execution context".to_string(),
        })?;
    let result = ctx.with_turn_parts(|interp, stack| {
        crate::coerce::to_js_string_or_throw(interp, stack, &exec, &value)
    });
    result
        .map_err(|error| crate::native_function::vm_to_native_error(ctx.interp_mut(), error, name))
}

/// §25.5.3 `JSON.rawJSON(text)`.
fn native_raw_json(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    let value = args.first().copied().unwrap_or_else(Value::undefined);
    let json_string = coerce_text_to_string(ctx, value, "rawJSON")?;
    let text = json_string.to_lossy_string(ctx.heap());

    // §25.5.3 step 2 — reject empty input or leading/trailing JSON
    // whitespace.
    let bytes = text.as_bytes();
    let bad_edge = bytes.is_empty()
        || matches!(bytes.first(), Some(0x09 | 0x0A | 0x0D | 0x20))
        || matches!(bytes.last(), Some(0x09 | 0x0A | 0x0D | 0x20));
    if bad_edge {
        return Err(NativeError::SyntaxError {
            name: "rawJSON",
            reason: "invalid rawJSON text".to_string(),
        });
    }

    ctx.scope(|mut scope| {
        let raw_value = scope.value(Value::string(json_string));

        // §25.5.3 steps 3–4 — must be a valid JSON primitive (not an
        // object or array). `raw_value` remains rooted while parsing allocates.
        match parse::parse(&text, scope.context().heap_mut()) {
            Ok(parsed) if parsed.as_object().is_some() || parsed.as_array().is_some() => {
                return Err(NativeError::SyntaxError {
                    name: "rawJSON",
                    reason: "rawJSON text must be a primitive JSON value".to_string(),
                });
            }
            Ok(_) => {}
            Err(err) => {
                return Err(NativeError::SyntaxError {
                    name: "rawJSON",
                    reason: format!("JSON Parse error: {} at byte {}", err.message, err.position),
                });
            }
        }

        // §25.5.3 steps 5–7 — null-proto object, own "rawJSON" data
        // property, [[IsRawJSON]] slot, then frozen.
        let obj = scope.bare_object()?;
        scope.set(obj, "rawJSON", raw_value)?;
        let obj_value = scope.raw(obj);
        let obj_handle = obj_value.as_object().expect("bare object handle");
        crate::object::set_is_raw_json(obj_handle, scope.context().heap_mut(), true);
        let obj_handle = scope.raw(obj).as_object().expect("rooted rawJSON object");
        crate::object::freeze(obj_handle, scope.context().heap_mut());
        Ok(scope.finish(obj))
    })
}

/// §25.5.4 `JSON.isRawJSON(O)`.
fn native_is_raw_json(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    let is_raw = args
        .first()
        .and_then(|v| v.as_object())
        .is_some_and(|obj| crate::object::is_raw_json(obj, ctx.heap()));
    Ok(Value::boolean(is_raw))
}

fn native_stringify(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    // §25.5.2.1 — the full algorithm needs a live execution context so
    // `toJSON`, the replacer, and accessor `[[Get]]` are observable.
    let context = ctx
        .execution_context()
        .cloned()
        .ok_or_else(|| NativeError::TypeError {
            name: "stringify",
            reason: "missing execution context".to_string(),
        })?;
    let result =
        ctx.with_turn_parts(|interp, stack| interp.json_stringify_spec(stack, &context, args));
    match result {
        Ok(v) => Ok(v),
        Err(err) => Err(vm_to_native_stringify(ctx.interp_mut(), err)),
    }
}

/// Map a serializer [`VmError`] to the native error surface. A user
/// exception thrown from a getter / `toJSON` / replacer must surface
/// verbatim (`VmError::Uncaught` → `NativeError::Thrown`) so its
/// original constructor is observable; only the serializer's own
/// synthetic failures (cyclic, BigInt, depth) become `TypeError`s.
fn vm_to_native_stringify(interp: &crate::Interpreter, err: VmError) -> NativeError {
    match err {
        VmError::Uncaught => {
            let value = match interp.take_error_detail() {
                Some(crate::run_control::ErrorDetail::Uncaught(m)) => m,
                _ => Default::default(),
            };
            NativeError::Thrown {
                name: "stringify",
                message: value.into(),
            }
        }
        VmError::SyntaxError => {
            let message = match interp.take_error_detail() {
                Some(crate::run_control::ErrorDetail::Message(m)) => m,
                _ => Default::default(),
            };
            NativeError::SyntaxError {
                name: "stringify",
                reason: message.into(),
            }
        }
        VmError::RangeError => {
            let message = match interp.take_error_detail() {
                Some(crate::run_control::ErrorDetail::Message(m)) => m,
                _ => Default::default(),
            };
            NativeError::RangeError {
                name: "stringify",
                reason: message.into(),
            }
        }
        VmError::Exit { code } => NativeError::Exit { code },
        VmError::TypeError => {
            let message = match interp.take_error_detail() {
                Some(crate::run_control::ErrorDetail::Message(m)) => m,
                _ => Default::default(),
            };
            NativeError::TypeError {
                name: "stringify",
                reason: message.into(),
            }
        }
        other => NativeError::TypeError {
            name: "stringify",
            reason: other.to_string(),
        },
    }
}

fn native_json_call(
    ctx: &mut NativeCtx<'_>,
    method: otter_bytecode::method_id::JsonMethod,
    args: &[Value],
    object_proto: Option<Value>,
) -> Result<Value, NativeError> {
    let mut external_visit = |visitor: &mut dyn FnMut(*mut RawGc)| {
        for value in args {
            value.trace_value_slots(visitor);
        }
        if let Some(value) = object_proto.as_ref() {
            value.trace_value_slots(visitor);
        }
    };
    call_with_roots(
        method,
        args,
        ctx.heap_mut(),
        &mut external_visit,
        object_proto,
    )
    .map_err(|err| {
        // §25.5.1 step 5 — `JSON.parse` reports malformed input as
        // `SyntaxError`. Every other failure (cycles, BigInt,
        // depth overflow, bad arguments, OOM) flows through
        // `TypeError` per spec.
        match err {
            JsonError::ParseFailed { message, position } => NativeError::SyntaxError {
                name: method.name(),
                reason: format!("JSON Parse error: {message} at byte {position}"),
            },
            other => NativeError::TypeError {
                name: method.name(),
                reason: other.to_string(),
            },
        }
    })
}

fn json_stringify(args: &[Value], gc_heap: &mut otter_gc::GcHeap) -> Result<Value, JsonError> {
    let value = args.first().cloned().unwrap_or(Value::undefined());
    let space = args.get(2).cloned().unwrap_or(Value::undefined());
    let opts = StringifyOptions::from_space_with_heap(&space, Some(gc_heap))?;
    match stringify_with_options(&value, &opts, gc_heap)? {
        Some(text) => Ok(Value::string(JsString::from_str(&text, gc_heap)?)),
        None => Ok(Value::undefined()),
    }
}

fn json_parse(args: &[Value], gc_heap: &mut otter_gc::GcHeap) -> Result<Value, JsonError> {
    let Some(s) = args.first().and_then(|v| v.as_string(gc_heap)) else {
        return Err(JsonError::BadArgument {
            name: "parse",
            index: 0,
            reason: "must be a string",
        });
    };
    let text = s.to_lossy_string(gc_heap);
    let value = parse(&text, gc_heap)?;
    Ok(value)
}

fn json_parse_with_roots(
    args: &[Value],
    gc_heap: &mut otter_gc::GcHeap,
    external_visit: &mut RootSlotVisitor<'_>,
    object_proto: Option<Value>,
) -> Result<Value, JsonError> {
    let Some(s) = args.first().and_then(|v| v.as_string(gc_heap)) else {
        return Err(JsonError::BadArgument {
            name: "parse",
            index: 0,
            reason: "must be a string",
        });
    };
    let text = s.to_lossy_string(gc_heap);
    let value = parse::parse_with_roots(&text, gc_heap, external_visit, object_proto)?;
    Ok(value)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn n(v: i32) -> Value {
        Value::number_i32(v)
    }

    fn make_heap() -> otter_gc::GcHeap {
        otter_gc::GcHeap::new().expect("gc heap")
    }

    #[test]
    fn stringify_primitives() {
        let mut heap = make_heap();
        assert_eq!(
            stringify(&Value::null(), &mut heap).unwrap().unwrap(),
            "null"
        );
        assert_eq!(
            stringify(&Value::boolean(true), &mut heap)
                .unwrap()
                .unwrap(),
            "true"
        );
        assert_eq!(stringify(&n(42), &mut heap).unwrap().unwrap(), "42");
        // Undefined → omitted (returns None).
        assert!(stringify(&Value::undefined(), &mut heap).unwrap().is_none());
    }

    #[test]
    fn stringify_nan_and_infinity_become_null() {
        let mut heap = make_heap();
        let nan = Value::number_f64(f64::NAN);
        let inf = Value::number_f64(f64::INFINITY);
        assert_eq!(stringify(&nan, &mut heap).unwrap().unwrap(), "null");
        assert_eq!(stringify(&inf, &mut heap).unwrap().unwrap(), "null");
    }

    #[test]
    fn stringify_object_preserves_insertion_order() {
        let mut heap = make_heap();
        let mut obj = crate::object::alloc_object_old_for_fixture(&mut heap).unwrap();
        crate::object::set(&mut obj, &mut heap, "b", n(1));
        crate::object::set(&mut obj, &mut heap, "a", n(2));
        let s = stringify(&Value::object(obj), &mut heap).unwrap().unwrap();
        assert_eq!(s, "{\"b\":1,\"a\":2}");
    }

    #[test]
    fn stringify_rejects_bigint() {
        let mut heap = make_heap();
        let bi = Value::big_int(
            crate::bigint::BigIntValue::from_decimal(&mut heap, "1")
                .unwrap()
                .unwrap(),
        );
        assert!(matches!(stringify(&bi, &mut heap), Err(JsonError::BigInt)));
    }

    #[test]
    fn stringify_uses_source_bytes_for_unmutated_parsed_array() {
        let mut heap = make_heap();
        let parsed = parse("[1,2,3,4]", &mut heap).unwrap();
        // Re-stringify should reproduce the input verbatim.
        let s = stringify(&parsed, &mut heap).unwrap().unwrap();
        assert_eq!(s, "[1,2,3,4]");
    }

    #[test]
    fn stringify_observably_equivalent_when_fast_path_disqualified() {
        let mut heap = make_heap();
        let Some(arr) = parse("[1,2,3]", &mut heap).unwrap().as_array() else {
            panic!("parsed value should be an array")
        };
        // Mutating the array invalidates source_bytes; stringify must
        // still produce a correct (though re-rendered) result.
        crate::array::set(arr, &mut heap, 0, Value::number_i32(99)).unwrap();
        let s = stringify(&Value::array(arr), &mut heap).unwrap().unwrap();
        assert_eq!(s, "[99,2,3]");
    }

    #[test]
    fn stringify_pretty_disables_source_bytes_fast_path() {
        let mut heap = make_heap();
        let parsed = parse("[1,2,3]", &mut heap).unwrap();
        let opts = StringifyOptions::from_space(&Value::number_i32(2)).unwrap();
        let s = stringify_with_options(&parsed, &opts, &mut heap)
            .unwrap()
            .unwrap();
        // Pretty output must reflect the indent setting, proving we
        // did not short-circuit through the captured raw bytes.
        assert_eq!(s, "[\n  1,\n  2,\n  3\n]");
    }

    #[test]
    fn parse_round_trip() {
        let mut heap = make_heap();
        let v = parse("{\"x\":[1,2,3]}", &mut heap).unwrap();
        if let Some(o) = v.as_object() {
            if let Some(arr) = crate::object::get(o, &heap, "x").and_then(|v| v.as_array()) {
                assert_eq!(crate::array::len(arr, &heap), 3);
                assert_eq!(crate::array::get(arr, &heap, 1).display_string(&heap), "2");
            } else {
                panic!("expected x: array");
            }
        } else {
            panic!("expected object");
        }
    }

    #[test]
    fn error_messages_are_specific() {
        // Cyclic — no path walk (cheap identity-pointer set on the
        // hot path; full path tracking can layer on later).
        let mut heap = make_heap();
        let mut obj = crate::object::alloc_object_old_for_fixture(&mut heap).unwrap();
        let self_ref = Value::object(obj);
        crate::object::set(&mut obj, &mut heap, "self", self_ref);
        let err = stringify(&Value::object(obj), &mut heap).unwrap_err();
        assert!(matches!(err, JsonError::Cyclic));
        assert_eq!(
            err.to_string(),
            "JSON.stringify cannot serialize cyclic structures.",
        );

        // BigInt.
        let bi = Value::big_int(
            crate::bigint::BigIntValue::from_decimal(&mut heap, "1")
                .unwrap()
                .unwrap(),
        );
        let err = stringify(&bi, &mut heap).unwrap_err();
        assert_eq!(
            err.to_string(),
            "JSON.stringify cannot serialize BigInt values.",
        );

        // Parse with byte position.
        let mut gc_heap = make_heap();
        let err = parse("[1, 2,]", &mut gc_heap).unwrap_err();
        assert_eq!(err.position, 6);
        assert_eq!(err.message, "trailing comma");
    }
}
