//! `%Date%` constructor installer.
//!
//! Implements ECMA-262 §21.4 Date Objects: the `Date()` constructor and
//! its prototype wiring.
//!
//! # See also
//! - <https://tc39.es/ecma262/#sec-date-objects>

use crate::Value;
use crate::{JsString, NativeCtx, NativeError};

// §21.4.3 Date statics — trampolines that route to the typed
// dispatcher with no `this`. The constructor's `[[Construct]]` /
// `[[Call]]` slot still handles the `Date(...)` and `new Date(...)`
// shapes via `date_ctor_call`.
fn date_now_call(ctx: &mut NativeCtx<'_>, _args: &[Value]) -> Result<Value, NativeError> {
    crate::date::dispatch::call_static(otter_bytecode::method_id::DateMethod::Now, &[], ctx.heap())
        .map_err(|err| NativeError::TypeError {
            name: "Date.now",
            reason: err.to_string(),
        })
}
fn date_parse_call(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    crate::date::dispatch::call_static(
        otter_bytecode::method_id::DateMethod::Parse,
        args,
        ctx.heap(),
    )
    .map_err(|err| NativeError::TypeError {
        name: "Date.parse",
        reason: err.to_string(),
    })
}
fn date_utc_call(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    crate::date::dispatch::call_static(otter_bytecode::method_id::DateMethod::UTC, args, ctx.heap())
        .map_err(|err| NativeError::TypeError {
            name: "Date.UTC",
            reason: err.to_string(),
        })
}

fn date_ctor_call(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    let time = {
        let heap = ctx.heap_mut();
        crate::date::dispatch::construct_time_value(args, heap)
    };
    if ctx.is_construct_call() {
        // §21.4.2.1 — `new Date(...)`. The construct receiver is
        // a freshly allocated JsObject (via OrdinaryCreateFromConstructor
        // on `Date`). Install the `[[DateValue]]` internal slot and
        // return it.
        if let Some(obj) = ctx.this_value().as_object() {
            crate::object::set_date_data(obj, ctx.heap_mut(), time);
            return Ok(Value::object(obj));
        }
        return Err(NativeError::TypeError {
            name: "Date",
            reason: "expected object receiver in `new Date(...)`".to_string(),
        });
    }
    // §21.4.2.2 — `Date()` without `new` returns the current time
    // rendered as an ISO string.
    let text = crate::date::to_iso_string(time).unwrap_or_else(|| "Invalid Date".to_string());
    let value =
        JsString::from_str(&text, ctx.heap_mut()).map_err(|err| NativeError::TypeError {
            name: "Date",
            reason: err.to_string(),
        })?;
    Ok(Value::string(value))
}

// `DATE_SPEC` + `Intrinsic` generated by `couch!`. §21.4 — Date
// constructor (`new Date(...)` produces a DateValue-bearing
// JsObject, bare `Date()` returns an ISO string). Statics
// (`now` / `parse` / `UTC`) trampoline to the typed dispatcher
// above. Prototype methods come from the pre-built
// `DATE_PROTOTYPE_METHODS` + `DATE_PROTOTYPE_EXTRA_METHODS`
// slices generated by the `date_prototype_methods!` decl-macro,
// fed in via the `method_specs = [...]` couch! field.
//
// Hand-written installer used a plain JsObject + `constructor_native`
// attachment; switched here to the standard NativeFunction
// constructor path that Proxy / Iterator / Promise use.
otter_macros::couch! {
    name = "Date",
    feature = CORE,
    constructor = (length = 7, call = date_ctor_call),
    statics = {
        "now"   / 0 => date_now_call,
        "parse" / 1 => date_parse_call,
        "UTC"   / 7 => date_utc_call,
    },
    prototype = {
        method_specs = [
            crate::date::prototype::DATE_PROTOTYPE_METHODS,
            crate::date::prototype::DATE_PROTOTYPE_EXTRA_METHODS,
        ],
    },
}
