//! `%Iterator%` constructor + post-bootstrap well-known wiring.
//!
//! Implements ECMA-262 §27.1 The Iterator Constructor (ES2025
//! iterator-helpers): the `Iterator()` abstract constructor and the
//! `%Iterator.prototype%` chain. The post-bootstrap hook attaches
//! `@@iterator` and `@@toStringTag` once the well-known symbol table
//! is materialised.
//!
//! # See also
//! - <https://tc39.es/ecma262/#sec-iterator-constructor>

use crate::Value;
use crate::bootstrap::native_static_with_value_roots;
use crate::js_surface::JsSurfaceError;
use crate::object::{self, JsObject};

/// §27.1.1.1 `Iterator()` constructor — abstract base for the
/// ES2025 iterator-helpers protocol. Direct calls / direct `new`
/// throw `TypeError`; subclass `super()` calls allocate an
/// ordinary object inheriting from the new-target's `.prototype`.
fn iterator_ctor_call(
    ctx: &mut crate::NativeCtx<'_>,
    _args: &[Value],
) -> Result<Value, crate::NativeError> {
    let new_target = ctx.new_target().cloned();
    let Some(new_target) = new_target else {
        return Err(crate::NativeError::TypeError {
            name: "Iterator",
            reason: "constructor Iterator requires 'new'".to_string(),
        });
    };
    // §27.1.1.1 step 2 — OrdinaryCreateFromConstructor(new.target,
    // "%Iterator.prototype%"). Resolve the prototype off the
    // new-target so subclass `class T extends Iterator { … }` /
    // `new T()` inherits from `T.prototype`.
    let new_target_root = new_target;
    let obj = ctx
        .alloc_object_with_roots(&[&new_target_root], &[])
        .map_err(|_| crate::NativeError::TypeError {
            name: "Iterator",
            reason: "out of memory".to_string(),
        })?;
    let proto = crate::intrinsics::shared::native_new_target_prototype(ctx, "Iterator")?;
    let proto_obj = match proto.and_then(|v| v.as_object()) {
        Some(p) => Some(p),
        // OrdinaryCreateFromConstructor fallback — a non-object
        // `prototype` resolves to the intrinsic default
        // `%Iterator.prototype%`.
        None => ctx
            .cx
            .interp
            .constructor_prototype_value("Iterator")
            .ok()
            .and_then(|v| v.as_object()),
    };
    if let Some(proto_obj) = proto_obj {
        crate::object::set_prototype(obj, ctx.heap_mut(), Some(proto_obj));
    }
    Ok(Value::object(obj))
}

// `ITERATOR_SPEC` + `IteratorIntrinsic` generated by `couch!`.
// §27.1 — ES2025 Iterator constructor (abstract base for the
// iterator-helpers protocol; calls / direct `new` throw, subclass
// `super()` allocates via OrdinaryCreateFromConstructor). The
// `couch!` install body links the prototype to `%Object.prototype%`
// per §27.1.2 + auto-installs the `constructor` back-pointer. The
// symbol-keyed members (`@@iterator`, `@@toStringTag`) land
// post-bootstrap in [`install_iterator_well_knowns_post_bootstrap`].
otter_macros::couch! {
    name = "Iterator",
    feature = CORE,
    intrinsic = IteratorIntrinsic,
    constructor = (length = 0, call = iterator_ctor_call),
    statics = {
        "from" / 1 => iterator_from_native,
    },
    prototype = {
        methods = {
            "map"     / 1 => iterator_proto_map,
            "filter"  / 1 => iterator_proto_filter,
            "take"    / 1 => iterator_proto_take,
            "drop"    / 1 => iterator_proto_drop,
            "flatMap" / 1 => iterator_proto_flat_map,
            "toArray" / 0 => iterator_proto_to_array,
            "forEach" / 1 => iterator_proto_for_each,
            "reduce"  / 1 => iterator_proto_reduce,
            "some"    / 1 => iterator_proto_some,
            "every"   / 1 => iterator_proto_every,
            "find"    / 1 => iterator_proto_find,
            // §27.1.2 — `%Iterator.prototype%` itself carries NO own
            // `next` / `return` / `throw`; those live on the concrete
            // iterator prototypes (`%IteratorHelperPrototype%`,
            // `%WrapForValidIteratorPrototype%`, the per-kind built-in
            // prototypes, `%GeneratorPrototype%`) built post-bootstrap.
        },
    },
}

/// §27.1.2.1 `Iterator.prototype[@@iterator]` — returns the
/// receiver unchanged so any iterator value is itself iterable.
///
/// <https://tc39.es/ecma262/#sec-iteratorprototype-%symbol.iterator%>
fn iterator_proto_symbol_iterator(
    ctx: &mut crate::NativeCtx<'_>,
    _args: &[Value],
) -> Result<Value, crate::NativeError> {
    Ok(*ctx.this_value())
}

/// Post-bootstrap pass that installs the symbol-keyed members of
/// `%Iterator.prototype%`: `@@iterator` (returns `this`) and
/// `@@toStringTag = "Iterator"`. Runs after the well-known symbol
/// table is materialised in the same phase that installs
/// `@@toStringTag` on TypedArray prototypes.
pub fn install_iterator_well_knowns_post_bootstrap(
    heap: &mut otter_gc::GcHeap,
    global: JsObject,
    well_known: &crate::symbol::WellKnownSymbols,
) -> Result<(), JsSurfaceError> {
    use crate::symbol::WellKnown;
    let iter_value = object::get(global, heap, "Iterator");
    let prototype = if let Some(ctor) = iter_value.as_ref().and_then(|v| v.as_native_function()) {
        ctor.own_property_descriptor(heap, "prototype")
            .ok()
            .flatten()
            .and_then(|d| match d.kind {
                crate::object::DescriptorKind::Data { value } => value.as_object(),
                _ => None,
            })
    } else if let Some(iterator_ctor) = iter_value.and_then(|v| v.as_object()) {
        object::get(iterator_ctor, heap, "prototype").and_then(|v| v.as_object())
    } else {
        None
    };
    let Some(prototype) = prototype else {
        return Ok(());
    };
    let proto_root = Value::object(prototype);
    let symbol_iter_fn = native_static_with_value_roots(
        heap,
        "[Symbol.iterator]",
        0,
        iterator_proto_symbol_iterator,
        &[&proto_root],
    )
    .map_err(|_| JsSurfaceError::OutOfMemory)?;
    let iter_sym = well_known.get(WellKnown::Iterator);
    object::define_own_symbol_property_partial(
        prototype,
        heap,
        iter_sym,
        crate::object::PartialPropertyDescriptor {
            value: Some(Value::native_function(symbol_iter_fn)),
            writable: Some(true),
            enumerable: Some(false),
            configurable: Some(true),
            ..Default::default()
        },
    );
    let tag_sym = well_known.get(WellKnown::ToStringTag);
    let tag = crate::string::JsString::from_str("Iterator", heap)
        .map_err(|_| JsSurfaceError::OutOfMemory)?;
    object::define_own_symbol_property_partial(
        prototype,
        heap,
        tag_sym,
        crate::object::PartialPropertyDescriptor {
            value: Some(Value::string(tag)),
            writable: Some(false),
            enumerable: Some(false),
            configurable: Some(true),
            ..Default::default()
        },
    );
    Ok(())
}

/// Build the per-kind iterator prototypes
/// (`%ArrayIteratorPrototype%`, `%MapIteratorPrototype%`,
/// `%SetIteratorPrototype%`, `%StringIteratorPrototype%`,
/// `%RegExpStringIteratorPrototype%`) chained off `parent`
/// (`%IteratorPrototype%`). Called post-bootstrap once
/// `%IteratorPrototype%` is reachable.
pub fn build_builtin_iterator_prototypes_post_bootstrap(
    heap: &mut otter_gc::GcHeap,
    shape_root: object::ShapeHandle,
    parent: JsObject,
    well_known: &crate::symbol::WellKnownSymbols,
) -> Result<crate::bootstrap::BuiltinIteratorPrototypes, JsSurfaceError> {
    use crate::symbol::WellKnown;
    let parent_value = Value::object(parent);
    let tag_sym = well_known.get(WellKnown::ToStringTag);
    let mut make = |tag: &'static str| -> Result<JsObject, JsSurfaceError> {
        let mut proto = {
            let mut visit = |visitor: &mut dyn FnMut(*mut otter_gc::raw::RawGc)| {
                parent_value.trace_value_slots(visitor);
            };
            object::alloc_object_with_shape_roots(heap, shape_root, &mut visit)
                .map_err(|_| JsSurfaceError::OutOfMemory)?
        };
        object::set_prototype(proto, heap, Some(parent));
        let tag_sym_root = tag_sym;
        let tag_string = {
            let mut visit = |visitor: &mut dyn FnMut(*mut otter_gc::raw::RawGc)| {
                parent_value.trace_value_slots(visitor);
                tag_sym_root.trace_value_slots(visitor);
                let p = &mut proto as *mut JsObject as *mut otter_gc::raw::RawGc;
                visitor(p);
            };
            crate::string::JsString::from_str_with_roots(tag, heap, &mut visit)
                .map_err(|_| JsSurfaceError::OutOfMemory)?
        };
        object::define_own_symbol_property_partial(
            proto,
            heap,
            tag_sym_root,
            object::PartialPropertyDescriptor {
                value: Some(Value::string(tag_string)),
                writable: Some(false),
                enumerable: Some(false),
                configurable: Some(true),
                ..Default::default()
            },
        );
        Ok(proto)
    };
    let array = make("Array Iterator")?;
    let map = make("Map Iterator")?;
    let set = make("Set Iterator")?;
    let string = make("String Iterator")?;
    let regexp_string = make("RegExp String Iterator")?;
    let helper = make("Iterator Helper")?;
    // §27.1.3.2 — `%WrapForValidIteratorPrototype%` carries no
    // `@@toStringTag` of its own.
    let wrap_for_valid_iterator = {
        let mut visit = |visitor: &mut dyn FnMut(*mut otter_gc::raw::RawGc)| {
            parent_value.trace_value_slots(visitor);
        };
        let proto = object::alloc_object_with_shape_roots(heap, shape_root, &mut visit)
            .map_err(|_| JsSurfaceError::OutOfMemory)?;
        object::set_prototype(proto, heap, Some(parent));
        proto
    };
    let install_method = |heap: &mut otter_gc::GcHeap,
                          proto: JsObject,
                          name: &'static str,
                          length: u8,
                          call: crate::native_function::NativeFastFn,
                          label: &'static str|
     -> Result<(), JsSurfaceError> {
        let proto_root = Value::object(proto);
        let f = native_static_with_value_roots(heap, name, length, call, &[&proto_root])
            .map_err(|_| JsSurfaceError::OutOfMemory)?;
        if !object::define_own_property(
            proto,
            heap,
            name,
            object::PropertyDescriptor::data(Value::native_function(f), true, false, true),
        ) {
            return Err(JsSurfaceError::DefinePropertyFailed(label));
        }
        Ok(())
    };
    install_method(
        heap,
        regexp_string,
        "next",
        0,
        regexp_string_iterator_proto_next,
        "RegExpStringIteratorPrototype.next",
    )?;
    // §22.1.5.1 / §23.1.5.1 / §24.1.5.1 / §24.2.5.1 — each per-kind
    // built-in iterator prototype owns its `next`.
    install_method(
        heap,
        array,
        "next",
        0,
        iterator_proto_next,
        "ArrayIteratorPrototype.next",
    )?;
    install_method(
        heap,
        map,
        "next",
        0,
        iterator_proto_next,
        "MapIteratorPrototype.next",
    )?;
    install_method(
        heap,
        set,
        "next",
        0,
        iterator_proto_next,
        "SetIteratorPrototype.next",
    )?;
    install_method(
        heap,
        string,
        "next",
        0,
        iterator_proto_next,
        "StringIteratorPrototype.next",
    )?;
    // §27.1.2.1 — `%IteratorHelperPrototype%` owns `next` and `return`.
    install_method(
        heap,
        helper,
        "next",
        0,
        iterator_proto_next,
        "IteratorHelperPrototype.next",
    )?;
    install_method(
        heap,
        helper,
        "return",
        1,
        iterator_proto_return,
        "IteratorHelperPrototype.return",
    )?;
    // §27.1.3.2 — `%WrapForValidIteratorPrototype%` owns `next` and
    // `return`, both forwarding to the wrapped iterator.
    install_method(
        heap,
        wrap_for_valid_iterator,
        "next",
        0,
        iterator_proto_next,
        "WrapForValidIteratorPrototype.next",
    )?;
    install_method(
        heap,
        wrap_for_valid_iterator,
        "return",
        1,
        iterator_proto_return,
        "WrapForValidIteratorPrototype.return",
    )?;
    Ok(crate::bootstrap::BuiltinIteratorPrototypes {
        array,
        map,
        set,
        string,
        regexp_string,
        helper,
        wrap_for_valid_iterator,
    })
}

fn iterator_receiver(
    ctx: &mut crate::NativeCtx<'_>,
    name: &'static str,
) -> Result<crate::IteratorHandle, crate::NativeError> {
    let this_value = *ctx.this_value();
    if let Some(h) = this_value.as_iterator() {
        return Ok(h);
    }
    if let Some(g) = this_value.as_generator() {
        let gen_value = Value::generator(g);
        let state = crate::IteratorState::Generator { handle: g };
        return ctx
            .alloc_iterator_state(state, &[&gen_value], &[])
            .map_err(|_| crate::NativeError::TypeError {
                name,
                reason: "iterator allocation failed".to_string(),
            });
    }
    // §7.4.4 GetIteratorDirect — the `Iterator.prototype.X` helpers
    // accept any Object receiver; `next` is read once here and NOT
    // checked for callability (a non-callable `next` throws when the
    // first step is driven, per IteratorNext).
    if !crate::abstract_ops::is_primitive(&this_value) {
        let (interp, exec_ctx) = ctx.interp_mut_and_context();
        let exec_ctx = exec_ctx.ok_or_else(|| crate::NativeError::TypeError {
            name,
            reason: "missing execution context".to_string(),
        })?;
        let next_key = crate::VmPropertyKey::String("next");
        let outcome = interp
            .ordinary_get_value(&exec_ctx, this_value, this_value, &next_key, 0)
            .map_err(|e| crate::native_function::vm_to_native_error(e, name))?;
        let next_method = match outcome {
            crate::VmGetOutcome::Value(v) => v,
            crate::VmGetOutcome::InvokeGetter { getter } => {
                let args: smallvec::SmallVec<[Value; 8]> = smallvec::SmallVec::new();
                interp
                    .run_callable_sync(&exec_ctx, &getter, this_value, args)
                    .map_err(|e| crate::native_function::vm_to_native_error(e, name))?
            }
        };
        let this_root = this_value;
        let state = crate::IteratorState::User {
            iterator: this_value,
            next_method: Some(next_method),
        };
        return ctx
            .alloc_iterator_state(state, &[&this_root, &next_method], &[])
            .map_err(|_| crate::NativeError::TypeError {
                name,
                reason: "iterator allocation failed".to_string(),
            });
    }
    Err(crate::NativeError::TypeError {
        name,
        reason: "this is not an object".to_string(),
    })
}

/// §27.1.4.x step 2 — every `Iterator.prototype.*` helper requires an
/// Object receiver; primitives throw TypeError before any argument
/// coercion or validation.
fn require_object_receiver(
    this_value: &Value,
    name: &'static str,
) -> Result<(), crate::NativeError> {
    if crate::abstract_ops::is_primitive(this_value) {
        return Err(crate::NativeError::TypeError {
            name,
            reason: "this is not an object".to_string(),
        });
    }
    Ok(())
}

/// §27.1.4.x — argument validation failures close the receiver
/// (IteratorClose with the validation error as completion) before the
/// iterator record is built. The original abrupt completion wins over
/// anything the close itself throws, per §7.4.9.
fn close_receiver_on_validation_failure(
    ctx: &mut crate::NativeCtx<'_>,
    this_value: Value,
    err: crate::NativeError,
) -> crate::NativeError {
    let (interp, exec_ctx) = ctx.interp_mut_and_context();
    let Some(exec_ctx) = exec_ctx else {
        return err;
    };
    let original_throw = interp.take_pending_uncaught_throw();
    let _ = interp.iterator_close_value_sync(&exec_ctx, this_value);
    let _ = interp.take_pending_uncaught_throw();
    if let Some(value) = original_throw {
        interp.set_pending_uncaught_throw(value);
    }
    err
}

/// Strict iterator receiver used by `%IteratorPrototype%.next/return/throw`.
/// Only accepts built-in iterator-shaped values (`Value::Iterator`,
/// `Value::Generator`); non-iterator receivers throw `TypeError` per
/// §27.1.5.1.2 step 2. The looser [`iterator_receiver`] used by the
/// helper terminals (map/filter/drop/take/forEach/…) would re-wrap an
/// ordinary object as `IteratorState::User`, which causes infinite
/// re-entry when the wrapped object's `next` resolves back to this
/// same native through the prototype chain.
fn iterator_receiver_builtin(
    ctx: &mut crate::NativeCtx<'_>,
    name: &'static str,
) -> Result<crate::IteratorHandle, crate::NativeError> {
    let this_value = *ctx.this_value();
    if let Some(h) = this_value.as_iterator() {
        return Ok(h);
    }
    if let Some(g) = this_value.as_generator() {
        let gen_value = Value::generator(g);
        let state = crate::IteratorState::Generator { handle: g };
        return ctx
            .alloc_iterator_state(state, &[&gen_value], &[])
            .map_err(|_| crate::NativeError::TypeError {
                name,
                reason: "iterator allocation failed".to_string(),
            });
    }
    Err(crate::NativeError::TypeError {
        name,
        reason: "this is not a built-in iterator".to_string(),
    })
}

fn require_callable_arg(
    ctx: &crate::NativeCtx<'_>,
    args: &[Value],
    name: &'static str,
    index: usize,
) -> Result<Value, crate::NativeError> {
    let v = args.get(index).cloned().unwrap_or(Value::undefined());
    if ctx.cx.interp.is_callable_runtime(&v) {
        Ok(v)
    } else {
        Err(crate::NativeError::TypeError {
            name,
            reason: "argument must be callable".to_string(),
        })
    }
}

fn iterator_proto_map(
    ctx: &mut crate::NativeCtx<'_>,
    args: &[Value],
) -> Result<Value, crate::NativeError> {
    let this_value = *ctx.this_value();
    require_object_receiver(&this_value, "Iterator.prototype.map")?;
    let mapper = match require_callable_arg(ctx, args, "Iterator.prototype.map", 0) {
        Ok(mapper) => mapper,
        Err(err) => return Err(close_receiver_on_validation_failure(ctx, this_value, err)),
    };
    let source = iterator_receiver(ctx, "Iterator.prototype.map")?;
    let source_value = Value::iterator(source);
    let state = crate::IteratorState::Map {
        source,
        mapper,
        counter: 0,
    };
    let handle = ctx
        .alloc_iterator_state(state, &[&source_value, &mapper], &[])
        .map_err(|_| crate::NativeError::TypeError {
            name: "Iterator.prototype.map",
            reason: "iterator allocation failed".to_string(),
        })?;
    Ok(Value::iterator(handle))
}

fn iterator_proto_filter(
    ctx: &mut crate::NativeCtx<'_>,
    args: &[Value],
) -> Result<Value, crate::NativeError> {
    let this_value = *ctx.this_value();
    require_object_receiver(&this_value, "Iterator.prototype.filter")?;
    let predicate = match require_callable_arg(ctx, args, "Iterator.prototype.filter", 0) {
        Ok(predicate) => predicate,
        Err(err) => return Err(close_receiver_on_validation_failure(ctx, this_value, err)),
    };
    let source = iterator_receiver(ctx, "Iterator.prototype.filter")?;
    let source_value = Value::iterator(source);
    let state = crate::IteratorState::Filter {
        source,
        predicate,
        counter: 0,
    };
    let handle = ctx
        .alloc_iterator_state(state, &[&source_value, &predicate], &[])
        .map_err(|_| crate::NativeError::TypeError {
            name: "Iterator.prototype.filter",
            reason: "iterator allocation failed".to_string(),
        })?;
    Ok(Value::iterator(handle))
}

fn iterator_proto_take(
    ctx: &mut crate::NativeCtx<'_>,
    args: &[Value],
) -> Result<Value, crate::NativeError> {
    let this_value = *ctx.this_value();
    require_object_receiver(&this_value, "Iterator.prototype.take")?;
    let n = match iterator_arg_count_native(ctx, args, "Iterator.prototype.take") {
        Ok(n) => n,
        Err(err) => return Err(close_receiver_on_validation_failure(ctx, this_value, err)),
    };
    let source = iterator_receiver(ctx, "Iterator.prototype.take")?;
    let source_value = Value::iterator(source);
    let state = crate::IteratorState::Take {
        source,
        remaining: n,
    };
    let handle = ctx
        .alloc_iterator_state(state, &[&source_value], &[])
        .map_err(|_| crate::NativeError::TypeError {
            name: "Iterator.prototype.take",
            reason: "iterator allocation failed".to_string(),
        })?;
    Ok(Value::iterator(handle))
}

fn iterator_proto_drop(
    ctx: &mut crate::NativeCtx<'_>,
    args: &[Value],
) -> Result<Value, crate::NativeError> {
    let this_value = *ctx.this_value();
    require_object_receiver(&this_value, "Iterator.prototype.drop")?;
    let n = match iterator_arg_count_native(ctx, args, "Iterator.prototype.drop") {
        Ok(n) => n,
        Err(err) => return Err(close_receiver_on_validation_failure(ctx, this_value, err)),
    };
    let source = iterator_receiver(ctx, "Iterator.prototype.drop")?;
    let source_value = Value::iterator(source);
    let state = crate::IteratorState::Drop { source, to_drop: n };
    let handle = ctx
        .alloc_iterator_state(state, &[&source_value], &[])
        .map_err(|_| crate::NativeError::TypeError {
            name: "Iterator.prototype.drop",
            reason: "iterator allocation failed".to_string(),
        })?;
    Ok(Value::iterator(handle))
}

fn iterator_proto_flat_map(
    ctx: &mut crate::NativeCtx<'_>,
    args: &[Value],
) -> Result<Value, crate::NativeError> {
    let this_value = *ctx.this_value();
    require_object_receiver(&this_value, "Iterator.prototype.flatMap")?;
    let mapper = match require_callable_arg(ctx, args, "Iterator.prototype.flatMap", 0) {
        Ok(mapper) => mapper,
        Err(err) => return Err(close_receiver_on_validation_failure(ctx, this_value, err)),
    };
    let source = iterator_receiver(ctx, "Iterator.prototype.flatMap")?;
    let source_value = Value::iterator(source);
    let state = crate::IteratorState::FlatMap {
        source,
        mapper,
        inner: None,
        counter: 0,
    };
    let handle = ctx
        .alloc_iterator_state(state, &[&source_value, &mapper], &[])
        .map_err(|_| crate::NativeError::TypeError {
            name: "Iterator.prototype.flatMap",
            reason: "iterator allocation failed".to_string(),
        })?;
    Ok(Value::iterator(handle))
}

fn iterator_arg_count_native(
    ctx: &mut crate::NativeCtx<'_>,
    args: &[Value],
    name: &'static str,
) -> Result<u64, crate::NativeError> {
    let arg = args.first().cloned().unwrap_or(Value::undefined());
    // §27.5.1.2 step 3 — `numLimit = ? ToNumber(limit)`. Non-
    // primitive operands route through `ToPrimitive(hint: number)`
    // so `valueOf` / `toString` / `Symbol.toPrimitive` hooks fire.
    let primitive = if crate::abstract_ops::is_primitive(&arg) {
        arg
    } else {
        let (interp, exec) = ctx.interp_mut_and_context();
        let exec = exec.ok_or_else(|| crate::NativeError::TypeError {
            name,
            reason: "missing execution context".to_string(),
        })?;
        interp
            .evaluate_to_primitive(&exec, &arg, crate::abstract_ops::ToPrimitiveHint::Number)
            .map_err(|e| crate::native_function::vm_to_native_error(e, name))?
    };
    let n = crate::number::to_number_value(&primitive, ctx.heap());
    if n.is_nan() {
        return Err(crate::NativeError::RangeError {
            name,
            reason: "argument must be a non-negative integer".to_string(),
        });
    }
    let trunc = n.trunc();
    if trunc < 0.0 {
        return Err(crate::NativeError::RangeError {
            name,
            reason: "argument must be a non-negative integer".to_string(),
        });
    }
    if n.is_infinite() {
        return Ok(u64::MAX);
    }
    Ok(trunc as u64)
}

fn iterator_proto_to_array(
    ctx: &mut crate::NativeCtx<'_>,
    _args: &[Value],
) -> Result<Value, crate::NativeError> {
    let handle = iterator_receiver(ctx, "Iterator.prototype.toArray")?;
    let exec_ctx =
        ctx.execution_context()
            .cloned()
            .ok_or_else(|| crate::NativeError::TypeError {
                name: "Iterator.prototype.toArray",
                reason: "missing execution context".to_string(),
            })?;
    let mut collected: Vec<Value> = Vec::new();
    loop {
        let (v, done) = ctx
            .cx
            .interp
            .iterator_next_full(&exec_ctx, &handle)
            .map_err(|e| {
                crate::native_function::vm_to_native_error(e, "Iterator.prototype.toArray")
            })?;
        if done {
            break;
        }
        collected.push(v);
    }
    let iter_value = Value::iterator(handle);
    let arr = ctx
        .array_from_elements_with_roots(
            collected.iter().cloned(),
            &[&iter_value],
            &[collected.as_slice()],
        )
        .map_err(|_| crate::NativeError::TypeError {
            name: "Iterator.prototype.toArray",
            reason: "array allocation failed".to_string(),
        })?;
    Ok(Value::array(arr))
}

fn iterator_proto_for_each(
    ctx: &mut crate::NativeCtx<'_>,
    args: &[Value],
) -> Result<Value, crate::NativeError> {
    let this_value = *ctx.this_value();
    require_object_receiver(&this_value, "Iterator.prototype.forEach")?;
    let callback = match require_callable_arg(ctx, args, "Iterator.prototype.forEach", 0) {
        Ok(callback) => callback,
        Err(err) => return Err(close_receiver_on_validation_failure(ctx, this_value, err)),
    };
    let handle = iterator_receiver(ctx, "Iterator.prototype.forEach")?;
    let exec_ctx =
        ctx.execution_context()
            .cloned()
            .ok_or_else(|| crate::NativeError::TypeError {
                name: "Iterator.prototype.forEach",
                reason: "missing execution context".to_string(),
            })?;
    let mut idx: f64 = 0.0;
    loop {
        let (v, done) = ctx
            .cx
            .interp
            .iterator_next_full(&exec_ctx, &handle)
            .map_err(|e| {
                crate::native_function::vm_to_native_error(e, "Iterator.prototype.forEach")
            })?;
        if done {
            break;
        }
        let mut cb_args: smallvec::SmallVec<[Value; 8]> = smallvec::SmallVec::new();
        cb_args.push(v);
        cb_args.push(Value::number(crate::number::NumberValue::from_f64(idx)));
        if let Err(err) =
            ctx.cx
                .interp
                .run_callable_sync(&exec_ctx, &callback, Value::undefined(), cb_args)
        {
            ctx.cx
                .interp
                .close_iterator_preserving_throw(&exec_ctx, &handle);
            return Err(crate::native_function::vm_to_native_error(
                err,
                "Iterator.prototype.forEach",
            ));
        }
        idx += 1.0;
    }
    Ok(Value::undefined())
}

fn iterator_proto_reduce(
    ctx: &mut crate::NativeCtx<'_>,
    args: &[Value],
) -> Result<Value, crate::NativeError> {
    let this_value = *ctx.this_value();
    require_object_receiver(&this_value, "Iterator.prototype.reduce")?;
    let reducer = match require_callable_arg(ctx, args, "Iterator.prototype.reduce", 0) {
        Ok(reducer) => reducer,
        Err(err) => return Err(close_receiver_on_validation_failure(ctx, this_value, err)),
    };
    let handle = iterator_receiver(ctx, "Iterator.prototype.reduce")?;
    let exec_ctx =
        ctx.execution_context()
            .cloned()
            .ok_or_else(|| crate::NativeError::TypeError {
                name: "Iterator.prototype.reduce",
                reason: "missing execution context".to_string(),
            })?;
    let has_initial = args.len() >= 2;
    let mut acc = if has_initial {
        args[1]
    } else {
        Value::undefined()
    };
    // `has_acc` flips to true once `acc` holds a real value — either
    // the caller-supplied initial value or the first yielded element
    // when no initial was passed.
    let mut has_acc = has_initial;
    let mut idx: f64 = 0.0;
    loop {
        let (v, done) = ctx
            .cx
            .interp
            .iterator_next_full(&exec_ctx, &handle)
            .map_err(|e| {
                crate::native_function::vm_to_native_error(e, "Iterator.prototype.reduce")
            })?;
        if done {
            break;
        }
        if !has_acc {
            acc = v;
            has_acc = true;
            idx += 1.0;
            continue;
        }
        let mut cb_args: smallvec::SmallVec<[Value; 8]> = smallvec::SmallVec::new();
        cb_args.push(acc);
        cb_args.push(v);
        cb_args.push(Value::number(crate::number::NumberValue::from_f64(idx)));
        acc =
            match ctx
                .cx
                .interp
                .run_callable_sync(&exec_ctx, &reducer, Value::undefined(), cb_args)
            {
                Ok(acc) => acc,
                Err(err) => {
                    ctx.cx
                        .interp
                        .close_iterator_preserving_throw(&exec_ctx, &handle);
                    return Err(crate::native_function::vm_to_native_error(
                        err,
                        "Iterator.prototype.reduce",
                    ));
                }
            };
        idx += 1.0;
    }
    if !has_acc {
        return Err(crate::NativeError::TypeError {
            name: "Iterator.prototype.reduce",
            reason: "reduce of empty iterator with no initial value".to_string(),
        });
    }
    Ok(acc)
}

fn iterator_proto_some(
    ctx: &mut crate::NativeCtx<'_>,
    args: &[Value],
) -> Result<Value, crate::NativeError> {
    iterator_predicate_drain(ctx, args, "Iterator.prototype.some", true, false)
}

fn iterator_proto_every(
    ctx: &mut crate::NativeCtx<'_>,
    args: &[Value],
) -> Result<Value, crate::NativeError> {
    iterator_predicate_drain(ctx, args, "Iterator.prototype.every", false, true)
}

fn iterator_proto_find(
    ctx: &mut crate::NativeCtx<'_>,
    args: &[Value],
) -> Result<Value, crate::NativeError> {
    let this_value = *ctx.this_value();
    require_object_receiver(&this_value, "Iterator.prototype.find")?;
    let predicate = match require_callable_arg(ctx, args, "Iterator.prototype.find", 0) {
        Ok(predicate) => predicate,
        Err(err) => return Err(close_receiver_on_validation_failure(ctx, this_value, err)),
    };
    let handle = iterator_receiver(ctx, "Iterator.prototype.find")?;
    let exec_ctx =
        ctx.execution_context()
            .cloned()
            .ok_or_else(|| crate::NativeError::TypeError {
                name: "Iterator.prototype.find",
                reason: "missing execution context".to_string(),
            })?;
    let mut idx: f64 = 0.0;
    loop {
        let (v, done) = ctx
            .cx
            .interp
            .iterator_next_full(&exec_ctx, &handle)
            .map_err(|e| {
                crate::native_function::vm_to_native_error(e, "Iterator.prototype.find")
            })?;
        if done {
            break;
        }
        let mut cb_args: smallvec::SmallVec<[Value; 8]> = smallvec::SmallVec::new();
        cb_args.push(v);
        cb_args.push(Value::number(crate::number::NumberValue::from_f64(idx)));
        let kept = match ctx.cx.interp.run_callable_sync(
            &exec_ctx,
            &predicate,
            Value::undefined(),
            cb_args,
        ) {
            Ok(kept) => kept,
            Err(err) => {
                ctx.cx
                    .interp
                    .close_iterator_preserving_throw(&exec_ctx, &handle);
                return Err(crate::native_function::vm_to_native_error(
                    err,
                    "Iterator.prototype.find",
                ));
            }
        };
        if kept.to_boolean(ctx.heap()) {
            ctx.cx
                .interp
                .iterator_close_value_sync(&exec_ctx, Value::iterator(handle))
                .map_err(|e| {
                    crate::native_function::vm_to_native_error(e, "Iterator.prototype.find")
                })?;
            return Ok(v);
        }
        idx += 1.0;
    }
    Ok(Value::undefined())
}

/// §27.1.5.1.2 `%IteratorPrototype%.next()` — drive one step on the
/// receiver iterator and wrap the (value, done) pair in the spec's
/// result record.
///
/// # See also
/// - <https://tc39.es/ecma262/#sec-%25iteratorprototype%25.next>
fn iterator_proto_next(
    ctx: &mut crate::NativeCtx<'_>,
    _args: &[Value],
) -> Result<Value, crate::NativeError> {
    let handle = iterator_receiver_builtin(ctx, "Iterator.prototype.next")?;
    let exec_ctx =
        ctx.execution_context()
            .cloned()
            .ok_or_else(|| crate::NativeError::TypeError {
                name: "Iterator.prototype.next",
                reason: "missing execution context".to_string(),
            })?;
    let iter_value = Value::iterator(handle);
    let (value, done) = ctx
        .cx
        .interp
        .iterator_next_full(&exec_ctx, &handle)
        .map_err(|e| crate::native_function::vm_to_native_error(e, "Iterator.prototype.next"))?;
    let obj = ctx
        .alloc_object_with_roots(&[&iter_value, &value], &[])
        .map_err(|_| crate::NativeError::TypeError {
            name: "Iterator.prototype.next",
            reason: "result allocation failed".to_string(),
        })?;
    ctx.set_property(obj, "value", value)
        .map_err(|e| crate::native_function::vm_to_native_error(e, "Iterator.prototype.next"))?;
    ctx.set_property(obj, "done", Value::boolean(done))
        .map_err(|e| crate::native_function::vm_to_native_error(e, "Iterator.prototype.next"))?;
    Ok(Value::object(obj))
}

/// §22.2.7.2 `%RegExpStringIteratorPrototype%.next`.
///
/// Unlike the generic `%IteratorPrototype%.next` helper, this own
/// method requires the receiver to carry RegExp String Iterator
/// internal state.
fn regexp_string_iterator_proto_next(
    ctx: &mut crate::NativeCtx<'_>,
    _args: &[Value],
) -> Result<Value, crate::NativeError> {
    let name = "RegExpStringIteratorPrototype.next";
    let this_value = *ctx.this_value();
    let Some(handle) = this_value.as_iterator() else {
        return Err(crate::NativeError::TypeError {
            name,
            reason: "this is not a RegExp String Iterator".to_string(),
        });
    };
    let is_regexp_string = ctx
        .cx
        .interp
        .gc_heap_for_cx()
        .read_payload(handle, |state| {
            matches!(state, crate::IteratorState::RegExpString { .. })
        });
    if !is_regexp_string {
        return Err(crate::NativeError::TypeError {
            name,
            reason: "this is not a RegExp String Iterator".to_string(),
        });
    }
    let exec_ctx =
        ctx.execution_context()
            .cloned()
            .ok_or_else(|| crate::NativeError::TypeError {
                name,
                reason: "missing execution context".to_string(),
            })?;
    let iter_value = Value::iterator(handle);
    let (value, done) = ctx
        .cx
        .interp
        .iterator_next_full(&exec_ctx, &handle)
        .map_err(|e| crate::native_function::vm_to_native_error(e, name))?;
    let obj = ctx
        .alloc_object_with_roots(&[&iter_value, &value], &[])
        .map_err(|_| crate::NativeError::TypeError {
            name,
            reason: "result allocation failed".to_string(),
        })?;
    ctx.set_property(obj, "value", value)
        .map_err(|e| crate::native_function::vm_to_native_error(e, name))?;
    ctx.set_property(obj, "done", Value::boolean(done))
        .map_err(|e| crate::native_function::vm_to_native_error(e, name))?;
    Ok(Value::object(obj))
}

/// §27.1.5.1.3 `%IteratorPrototype%.return(value)` — mark the
/// receiver iterator exhausted and return the spec result record
/// `{ value, done: true }`. Generator-backed iterators delegate
/// to the generator's `return` handler through `iterator_helper_dispatch`.
///
/// # See also
/// - <https://tc39.es/ecma262/#sec-%25iteratorprototype%25.return>
fn iterator_proto_return(
    ctx: &mut crate::NativeCtx<'_>,
    args: &[Value],
) -> Result<Value, crate::NativeError> {
    let this_value = *ctx.this_value();
    let handle = iterator_receiver_builtin(ctx, "Iterator.prototype.return")?;
    let arg = args.first().cloned().unwrap_or(Value::undefined());
    let iter_value = Value::iterator(handle);
    // §27.1.2.1.2 — `return` on a helper forwards IteratorClose to the
    // underlying iterator chain (helper sources, user `return`
    // methods, suspended generator bodies). Async generators keep the
    // promise-shaped resumption path instead.
    let receiver_is_async_generator = this_value
        .as_generator()
        .is_some_and(|g| g.is_async(ctx.interp_mut().gc_heap()));
    if !receiver_is_async_generator {
        let exec_ctx =
            ctx.execution_context()
                .cloned()
                .ok_or_else(|| crate::NativeError::TypeError {
                    name: "Iterator.prototype.return",
                    reason: "missing execution context".to_string(),
                })?;
        ctx.cx
            .interp
            .iterator_close_value_sync(&exec_ctx, iter_value)
            .map_err(|e| {
                crate::native_function::vm_to_native_error(e, "Iterator.prototype.return")
            })?;
    }
    ctx.cx
        .interp
        .gc_heap_for_cx_mut()
        .with_payload(handle, |state| {
            state.exhaust();
        });
    let obj = ctx
        .alloc_object_with_roots(&[&iter_value, &arg], &[])
        .map_err(|_| crate::NativeError::TypeError {
            name: "Iterator.prototype.return",
            reason: "result allocation failed".to_string(),
        })?;
    ctx.set_property(obj, "value", arg)
        .map_err(|e| crate::native_function::vm_to_native_error(e, "Iterator.prototype.return"))?;
    ctx.set_property(obj, "done", Value::boolean(true))
        .map_err(|e| crate::native_function::vm_to_native_error(e, "Iterator.prototype.return"))?;
    Ok(Value::object(obj))
}

/// §27.1.5.1.4 `%IteratorPrototype%.throw(value)` — propagate the
/// argument as a thrown completion. Built-in (non-generator)
/// iterators have no `[[Throw]]` handler, so the abstract algorithm
/// degrades to "throw value".
///
/// # See also
/// - <https://tc39.es/ecma262/#sec-%25iteratorprototype%25.throw>
fn iterator_proto_throw(
    ctx: &mut crate::NativeCtx<'_>,
    args: &[Value],
) -> Result<Value, crate::NativeError> {
    let _handle = iterator_receiver_builtin(ctx, "Iterator.prototype.throw")?;
    let arg = args.first().cloned().unwrap_or(Value::undefined());
    Err(crate::NativeError::Thrown {
        name: "Iterator.prototype.throw",
        message: arg.display_string(ctx.heap()),
    })
}

fn iterator_predicate_drain(
    ctx: &mut crate::NativeCtx<'_>,
    args: &[Value],
    name: &'static str,
    short_on_truthy: bool,
    initial: bool,
) -> Result<Value, crate::NativeError> {
    let this_value = *ctx.this_value();
    require_object_receiver(&this_value, name)?;
    let predicate = match require_callable_arg(ctx, args, name, 0) {
        Ok(predicate) => predicate,
        Err(err) => return Err(close_receiver_on_validation_failure(ctx, this_value, err)),
    };
    let handle = iterator_receiver(ctx, name)?;
    let exec_ctx =
        ctx.execution_context()
            .cloned()
            .ok_or_else(|| crate::NativeError::TypeError {
                name,
                reason: "missing execution context".to_string(),
            })?;
    let mut idx: f64 = 0.0;
    loop {
        let (v, done) = ctx
            .cx
            .interp
            .iterator_next_full(&exec_ctx, &handle)
            .map_err(|e| crate::native_function::vm_to_native_error(e, name))?;
        if done {
            return Ok(Value::boolean(initial));
        }
        let mut cb_args: smallvec::SmallVec<[Value; 8]> = smallvec::SmallVec::new();
        cb_args.push(v);
        cb_args.push(Value::number(crate::number::NumberValue::from_f64(idx)));
        // §27.1.4.x — IfAbruptCloseIterator: a throwing predicate
        // closes the underlying iterator before propagating.
        let kept = match ctx.cx.interp.run_callable_sync(
            &exec_ctx,
            &predicate,
            Value::undefined(),
            cb_args,
        ) {
            Ok(kept) => kept,
            Err(err) => {
                ctx.cx
                    .interp
                    .close_iterator_preserving_throw(&exec_ctx, &handle);
                return Err(crate::native_function::vm_to_native_error(err, name));
            }
        };
        if kept.to_boolean(ctx.heap()) == short_on_truthy {
            // Early exit closes the underlying iterator with a normal
            // completion; a throwing `return` propagates.
            ctx.cx
                .interp
                .iterator_close_value_sync(&exec_ctx, Value::iterator(handle))
                .map_err(|e| crate::native_function::vm_to_native_error(e, name))?;
            return Ok(Value::boolean(short_on_truthy));
        }
        idx += 1.0;
    }
}

/// §27.1.4.1 `Iterator.from(iterable)` — wraps the operand into a
/// foundation iterator. Already-iterator inputs pass through;
/// iterable objects route through `GetIterator` so `[Symbol.iterator]()`
/// fires and the resulting user iterator is wrapped in
/// `IteratorState::User`. Plain Array / Set / Map / String operands
/// route through their respective `IteratorState` shapes via the
/// existing `make_*_iterator_factory` helpers. Primitive inputs that
/// aren't iterable raise TypeError per spec step 4.
fn iterator_from_native(
    ctx: &mut crate::NativeCtx<'_>,
    args: &[Value],
) -> Result<Value, crate::NativeError> {
    let input = args.first().cloned().unwrap_or(Value::undefined());
    if input.is_iterator() {
        return Ok(input);
    }
    if let Some(arr) = input.as_array() {
        let arr_value = Value::array(arr);
        let state = crate::IteratorState::Array {
            array: arr,
            index: 0,
            origin: crate::BuiltinIteratorOrigin::Array,
        };
        let handle = ctx
            .alloc_iterator_state(state, &[&arr_value], &[])
            .map_err(|_| crate::NativeError::TypeError {
                name: "Iterator.from",
                reason: "iterator allocation failed".to_string(),
            })?;
        return Ok(Value::iterator(handle));
    }
    if let Some(g) = input.as_generator() {
        let state = crate::IteratorState::Generator { handle: g };
        let handle = ctx
            .alloc_iterator_state(state, &[&input], &[])
            .map_err(|_| crate::NativeError::TypeError {
                name: "Iterator.from",
                reason: "iterator allocation failed".to_string(),
            })?;
        return Ok(Value::iterator(handle));
    }
    if let Some(s) = input.as_string(ctx.heap()) {
        let state = crate::IteratorState::String {
            string: s,
            index: 0,
        };
        let handle = ctx
            .alloc_iterator_state(state, &[&input], &[])
            .map_err(|_| crate::NativeError::TypeError {
                name: "Iterator.from",
                reason: "iterator allocation failed".to_string(),
            })?;
        return Ok(Value::iterator(handle));
    }
    // §27.1.4.1 step 1 — `iterable` may also be an Object with
    // `@@iterator`; look up the method, call it, and wrap the
    // resulting iterator object in `IteratorState::User`.
    if input.is_object()
        || input.is_set()
        || input.is_map()
        || input.is_function()
        || input.is_closure()
        || input.is_native_function()
        || input.is_bound_function()
        || input.is_class_constructor()
        || input.is_proxy()
    {
        let iterator_sym = ctx
            .cx
            .interp
            .well_known_symbols()
            .get(crate::symbol::WellKnown::Iterator);
        let (interp, exec_ctx) = ctx.interp_mut_and_context();
        let exec_ctx = exec_ctx.ok_or_else(|| crate::NativeError::TypeError {
            name: "Iterator.from",
            reason: "missing execution context".to_string(),
        })?;
        let key = crate::VmPropertyKey::Symbol(iterator_sym);
        let outcome = interp
            .ordinary_get_value(&exec_ctx, input, input, &key, 0)
            .map_err(|e| crate::native_function::vm_to_native_error(e, "Iterator.from"))?;
        let iter_method = match outcome {
            crate::VmGetOutcome::Value(v) => v,
            crate::VmGetOutcome::InvokeGetter { getter } => {
                let args: smallvec::SmallVec<[Value; 8]> = smallvec::SmallVec::new();
                interp
                    .run_callable_sync(&exec_ctx, &getter, input, args)
                    .map_err(|e| crate::native_function::vm_to_native_error(e, "Iterator.from"))?
            }
        };
        let iter_value = if iter_method.is_nullish() {
            input
        } else if interp.is_callable_runtime(&iter_method) {
            let args: smallvec::SmallVec<[Value; 8]> = smallvec::SmallVec::new();
            interp
                .run_callable_sync(&exec_ctx, &iter_method, input, args)
                .map_err(|e| crate::native_function::vm_to_native_error(e, "Iterator.from"))?
        } else {
            return Err(crate::NativeError::TypeError {
                name: "Iterator.from",
                reason: "argument is not iterable".to_string(),
            });
        };
        if iter_value.is_iterator() {
            return Ok(iter_value);
        }
        // §7.4.4 GetIteratorDirect — `next` is read once here, not
        // per step.
        let next_key = crate::VmPropertyKey::String("next");
        let next_outcome = interp
            .ordinary_get_value(&exec_ctx, iter_value, iter_value, &next_key, 0)
            .map_err(|e| crate::native_function::vm_to_native_error(e, "Iterator.from"))?;
        let next_method = match next_outcome {
            crate::VmGetOutcome::Value(v) => v,
            crate::VmGetOutcome::InvokeGetter { getter } => {
                let args: smallvec::SmallVec<[Value; 8]> = smallvec::SmallVec::new();
                interp
                    .run_callable_sync(&exec_ctx, &getter, iter_value, args)
                    .map_err(|e| crate::native_function::vm_to_native_error(e, "Iterator.from"))?
            }
        };
        let state = crate::IteratorState::User {
            iterator: iter_value,
            next_method: Some(next_method),
        };
        let handle = ctx
            .alloc_iterator_state(state, &[&iter_value, &next_method], &[])
            .map_err(|_| crate::NativeError::TypeError {
                name: "Iterator.from",
                reason: "iterator allocation failed".to_string(),
            })?;
        return Ok(Value::iterator(handle));
    }
    Err(crate::NativeError::TypeError {
        name: "Iterator.from",
        reason: "argument is not iterable".to_string(),
    })
}

/// §27.5.1 `%GeneratorPrototype%` brand check: the receiver must be a
/// synchronous generator object.
fn require_sync_generator(
    ctx: &mut crate::NativeCtx<'_>,
    name: &'static str,
) -> Result<(), crate::NativeError> {
    let this = *ctx.this_value();
    let ok = this
        .as_generator()
        .is_some_and(|g| !g.is_async(ctx.interp_mut().gc_heap()));
    if ok {
        Ok(())
    } else {
        Err(crate::NativeError::TypeError {
            name,
            reason: "receiver is not a generator object".to_string(),
        })
    }
}

/// §27.5.1.2 `%GeneratorPrototype%.next(value)`.
pub(crate) fn generator_proto_next(
    ctx: &mut crate::NativeCtx<'_>,
    args: &[Value],
) -> Result<Value, crate::NativeError> {
    require_sync_generator(ctx, "Generator.prototype.next")?;
    iterator_proto_next(ctx, args)
}

/// §27.5.1.4 `%GeneratorPrototype%.return(value)`.
pub(crate) fn generator_proto_return(
    ctx: &mut crate::NativeCtx<'_>,
    args: &[Value],
) -> Result<Value, crate::NativeError> {
    require_sync_generator(ctx, "Generator.prototype.return")?;
    iterator_proto_return(ctx, args)
}

/// §27.5.1.5 `%GeneratorPrototype%.throw(exception)`.
pub(crate) fn generator_proto_throw(
    ctx: &mut crate::NativeCtx<'_>,
    args: &[Value],
) -> Result<Value, crate::NativeError> {
    require_sync_generator(ctx, "Generator.prototype.throw")?;
    iterator_proto_throw(ctx, args)
}

/// §27.6.1 AsyncGeneratorValidate-shaped guard: a wrong receiver
/// REJECTS the returned promise instead of throwing (§27.6.1.2 step
/// 3 / AWAIT-shaped completions). `Ok(None)` means the receiver is a
/// genuine async generator and the caller should proceed.
fn async_generator_validate(
    ctx: &mut crate::NativeCtx<'_>,
    name: &'static str,
) -> Result<Option<Value>, crate::NativeError> {
    let this = *ctx.this_value();
    let ok = this
        .as_generator()
        .is_some_and(|g| g.is_async(ctx.interp_mut().gc_heap()));
    if ok {
        return Ok(None);
    }
    let (interp, exec_ctx) = ctx.interp_mut_and_context();
    let Some(exec_ctx) = exec_ctx else {
        return Err(crate::NativeError::TypeError {
            name,
            reason: "missing execution context".to_string(),
        });
    };
    let reason = interp
        .make_type_error_with_stack_roots(
            &smallvec::SmallVec::new(),
            "receiver is not an async generator object",
        )
        .map_err(|_| crate::NativeError::TypeError {
            name,
            reason: "rejection allocation failed".to_string(),
        })?;
    let promise = crate::promise_dispatch::PromiseBuilder::with_context(exec_ctx)
        .rejected_runtime_rooted(interp, reason, &[&reason], &[])
        .map_err(|_| crate::NativeError::TypeError {
            name,
            reason: "rejection allocation failed".to_string(),
        })?;
    Ok(Some(Value::promise(promise)))
}

/// Run one async-generator resumption method: §27.6.1 always returns
/// a promise, so a throw completion from the underlying machinery
/// (e.g. `throw` against a suspended-start or completed body) becomes
/// a rejection of the returned promise rather than a synchronous
/// throw.
fn async_generator_resumption(
    ctx: &mut crate::NativeCtx<'_>,
    args: &[Value],
    name: &'static str,
    method: crate::native_function::NativeFastFn,
) -> Result<Value, crate::NativeError> {
    if let Some(rejected) = async_generator_validate(ctx, name)? {
        return Ok(rejected);
    }
    match method(ctx, args) {
        Ok(value) => Ok(value),
        Err(err) => {
            let (interp, exec_ctx) = ctx.interp_mut_and_context();
            let Some(exec_ctx) = exec_ctx else {
                return Err(err);
            };
            let reason = match interp.take_pending_uncaught_throw() {
                Some(thrown) => thrown,
                None => interp
                    .make_type_error_with_stack_roots(
                        &smallvec::SmallVec::new(),
                        &format!("{err:?}"),
                    )
                    .map_err(|_| err)?,
            };
            let promise = crate::promise_dispatch::PromiseBuilder::with_context(exec_ctx)
                .rejected_runtime_rooted(interp, reason, &[&reason], &[])
                .map_err(|_| crate::NativeError::TypeError {
                    name,
                    reason: "rejection allocation failed".to_string(),
                })?;
            Ok(Value::promise(promise))
        }
    }
}

/// §27.6.1.2 `%AsyncGeneratorPrototype%.next(value)`.
pub(crate) fn async_generator_proto_next(
    ctx: &mut crate::NativeCtx<'_>,
    args: &[Value],
) -> Result<Value, crate::NativeError> {
    async_generator_resumption(
        ctx,
        args,
        "AsyncGenerator.prototype.next",
        iterator_proto_next,
    )
}

/// §27.6.1.3 `%AsyncGeneratorPrototype%.return(value)`.
pub(crate) fn async_generator_proto_return(
    ctx: &mut crate::NativeCtx<'_>,
    args: &[Value],
) -> Result<Value, crate::NativeError> {
    async_generator_resumption(
        ctx,
        args,
        "AsyncGenerator.prototype.return",
        iterator_proto_return,
    )
}

/// §27.6.1.4 `%AsyncGeneratorPrototype%.throw(exception)`.
pub(crate) fn async_generator_proto_throw(
    ctx: &mut crate::NativeCtx<'_>,
    args: &[Value],
) -> Result<Value, crate::NativeError> {
    async_generator_resumption(
        ctx,
        args,
        "AsyncGenerator.prototype.throw",
        iterator_proto_throw,
    )
}

/// §27.1.3.1 `%AsyncIteratorPrototype%[@@asyncIterator]` — returns
/// the receiver unchanged.
pub(crate) fn async_iterator_proto_symbol_async_iterator(
    ctx: &mut crate::NativeCtx<'_>,
    _args: &[Value],
) -> Result<Value, crate::NativeError> {
    Ok(*ctx.this_value())
}
