//! `%Proxy%` constructor installer.
//!
//! Implements ECMA-262 §28 Proxy Objects: the `Proxy` constructor
//! itself, the `Proxy.revocable(target, handler)` factory, and the
//! revocation closure attached to its `revoke` slot.
//!
//! # Contents
//! - Constructor validation and revocable-proxy result construction.
//! - Captured revoker closure and the static intrinsic spec.
//!
//! # Invariants
//! - Target, handler, proxy, revoker and result live in the native handle arena.
//! - Result fields use CreateDataProperty descriptors, independent of setters.
//! - Allocator failures retain the canonical native OutOfMemory outcome.
//!
//! # See also
//! - <https://tc39.es/ecma262/#sec-proxy-objects>

use crate::{NativeCtx, NativeError, Value};

fn proxy_target_is_object(value: &Value) -> bool {
    // §28.2.1 step 1 — `Type(target) is Object`. Spec `Object`
    // includes callable / exotic objects (functions, arrays,
    // proxies, …), not just ordinary objects. `is_object_like` only
    // tests `TAG_PTR_OBJECT`, so use the wider `is_object_type`.
    value.is_object_type()
}

fn proxy_target_arg(args: &[Value]) -> Result<Value, NativeError> {
    match args.first() {
        Some(value) if proxy_target_is_object(value) => Ok(*value),
        _ => Err(NativeError::TypeError {
            name: "Proxy",
            reason: "target must be an object".to_string(),
        }),
    }
}

fn proxy_handler_arg(args: &[Value]) -> Result<Value, NativeError> {
    match args.get(1) {
        Some(value) if proxy_target_is_object(value) => Ok(*value),
        _ => Err(NativeError::TypeError {
            name: "Proxy",
            reason: "handler must be an object".to_string(),
        }),
    }
}

fn proxy_ctor_call(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    if !ctx.is_construct_call() {
        return Err(NativeError::TypeError {
            name: "Proxy",
            reason: "constructor requires new".to_string(),
        });
    }
    let target = proxy_target_arg(args)?;
    let handler = proxy_handler_arg(args)?;
    ctx.scope(|mut scope| {
        let target = scope.value(target);
        let handler = scope.value(handler);
        let proxy = scope.proxy(target, handler)?;
        Ok(scope.finish(proxy))
    })
}

fn proxy_revocable_call(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    let target = proxy_target_arg(args)?;
    let handler = proxy_handler_arg(args)?;
    ctx.scope(|mut scope| {
        let target = scope.value(target);
        let handler = scope.value(handler);
        let proxy = scope.proxy(target, handler)?;
        let revoke = scope.native_closure("", 0, &[proxy], |ctx, _, captures| {
            if let Some(proxy) = captures.first().and_then(|value| value.as_proxy()) {
                proxy.revoke(ctx.heap_mut());
            }
            Ok(Value::undefined())
        })?;
        let result = scope.object()?;
        let flags = crate::object::PropertyFlags::data_default();
        scope.define(result, "proxy", proxy, flags)?;
        scope.define(result, "revoke", revoke, flags)?;
        Ok(scope.finish(result))
    })
}

// `PROXY_SPEC` + `Intrinsic` generated by `couch!`. §28.2 — Proxy
// has no own `prototype` property (spec wording: 'The Proxy
// constructor does not have a "prototype" property'), so the
// `couch!` empty-prototype-skip path matches verbatim.
otter_macros::couch! {
    name = "Proxy",
    feature = CORE,
    constructor = (length = 2, call = proxy_ctor_call),
    no_prototype = true,
    statics = {
        "revocable" / 2 => proxy_revocable_call,
    },
}
