//! Builtin CommonJS modules compiled at product build time, and the Node
//! `lib/` sources among them running over a compat realm.
//!
//! The files under `nodelib/` (except `compat/`) are taken from `nodejs/node`
//! at the same commit the conformance corpus tracks, so their behavior — error
//! messages included — is Node's own. They are compiled against the contract
//! Node's native wrapper provides: the `primordials` bag and
//! `internalBinding`. `compat/bootstrap_realm.js` supplies both, and every
//! vendored source is prefixed with one `require` of it; the remaining
//! `compat/*` files are narrow hand-written stand-ins for the `internal/*`
//! dependencies whose real implementations sit on native bindings.
//!
//! # Contents
//! - [`embedded`] — one build-produced [`otter_runtime::EmbeddedCommonJs`] per
//!   row of `builtin_table.rs` (wrapper text plus verified-at-build bytecode).
//! - One hosted-module installer per `installer` row, generated by this file's
//!   `builtin_table!` expansion; the hosted-module rows live in the crate's
//!   main registry table.
//! - Hand-written installers for builtins that need native set-up around the
//!   module (`internal/console/global`, `events`, `internal/otter/stdio`).
//!
//! # Invariants
//! - A builtin's code is linked lazily, on its first `require`, from the
//!   embedded module after runtime verification; no builtin is compiled at
//!   run time or touches the compile cache.
//! - Vendored files are verbatim copies except for hunks marked `// Otter:`;
//!   other behavioral divergence is fixed in the compat layer or the engine,
//!   so refreshing the vendored tree stays a copy plus those hunks.
//! - Every `internal/*` specifier a vendored file requires resolves to a row
//!   here; a miss is a load error at require time, never a silent stub.
//!
//! # See also
//! - `build/builtins.rs` — the producer of every embedded module.
//! - `scripts/fetch-node-tests.sh` — the sparse checkout the sources come
//!   from (`lib/` is part of it).

use otter_runtime::{
    CapabilitySet, RuntimeLocal as Local, RuntimeNativeError as NativeError,
    RuntimeNativeScope as NativeScope, RuntimeTaskSpawner,
};

macro_rules! builtin_table {
    ($($role:ident $name:ident $url:literal $body:ident $($path:literal)+;)*) => {
        /// The build-produced builtin modules, one per `builtin_table.rs` row.
        pub mod embedded {
            $(
                #[doc = concat!("`", $url, "`, compiled at product build time.")]
                #[allow(non_upper_case_globals)]
                pub static $name: otter_runtime::EmbeddedCommonJs = otter_runtime::EmbeddedCommonJs {
                    url: $url,
                    source: include_str!(concat!(
                        env!("OUT_DIR"), "/builtins/", stringify!($name), ".js"
                    )),
                    bytecode: include_bytes!(concat!(
                        env!("OUT_DIR"), "/builtins/", stringify!($name), ".bytecode"
                    )),
                };
            )*
            /// Every row, in table order.
            #[cfg(test)]
            pub(crate) const ALL: &[&otter_runtime::EmbeddedCommonJs] = &[$(&$name),*];
        }
        $(builtin_table!(@installer $role $name $url);)*
    };
    (@installer installer $name:ident $url:literal) => {
        #[doc = concat!("Hosted-module installer of `", $url, "`.")]
        ///
        /// # Errors
        /// Returns a native error when the module fails to verify, link, or
        /// evaluate.
        pub fn $name<'scope>(
            scope: &mut NativeScope<'scope, '_>,
            _caps: &CapabilitySet,
            _runtime_task_spawner: Option<RuntimeTaskSpawner>,
            module: Local<'scope>,
            require: Local<'scope>,
        ) -> Result<Local<'scope>, NativeError> {
            otter_runtime::run_builtin_cjs_shim(scope, &embedded::$name, module, require)
        }
    };
    (@installer embedded $name:ident $url:literal) => {};
}

include!("builtin_table.rs");

/// `internal/console/global`, answering a console that can already write.
///
/// Node binds the global console to the process's streams during bootstrap,
/// before any module can reach for it. This runtime builds the console the
/// first time it is looked at, and that first look can be a `require` of this
/// module rather than a read of the global — the test runner's is — so the
/// binding happens where the console is built.
///
/// # Errors
/// Returns a native error when the module fails to evaluate or the binding
/// call throws.
pub fn internal_console_global<'scope>(
    scope: &mut NativeScope<'scope, '_>,
    caps: &CapabilitySet,
    runtime_task_spawner: Option<RuntimeTaskSpawner>,
    module: Local<'scope>,
    require: Local<'scope>,
) -> Result<Local<'scope>, NativeError> {
    let exports =
        internal_console_global_unbound(scope, caps, runtime_task_spawner, module, require)?;
    let constructor =
        otter_runtime::require_commonjs_dependency(scope, require, "internal/console/constructor")?;
    let initialize = scope.get(constructor, "initializeGlobalConsole")?;
    let undefined = scope.undefined();
    scope.call(initialize, undefined, &[exports])?;
    Ok(exports)
}

/// `internal/otter/stdio`: the streams standard descriptors become, plus the
/// runtime natives through which Node's console reaches a descriptor before
/// any stream exists (see [`otter_runtime::define_stdio_natives`]).
///
/// # Errors
/// Returns a native error when the module fails to evaluate or a native
/// cannot be defined.
pub fn internal_otter_stdio<'scope>(
    scope: &mut NativeScope<'scope, '_>,
    _caps: &CapabilitySet,
    _runtime_task_spawner: Option<RuntimeTaskSpawner>,
    module: Local<'scope>,
    require: Local<'scope>,
) -> Result<Local<'scope>, NativeError> {
    let exports = otter_runtime::run_builtin_cjs_shim(
        scope,
        &embedded::internal_otter_stdio,
        module,
        require,
    )?;
    otter_runtime::define_stdio_natives(scope, exports)?;
    Ok(exports)
}

/// The vendored `events` module plus a one-time process-prototype graft:
/// Node's `process` inherits from `EventEmitter` through an intermediate
/// constructor named `process`, and the corpus asserts that exact chain.
/// The graft rides the first `events` load because the runtime-built
/// `process` object exists before any module — and therefore before
/// `EventEmitter` — does.
///
/// # Errors
/// Returns a native error when the shim fails to allocate or evaluate.
pub fn node_events_with_process_graft<'scope>(
    scope: &mut NativeScope<'scope, '_>,
    caps: &CapabilitySet,
    runtime_task_spawner: Option<RuntimeTaskSpawner>,
    module: Local<'scope>,
    require: Local<'scope>,
) -> Result<Local<'scope>, NativeError> {
    let exports = node_events(scope, caps, runtime_task_spawner, module, require)?;
    let graft_module = scope.object()?;
    let graft_exports = scope.object()?;
    scope.set(graft_module, "exports", graft_exports)?;
    otter_runtime::run_builtin_cjs_shim(
        scope,
        &embedded::internal_otter_process_graft,
        graft_module,
        require,
    )?;
    Ok(exports)
}

#[cfg(test)]
mod tests {
    use super::embedded;
    use otter_bytecode::commonjs::{WRAPPER_PREFIX, WRAPPER_SUFFIX};

    #[test]
    fn every_embedded_builtin_verifies_under_its_url() {
        assert!(embedded::ALL.len() > 200);
        for unit in embedded::ALL {
            let verified = otter_bytecode::binary::decode_module(unit.bytecode)
                .unwrap_or_else(|error| panic!("{}: {error}", unit.url));
            assert_eq!(verified.module().module, unit.url);
            assert!(
                verified
                    .module()
                    .functions
                    .iter()
                    .all(|function| function.module_url == unit.url),
                "{}",
                unit.url
            );
            assert!(unit.source.starts_with(WRAPPER_PREFIX), "{}", unit.url);
            assert!(unit.source.ends_with(WRAPPER_SUFFIX), "{}", unit.url);
        }
    }

    #[test]
    fn vendored_builtins_carry_the_realm_line_on_the_wrapper_line() {
        let body = &embedded::node_path.source[WRAPPER_PREFIX.len()..];
        assert!(body.starts_with(
            "'use strict';const { primordials, internalBinding } = require('internal/bootstrap/realm');\n"
        ));
        assert_eq!(
            &embedded::node_fs_promises.source[WRAPPER_PREFIX.len()..],
            "'use strict';\nmodule.exports = require('fs').promises;\n\n})"
        );
    }

    #[test]
    fn a_configured_compile_hook_compiles_builtin_wrapper_text() {
        use crate::NodeApiBuilderExt;
        use std::sync::{Arc, Mutex};

        let seen = Arc::new(Mutex::new(Vec::<(String, bool, bool)>::new()));
        let record = seen.clone();
        let dir = tempfile::tempdir().expect("tempdir");
        let entry = dir.path().join("entry.cjs");
        std::fs::write(
            &entry,
            "if (require('path').join('a', 'b') !== 'a/b') throw new Error('path');\n",
        )
        .expect("entry");
        let mut runtime = otter_runtime::Runtime::builder()
            .with_node_apis()
            .compile_hook(move |request: otter_runtime::RuntimeCompileRequest<'_>| {
                let text = &request.source.text;
                record.lock().expect("hook record").push((
                    request.source.url.clone(),
                    text.starts_with(WRAPPER_PREFIX),
                    text.contains("process.openStdin = function openStdin()"),
                ));
                otter_compiler::compile_script_source_to_module(
                    text,
                    request.source.kind,
                    &request.source.url,
                )
                .map_err(|error| otter_runtime::OtterError::Internal {
                    code: "TEST_HOOK".to_owned(),
                    message: error.to_string(),
                })
            })
            .build()
            .expect("runtime");
        runtime
            .run_file(&entry)
            .expect("hook-compiled builtins run");
        let seen = seen.lock().expect("hook record");
        for url in ["node:path", "internal/bootstrap/realm"] {
            assert!(
                seen.iter()
                    .any(|(seen, wrapped, _)| seen == url && *wrapped),
                "{url} was not compiled by the hook: {seen:?}"
            );
        }
        assert!(
            seen.iter()
                .any(|(url, _, node_installer)| url == "<realm-installer>" && *node_installer)
        );
    }
}
