//! Vendored Node.js `lib/` sources running over a compat realm.
//!
//! The files under `nodelib/` (except `compat/`) are taken verbatim from
//! `nodejs/node` at the same commit the conformance corpus tracks, so their
//! behavior — error messages included — is Node's own. They are compiled
//! against the contract Node's native wrapper provides: the `primordials`
//! bag and `internalBinding`. `compat/bootstrap_realm.js` supplies both, and
//! every vendored source is prefixed with one `require` of it; the remaining
//! `compat/*` files are narrow hand-written stand-ins for the `internal/*`
//! dependencies whose real implementations sit on native bindings.
//!
//! # Contents
//! - One shim function per vendored or compat module, generated by
//!   `nodelib_module!`; the hosted-module rows live in the crate's main
//!   registry table.
//!
//! # Invariants
//! - Vendored files are never edited; behavioral divergence is fixed in the
//!   compat layer or the engine, so refreshing the vendored tree stays a
//!   plain copy.
//! - Every `internal/*` specifier a vendored file requires resolves to a row
//!   here; a miss is a load error at require time, never a silent stub.
//!
//! # See also
//! - `scripts/fetch-node-tests.sh` — the sparse checkout the sources come
//!   from (`lib/` is part of it).

use otter_runtime::{
    CapabilitySet, RuntimeLocal as Local, RuntimeNativeError as NativeError,
    RuntimeNativeScope as NativeScope, RuntimeTaskSpawner,
};

macro_rules! nodelib_module {
    ($fn_name:ident, $specifier:literal, vendored $path:literal) => {
        /// One vendored Node lib module, compiled over the compat realm.
        ///
        /// # Errors
        /// Returns a native error when the shim fails to allocate or
        /// evaluate.
        pub fn $fn_name<'scope>(
            scope: &mut NativeScope<'scope, '_>,
            _caps: &CapabilitySet,
            _runtime_task_spawner: Option<RuntimeTaskSpawner>,
            module: Local<'scope>,
            require: Local<'scope>,
        ) -> Result<Local<'scope>, NativeError> {
            otter_runtime::run_builtin_cjs_shim(
                scope,
                $specifier,
                concat!(
                    "'use strict';const { primordials, internalBinding } = require('internal/bootstrap/realm');\n",
                    include_str!($path)
                ),
                module,
                require,
            )
        }
    };
    ($fn_name:ident, $specifier:literal, compat $path:literal) => {
        /// One hand-written compat module standing in for a native-backed
        /// `internal/*` dependency.
        ///
        /// # Errors
        /// Returns a native error when the shim fails to allocate or
        /// evaluate.
        pub fn $fn_name<'scope>(
            scope: &mut NativeScope<'scope, '_>,
            _caps: &CapabilitySet,
            _runtime_task_spawner: Option<RuntimeTaskSpawner>,
            module: Local<'scope>,
            require: Local<'scope>,
        ) -> Result<Local<'scope>, NativeError> {
            otter_runtime::run_builtin_cjs_shim(
                scope,
                $specifier,
                include_str!($path),
                module,
                require,
            )
        }
    };
}

nodelib_module!(bootstrap_realm, "internal/bootstrap/realm", compat "nodelib/compat/bootstrap_realm.js");
nodelib_module!(internal_util, "internal/util", compat "nodelib/compat/internal_util.js");
nodelib_module!(internal_util_types, "internal/util/types", compat "nodelib/compat/internal_util_types.js");
nodelib_module!(internal_util_inspect, "internal/util/inspect", vendored "nodelib/internal/util/inspect.js");
nodelib_module!(internal_util_comparisons, "internal/util/comparisons", vendored "nodelib/internal/util/comparisons.js");
nodelib_module!(internal_util_debuglog, "internal/util/debuglog", compat "nodelib/compat/internal_util_debuglog.js");
nodelib_module!(internal_util_colors, "internal/util/colors", compat "nodelib/compat/internal_util_colors.js");
nodelib_module!(internal_assert, "internal/assert", compat "nodelib/compat/internal_assert.js");
nodelib_module!(internal_options, "internal/options", compat "nodelib/compat/internal_options.js");
nodelib_module!(internal_events_abort_listener, "internal/events/abort_listener", compat "nodelib/compat/internal_events_abort_listener.js");
nodelib_module!(internal_abort_controller, "internal/abort_controller", compat "nodelib/compat/internal_abort_controller.js");
nodelib_module!(internal_webstreams_adapters, "internal/webstreams/adapters", compat "nodelib/compat/internal_webstreams_adapters.js");
nodelib_module!(internal_event_target, "internal/event_target", compat "nodelib/compat/internal_event_target.js");
nodelib_module!(internal_v8_startup_snapshot, "internal/v8/startup_snapshot", compat "nodelib/compat/internal_v8_startup_snapshot.js");
nodelib_module!(internal_modules_helpers, "internal/modules/helpers", compat "nodelib/compat/internal_modules_helpers.js");
nodelib_module!(internal_process_task_queues, "internal/process/task_queues", compat "nodelib/compat/internal_process_task_queues.js");
nodelib_module!(internal_buffer, "internal/buffer", compat "nodelib/compat/internal_buffer.js");
nodelib_module!(internal_encoding, "internal/encoding", compat "nodelib/compat/internal_encoding.js");
nodelib_module!(internal_blob, "internal/blob", compat "nodelib/compat/internal_blob.js");
nodelib_module!(internal_source_map_cache, "internal/source_map/source_map_cache", compat "nodelib/compat/internal_source_map_cache.js");
nodelib_module!(internal_crypto_keys, "internal/crypto/keys", compat "nodelib/compat/internal_crypto_keys.js");
nodelib_module!(internal_async_hooks, "internal/async_hooks", compat "nodelib/compat/internal_async_hooks.js");
nodelib_module!(internal_async_context_frame, "internal/async_context_frame", compat "nodelib/compat/internal_async_context_frame.js");

nodelib_module!(internal_errors, "internal/errors", vendored "nodelib/internal/errors.js");
nodelib_module!(internal_validators, "internal/validators", vendored "nodelib/internal/validators.js");
nodelib_module!(node_stream, "node:stream", vendored "nodelib/stream.js");
nodelib_module!(stream_promises, "stream/promises", vendored "nodelib/stream/promises.js");
nodelib_module!(streams_add_abort_signal, "internal/streams/add-abort-signal", vendored "nodelib/internal/streams/add-abort-signal.js");
nodelib_module!(streams_compose, "internal/streams/compose", vendored "nodelib/internal/streams/compose.js");
nodelib_module!(streams_destroy, "internal/streams/destroy", vendored "nodelib/internal/streams/destroy.js");
nodelib_module!(streams_duplex, "internal/streams/duplex", vendored "nodelib/internal/streams/duplex.js");
nodelib_module!(streams_duplexify, "internal/streams/duplexify", vendored "nodelib/internal/streams/duplexify.js");
nodelib_module!(streams_duplexpair, "internal/streams/duplexpair", vendored "nodelib/internal/streams/duplexpair.js");
nodelib_module!(streams_end_of_stream, "internal/streams/end-of-stream", vendored "nodelib/internal/streams/end-of-stream.js");
nodelib_module!(streams_from, "internal/streams/from", vendored "nodelib/internal/streams/from.js");
nodelib_module!(streams_lazy_transform, "internal/streams/lazy_transform", vendored "nodelib/internal/streams/lazy_transform.js");
nodelib_module!(streams_legacy, "internal/streams/legacy", vendored "nodelib/internal/streams/legacy.js");
nodelib_module!(streams_operators, "internal/streams/operators", vendored "nodelib/internal/streams/operators.js");
nodelib_module!(streams_passthrough, "internal/streams/passthrough", vendored "nodelib/internal/streams/passthrough.js");
nodelib_module!(streams_pipeline, "internal/streams/pipeline", vendored "nodelib/internal/streams/pipeline.js");
nodelib_module!(streams_readable, "internal/streams/readable", vendored "nodelib/internal/streams/readable.js");
nodelib_module!(streams_state, "internal/streams/state", vendored "nodelib/internal/streams/state.js");
nodelib_module!(streams_transform, "internal/streams/transform", vendored "nodelib/internal/streams/transform.js");
nodelib_module!(streams_utils, "internal/streams/utils", vendored "nodelib/internal/streams/utils.js");
nodelib_module!(streams_writable, "internal/streams/writable", vendored "nodelib/internal/streams/writable.js");
nodelib_module!(streams_iter_types, "internal/streams/iter/types", vendored "nodelib/internal/streams/iter/types.js");
nodelib_module!(streams_iter_classic, "internal/streams/iter/classic", vendored "nodelib/internal/streams/iter/classic.js");
nodelib_module!(streams_iter_from, "internal/streams/iter/from", vendored "nodelib/internal/streams/iter/from.js");
nodelib_module!(streams_iter_utils, "internal/streams/iter/utils", vendored "nodelib/internal/streams/iter/utils.js");
nodelib_module!(streams_iter_broadcast, "internal/streams/iter/broadcast", vendored "nodelib/internal/streams/iter/broadcast.js");
nodelib_module!(streams_iter_consumers, "internal/streams/iter/consumers", vendored "nodelib/internal/streams/iter/consumers.js");
nodelib_module!(streams_iter_duplex, "internal/streams/iter/duplex", vendored "nodelib/internal/streams/iter/duplex.js");
nodelib_module!(streams_iter_pull, "internal/streams/iter/pull", vendored "nodelib/internal/streams/iter/pull.js");
nodelib_module!(streams_iter_push, "internal/streams/iter/push", vendored "nodelib/internal/streams/iter/push.js");
nodelib_module!(streams_iter_ringbuffer, "internal/streams/iter/ringbuffer", vendored "nodelib/internal/streams/iter/ringbuffer.js");
nodelib_module!(streams_iter_share, "internal/streams/iter/share", vendored "nodelib/internal/streams/iter/share.js");
nodelib_module!(stream_iter, "stream/iter", vendored "nodelib/stream/iter.js");
nodelib_module!(internal_fixed_queue, "internal/fixed_queue", vendored "nodelib/internal/fixed_queue.js");
nodelib_module!(internal_events_symbols, "internal/events/symbols", vendored "nodelib/internal/events/symbols.js");
nodelib_module!(node_events, "node:events", vendored "nodelib/events.js");
nodelib_module!(node_util, "node:util", vendored "nodelib/util.js");
