//! Vendored Node.js `lib/` sources running over a compat realm.
//!
//! The files under `nodelib/` (except `compat/`) are taken verbatim from
//! `nodejs/node` at the same commit the conformance corpus tracks, so their
//! behavior — error messages included — is Node's own. They are compiled
//! against the contract Node's native wrapper provides: the `primordials`
//! bag and `internalBinding`. `compat/bootstrap_realm.js` supplies both, and
//! every vendored source is prefixed with one `require` of it; the remaining
//! `compat/*` files are narrow hand-written stand-ins for the `internal/*`
//! dependencies whose real implementations sit on native bindings.
//!
//! # Contents
//! - One shim function per vendored or compat module, generated by
//!   `nodelib_module!`; the hosted-module rows live in the crate's main
//!   registry table.
//!
//! # Invariants
//! - Vendored files are never edited; behavioral divergence is fixed in the
//!   compat layer or the engine, so refreshing the vendored tree stays a
//!   plain copy.
//! - Every `internal/*` specifier a vendored file requires resolves to a row
//!   here; a miss is a load error at require time, never a silent stub.
//!
//! # See also
//! - `scripts/fetch-node-tests.sh` — the sparse checkout the sources come
//!   from (`lib/` is part of it).

use otter_runtime::{
    CapabilitySet, RuntimeLocal as Local, RuntimeNativeError as NativeError,
    RuntimeNativeScope as NativeScope, RuntimeTaskSpawner,
};

macro_rules! nodelib_module {
    ($fn_name:ident, $specifier:literal, vendored $path:literal) => {
        /// One vendored Node lib module, compiled over the compat realm.
        ///
        /// # Errors
        /// Returns a native error when the shim fails to allocate or
        /// evaluate.
        pub fn $fn_name<'scope>(
            scope: &mut NativeScope<'scope, '_>,
            _caps: &CapabilitySet,
            _runtime_task_spawner: Option<RuntimeTaskSpawner>,
            module: Local<'scope>,
            require: Local<'scope>,
        ) -> Result<Local<'scope>, NativeError> {
            otter_runtime::run_builtin_cjs_shim(
                scope,
                $specifier,
                concat!(
                    "'use strict';const { primordials, internalBinding } = require('internal/bootstrap/realm');\n",
                    include_str!($path)
                ),
                module,
                require,
            )
        }
    };
    ($fn_name:ident, $specifier:literal, compat $path:literal) => {
        /// One hand-written compat module standing in for a native-backed
        /// `internal/*` dependency.
        ///
        /// # Errors
        /// Returns a native error when the shim fails to allocate or
        /// evaluate.
        pub fn $fn_name<'scope>(
            scope: &mut NativeScope<'scope, '_>,
            _caps: &CapabilitySet,
            _runtime_task_spawner: Option<RuntimeTaskSpawner>,
            module: Local<'scope>,
            require: Local<'scope>,
        ) -> Result<Local<'scope>, NativeError> {
            otter_runtime::run_builtin_cjs_shim(
                scope,
                $specifier,
                include_str!($path),
                module,
                require,
            )
        }
    };
}

nodelib_module!(bootstrap_realm, "internal/bootstrap/realm", compat "nodelib/compat/bootstrap_realm.js");
// `internal/util` is vendored; the file sits beside the `internal/util/`
// directory, hence the `_module` basename — the content is a verbatim copy.
nodelib_module!(internal_util, "internal/util", vendored "nodelib/internal/util_module.js");
nodelib_module!(internal_util_types, "internal/util/types", compat "nodelib/compat/internal_util_types.js");
nodelib_module!(internal_util_inspect, "internal/util/inspect", vendored "nodelib/internal/util/inspect.js");
nodelib_module!(internal_util_comparisons, "internal/util/comparisons", vendored "nodelib/internal/util/comparisons.js");
nodelib_module!(internal_util_debuglog, "internal/util/debuglog", compat "nodelib/compat/internal_util_debuglog.js");
nodelib_module!(internal_util_colors, "internal/util/colors", compat "nodelib/compat/internal_util_colors.js");
nodelib_module!(internal_assert, "internal/assert", compat "nodelib/compat/internal_assert.js");
nodelib_module!(internal_options, "internal/options", compat "nodelib/compat/internal_options.js");
nodelib_module!(internal_deps_undici, "internal/deps/undici/undici", compat "nodelib/compat/internal_deps_undici.js");
nodelib_module!(internal_events_abort_listener, "internal/events/abort_listener", compat "nodelib/compat/internal_events_abort_listener.js");
nodelib_module!(internal_abort_controller, "internal/abort_controller", compat "nodelib/compat/internal_abort_controller.js");
nodelib_module!(internal_webstreams_adapters, "internal/webstreams/adapters", vendored "nodelib/internal/webstreams/adapters.js");
nodelib_module!(internal_webstreams_readablestream, "internal/webstreams/readablestream", compat "nodelib/compat/internal_webstreams_readablestream.js");
nodelib_module!(internal_webstreams_writablestream, "internal/webstreams/writablestream", compat "nodelib/compat/internal_webstreams_writablestream.js");
nodelib_module!(internal_webstreams_queuingstrategies, "internal/webstreams/queuingstrategies", compat "nodelib/compat/internal_webstreams_queuingstrategies.js");
nodelib_module!(internal_event_target, "internal/event_target", compat "nodelib/compat/internal_event_target.js");
nodelib_module!(internal_v8_startup_snapshot, "internal/v8/startup_snapshot", compat "nodelib/compat/internal_v8_startup_snapshot.js");
nodelib_module!(internal_modules_helpers, "internal/modules/helpers", compat "nodelib/compat/internal_modules_helpers.js");
nodelib_module!(internal_process_task_queues, "internal/process/task_queues", compat "nodelib/compat/internal_process_task_queues.js");
nodelib_module!(internal_process_execution, "internal/process/execution", compat "nodelib/compat/internal_process_execution.js");
nodelib_module!(internal_process_warning, "internal/process/warning", compat "nodelib/compat/internal_process_warning.js");
nodelib_module!(internal_buffer, "internal/buffer", compat "nodelib/compat/internal_buffer.js");
nodelib_module!(internal_encoding, "internal/encoding", compat "nodelib/compat/internal_encoding.js");
nodelib_module!(internal_blob, "internal/blob", compat "nodelib/compat/internal_blob.js");
nodelib_module!(internal_source_map_cache, "internal/source_map/source_map_cache", compat "nodelib/compat/internal_source_map_cache.js");
nodelib_module!(internal_crypto_keys, "internal/crypto/keys", compat "nodelib/compat/internal_crypto_keys.js");
nodelib_module!(internal_async_hooks, "internal/async_hooks", compat "nodelib/compat/internal_async_hooks.js");
nodelib_module!(internal_async_context_frame, "internal/async_context_frame", compat "nodelib/compat/internal_async_context_frame.js");

nodelib_module!(internal_errors, "internal/errors", vendored "nodelib/internal/errors.js");
nodelib_module!(internal_validators, "internal/validators", vendored "nodelib/internal/validators.js");
nodelib_module!(node_stream, "node:stream", vendored "nodelib/stream.js");
nodelib_module!(stream_promises, "stream/promises", vendored "nodelib/stream/promises.js");
nodelib_module!(streams_add_abort_signal, "internal/streams/add-abort-signal", vendored "nodelib/internal/streams/add-abort-signal.js");
nodelib_module!(streams_compose, "internal/streams/compose", vendored "nodelib/internal/streams/compose.js");
nodelib_module!(streams_destroy, "internal/streams/destroy", vendored "nodelib/internal/streams/destroy.js");
nodelib_module!(streams_duplex, "internal/streams/duplex", vendored "nodelib/internal/streams/duplex.js");
nodelib_module!(streams_duplexify, "internal/streams/duplexify", vendored "nodelib/internal/streams/duplexify.js");
nodelib_module!(streams_duplexpair, "internal/streams/duplexpair", vendored "nodelib/internal/streams/duplexpair.js");
nodelib_module!(streams_end_of_stream, "internal/streams/end-of-stream", vendored "nodelib/internal/streams/end-of-stream.js");
nodelib_module!(streams_from, "internal/streams/from", vendored "nodelib/internal/streams/from.js");
nodelib_module!(streams_lazy_transform, "internal/streams/lazy_transform", vendored "nodelib/internal/streams/lazy_transform.js");
nodelib_module!(streams_legacy, "internal/streams/legacy", vendored "nodelib/internal/streams/legacy.js");
nodelib_module!(streams_operators, "internal/streams/operators", vendored "nodelib/internal/streams/operators.js");
nodelib_module!(streams_passthrough, "internal/streams/passthrough", vendored "nodelib/internal/streams/passthrough.js");
nodelib_module!(streams_pipeline, "internal/streams/pipeline", vendored "nodelib/internal/streams/pipeline.js");
nodelib_module!(streams_readable, "internal/streams/readable", vendored "nodelib/internal/streams/readable.js");
nodelib_module!(streams_state, "internal/streams/state", vendored "nodelib/internal/streams/state.js");
nodelib_module!(streams_transform, "internal/streams/transform", vendored "nodelib/internal/streams/transform.js");
nodelib_module!(streams_utils, "internal/streams/utils", vendored "nodelib/internal/streams/utils.js");
nodelib_module!(streams_writable, "internal/streams/writable", vendored "nodelib/internal/streams/writable.js");
nodelib_module!(streams_iter_types, "internal/streams/iter/types", vendored "nodelib/internal/streams/iter/types.js");
nodelib_module!(streams_iter_classic, "internal/streams/iter/classic", vendored "nodelib/internal/streams/iter/classic.js");
nodelib_module!(streams_iter_from, "internal/streams/iter/from", vendored "nodelib/internal/streams/iter/from.js");
nodelib_module!(streams_iter_utils, "internal/streams/iter/utils", vendored "nodelib/internal/streams/iter/utils.js");
nodelib_module!(streams_iter_broadcast, "internal/streams/iter/broadcast", vendored "nodelib/internal/streams/iter/broadcast.js");
nodelib_module!(streams_iter_consumers, "internal/streams/iter/consumers", vendored "nodelib/internal/streams/iter/consumers.js");
nodelib_module!(streams_iter_duplex, "internal/streams/iter/duplex", vendored "nodelib/internal/streams/iter/duplex.js");
nodelib_module!(streams_iter_pull, "internal/streams/iter/pull", vendored "nodelib/internal/streams/iter/pull.js");
nodelib_module!(streams_iter_push, "internal/streams/iter/push", vendored "nodelib/internal/streams/iter/push.js");
nodelib_module!(streams_iter_ringbuffer, "internal/streams/iter/ringbuffer", vendored "nodelib/internal/streams/iter/ringbuffer.js");
nodelib_module!(streams_iter_share, "internal/streams/iter/share", vendored "nodelib/internal/streams/iter/share.js");
nodelib_module!(streams_iter_transform, "internal/streams/iter/transform", vendored "nodelib/internal/streams/iter/transform.js");
nodelib_module!(zlib_iter, "node:zlib/iter", vendored "nodelib/zlib/iter.js");
nodelib_module!(stream_iter, "stream/iter", vendored "nodelib/stream/iter.js");
nodelib_module!(internal_fixed_queue, "internal/fixed_queue", vendored "nodelib/internal/fixed_queue.js");
nodelib_module!(internal_events_symbols, "internal/events/symbols", vendored "nodelib/internal/events/symbols.js");
nodelib_module!(node_events, "node:events", vendored "nodelib/events.js");
nodelib_module!(node_util, "node:util", vendored "nodelib/util.js");
nodelib_module!(internal_http_parser, "internal/http_parser", compat "nodelib/compat/internal_http_parser.js");
nodelib_module!(internal_timers, "internal/timers", compat "nodelib/compat/internal_timers.js");
nodelib_module!(internal_url, "internal/url", compat "nodelib/compat/internal_url.js");
nodelib_module!(internal_perf_observe, "internal/perf/observe", compat "nodelib/compat/internal_perf_observe.js");
nodelib_module!(internal_net, "internal/net", vendored "nodelib/internal/net.js");
nodelib_module!(internal_stream_base_commons, "internal/stream_base_commons", vendored "nodelib/internal/stream_base_commons.js");
nodelib_module!(node_net, "node:net", vendored "nodelib/net.js");
nodelib_module!(internal_stream_wrap, "internal/otter/stream_wrap", compat "nodelib/compat/internal_stream_wrap.js");
nodelib_module!(internal_otter_stream_handle, "internal/otter/stream_handle", compat "nodelib/compat/internal_otter_stream_handle.js");
nodelib_module!(internal_tcp_wrap, "internal/otter/tcp_wrap", compat "nodelib/compat/internal_tcp_wrap.js");
nodelib_module!(internal_pipe_wrap, "internal/otter/pipe_wrap", compat "nodelib/compat/internal_pipe_wrap.js");
nodelib_module!(internal_udp_wrap, "internal/otter/udp_wrap", compat "nodelib/compat/internal_udp_wrap.js");
nodelib_module!(internal_zlib_handle, "internal/otter/zlib_handle", compat "nodelib/compat/internal_zlib_handle.js");
nodelib_module!(internal_fs_binding, "internal/otter/fs_binding", compat "nodelib/compat/internal_fs_binding.js");
nodelib_module!(internal_fs_dir, "internal/otter/fs_dir", compat "nodelib/compat/internal_fs_dir.js");
nodelib_module!(internal_otter_stdio, "internal/otter/stdio", compat "nodelib/compat/internal_otter_stdio.js");
nodelib_module!(internal_child_process, "internal/child_process", compat "nodelib/compat/internal_child_process.js");
nodelib_module!(internal_fs_event_wrap, "internal/otter/fs_event_wrap", compat "nodelib/compat/internal_fs_event_wrap.js");
nodelib_module!(readline_interface, "internal/readline/interface", vendored "nodelib/internal/readline/interface.js");
nodelib_module!(readline_callbacks, "internal/readline/callbacks", vendored "nodelib/internal/readline/callbacks.js");
nodelib_module!(readline_utils, "internal/readline/utils", vendored "nodelib/internal/readline/utils.js");
nodelib_module!(repl_history, "internal/repl/history", vendored "nodelib/internal/repl/history.js");
nodelib_module!(streams_fast_utf8, "internal/streams/fast-utf8-stream", vendored "nodelib/internal/streams/fast-utf8-stream.js");
nodelib_module!(internal_process_permission, "internal/process/permission", compat "nodelib/compat/internal_process_permission.js");
nodelib_module!(fs_utils, "internal/fs/utils", vendored "nodelib/internal/fs/utils.js");
nodelib_module!(fs_streams, "internal/fs/streams", vendored "nodelib/internal/fs/streams.js");
nodelib_module!(fs_promises, "internal/fs/promises", vendored "nodelib/internal/fs/promises.js");
nodelib_module!(fs_dir, "internal/fs/dir", vendored "nodelib/internal/fs/dir.js");
nodelib_module!(fs_watchers, "internal/fs/watchers", vendored "nodelib/internal/fs/watchers.js");
nodelib_module!(fs_rimraf, "internal/fs/rimraf", vendored "nodelib/internal/fs/rimraf.js");
nodelib_module!(fs_sync_write_stream, "internal/fs/sync_write_stream", vendored "nodelib/internal/fs/sync_write_stream.js");
nodelib_module!(fs_glob, "internal/fs/glob", vendored "nodelib/internal/fs/glob.js");
nodelib_module!(fs_cp, "internal/fs/cp/cp", vendored "nodelib/internal/fs/cp/cp.js");
nodelib_module!(fs_cp_sync, "internal/fs/cp/cp-sync", vendored "nodelib/internal/fs/cp/cp-sync.js");
nodelib_module!(fs_read_context, "internal/fs/read/context", vendored "nodelib/internal/fs/read/context.js");
nodelib_module!(fs_recursive_watch, "internal/fs/recursive_watch", vendored "nodelib/internal/fs/recursive_watch.js");
nodelib_module!(node_fs, "node:fs", vendored "nodelib/fs.js");
nodelib_module!(node_zlib, "node:zlib", vendored "nodelib/zlib.js");
nodelib_module!(internal_dgram, "internal/dgram", vendored "nodelib/internal/dgram.js");
nodelib_module!(node_dgram, "node:dgram", vendored "nodelib/dgram.js");
nodelib_module!(internal_cares_wrap, "internal/otter/cares_wrap", compat "nodelib/compat/internal_cares_wrap.js");
nodelib_module!(internal_otter_ip, "internal/otter/ip", compat "nodelib/compat/internal_otter_ip.js");
nodelib_module!(internal_blocklist, "internal/blocklist", compat "nodelib/compat/internal_blocklist.js");
nodelib_module!(internal_socketaddress, "internal/socketaddress", compat "nodelib/compat/internal_socketaddress.js");
nodelib_module!(internal_worker_js_transferable, "internal/worker/js_transferable", compat "nodelib/compat/internal_worker_js_transferable.js");
nodelib_module!(internal_constants, "internal/constants", vendored "nodelib/internal/constants.js");
nodelib_module!(internal_freelist, "internal/freelist", vendored "nodelib/internal/freelist.js");
nodelib_module!(internal_http, "internal/http", vendored "nodelib/internal/http.js");
nodelib_module!(http_common, "_http_common", vendored "nodelib/_http_common.js");
nodelib_module!(http_agent, "_http_agent", vendored "nodelib/_http_agent.js");
nodelib_module!(http_client, "_http_client", vendored "nodelib/_http_client.js");
nodelib_module!(http_incoming, "_http_incoming", vendored "nodelib/_http_incoming.js");
nodelib_module!(http_outgoing, "_http_outgoing", vendored "nodelib/_http_outgoing.js");
nodelib_module!(http_server, "_http_server", vendored "nodelib/_http_server.js");
nodelib_module!(node_http, "node:http", vendored "nodelib/http.js");
nodelib_module!(parse_args, "internal/util/parse_args/parse_args", vendored "nodelib/internal/util/parse_args/parse_args.js");
nodelib_module!(parse_args_utils, "internal/util/parse_args/utils", vendored "nodelib/internal/util/parse_args/utils.js");
nodelib_module!(internal_mime, "internal/mime", vendored "nodelib/internal/mime.js");
nodelib_module!(internal_deps_minimatch, "internal/deps/minimatch/index", vendored "nodelib/internal/deps/minimatch/index.js");
nodelib_module!(internal_util_diff, "internal/util/diff", vendored "nodelib/internal/util/diff.js");
nodelib_module!(internal_myers_diff, "internal/assert/myers_diff", vendored "nodelib/internal/assert/myers_diff.js");
nodelib_module!(internal_trace_sigint, "internal/util/trace_sigint", vendored "nodelib/internal/util/trace_sigint.js");
nodelib_module!(internal_watchdog, "internal/watchdog", compat "nodelib/compat/internal_watchdog.js");
nodelib_module!(internal_string_decoder, "internal/string_decoder_binding", compat "nodelib/compat/internal_string_decoder.js");
nodelib_module!(node_string_decoder, "node:string_decoder", vendored "nodelib/string_decoder.js");
nodelib_module!(internal_linkedlist, "internal/linkedlist", vendored "nodelib/internal/linkedlist.js");
nodelib_module!(internal_util_inspector, "internal/util/inspector", vendored "nodelib/internal/util/inspector.js");
nodelib_module!(internal_cluster_utils, "internal/cluster/utils", vendored "nodelib/internal/cluster/utils.js");
nodelib_module!(internal_cluster_worker, "internal/cluster/worker", vendored "nodelib/internal/cluster/worker.js");
nodelib_module!(internal_cluster_shared_handle, "internal/cluster/shared_handle", vendored "nodelib/internal/cluster/shared_handle.js");
nodelib_module!(internal_cluster_round_robin_handle, "internal/cluster/round_robin_handle", vendored "nodelib/internal/cluster/round_robin_handle.js");
nodelib_module!(internal_cluster_child, "internal/cluster/child", vendored "nodelib/internal/cluster/child.js");
nodelib_module!(internal_cluster_primary, "internal/cluster/primary", vendored "nodelib/internal/cluster/primary.js");
nodelib_module!(internal_otter_cluster, "internal/otter/cluster", vendored "nodelib/cluster.js");
nodelib_module!(node_cluster, "node:cluster", compat "nodelib/compat/node_cluster.js");

/// The vendored `events` module plus a one-time process-prototype graft:
/// Node's `process` inherits from `EventEmitter` through an intermediate
/// constructor named `process`, and the corpus asserts that exact chain.
/// The graft rides the first `events` load because the runtime-built
/// `process` object exists before any module — and therefore before
/// `EventEmitter` — does.
///
/// # Errors
/// Returns a native error when the shim fails to allocate or evaluate.
pub fn node_events_with_process_graft<'scope>(
    scope: &mut NativeScope<'scope, '_>,
    caps: &CapabilitySet,
    runtime_task_spawner: Option<RuntimeTaskSpawner>,
    module: Local<'scope>,
    require: Local<'scope>,
) -> Result<Local<'scope>, NativeError> {
    let exports = node_events(scope, caps, runtime_task_spawner, module, require)?;
    let graft_module = scope.object()?;
    let graft_exports = scope.object()?;
    scope.set(graft_module, "exports", graft_exports)?;
    otter_runtime::run_builtin_cjs_shim(
        scope,
        "internal/otter/process-graft",
        r#"'use strict';
const { EventEmitter } = require('events');
const target = globalThis.process;
if (typeof target === 'object' && !(target instanceof EventEmitter)) {
  const ProcessCtor = function process() {};
  Object.setPrototypeOf(ProcessCtor.prototype, EventEmitter.prototype);
  Object.setPrototypeOf(ProcessCtor, EventEmitter);
  Object.setPrototypeOf(target, ProcessCtor.prototype);
}
if (typeof target === 'object' && typeof target.getBuiltinModule !== 'function') {
  const Module = require('module');
  const realmRequire = require;
  Object.defineProperty(target, 'getBuiltinModule', {
    value: function getBuiltinModule(id) {
      if (typeof id !== 'string') {
        const suffix = id === null ? ' Received null'
          : ` Received type ${typeof id}`;
        const err = new TypeError(
          `The "id" argument must be of type string.${suffix}`);
        err.code = 'ERR_INVALID_ARG_TYPE';
        throw err;
      }
      if (!Module.isBuiltin(id)) return undefined;
      return realmRequire(id);
    },
    writable: true,
    enumerable: false,
    configurable: true,
  });
}
if (typeof target === 'object') {
  const { internalBinding } = require('internal/bootstrap/realm');
  const utilTypes = require('util').types;
  const utilBindingKeys = [
    'isAnyArrayBuffer', 'isArrayBuffer', 'isArrayBufferView', 'isAsyncFunction',
    'isDataView', 'isDate', 'isExternal', 'isMap', 'isMapIterator',
    'isNativeError', 'isPromise', 'isRegExp', 'isSet', 'isSetIterator',
    'isTypedArray', 'isUint8Array',
  ];
  const allowedBindings = [
    'buffer', 'cares_wrap', 'constants', 'contextify', 'fs', 'fs_event_wrap',
    'icu', 'inspector', 'js_stream', 'natives', 'os', 'pipe_wrap',
    'spawn_sync', 'stream_wrap', 'tcp_wrap', 'tls_wrap', 'tty_wrap',
    'udp_wrap', 'util', 'uv', 'zlib',
  ];
  const cache = new Map();
  Object.defineProperty(target, 'binding', {
    value: function binding(name) {
      name = String(name);
      if (cache.has(name)) return cache.get(name);
      let bound;
      if (name === 'util') {
        bound = {};
        for (const key of utilBindingKeys) bound[key] = utilTypes[key];
      } else if (allowedBindings.includes(name)) {
        try {
          bound = internalBinding(name);
        } catch {
          bound = undefined;
        }
        if (bound === undefined || bound === null) bound = {};
      } else {
        throw new Error(`No such module: ${name}`);
      }
      cache.set(name, bound);
      return bound;
    },
    writable: true,
    enumerable: false,
    configurable: true,
  });
}
"#,
        graft_module,
        require,
    )?;
    Ok(exports)
}
