//! Build-time codegen for the `v`-flag emoji string properties.
//!
//! Parses the vendored UCD `emoji-sequences.txt` and
//! `emoji-zwj-sequences.txt` (UTS#51) into per-property tables — a set of
//! single-code-point ranges and a set of multi-code-point string
//! sequences — and emits them as a generated Rust module. The runtime
//! (`unicode::string_props`) turns these into the `ClassSet` a
//! `\p{Basic_Emoji}` / `\p{RGI_Emoji…}` operand contributes.
//!
//! Regenerating only happens when the data files change.

use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::path::Path;

/// Property identifiers in the order their generated constants are emitted.
/// `RGI_Emoji` is synthesised at runtime as the union of the rest.
const PROPERTIES: &[&str] = &[
    "Basic_Emoji",
    "Emoji_Keycap_Sequence",
    "RGI_Emoji_Flag_Sequence",
    "RGI_Emoji_Modifier_Sequence",
    "RGI_Emoji_Tag_Sequence",
    "RGI_Emoji_ZWJ_Sequence",
];

fn const_prefix(property: &str) -> String {
    property.to_uppercase()
}

/// A property's parsed contents: single-code-point ranges and multi-code
/// point string sequences.
#[derive(Default)]
struct PropertyData {
    ranges: Vec<(u32, u32)>,
    strings: BTreeSet<Vec<u32>>,
}

fn parse_file(path: &Path, out: &mut std::collections::BTreeMap<String, PropertyData>) {
    let text =
        std::fs::read_to_string(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    for line in text.lines() {
        let line = line.split('#').next().unwrap_or("").trim();
        if line.is_empty() {
            continue;
        }
        let mut fields = line.split(';');
        let cps = fields.next().unwrap_or("").trim();
        let Some(property) = fields.next().map(str::trim) else {
            continue;
        };
        if !PROPERTIES.contains(&property) {
            continue;
        }
        let entry = out.entry(property.to_string()).or_default();
        if let Some((lo, hi)) = cps.split_once("..") {
            entry.ranges.push((parse_cp(lo), parse_cp(hi)));
        } else {
            let seq: Vec<u32> = cps.split_whitespace().map(parse_cp).collect();
            match seq.as_slice() {
                [cp] => entry.ranges.push((*cp, *cp)),
                _ => {
                    entry.strings.insert(seq);
                }
            }
        }
    }
}

fn parse_cp(s: &str) -> u32 {
    u32::from_str_radix(s.trim(), 16).unwrap_or_else(|_| panic!("bad code point `{s}`"))
}

fn main() {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let data_dir = Path::new(&manifest).join("data");
    let seq = data_dir.join("emoji-sequences.txt");
    let zwj = data_dir.join("emoji-zwj-sequences.txt");
    println!("cargo:rerun-if-changed={}", seq.display());
    println!("cargo:rerun-if-changed={}", zwj.display());

    let mut props: std::collections::BTreeMap<String, PropertyData> = Default::default();
    parse_file(&seq, &mut props);
    parse_file(&zwj, &mut props);

    let mut code = String::new();
    code.push_str("// @generated by build.rs from vendored UCD emoji data.\n\n");
    for property in PROPERTIES {
        let data = props.entry((*property).to_string()).or_default();
        let prefix = const_prefix(property);

        write!(
            code,
            "pub(crate) static {prefix}_RANGES: &[(u32, u32)] = &["
        )
        .unwrap();
        for (lo, hi) in &data.ranges {
            write!(code, "({lo},{hi}),").unwrap();
        }
        code.push_str("];\n");

        write!(code, "pub(crate) static {prefix}_STRINGS: &[&[u32]] = &[").unwrap();
        for s in &data.strings {
            code.push('&');
            code.push('[');
            for cp in s {
                write!(code, "{cp},").unwrap();
            }
            code.push_str("],");
        }
        code.push_str("];\n");
    }

    let out = Path::new(&std::env::var("OUT_DIR").unwrap()).join("emoji_data.rs");
    std::fs::write(&out, code).unwrap();
}
