//! `Math` namespace — constants and unary / variadic numeric
//! functions reachable through the dedicated `Op::MathLoad` and
//! `Op::MathCall` opcodes.
//!
//! `Math` is also exposed as a real global namespace through the
//! static spec / builder bootstrap flow. The dedicated
//! opcodes remain as a compiler fast path for direct
//! `Math.<name>(...)` calls, while extracted methods such as
//! `let abs = Math.abs; abs(-1)` dispatch through static native
//! function pointers.
//!
//! # Contents
//! - [`MATH_SPEC`] — static namespace spec used by bootstrap.
//! - [`load_constant`] — used by `Op::MathLoad`.
//! - [`call`] — used by `Op::MathCall` and native wrappers.
//! - [`MathError`] — failure modes the dispatcher converts to
//!   `VmError`.
//!
//! # See also
//! - <https://tc39.es/ecma262/#sec-math-object>

use crate::native_function::NativeFastFn;
use crate::number::{NumberValue, bitwise};
use crate::object::{self, JsObject};
use crate::{NativeCtx, NativeError, Value};

/// Foundation `Math` constants per ECMA-262 §21.3.1. Each constant
/// is a static `f64` so the compiler can fold them at intern time
/// when it wants to skip the runtime hop.
///
/// # See also
/// - <https://tc39.es/ecma262/#sec-value-properties-of-the-math-object>
pub const PI: f64 = std::f64::consts::PI;
/// Base of the natural logarithm.
pub const E: f64 = std::f64::consts::E;
/// Natural logarithm of 2.
pub const LN2: f64 = std::f64::consts::LN_2;
/// Natural logarithm of 10.
pub const LN10: f64 = std::f64::consts::LN_10;
/// Base-2 logarithm of `e`.
pub const LOG2E: f64 = std::f64::consts::LOG2_E;
/// Base-10 logarithm of `e`.
pub const LOG10E: f64 = std::f64::consts::LOG10_E;
/// Square root of 0.5.
pub const SQRT1_2: f64 = std::f64::consts::FRAC_1_SQRT_2;
/// Square root of 2.
pub const SQRT2: f64 = std::f64::consts::SQRT_2;

// `MATH_SPEC` + `Intrinsic` generated by `holt!`. Math is a
// non-constructible namespace object — no `[[Construct]]`, no
// prototype, just methods + read-only floating-point constants
// per ECMA-262 §21.3.
otter_macros::holt! {
    name = "Math",
    feature = CORE,
    constants = [
        ("E",       Number(E)),
        ("LN10",    Number(LN10)),
        ("LN2",     Number(LN2)),
        ("LOG10E",  Number(LOG10E)),
        ("LOG2E",   Number(LOG2E)),
        ("PI",      Number(PI)),
        ("SQRT1_2", Number(SQRT1_2)),
        ("SQRT2",   Number(SQRT2)),
    ],
    methods = {
        "abs"    / 1 => native_abs,
        "floor"  / 1 => native_floor,
        "ceil"   / 1 => native_ceil,
        "round"  / 1 => native_round,
        "trunc"  / 1 => native_trunc,
        "sqrt"   / 1 => native_sqrt,
        "pow"    / 2 => native_pow,
        "min"    / 2 => native_min,
        "max"    / 2 => native_max,
        "log"    / 1 => native_log,
        "log2"   / 1 => native_log2,
        "log10"  / 1 => native_log10,
        "log1p"  / 1 => native_log1p,
        "exp"    / 1 => native_exp,
        "expm1"  / 1 => native_expm1,
        "sin"    / 1 => native_sin,
        "cos"    / 1 => native_cos,
        "tan"    / 1 => native_tan,
        "asin"   / 1 => native_asin,
        "acos"   / 1 => native_acos,
        "atan"   / 1 => native_atan,
        "atan2"  / 2 => native_atan2,
        "sinh"   / 1 => native_sinh,
        "cosh"   / 1 => native_cosh,
        "tanh"   / 1 => native_tanh,
        "asinh"  / 1 => native_asinh,
        "acosh"  / 1 => native_acosh,
        "atanh"  / 1 => native_atanh,
        "cbrt"   / 1 => native_cbrt,
        "fround" / 1 => native_fround,
        "hypot"  / 2 => native_hypot,
        "sign"   / 1 => native_sign,
        "clz32"  / 1 => native_clz32,
        "imul"   / 2 => native_imul,
        "random" / 0 => native_random,
        "sumPrecise" / 1 => native_sum_precise,
        "f16round" / 1 => native_f16round,
    },
}

/// Failure modes for [`call`].
#[derive(Debug, Clone, thiserror::Error)]
#[non_exhaustive]
pub enum MathError {
    /// `name` is not a registered Math.* function or constant.
    #[error("Math.{0} is not defined")]
    UnknownMember(String),
    /// Argument is the wrong type or out of range.
    #[error("Math.{name} argument {index} {reason}")]
    BadArgument {
        /// Function name.
        name: &'static str,
        /// Argument index (0-based).
        index: u16,
        /// Short reason.
        reason: &'static str,
    },
}

/// Read a constant or other read-only Math property by name.
/// Returns `None` for unknown names so the dispatcher can surface
/// a uniform `UnknownMember` diagnostic.
#[must_use]
pub fn load_constant(name: &str) -> Option<Value> {
    let v = match name {
        "PI" => PI,
        "E" => E,
        "LN2" => LN2,
        "LN10" => LN10,
        "LOG2E" => LOG2E,
        "LOG10E" => LOG10E,
        "SQRT1_2" => SQRT1_2,
        "SQRT2" => SQRT2,
        _ => return None,
    };
    Some(Value::number(NumberValue::from_f64(v)))
}

/// Dispatch a `Math.<method>(args...)` call. Routes via the
/// typed method id emitted by the compiler — direct match, no
/// table scan or string compare.
pub fn call(
    method: otter_bytecode::method_id::MathMethod,
    args: &[Value],
    heap: &otter_gc::GcHeap,
) -> Result<Value, MathError> {
    use otter_bytecode::method_id::MathMethod as M;
    let nums = coerce_all(method.name(), args, heap)?;
    let value = match method {
        M::Abs => impl_abs(&nums),
        M::Acos => impl_acos(&nums),
        M::Acosh => impl_acosh(&nums),
        M::Asin => impl_asin(&nums),
        M::Asinh => impl_asinh(&nums),
        M::Atan => impl_atan(&nums),
        M::Atan2 => impl_atan2(&nums),
        M::Atanh => impl_atanh(&nums),
        M::Cbrt => impl_cbrt(&nums),
        M::Ceil => impl_ceil(&nums),
        M::Clz32 => impl_clz32(&nums),
        M::Cos => impl_cos(&nums),
        M::Cosh => impl_cosh(&nums),
        M::Exp => impl_exp(&nums),
        M::Expm1 => impl_expm1(&nums),
        M::Floor => impl_floor(&nums),
        M::Fround => impl_fround(&nums),
        M::Hypot => impl_hypot(&nums),
        M::Imul => impl_imul(&nums),
        M::Log => impl_log(&nums),
        M::Log10 => impl_log10(&nums),
        M::Log1p => impl_log1p(&nums),
        M::Log2 => impl_log2(&nums),
        M::Max => impl_max(&nums),
        M::Min => impl_min(&nums),
        M::Pow => impl_pow(&nums),
        M::Random => impl_random(&nums),
        M::Round => impl_round(&nums),
        M::Sign => impl_sign(&nums),
        M::Sin => impl_sin(&nums),
        M::Sinh => impl_sinh(&nums),
        M::Sqrt => impl_sqrt(&nums),
        M::Tan => impl_tan(&nums),
        M::Tanh => impl_tanh(&nums),
        M::Trunc => impl_trunc(&nums),
    };
    Ok(Value::number(value))
}

/// Return the original realm `Math` object when `Math.<method>` still points at
/// the bootstrap native function for `method`.
pub(crate) fn original_method_receiver(
    global: JsObject,
    heap: &otter_gc::GcHeap,
    method: otter_bytecode::method_id::MathMethod,
) -> Option<JsObject> {
    let math = object::get(global, heap, "Math")?.as_object()?;
    let native = object::get(math, heap, method.name())?.as_native_function()?;
    native
        .is_static_fn(heap, original_native_fn(method))
        .then_some(math)
}

/// `true` when direct [`call`] can run without observable `ToPrimitive`.
pub(crate) fn args_skip_to_primitive(args: &[Value]) -> bool {
    args.iter().all(|value| !needs_to_primitive_for_math(value))
}

fn original_native_fn(method: otter_bytecode::method_id::MathMethod) -> NativeFastFn {
    use otter_bytecode::method_id::MathMethod as M;
    match method {
        M::Abs => native_abs,
        M::Acos => native_acos,
        M::Acosh => native_acosh,
        M::Asin => native_asin,
        M::Asinh => native_asinh,
        M::Atan => native_atan,
        M::Atan2 => native_atan2,
        M::Atanh => native_atanh,
        M::Cbrt => native_cbrt,
        M::Ceil => native_ceil,
        M::Clz32 => native_clz32,
        M::Cos => native_cos,
        M::Cosh => native_cosh,
        M::Exp => native_exp,
        M::Expm1 => native_expm1,
        M::Floor => native_floor,
        M::Fround => native_fround,
        M::Hypot => native_hypot,
        M::Imul => native_imul,
        M::Log => native_log,
        M::Log10 => native_log10,
        M::Log1p => native_log1p,
        M::Log2 => native_log2,
        M::Max => native_max,
        M::Min => native_min,
        M::Pow => native_pow,
        M::Random => native_random,
        M::Round => native_round,
        M::Sign => native_sign,
        M::Sin => native_sin,
        M::Sinh => native_sinh,
        M::Sqrt => native_sqrt,
        M::Tan => native_tan,
        M::Tanh => native_tanh,
        M::Trunc => native_trunc,
    }
}

fn native_call(
    ctx: &mut NativeCtx<'_>,
    method: otter_bytecode::method_id::MathMethod,
    args: &[Value],
) -> Result<Value, NativeError> {
    // §21.3.2.{24,25} — `Math.max` / `Math.min` and every other
    // unary / binary Math method call `ToNumber` on each argument,
    // which runs `ToPrimitive(arg, "number")` for non-primitives.
    // Pre-coerce object operands here so `coerce_all` below sees
    // primitives and the user-installed `@@toPrimitive` / `valueOf`
    // / `toString` ladder fires per spec.
    let coerced = coerce_math_args(ctx, args)?;
    call(method, &coerced, ctx.heap()).map_err(|err| match err {
        MathError::UnknownMember(member) => NativeError::TypeError {
            name: method.name(),
            reason: format!("unknown Math member {member}"),
        },
        MathError::BadArgument { reason, .. } => NativeError::TypeError {
            name: method.name(),
            reason: reason.to_string(),
        },
    })
}

fn coerce_math_args(
    ctx: &mut NativeCtx<'_>,
    args: &[Value],
) -> Result<smallvec::SmallVec<[Value; 4]>, NativeError> {
    let mut out: smallvec::SmallVec<[Value; 4]> = args.iter().cloned().collect();
    for slot in out.iter_mut() {
        if needs_to_primitive_for_math(slot) {
            let (interp, exec) = ctx.interp_mut_and_context();
            let exec = exec.ok_or_else(|| NativeError::TypeError {
                name: "Math",
                reason: "missing execution context".to_string(),
            })?;
            let primitive = interp
                .evaluate_to_primitive(&exec, slot, crate::abstract_ops::ToPrimitiveHint::Number)
                .map_err(|e| NativeError::TypeError {
                    name: "Math",
                    reason: e.to_string(),
                })?;
            *slot = primitive;
        }
    }
    Ok(out)
}

fn needs_to_primitive_for_math(v: &Value) -> bool {
    v.is_object()
        || v.is_array()
        || v.is_function()
        || v.is_closure()
        || v.is_native_function()
        || v.is_bound_function()
        || v.is_class_constructor()
        || v.is_proxy()
        || v.is_regexp()
}

macro_rules! native_math {
    ($fn_name:ident, $variant:ident) => {
        fn $fn_name(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
            native_call(ctx, otter_bytecode::method_id::MathMethod::$variant, args)
        }
    };
}

native_math!(native_abs, Abs);
native_math!(native_floor, Floor);
native_math!(native_ceil, Ceil);
native_math!(native_round, Round);
native_math!(native_trunc, Trunc);
native_math!(native_sqrt, Sqrt);
native_math!(native_pow, Pow);
native_math!(native_min, Min);
native_math!(native_max, Max);
native_math!(native_log, Log);
native_math!(native_log2, Log2);
native_math!(native_log10, Log10);
native_math!(native_log1p, Log1p);
native_math!(native_exp, Exp);
native_math!(native_expm1, Expm1);
native_math!(native_sin, Sin);
native_math!(native_cos, Cos);
native_math!(native_tan, Tan);
native_math!(native_asin, Asin);
native_math!(native_acos, Acos);
native_math!(native_atan, Atan);
native_math!(native_atan2, Atan2);
native_math!(native_sinh, Sinh);
native_math!(native_cosh, Cosh);
native_math!(native_tanh, Tanh);
native_math!(native_asinh, Asinh);
native_math!(native_acosh, Acosh);
native_math!(native_atanh, Atanh);
native_math!(native_cbrt, Cbrt);
native_math!(native_fround, Fround);
native_math!(native_hypot, Hypot);
native_math!(native_sign, Sign);
native_math!(native_clz32, Clz32);
native_math!(native_imul, Imul);
native_math!(native_random, Random);

fn coerce_all(
    name: &'static str,
    args: &[Value],
    heap: &otter_gc::GcHeap,
) -> Result<Vec<NumberValue>, MathError> {
    let mut out = Vec::with_capacity(args.len());
    for (idx, v) in args.iter().enumerate() {
        let n = if let Some(n) = v.as_number() {
            n
        } else if let Some(b) = v.as_boolean() {
            if b {
                NumberValue::Smi(1)
            } else {
                NumberValue::Smi(0)
            }
        } else if v.is_null() {
            NumberValue::Smi(0)
        } else if v.is_undefined() {
            NumberValue::Double(f64::NAN)
        } else if let Some(s) = v.as_string(heap) {
            // §7.1.4 ToNumber on String.
            crate::number::parse::to_number_from_string(&s.to_lossy_string(heap))
        } else if v.is_big_int() {
            return Err(MathError::BadArgument {
                name,
                index: idx as u16,
                reason: "cannot convert a BigInt to a number",
            });
        } else if v.is_symbol() {
            return Err(MathError::BadArgument {
                name,
                index: idx as u16,
                reason: "cannot convert a Symbol to a number",
            });
        } else {
            // Non-primitive operands should have been routed through
            // `Interpreter::math_coerce_args` before reaching this
            // table. Soft NaN so Math.max / Math.min produce the
            // §21.3.2.{24,25} step 3 NaN result.
            NumberValue::Double(f64::NAN)
        };
        out.push(n);
    }
    Ok(out)
}

fn impl_abs(args: &[NumberValue]) -> NumberValue {
    let f = first_or_nan(args);
    NumberValue::Double(f.as_f64().abs()).canonicalize()
}

fn impl_floor(args: &[NumberValue]) -> NumberValue {
    NumberValue::Double(first_or_nan(args).as_f64().floor()).canonicalize()
}

fn impl_ceil(args: &[NumberValue]) -> NumberValue {
    NumberValue::Double(first_or_nan(args).as_f64().ceil()).canonicalize()
}

fn impl_round(args: &[NumberValue]) -> NumberValue {
    let f = first_or_nan(args).as_f64();
    // ES spec: half-to-positive-infinity (so .5 rounds up, -.5
    // rounds toward zero). Rust's `f64::round` rounds half-away-
    // from-zero, which differs for negative half-integers.
    let rounded = if f.is_nan() || f.is_infinite() || f == 0.0 {
        // Preserves NaN, ±Infinity, and the sign of ±0.
        f
    } else {
        // §21.3.2.28 half-to-positive-infinity. `(f + 0.5).floor()` is
        // imprecise: for f = 0.49999999999999994 the sum rounds up to 1
        // and yields 1 instead of the spec's +0. Round from the integer
        // floor and its fractional part instead, so the addition never
        // perturbs the result.
        let floor = f.floor();
        let r = if f - floor >= 0.5 { floor + 1.0 } else { floor };
        // For x in [-0.5, 0) the result is -0, so restore the sign of a
        // zero result whose input was negative.
        if r == 0.0 && f < 0.0 { -0.0 } else { r }
    };
    NumberValue::Double(rounded).canonicalize()
}

fn impl_trunc(args: &[NumberValue]) -> NumberValue {
    NumberValue::Double(first_or_nan(args).as_f64().trunc()).canonicalize()
}

fn impl_sqrt(args: &[NumberValue]) -> NumberValue {
    NumberValue::Double(first_or_nan(args).as_f64().sqrt()).canonicalize()
}

fn impl_pow(args: &[NumberValue]) -> NumberValue {
    let base = args
        .first()
        .copied()
        .unwrap_or(NumberValue::Double(f64::NAN));
    let exp = args
        .get(1)
        .copied()
        .unwrap_or(NumberValue::Double(f64::NAN));
    bitwise::pow(base, exp)
}

fn impl_min(args: &[NumberValue]) -> NumberValue {
    if args.is_empty() {
        return NumberValue::Double(f64::INFINITY);
    }
    let mut current = args[0].as_f64();
    for v in &args[1..] {
        let f = v.as_f64();
        if f.is_nan() {
            return NumberValue::Double(f64::NAN);
        }
        // Per spec: -0 < +0.
        if f < current || (f == 0.0 && current == 0.0 && f.is_sign_negative()) {
            current = f;
        }
    }
    NumberValue::Double(current).canonicalize()
}

fn impl_max(args: &[NumberValue]) -> NumberValue {
    if args.is_empty() {
        return NumberValue::Double(f64::NEG_INFINITY);
    }
    let mut current = args[0].as_f64();
    for v in &args[1..] {
        let f = v.as_f64();
        if f.is_nan() {
            return NumberValue::Double(f64::NAN);
        }
        if f > current || (f == 0.0 && current == 0.0 && current.is_sign_negative()) {
            current = f;
        }
    }
    NumberValue::Double(current).canonicalize()
}

/// §21.3.2 — wrap a unary `f64 → f64` into a Math function impl.
fn unary(args: &[NumberValue], f: fn(f64) -> f64) -> NumberValue {
    NumberValue::Double(f(first_or_nan(args).as_f64())).canonicalize()
}

fn impl_log(args: &[NumberValue]) -> NumberValue {
    unary(args, f64::ln)
}
fn impl_log2(args: &[NumberValue]) -> NumberValue {
    unary(args, f64::log2)
}
fn impl_log10(args: &[NumberValue]) -> NumberValue {
    unary(args, f64::log10)
}
fn impl_log1p(args: &[NumberValue]) -> NumberValue {
    unary(args, f64::ln_1p)
}
fn impl_exp(args: &[NumberValue]) -> NumberValue {
    unary(args, f64::exp)
}
fn impl_expm1(args: &[NumberValue]) -> NumberValue {
    unary(args, f64::exp_m1)
}
fn impl_sin(args: &[NumberValue]) -> NumberValue {
    unary(args, f64::sin)
}
fn impl_cos(args: &[NumberValue]) -> NumberValue {
    unary(args, f64::cos)
}
fn impl_tan(args: &[NumberValue]) -> NumberValue {
    unary(args, f64::tan)
}
fn impl_asin(args: &[NumberValue]) -> NumberValue {
    unary(args, f64::asin)
}
fn impl_acos(args: &[NumberValue]) -> NumberValue {
    unary(args, f64::acos)
}
fn impl_atan(args: &[NumberValue]) -> NumberValue {
    unary(args, f64::atan)
}
fn impl_sinh(args: &[NumberValue]) -> NumberValue {
    unary(args, f64::sinh)
}
fn impl_cosh(args: &[NumberValue]) -> NumberValue {
    unary(args, f64::cosh)
}
fn impl_tanh(args: &[NumberValue]) -> NumberValue {
    unary(args, f64::tanh)
}
fn impl_asinh(args: &[NumberValue]) -> NumberValue {
    unary(args, f64::asinh)
}
fn impl_acosh(args: &[NumberValue]) -> NumberValue {
    unary(args, f64::acosh)
}
fn impl_atanh(args: &[NumberValue]) -> NumberValue {
    unary(args, f64::atanh)
}
fn impl_cbrt(args: &[NumberValue]) -> NumberValue {
    unary(args, f64::cbrt)
}
fn impl_fround(args: &[NumberValue]) -> NumberValue {
    NumberValue::Double(first_or_nan(args).as_f64() as f32 as f64).canonicalize()
}

/// §21.3.2.2 Math.atan2(y, x).
fn impl_atan2(args: &[NumberValue]) -> NumberValue {
    let y = args
        .first()
        .copied()
        .unwrap_or(NumberValue::Double(f64::NAN))
        .as_f64();
    let x = args
        .get(1)
        .copied()
        .unwrap_or(NumberValue::Double(f64::NAN))
        .as_f64();
    NumberValue::Double(y.atan2(x)).canonicalize()
}

/// §21.3.2.18 Math.hypot(...args).
fn impl_hypot(args: &[NumberValue]) -> NumberValue {
    if args.is_empty() {
        return NumberValue::Smi(0);
    }
    let mut sum_sq = 0.0f64;
    let mut any_nan = false;
    let mut any_inf = false;
    for v in args {
        let f = v.as_f64();
        if f.is_nan() {
            any_nan = true;
        } else if f.is_infinite() {
            any_inf = true;
        } else {
            sum_sq += f * f;
        }
    }
    let result = if any_inf {
        f64::INFINITY
    } else if any_nan {
        f64::NAN
    } else {
        sum_sq.sqrt()
    };
    NumberValue::Double(result).canonicalize()
}

/// §21.3.2.30 Math.sign(x).
fn impl_sign(args: &[NumberValue]) -> NumberValue {
    let f = first_or_nan(args).as_f64();
    if f.is_nan() {
        NumberValue::Double(f64::NAN)
    } else if f == 0.0 {
        // Preserve `±0` per spec — return the same zero shape.
        NumberValue::Double(f).canonicalize()
    } else if f > 0.0 {
        NumberValue::Smi(1)
    } else {
        NumberValue::Smi(-1)
    }
}

/// §21.3.2.5 Math.clz32(x) — count leading zeros after ToUint32.
fn impl_clz32(args: &[NumberValue]) -> NumberValue {
    let f = first_or_nan(args).as_f64();
    if !f.is_finite() {
        return NumberValue::Smi(32);
    }
    let n = (f as i64) as u32;
    NumberValue::Smi(n.leading_zeros() as i32)
}

/// §21.3.2.20 Math.imul(a, b) — 32-bit integer multiplication.
fn impl_imul(args: &[NumberValue]) -> NumberValue {
    let a = args
        .first()
        .copied()
        .unwrap_or(NumberValue::Double(f64::NAN))
        .as_f64();
    let b = args
        .get(1)
        .copied()
        .unwrap_or(NumberValue::Double(f64::NAN))
        .as_f64();
    let ai = if a.is_finite() { a as i64 as i32 } else { 0 };
    let bi = if b.is_finite() { b as i64 as i32 } else { 0 };
    NumberValue::Smi(ai.wrapping_mul(bi))
}

/// §21.3.2.27 Math.random() — non-cryptographic pseudo-random.
/// Uses a process-local SplitMix64 stream seeded from the system
/// clock. This is intentionally not cryptographic.
fn impl_random(_args: &[NumberValue]) -> NumberValue {
    use std::sync::atomic::{AtomicU64, Ordering};

    static SEED: AtomicU64 = AtomicU64::new(0);

    fn initial_seed() -> u64 {
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_nanos() as u64)
            .unwrap_or(0xDEADBEEFu64)
            | 1
    }

    let mut s = SEED.load(Ordering::Relaxed);
    if s == 0 {
        let init = initial_seed();
        s = SEED
            .compare_exchange(0, init, Ordering::AcqRel, Ordering::Acquire)
            .unwrap_or_else(|actual| actual);
    }

    loop {
        let next = s.wrapping_add(0x9E3779B97F4A7C15);
        match SEED.compare_exchange_weak(s, next, Ordering::AcqRel, Ordering::Acquire) {
            Ok(_) => {
                let mut z = next;
                z = (z ^ (z >> 30)).wrapping_mul(0xBF58476D1CE4E5B9);
                z = (z ^ (z >> 27)).wrapping_mul(0x94D049BB133111EB);
                z ^= z >> 31;
                // Map upper 53 bits into `[0, 1)`.
                let bits = (z >> 11) as f64 / (1u64 << 53) as f64;
                return NumberValue::Double(bits);
            }
            Err(0) => {
                let init = initial_seed();
                s = SEED
                    .compare_exchange(0, init, Ordering::AcqRel, Ordering::Acquire)
                    .unwrap_or_else(|current| current);
            }
            Err(actual) => s = actual,
        }
    }
}

fn first_or_nan(args: &[NumberValue]) -> NumberValue {
    args.first()
        .copied()
        .unwrap_or(NumberValue::Double(f64::NAN))
}

/// Running classification of the sum per the `Math.sumPrecise`
/// state machine (sec-math.sumprecise). Only the [`SumState::Finite`]
/// case touches the exact accumulator.
#[derive(Clone, Copy, PartialEq, Eq)]
enum SumState {
    MinusZero,
    Finite,
    PlusInfinity,
    MinusInfinity,
    NotANumber,
}

/// §21.3.2.x `Math.sumPrecise(items)` — maximally precise (correctly
/// rounded) summation of an iterable of Numbers.
///
/// Finite addends are summed without rounding error by decomposing
/// each double into `mantissa × 2^e` (with `e ≥ -1074`) and
/// accumulating `mantissa << (e + 1074)` into an exact big integer
/// scaled by `2^1074`. The final magnitude is rounded once,
/// round-half-to-even, back to an `f64`. Non-finite values and signed
/// zero are tracked by the state machine, never by the accumulator.
fn native_sum_precise(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    use crate::native_function::vm_to_native_error;

    let items = args.first().copied().unwrap_or_else(Value::undefined);
    let (interp, exec) = ctx.interp_mut_and_context();
    let exec = exec.ok_or_else(|| NativeError::TypeError {
        name: "Math.sumPrecise",
        reason: "missing execution context".to_string(),
    })?;

    // step — GetIterator(items, sync). Rejects non-iterables (and the
    // `Math.sumPrecise()` / `{}` cases) with a TypeError.
    let iter_result = interp.get_iterator_sync(&exec, &items);
    let (iterator, next) =
        iter_result.map_err(|e| vm_to_native_error(interp, e, "Math.sumPrecise"))?;

    let mut state = SumState::MinusZero;
    let mut acc = num_bigint::BigInt::from(0);
    let mut count: u64 = 0;

    loop {
        match interp.iterator_step_sync(&exec, &iterator, &next) {
            Ok(None) => break,
            Ok(Some(value)) => {
                count += 1;
                // step — count is bounded by 2^53 - 1.
                if count >= (1u64 << 53) {
                    let _ = interp.iterator_close_sync(&exec, &iterator);
                    return Err(NativeError::RangeError {
                        name: "Math.sumPrecise",
                        reason: "input exceeds 2^53 - 1 elements".to_string(),
                    });
                }
                // step — every element must be a Number, checked before
                // any state transition and without coercion. A non-Number
                // closes the iterator, then throws.
                let Some(n) = value.as_number() else {
                    let _ = interp.iterator_close_sync(&exec, &iterator);
                    return Err(NativeError::TypeError {
                        name: "Math.sumPrecise",
                        reason: "every element must be a Number".to_string(),
                    });
                };
                if state == SumState::NotANumber {
                    continue;
                }
                let n = n.as_f64();
                if n.is_nan() {
                    state = SumState::NotANumber;
                } else if n == f64::INFINITY {
                    state = if state == SumState::MinusInfinity {
                        SumState::NotANumber
                    } else {
                        SumState::PlusInfinity
                    };
                } else if n == f64::NEG_INFINITY {
                    state = if state == SumState::PlusInfinity {
                        SumState::NotANumber
                    } else {
                        SumState::MinusInfinity
                    };
                } else if (state == SumState::MinusZero || state == SumState::Finite)
                    && !(n == 0.0 && n.is_sign_negative())
                {
                    // Finite, non-(-0) addend joins the exact sum.
                    state = SumState::Finite;
                    add_finite_f64(&mut acc, n);
                }
            }
            // IteratorStepValue threw: the record is already closed by
            // the protocol; propagate without re-closing.
            Err(e) => return Err(vm_to_native_error(interp, e, "Math.sumPrecise")),
        }
    }

    let result = match state {
        SumState::NotANumber => f64::NAN,
        SumState::PlusInfinity => f64::INFINITY,
        SumState::MinusInfinity => f64::NEG_INFINITY,
        SumState::MinusZero => -0.0,
        SumState::Finite => scaled_bigint_to_f64(&acc),
    };
    Ok(Value::number(NumberValue::from_f64(result)))
}

/// §21.3.2.16 `Math.f16round(x)` — round `x` to the nearest IEEE-754
/// half (binary16) and return it back as a `Number`.
fn native_f16round(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
    let coerced = coerce_math_args(ctx, args)?;
    let nums = coerce_all("Math.f16round", &coerced, ctx.heap()).map_err(|err| match err {
        MathError::BadArgument { reason, .. } => NativeError::TypeError {
            name: "Math.f16round",
            reason: reason.to_string(),
        },
        MathError::UnknownMember(member) => NativeError::TypeError {
            name: "Math.f16round",
            reason: format!("unknown Math member {member}"),
        },
    })?;
    let x = first_or_nan(&nums).as_f64();
    let bits = crate::binary::typed_array::f64_to_f16_bits(x);
    let rounded = crate::binary::typed_array::f16_bits_to_f64(bits);
    Ok(Value::number(NumberValue::from_f64(rounded)))
}

/// Add a finite `f64` to the `2^1074`-scaled exact accumulator.
fn add_finite_f64(acc: &mut num_bigint::BigInt, n: f64) {
    if n == 0.0 {
        return; // ±0 contributes nothing to the magnitude.
    }
    let bits = n.to_bits();
    let negative = (bits >> 63) == 1;
    let exp_field = ((bits >> 52) & 0x7ff) as i64;
    let frac = bits & 0x000F_FFFF_FFFF_FFFF;
    // value = mantissa × 2^exp, with exp ≥ -1074 for every finite double.
    let (mantissa, exp) = if exp_field == 0 {
        (frac, -1074_i64)
    } else {
        (frac | 0x0010_0000_0000_0000, exp_field - 1075)
    };
    let shift = (exp + 1074) as usize; // ≥ 0
    let term = num_bigint::BigInt::from(mantissa) << shift;
    if negative {
        *acc -= term;
    } else {
        *acc += term;
    }
}

/// Round the `2^1074`-scaled exact integer back to the nearest `f64`
/// (round-half-to-even). The sign of a zero result is positive, matching
/// `𝔽(0)` for the finite-sum case.
fn scaled_bigint_to_f64(acc: &num_bigint::BigInt) -> f64 {
    use num_bigint::Sign;
    use num_traits::ToPrimitive;

    if acc.sign() == Sign::NoSign {
        return 0.0;
    }
    let negative = acc.sign() == Sign::Minus;
    let mag = acc.magnitude(); // &BigUint, value = mag × 2^-1074
    let bits = mag.bits(); // index of MSB + 1

    let abs = if bits <= 53 {
        // mag ∈ [1, 2^53): `mag × 2^-1074` is exactly a subnormal or the
        // smallest normal binade, whose bit pattern is `mag` itself.
        f64::from_bits(mag.to_u64().expect("≤ 53 bits fits in u64"))
    } else {
        let drop = bits - 53; // > 0
        let high_big = mag >> drop as usize;
        let mut high = high_big.to_u64().expect("53-bit value fits in u64"); // ∈ [2^52, 2^53)
        // Round-half-to-even on the dropped low bits.
        let mask =
            (num_bigint::BigUint::from(1u8) << drop as usize) - num_bigint::BigUint::from(1u8);
        let rem = mag & &mask;
        let half = num_bigint::BigUint::from(1u8) << (drop - 1) as usize;
        let mut e = (bits as i64 - 1) - 1074; // unbiased exponent of the value
        if rem > half || (rem == half && (high & 1) == 1) {
            high += 1;
            if high == (1u64 << 53) {
                high = 1u64 << 52;
                e += 1;
            }
        }
        if e > 1023 {
            f64::INFINITY
        } else {
            // bits > 53 ⇒ value ≥ 2^-1021, so the result is normal
            // (unbiased exponent e ∈ [-1021, 1023], biased ∈ [2, 2046]).
            let biased = (e + 1023) as u64;
            let frac = high & 0x000F_FFFF_FFFF_FFFF;
            f64::from_bits((biased << 52) | frac)
        }
    };
    if negative { -abs } else { abs }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn n(v: i32) -> Value {
        Value::number(NumberValue::Smi(v))
    }

    #[test]
    fn constants_resolve() {
        let pi = load_constant("PI").unwrap();
        assert!((pi.as_number().unwrap().as_f64() - PI).abs() < 1e-12);
        assert!(load_constant("nope").is_none());
    }

    #[test]
    fn min_and_max_handle_nan() {
        use otter_bytecode::method_id::MathMethod;
        let heap = otter_gc::GcHeap::new().expect("heap");
        let r = call(MathMethod::Min, &[n(1), n(2), n(3)], &heap).unwrap();
        assert_eq!(r.as_number().unwrap().as_smi(), Some(1));
        let r = call(MathMethod::Max, &[n(1), n(2), n(3)], &heap).unwrap();
        assert_eq!(r.as_number().unwrap().as_smi(), Some(3));
        let nan_r = call(
            MathMethod::Max,
            &[n(1), Value::number(NumberValue::Double(f64::NAN))],
            &heap,
        )
        .unwrap();
        assert!(nan_r.as_number().unwrap().is_nan());
    }

    #[test]
    fn pow_routes_to_bitwise_pow() {
        use otter_bytecode::method_id::MathMethod;
        let heap = otter_gc::GcHeap::new().expect("heap");
        let r = call(MathMethod::Pow, &[n(2), n(10)], &heap).unwrap();
        assert_eq!(r.as_number().unwrap().as_smi(), Some(1024));
    }
}
