//! `Math` namespace — constants and unary / variadic numeric
//! functions reachable through the dedicated `Op::MathLoad` and
//! `Op::MathCall` opcodes.
//!
//! `Math` is also exposed as a real global namespace through the
//! static spec / builder bootstrap flow. The dedicated
//! opcodes remain as a compiler fast path for direct
//! `Math.<name>(...)` calls, while extracted methods such as
//! `let abs = Math.abs; abs(-1)` dispatch through static native
//! function pointers.
//!
//! # Contents
//! - [`MATH_SPEC`] — static namespace spec used by bootstrap.
//! - [`load_constant`] — used by `Op::MathLoad`.
//! - [`call`] — used by `Op::MathCall` and native wrappers.
//! - [`MathError`] — failure modes the dispatcher converts to
//!   `VmError`.
//!
//! # See also
//! - <https://tc39.es/ecma262/#sec-math-object>

use crate::number::{NumberValue, bitwise};
use crate::{NativeCtx, NativeError, Value};

/// Foundation `Math` constants per ECMA-262 §21.3.1. Each constant
/// is a static `f64` so the compiler can fold them at intern time
/// when it wants to skip the runtime hop.
///
/// # See also
/// - <https://tc39.es/ecma262/#sec-value-properties-of-the-math-object>
pub const PI: f64 = std::f64::consts::PI;
/// Base of the natural logarithm.
pub const E: f64 = std::f64::consts::E;
/// Natural logarithm of 2.
pub const LN2: f64 = std::f64::consts::LN_2;
/// Natural logarithm of 10.
pub const LN10: f64 = std::f64::consts::LN_10;
/// Base-2 logarithm of `e`.
pub const LOG2E: f64 = std::f64::consts::LOG2_E;
/// Base-10 logarithm of `e`.
pub const LOG10E: f64 = std::f64::consts::LOG10_E;
/// Square root of 0.5.
pub const SQRT1_2: f64 = std::f64::consts::FRAC_1_SQRT_2;
/// Square root of 2.
pub const SQRT2: f64 = std::f64::consts::SQRT_2;

// `MATH_SPEC` + `Intrinsic` generated by `holt!`. Math is a
// non-constructible namespace object — no `[[Construct]]`, no
// prototype, just methods + read-only floating-point constants
// per ECMA-262 §21.3.
otter_macros::holt! {
    name = "Math",
    feature = CORE,
    constants = [
        ("E",       Number(E)),
        ("LN10",    Number(LN10)),
        ("LN2",     Number(LN2)),
        ("LOG10E",  Number(LOG10E)),
        ("LOG2E",   Number(LOG2E)),
        ("PI",      Number(PI)),
        ("SQRT1_2", Number(SQRT1_2)),
        ("SQRT2",   Number(SQRT2)),
    ],
    methods = {
        "abs"    / 1 => native_abs,
        "floor"  / 1 => native_floor,
        "ceil"   / 1 => native_ceil,
        "round"  / 1 => native_round,
        "trunc"  / 1 => native_trunc,
        "sqrt"   / 1 => native_sqrt,
        "pow"    / 2 => native_pow,
        "min"    / 2 => native_min,
        "max"    / 2 => native_max,
        "log"    / 1 => native_log,
        "log2"   / 1 => native_log2,
        "log10"  / 1 => native_log10,
        "log1p"  / 1 => native_log1p,
        "exp"    / 1 => native_exp,
        "expm1"  / 1 => native_expm1,
        "sin"    / 1 => native_sin,
        "cos"    / 1 => native_cos,
        "tan"    / 1 => native_tan,
        "asin"   / 1 => native_asin,
        "acos"   / 1 => native_acos,
        "atan"   / 1 => native_atan,
        "atan2"  / 2 => native_atan2,
        "sinh"   / 1 => native_sinh,
        "cosh"   / 1 => native_cosh,
        "tanh"   / 1 => native_tanh,
        "asinh"  / 1 => native_asinh,
        "acosh"  / 1 => native_acosh,
        "atanh"  / 1 => native_atanh,
        "cbrt"   / 1 => native_cbrt,
        "fround" / 1 => native_fround,
        "hypot"  / 2 => native_hypot,
        "sign"   / 1 => native_sign,
        "clz32"  / 1 => native_clz32,
        "imul"   / 2 => native_imul,
        "random" / 0 => native_random,
    },
}

/// Failure modes for [`call`].
#[derive(Debug, Clone, thiserror::Error)]
#[non_exhaustive]
pub enum MathError {
    /// `name` is not a registered Math.* function or constant.
    #[error("Math.{0} is not defined")]
    UnknownMember(String),
    /// Argument is the wrong type or out of range.
    #[error("Math.{name} argument {index} {reason}")]
    BadArgument {
        /// Function name.
        name: &'static str,
        /// Argument index (0-based).
        index: u16,
        /// Short reason.
        reason: &'static str,
    },
}

/// Read a constant or other read-only Math property by name.
/// Returns `None` for unknown names so the dispatcher can surface
/// a uniform `UnknownMember` diagnostic.
#[must_use]
pub fn load_constant(name: &str) -> Option<Value> {
    let v = match name {
        "PI" => PI,
        "E" => E,
        "LN2" => LN2,
        "LN10" => LN10,
        "LOG2E" => LOG2E,
        "LOG10E" => LOG10E,
        "SQRT1_2" => SQRT1_2,
        "SQRT2" => SQRT2,
        _ => return None,
    };
    Some(Value::number(NumberValue::from_f64(v)))
}

/// Dispatch a `Math.<method>(args...)` call. Routes via the
/// typed method id emitted by the compiler — direct match, no
/// table scan or string compare.
pub fn call(
    method: otter_bytecode::method_id::MathMethod,
    args: &[Value],
    heap: &otter_gc::GcHeap,
) -> Result<Value, MathError> {
    use otter_bytecode::method_id::MathMethod as M;
    let nums = coerce_all(method.name(), args, heap)?;
    let value = match method {
        M::Abs => impl_abs(&nums),
        M::Acos => impl_acos(&nums),
        M::Acosh => impl_acosh(&nums),
        M::Asin => impl_asin(&nums),
        M::Asinh => impl_asinh(&nums),
        M::Atan => impl_atan(&nums),
        M::Atan2 => impl_atan2(&nums),
        M::Atanh => impl_atanh(&nums),
        M::Cbrt => impl_cbrt(&nums),
        M::Ceil => impl_ceil(&nums),
        M::Clz32 => impl_clz32(&nums),
        M::Cos => impl_cos(&nums),
        M::Cosh => impl_cosh(&nums),
        M::Exp => impl_exp(&nums),
        M::Expm1 => impl_expm1(&nums),
        M::Floor => impl_floor(&nums),
        M::Fround => impl_fround(&nums),
        M::Hypot => impl_hypot(&nums),
        M::Imul => impl_imul(&nums),
        M::Log => impl_log(&nums),
        M::Log10 => impl_log10(&nums),
        M::Log1p => impl_log1p(&nums),
        M::Log2 => impl_log2(&nums),
        M::Max => impl_max(&nums),
        M::Min => impl_min(&nums),
        M::Pow => impl_pow(&nums),
        M::Random => impl_random(&nums),
        M::Round => impl_round(&nums),
        M::Sign => impl_sign(&nums),
        M::Sin => impl_sin(&nums),
        M::Sinh => impl_sinh(&nums),
        M::Sqrt => impl_sqrt(&nums),
        M::Tan => impl_tan(&nums),
        M::Tanh => impl_tanh(&nums),
        M::Trunc => impl_trunc(&nums),
    };
    Ok(Value::number(value))
}

fn native_call(
    ctx: &mut NativeCtx<'_>,
    method: otter_bytecode::method_id::MathMethod,
    args: &[Value],
) -> Result<Value, NativeError> {
    // §21.3.2.{24,25} — `Math.max` / `Math.min` and every other
    // unary / binary Math method call `ToNumber` on each argument,
    // which runs `ToPrimitive(arg, "number")` for non-primitives.
    // Pre-coerce object operands here so `coerce_all` below sees
    // primitives and the user-installed `@@toPrimitive` / `valueOf`
    // / `toString` ladder fires per spec.
    let coerced = coerce_math_args(ctx, args)?;
    call(method, &coerced, ctx.heap()).map_err(|err| match err {
        MathError::UnknownMember(member) => NativeError::TypeError {
            name: method.name(),
            reason: format!("unknown Math member {member}"),
        },
        MathError::BadArgument { reason, .. } => NativeError::TypeError {
            name: method.name(),
            reason: reason.to_string(),
        },
    })
}

fn coerce_math_args(
    ctx: &mut NativeCtx<'_>,
    args: &[Value],
) -> Result<smallvec::SmallVec<[Value; 4]>, NativeError> {
    let mut out: smallvec::SmallVec<[Value; 4]> = args.iter().cloned().collect();
    for slot in out.iter_mut() {
        if needs_to_primitive_for_math(slot) {
            let (interp, exec) = ctx.interp_mut_and_context();
            let exec = exec.ok_or(NativeError::TypeError {
                name: "Math",
                reason: "missing execution context".to_string(),
            })?;
            let primitive = interp
                .evaluate_to_primitive(&exec, slot, crate::abstract_ops::ToPrimitiveHint::Number)
                .map_err(|e| NativeError::TypeError {
                    name: "Math",
                    reason: e.to_string(),
                })?;
            *slot = primitive;
        }
    }
    Ok(out)
}

fn needs_to_primitive_for_math(v: &Value) -> bool {
    v.is_object()
        || v.is_array()
        || v.is_function()
        || v.is_closure()
        || v.is_native_function()
        || v.is_bound_function()
        || v.is_class_constructor()
        || v.is_proxy()
        || v.is_regexp()
}

macro_rules! native_math {
    ($fn_name:ident, $variant:ident) => {
        fn $fn_name(ctx: &mut NativeCtx<'_>, args: &[Value]) -> Result<Value, NativeError> {
            native_call(ctx, otter_bytecode::method_id::MathMethod::$variant, args)
        }
    };
}

native_math!(native_abs, Abs);
native_math!(native_floor, Floor);
native_math!(native_ceil, Ceil);
native_math!(native_round, Round);
native_math!(native_trunc, Trunc);
native_math!(native_sqrt, Sqrt);
native_math!(native_pow, Pow);
native_math!(native_min, Min);
native_math!(native_max, Max);
native_math!(native_log, Log);
native_math!(native_log2, Log2);
native_math!(native_log10, Log10);
native_math!(native_log1p, Log1p);
native_math!(native_exp, Exp);
native_math!(native_expm1, Expm1);
native_math!(native_sin, Sin);
native_math!(native_cos, Cos);
native_math!(native_tan, Tan);
native_math!(native_asin, Asin);
native_math!(native_acos, Acos);
native_math!(native_atan, Atan);
native_math!(native_atan2, Atan2);
native_math!(native_sinh, Sinh);
native_math!(native_cosh, Cosh);
native_math!(native_tanh, Tanh);
native_math!(native_asinh, Asinh);
native_math!(native_acosh, Acosh);
native_math!(native_atanh, Atanh);
native_math!(native_cbrt, Cbrt);
native_math!(native_fround, Fround);
native_math!(native_hypot, Hypot);
native_math!(native_sign, Sign);
native_math!(native_clz32, Clz32);
native_math!(native_imul, Imul);
native_math!(native_random, Random);

fn coerce_all(
    name: &'static str,
    args: &[Value],
    heap: &otter_gc::GcHeap,
) -> Result<Vec<NumberValue>, MathError> {
    let mut out = Vec::with_capacity(args.len());
    for (idx, v) in args.iter().enumerate() {
        let n = if let Some(n) = v.as_number() {
            n
        } else if let Some(b) = v.as_boolean() {
            if b {
                NumberValue::Smi(1)
            } else {
                NumberValue::Smi(0)
            }
        } else if v.is_null() {
            NumberValue::Smi(0)
        } else if v.is_undefined() {
            NumberValue::Double(f64::NAN)
        } else if let Some(s) = v.as_string(heap) {
            // §7.1.4 ToNumber on String.
            crate::number::parse::to_number_from_string(&s.to_lossy_string(heap))
        } else if v.is_big_int() {
            return Err(MathError::BadArgument {
                name,
                index: idx as u16,
                reason: "cannot convert a BigInt to a number",
            });
        } else if v.is_symbol() {
            return Err(MathError::BadArgument {
                name,
                index: idx as u16,
                reason: "cannot convert a Symbol to a number",
            });
        } else {
            // Non-primitive operands should have been routed through
            // `Interpreter::math_coerce_args` before reaching this
            // table. Soft NaN so Math.max / Math.min produce the
            // §21.3.2.{24,25} step 3 NaN result.
            NumberValue::Double(f64::NAN)
        };
        out.push(n);
    }
    Ok(out)
}

fn impl_abs(args: &[NumberValue]) -> NumberValue {
    let f = first_or_nan(args);
    NumberValue::Double(f.as_f64().abs()).canonicalize()
}

fn impl_floor(args: &[NumberValue]) -> NumberValue {
    NumberValue::Double(first_or_nan(args).as_f64().floor()).canonicalize()
}

fn impl_ceil(args: &[NumberValue]) -> NumberValue {
    NumberValue::Double(first_or_nan(args).as_f64().ceil()).canonicalize()
}

fn impl_round(args: &[NumberValue]) -> NumberValue {
    let f = first_or_nan(args).as_f64();
    // ES spec: half-to-positive-infinity (so .5 rounds up, -.5
    // rounds toward zero). Rust's `f64::round` rounds half-away-
    // from-zero, which differs for negative half-integers.
    let rounded = if f.is_nan() {
        f64::NAN
    } else if f.is_infinite() {
        f
    } else {
        (f + 0.5).floor()
    };
    NumberValue::Double(rounded).canonicalize()
}

fn impl_trunc(args: &[NumberValue]) -> NumberValue {
    NumberValue::Double(first_or_nan(args).as_f64().trunc()).canonicalize()
}

fn impl_sqrt(args: &[NumberValue]) -> NumberValue {
    NumberValue::Double(first_or_nan(args).as_f64().sqrt()).canonicalize()
}

fn impl_pow(args: &[NumberValue]) -> NumberValue {
    let base = args
        .first()
        .copied()
        .unwrap_or(NumberValue::Double(f64::NAN));
    let exp = args
        .get(1)
        .copied()
        .unwrap_or(NumberValue::Double(f64::NAN));
    bitwise::pow(base, exp)
}

fn impl_min(args: &[NumberValue]) -> NumberValue {
    if args.is_empty() {
        return NumberValue::Double(f64::INFINITY);
    }
    let mut current = args[0].as_f64();
    for v in &args[1..] {
        let f = v.as_f64();
        if f.is_nan() {
            return NumberValue::Double(f64::NAN);
        }
        // Per spec: -0 < +0.
        if f < current || (f == 0.0 && current == 0.0 && f.is_sign_negative()) {
            current = f;
        }
    }
    NumberValue::Double(current).canonicalize()
}

fn impl_max(args: &[NumberValue]) -> NumberValue {
    if args.is_empty() {
        return NumberValue::Double(f64::NEG_INFINITY);
    }
    let mut current = args[0].as_f64();
    for v in &args[1..] {
        let f = v.as_f64();
        if f.is_nan() {
            return NumberValue::Double(f64::NAN);
        }
        if f > current || (f == 0.0 && current == 0.0 && current.is_sign_negative()) {
            current = f;
        }
    }
    NumberValue::Double(current).canonicalize()
}

/// §21.3.2 — wrap a unary `f64 → f64` into a Math function impl.
fn unary(args: &[NumberValue], f: fn(f64) -> f64) -> NumberValue {
    NumberValue::Double(f(first_or_nan(args).as_f64())).canonicalize()
}

fn impl_log(args: &[NumberValue]) -> NumberValue {
    unary(args, f64::ln)
}
fn impl_log2(args: &[NumberValue]) -> NumberValue {
    unary(args, f64::log2)
}
fn impl_log10(args: &[NumberValue]) -> NumberValue {
    unary(args, f64::log10)
}
fn impl_log1p(args: &[NumberValue]) -> NumberValue {
    unary(args, f64::ln_1p)
}
fn impl_exp(args: &[NumberValue]) -> NumberValue {
    unary(args, f64::exp)
}
fn impl_expm1(args: &[NumberValue]) -> NumberValue {
    unary(args, f64::exp_m1)
}
fn impl_sin(args: &[NumberValue]) -> NumberValue {
    unary(args, f64::sin)
}
fn impl_cos(args: &[NumberValue]) -> NumberValue {
    unary(args, f64::cos)
}
fn impl_tan(args: &[NumberValue]) -> NumberValue {
    unary(args, f64::tan)
}
fn impl_asin(args: &[NumberValue]) -> NumberValue {
    unary(args, f64::asin)
}
fn impl_acos(args: &[NumberValue]) -> NumberValue {
    unary(args, f64::acos)
}
fn impl_atan(args: &[NumberValue]) -> NumberValue {
    unary(args, f64::atan)
}
fn impl_sinh(args: &[NumberValue]) -> NumberValue {
    unary(args, f64::sinh)
}
fn impl_cosh(args: &[NumberValue]) -> NumberValue {
    unary(args, f64::cosh)
}
fn impl_tanh(args: &[NumberValue]) -> NumberValue {
    unary(args, f64::tanh)
}
fn impl_asinh(args: &[NumberValue]) -> NumberValue {
    unary(args, f64::asinh)
}
fn impl_acosh(args: &[NumberValue]) -> NumberValue {
    unary(args, f64::acosh)
}
fn impl_atanh(args: &[NumberValue]) -> NumberValue {
    unary(args, f64::atanh)
}
fn impl_cbrt(args: &[NumberValue]) -> NumberValue {
    unary(args, f64::cbrt)
}
fn impl_fround(args: &[NumberValue]) -> NumberValue {
    NumberValue::Double(first_or_nan(args).as_f64() as f32 as f64).canonicalize()
}

/// §21.3.2.2 Math.atan2(y, x).
fn impl_atan2(args: &[NumberValue]) -> NumberValue {
    let y = args
        .first()
        .copied()
        .unwrap_or(NumberValue::Double(f64::NAN))
        .as_f64();
    let x = args
        .get(1)
        .copied()
        .unwrap_or(NumberValue::Double(f64::NAN))
        .as_f64();
    NumberValue::Double(y.atan2(x)).canonicalize()
}

/// §21.3.2.18 Math.hypot(...args).
fn impl_hypot(args: &[NumberValue]) -> NumberValue {
    if args.is_empty() {
        return NumberValue::Smi(0);
    }
    let mut sum_sq = 0.0f64;
    let mut any_nan = false;
    let mut any_inf = false;
    for v in args {
        let f = v.as_f64();
        if f.is_nan() {
            any_nan = true;
        } else if f.is_infinite() {
            any_inf = true;
        } else {
            sum_sq += f * f;
        }
    }
    let result = if any_inf {
        f64::INFINITY
    } else if any_nan {
        f64::NAN
    } else {
        sum_sq.sqrt()
    };
    NumberValue::Double(result).canonicalize()
}

/// §21.3.2.30 Math.sign(x).
fn impl_sign(args: &[NumberValue]) -> NumberValue {
    let f = first_or_nan(args).as_f64();
    if f.is_nan() {
        NumberValue::Double(f64::NAN)
    } else if f == 0.0 {
        // Preserve `±0` per spec — return the same zero shape.
        NumberValue::Double(f).canonicalize()
    } else if f > 0.0 {
        NumberValue::Smi(1)
    } else {
        NumberValue::Smi(-1)
    }
}

/// §21.3.2.5 Math.clz32(x) — count leading zeros after ToUint32.
fn impl_clz32(args: &[NumberValue]) -> NumberValue {
    let f = first_or_nan(args).as_f64();
    if !f.is_finite() {
        return NumberValue::Smi(32);
    }
    let n = (f as i64) as u32;
    NumberValue::Smi(n.leading_zeros() as i32)
}

/// §21.3.2.20 Math.imul(a, b) — 32-bit integer multiplication.
fn impl_imul(args: &[NumberValue]) -> NumberValue {
    let a = args
        .first()
        .copied()
        .unwrap_or(NumberValue::Double(f64::NAN))
        .as_f64();
    let b = args
        .get(1)
        .copied()
        .unwrap_or(NumberValue::Double(f64::NAN))
        .as_f64();
    let ai = if a.is_finite() { a as i64 as i32 } else { 0 };
    let bi = if b.is_finite() { b as i64 as i32 } else { 0 };
    NumberValue::Smi(ai.wrapping_mul(bi))
}

/// §21.3.2.27 Math.random() — non-cryptographic pseudo-random.
/// Uses a thread-local linear-congruential generator seeded from
/// the system clock so foundation runs are reproducible inside a
/// single VM but vary across processes.
fn impl_random(_args: &[NumberValue]) -> NumberValue {
    use std::cell::Cell;
    thread_local! {
        static SEED: Cell<u64> = Cell::new({
            let now = std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|d| d.as_nanos() as u64)
                .unwrap_or(0xDEADBEEFu64);
            now | 1
        });
    }
    SEED.with(|cell| {
        let mut s = cell.get();
        // SplitMix64 step.
        s = s.wrapping_add(0x9E3779B97F4A7C15);
        let mut z = s;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58476D1CE4E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D049BB133111EB);
        z ^= z >> 31;
        cell.set(s);
        // Map upper 53 bits into `[0, 1)`.
        let bits = (z >> 11) as f64 / (1u64 << 53) as f64;
        NumberValue::Double(bits)
    })
}

fn first_or_nan(args: &[NumberValue]) -> NumberValue {
    args.first()
        .copied()
        .unwrap_or(NumberValue::Double(f64::NAN))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn n(v: i32) -> Value {
        Value::number(NumberValue::Smi(v))
    }

    #[test]
    fn constants_resolve() {
        let pi = load_constant("PI").unwrap();
        assert!((pi.as_number().unwrap().as_f64() - PI).abs() < 1e-12);
        assert!(load_constant("nope").is_none());
    }

    #[test]
    fn min_and_max_handle_nan() {
        use otter_bytecode::method_id::MathMethod;
        let heap = otter_gc::GcHeap::new().expect("heap");
        let r = call(MathMethod::Min, &[n(1), n(2), n(3)], &heap).unwrap();
        assert_eq!(r.as_number().unwrap().as_smi(), Some(1));
        let r = call(MathMethod::Max, &[n(1), n(2), n(3)], &heap).unwrap();
        assert_eq!(r.as_number().unwrap().as_smi(), Some(3));
        let nan_r = call(
            MathMethod::Max,
            &[n(1), Value::number(NumberValue::Double(f64::NAN))],
            &heap,
        )
        .unwrap();
        assert!(nan_r.as_number().unwrap().is_nan());
    }

    #[test]
    fn pow_routes_to_bitwise_pow() {
        use otter_bytecode::method_id::MathMethod;
        let heap = otter_gc::GcHeap::new().expect("heap");
        let r = call(MathMethod::Pow, &[n(2), n(10)], &heap).unwrap();
        assert_eq!(r.as_number().unwrap().as_smi(), Some(1024));
    }
}
