/**
 * The `node:path` module provides utilities for working with file and directory paths.
 * @module node:path
 */
declare module "node:path" {
    /**
     * A parsed path object generated by path.parse() or consumed by path.format().
     */
    export interface ParsedPath {
        /** The root of the path such as '/' or 'c:\' */
        root: string;
        /** The full directory path such as '/home/user/dir' or 'c:\path\dir' */
        dir: string;
        /** The file name including extension (if any) such as 'index.html' */
        base: string;
        /** The file extension (if any) such as '.html' */
        ext: string;
        /** The file name without extension (if any) such as 'index' */
        name: string;
    }

    /**
     * Join all arguments together and normalize the resulting path.
     * @param paths Path segments to join
     * @returns The joined path
     * @example
     * path.join('/foo', 'bar', 'baz/asdf', 'quux', '..');
     * // Returns: '/foo/bar/baz/asdf'
     */
    export function join(...paths: string[]): string;

    /**
     * Resolve a sequence of paths or path segments into an absolute path.
     * @param paths Path segments to resolve
     * @returns The resolved absolute path
     * @example
     * path.resolve('/foo/bar', './baz');
     * // Returns: '/foo/bar/baz'
     */
    export function resolve(...paths: string[]): string;

    /**
     * Return the directory name of a path.
     * @param p The path to evaluate
     * @returns The directory name
     * @example
     * path.dirname('/foo/bar/baz.txt');
     * // Returns: '/foo/bar'
     */
    export function dirname(p: string): string;

    /**
     * Return the last portion of a path, similar to the Unix basename command.
     * @param p The path to evaluate
     * @param suffix An optional suffix to remove from the result
     * @returns The base name
     * @example
     * path.basename('/foo/bar/baz.txt');
     * // Returns: 'baz.txt'
     * path.basename('/foo/bar/baz.txt', '.txt');
     * // Returns: 'baz'
     */
    export function basename(p: string, suffix?: string): string;

    /**
     * Return the extension of the path, from the last '.' to end of string.
     * @param p The path to evaluate
     * @returns The extension including the dot
     * @example
     * path.extname('index.html');
     * // Returns: '.html'
     */
    export function extname(p: string): string;

    /**
     * Determine whether a path is an absolute path.
     * @param p The path to check
     * @returns True if the path is absolute
     * @example
     * path.isAbsolute('/foo/bar'); // true
     * path.isAbsolute('baz/..');   // false
     */
    export function isAbsolute(p: string): boolean;

    /**
     * Normalize a path, resolving '..' and '.' segments.
     * @param p The path to normalize
     * @returns The normalized path
     * @example
     * path.normalize('/foo/bar//baz/asdf/quux/..');
     * // Returns: '/foo/bar/baz/asdf'
     */
    export function normalize(p: string): string;

    /**
     * Solve the relative path from {from} to {to}.
     * @param from Start path
     * @param to Target path
     * @returns The relative path
     * @example
     * path.relative('/data/orandea/test/aaa', '/data/orandea/impl/bbb');
     * // Returns: '../../impl/bbb'
     */
    export function relative(from: string, to: string): string;

    /**
     * Return an object whose properties represent significant elements of the path.
     * @param p The path to parse
     * @returns An object containing the path components
     * @example
     * path.parse('/home/user/file.txt');
     * // Returns: { root: '/', dir: '/home/user', base: 'file.txt', ext: '.txt', name: 'file' }
     */
    export function parse(p: string): ParsedPath;

    /**
     * Return a path string from an object - the opposite of path.parse().
     * @param pathObject The path object to format
     * @returns The formatted path string
     */
    export function format(pathObject: ParsedPath): string;

    /**
     * The platform-specific path segment separator.
     * - POSIX: '/'
     * - Windows: '\\'
     */
    export const sep: string;

    /**
     * The platform-specific path delimiter.
     * - POSIX: ':'
     * - Windows: ';'
     */
    export const delimiter: string;
}

// Also support the 'path' module (without node: prefix)
declare module "path" {
    export * from "node:path";
}
