//! Native-stack JavaScript frame creation and execution continuations.
//!
//! # Contents
//! - [`CallRequest`] describes one selected callable and its incoming values.
//! - [`call_trampoline`] owns the frame, registers and actual-argument window.
//! - Architecture bodies resume an entry after a child returns without keeping
//!   a Rust dispatcher on the stack.
//! - Tier-entry requests at entry resume the existing published activation.
//!
//! # Invariants
//! The request and its argument source remain valid until the trampoline has
//! copied them; no allocation or reentry occurs during that copy. Every slot
//! is initialized before publishing the frame. Entries consume the completion
//! before allocating and return only statuses in the execution domain. Stack
//! checks precede reservation; both the frame and stack pointer are aligned.
//! No Rust unwind may cross an entry. The caller's frame is restored before
//! the trampoline returns, including on abrupt completion.
//!
//! # See also
//! - [`super::JitCtx`] for the shared context and continuation mailbox.
//! - [`super::Frame`] for the single frame layout.
//! - [`super::NativeResultDomain::Execution`] for entry result validation.

mod deopt;
pub use crate::interp::host_call::{
    derived_construct_result, prepare_activation, promote_entered_function,
};
pub use deopt::deopt_call_entry;

use super::{JitCtx, JitEntry, NativeResultPair, VmFrameHeader};
use crate::{Value, VmError};

/// Mailbox destination identifying completion of a tier transfer on this frame.
pub(crate) const TIER_COMPLETION_DESTINATION: u32 = u32::MAX - 1;

/// Byte offset of a request's frame-flag byte.
const REQUEST_FLAGS_OFFSET: usize =
    std::mem::offset_of!(CallRequest, header) + std::mem::offset_of!(VmFrameHeader, flags);
/// Byte offset of a request's frame-kind byte.
const REQUEST_KIND_OFFSET: usize =
    std::mem::offset_of!(CallRequest, header) + std::mem::offset_of!(VmFrameHeader, kind);
/// Request bits a classified call carries into its published frame header.
const REQUEST_FRAME_FLAGS: u8 = super::NativeFrameFlags::CONSTRUCT
    | super::NativeFrameFlags::DERIVED_CONSTRUCTOR
    | super::NativeFrameFlags::TAIL_CALL;
/// GC cell header bytes preceding every body payload.
const BODY: usize = otter_gc::header::HEADER_SIZE;

/// Machine-readable request consumed before entering the selected callee.
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct CallRequest {
    /// Selected interpreter or generated entry; zero is an invalid request.
    pub entry: u64,
    /// Complete callee header, with the full canonical register count.
    pub header: VmFrameHeader,
    /// Installed generation, or zero for interpreter execution.
    pub code_object_id: u32,
    /// Address of `argument_count` initialized tagged actual arguments.
    pub arguments: *const Value,
    /// Full actual count, including arguments beyond the formal prefix.
    pub argument_count: u32,
    /// Formal prefix to initialize from actuals; at most the register count.
    pub parameter_count: u32,
    /// Exact callable, including its captured lexical context.
    pub callee: Value,
    /// Prepared receiver, or the derived-constructor uninitialized value.
    pub receiver: Value,
    /// Actual new.target, or undefined for a normal call.
    pub new_target: Value,
    /// Optional initialized register prefix restored at entry, after formals.
    pub initial_registers: *const Value,
    /// Number of values in the optional prefix, at most the register capacity.
    pub initial_register_count: u32,
    /// Caller destination; u32::MAX returns through the native result ABI.
    pub return_destination: u32,
    /// Existing cold state transferred to this native activation.
    pub cold: Option<crate::cold_frame::ColdFrameIdx>,
    /// Observable arguments identity restored from a suspended invocation.
    pub arguments_object: crate::JsObject,
}

impl CallRequest {
    /// Empty mailbox. Execution must install a selected entry before calling.
    pub const EMPTY: Self = Self {
        entry: 0,
        header: VmFrameHeader::interpreter(0, 0),
        code_object_id: 0,
        arguments: std::ptr::null(),
        argument_count: 0,
        parameter_count: 0,
        callee: Value::UNDEFINED,
        receiver: Value::UNDEFINED,
        new_target: Value::UNDEFINED,
        initial_registers: std::ptr::null(),
        initial_register_count: 0,
        return_destination: u32::MAX,
        cold: None,
        arguments_object: crate::JsObject::null(),
    };

    /// Select an entry while retaining the request's complete call state.
    pub fn set_entry(&mut self, entry: JitEntry) {
        self.entry = entry as usize as u64;
    }

    /// Continue the published physical frame in the interpreter after deopt.
    /// Preparation has already restored its windows, PC and catch state.
    pub fn resume_interpreter() -> Self {
        let mut request = Self::EMPTY;
        request.set_entry(crate::interp::call_dispatch::interpreter_resume_entry);
        request.header.flags =
            super::NativeFrameFlags::from_bits(super::NativeFrameFlags::TIER_ENTRY);
        request
    }
}

/// Enter a callable through the JavaScript call ABI and classify it.
///
/// This is the entry of every interpreter destination and of every generated
/// call whose target is not a proven bytecode generation. A closure or
/// function id whose current generation is compiled, whose span already
/// covers its formals and whose call kind it accepts is entered directly:
/// the caller's frame and span become the callee's. Any other callee is
/// recorded in the context's request and continues in [`call_trampoline`],
/// which classifies it, pads its span, and builds every interpreter and host
/// frame.
///
/// # Safety
/// The caller follows the JavaScript call ABI: `x0` context, `x1` callee,
/// `x2` receiver, `x3` `new.target` (`undefined` for `[[Call]]`), `x4` the
/// actual count and the actual span at `sp`, readable until the trampoline
/// copies it.
#[cfg(target_arch = "aarch64")]
#[unsafe(naked)]
pub unsafe extern "C" fn call_generic_entry(_ctx: *mut JitCtx) -> NativeResultPair {
    core::arch::naked_asm!(
        // A function-id immediate names its function directly.
        "and x9, x1, #0xffff",
        "cmp x9, #{fid_tag}",
        "b.ne 1f",
        "tst x1, #{number_tag}",
        "b.ne 1f",
        "ubfx x12, x1, #16, #32",
        "b 2f",
        "1:",
        "cbz x1, 9f",
        "tst x1, #{number_tag}",
        "b.ne 9f",
        "tst x1, #{other_tag}",
        "b.ne 9f",
        "ldrb w9, [x1]",
        "cmp w9, #{closure_tag}",
        "b.ne 9f",
        "ldr w12, [x1, #{closure_fid}]",
        "2:",
        "ldr x9, [x0, #{thread}]",
        "ldr x9, [x9, #{thread_registry}]",
        "cbz x9, 9f",
        "ldr x10, [x9, #{registry_count}]",
        "cmp x12, x10",
        "b.hs 9f",
        "ldr x9, [x9, #{registry_entries}]",
        "ldr x13, [x9, x12, lsl #3]",
        "cbz x13, 9f",
        "ldr w9, [x13, #{cell_call_flags}]",
        "tbnz w9, #{suspendable_bit}, 9f",
        "cmp x3, #{undefined}",
        "b.eq 3f",
        "tbz w9, #{constructible_bit}, 9f",
        "3:",
        "ldrh w10, [x13, #{cell_param_count}]",
        "cmp x4, x10",
        "b.lo 9f",
        "ldr x8, [x13]",
        "ldr x10, [x8, #{generation_code_object}]",
        "cbz x10, 9f",
        "ldr x16, [x8]",
        "br x16",
        // Classification in the trampoline.
        "9:",
        "add x9, x0, #{request}",
        "str xzr, [x9]",
        "mov x10, #{undefined}",
        "cmp x3, x10",
        "cset w10, ne",
        "lsl w10, w10, #{construct_bit}",
        "strb w10, [x9, #{req_flags}]",
        "stp x1, x2, [x9, #{req_callee}]",
        "str x3, [x9, #{req_new_target}]",
        "mov x10, sp",
        "str x10, [x9, #{req_arguments}]",
        "str w4, [x9, #{req_argument_count}]",
        "str xzr, [x9, #{req_initial}]",
        "mov x10, #-4294967296",
        "str x10, [x9, #{req_initial_count}]",
        "str xzr, [x9, #{req_cold}]",
        "b {trampoline}",
        request = const std::mem::offset_of!(JitCtx, pending_call),
        thread = const std::mem::offset_of!(JitCtx, thread),
        thread_registry = const std::mem::offset_of!(super::VmThread, code_registry),
        registry_entries = const std::mem::offset_of!(super::CodeRegistryView, function_entries),
        registry_count = const std::mem::offset_of!(super::CodeRegistryView, function_entry_count),
        cell_call_flags = const super::FUNCTION_ENTRY_CALL_FLAGS_OFFSET,
        cell_param_count = const super::FUNCTION_ENTRY_PARAM_COUNT_OFFSET,
        generation_code_object = const std::mem::offset_of!(super::CodeEntryCell, code_object_id),
        suspendable_bit = const super::FUNCTION_CALL_SUSPENDABLE.trailing_zeros(),
        constructible_bit = const super::FUNCTION_CALL_CONSTRUCTIBLE.trailing_zeros(),
        fid_tag = const crate::value::tag::FUNCTION_ID_TAG,
        number_tag = const crate::value::tag::NUMBER_TAG,
        other_tag = const crate::value::tag::OTHER_TAG,
        closure_tag = const crate::closure::JS_CLOSURE_BODY_TYPE_TAG,
        closure_fid = const BODY + crate::closure::CLOSURE_BODY_FUNCTION_ID_OFFSET,
        undefined = const Value::UNDEFINED.to_abi_bits(),
        construct_bit = const super::NativeFrameFlags::CONSTRUCT.trailing_zeros(),
        req_flags = const REQUEST_FLAGS_OFFSET,
        req_callee = const std::mem::offset_of!(CallRequest, callee),
        req_new_target = const std::mem::offset_of!(CallRequest, new_target),
        req_arguments = const std::mem::offset_of!(CallRequest, arguments),
        req_argument_count = const std::mem::offset_of!(CallRequest, argument_count),
        req_initial = const std::mem::offset_of!(CallRequest, initial_registers),
        req_initial_count = const std::mem::offset_of!(CallRequest, initial_register_count),
        req_cold = const std::mem::offset_of!(CallRequest, cold),
        trampoline = sym call_trampoline,
    );
}

/// Enter a callable through the JavaScript call ABI, directly into a
/// compiled current generation or through classification; see the AArch64
/// entry.
///
/// # Safety
/// The caller follows the x86-64 JavaScript call ABI: `rdi` context, `rsi`
/// callee, `rdx` receiver, `rcx` `new.target` (`undefined` for `[[Call]]`),
/// `r8` the actual count and the actual span above the return address,
/// readable until the trampoline copies it. The completion returns in
/// `rax`/`rdx` on every platform.
#[cfg(target_arch = "x86_64")]
#[unsafe(naked)]
pub unsafe extern "C" fn call_generic_entry(_ctx: *mut JitCtx) -> NativeResultPair {
    core::arch::naked_asm!(
        // A function-id immediate names its function directly.
        "mov eax, esi",
        "and eax, 0xffff",
        "cmp eax, {fid_tag}",
        "jne 1f",
        "mov rax, {number_tag}",
        "test rsi, rax",
        "jnz 1f",
        "mov r10, rsi",
        "shr r10, 16",
        "mov r10d, r10d",
        "jmp 2f",
        "1:",
        "test rsi, rsi",
        "jz 9f",
        "mov rax, {number_tag}",
        "test rsi, rax",
        "jnz 9f",
        "test rsi, {other_tag}",
        "jnz 9f",
        "cmp byte ptr [rsi], {closure_tag}",
        "jne 9f",
        "mov r10d, [rsi + {closure_fid}]",
        "2:",
        "mov rax, [rdi + {thread}]",
        "mov rax, [rax + {thread_registry}]",
        "test rax, rax",
        "jz 9f",
        "cmp r10, [rax + {registry_count}]",
        "jae 9f",
        "mov rax, [rax + {registry_entries}]",
        "mov r11, [rax + r10 * 8]",
        "test r11, r11",
        "jz 9f",
        "mov eax, [r11 + {cell_call_flags}]",
        "test eax, {suspendable_flag}",
        "jnz 9f",
        "cmp rcx, {undefined}",
        "je 3f",
        "test eax, {constructible_flag}",
        "jz 9f",
        "3:",
        "movzx eax, word ptr [r11 + {cell_param_count}]",
        "cmp r8, rax",
        "jb 9f",
        "mov r9, [r11]",
        "cmp qword ptr [r9 + {generation_code_object}], 0",
        "je 9f",
        "jmp qword ptr [r9]",
        // Classification in the trampoline.
        "9:",
        "lea r10, [rdi + {request}]",
        "mov qword ptr [r10], 0",
        "mov rax, {undefined}",
        "xor r11d, r11d",
        "cmp rcx, rax",
        "setne r11b",
        "shl r11d, {construct_bit}",
        "mov byte ptr [r10 + {req_flags}], r11b",
        "mov [r10 + {req_callee}], rsi",
        "mov [r10 + {req_receiver}], rdx",
        "mov [r10 + {req_new_target}], rcx",
        "lea rax, [rsp + 8]",
        "mov [r10 + {req_arguments}], rax",
        "mov [r10 + {req_argument_count}], r8d",
        "mov qword ptr [r10 + {req_initial}], 0",
        "mov rax, -4294967296",
        "mov [r10 + {req_initial_count}], rax",
        "mov qword ptr [r10 + {req_cold}], 0",
        ".if {windows}",
        "push rbp",
        "mov rbp, rsp",
        "sub rsp, 48",
        "mov rdx, rdi",
        "lea rcx, [rsp + 32]",
        "call {trampoline}",
        "mov rax, [rsp + 32]",
        "mov rdx, [rsp + 40]",
        "leave",
        "ret",
        ".else",
        "jmp {trampoline}",
        ".endif",
        windows = const cfg!(target_os = "windows") as u8,
        request = const std::mem::offset_of!(JitCtx, pending_call),
        thread = const std::mem::offset_of!(JitCtx, thread),
        thread_registry = const std::mem::offset_of!(super::VmThread, code_registry),
        registry_entries = const std::mem::offset_of!(super::CodeRegistryView, function_entries),
        registry_count = const std::mem::offset_of!(super::CodeRegistryView, function_entry_count),
        cell_call_flags = const super::FUNCTION_ENTRY_CALL_FLAGS_OFFSET,
        cell_param_count = const super::FUNCTION_ENTRY_PARAM_COUNT_OFFSET,
        generation_code_object = const std::mem::offset_of!(super::CodeEntryCell, code_object_id),
        suspendable_flag = const super::FUNCTION_CALL_SUSPENDABLE,
        constructible_flag = const super::FUNCTION_CALL_CONSTRUCTIBLE,
        fid_tag = const crate::value::tag::FUNCTION_ID_TAG,
        number_tag = const crate::value::tag::NUMBER_TAG,
        other_tag = const crate::value::tag::OTHER_TAG,
        closure_tag = const crate::closure::JS_CLOSURE_BODY_TYPE_TAG,
        closure_fid = const BODY + crate::closure::CLOSURE_BODY_FUNCTION_ID_OFFSET,
        undefined = const Value::UNDEFINED.to_abi_bits(),
        construct_bit = const super::NativeFrameFlags::CONSTRUCT.trailing_zeros(),
        req_flags = const REQUEST_FLAGS_OFFSET,
        req_callee = const std::mem::offset_of!(CallRequest, callee),
        req_receiver = const std::mem::offset_of!(CallRequest, receiver),
        req_new_target = const std::mem::offset_of!(CallRequest, new_target),
        req_arguments = const std::mem::offset_of!(CallRequest, arguments),
        req_argument_count = const std::mem::offset_of!(CallRequest, argument_count),
        req_initial = const std::mem::offset_of!(CallRequest, initial_registers),
        req_initial_count = const std::mem::offset_of!(CallRequest, initial_register_count),
        req_cold = const std::mem::offset_of!(CallRequest, cold),
        trampoline = sym call_trampoline,
    );
}

/// The AArch64 trampoline body; only host-entry address materialization
/// differs between object formats.
#[cfg(target_arch = "aarch64")]
macro_rules! arm64_call_trampoline {
    ($host_page:literal, $host_offset:literal, $interp_page:literal, $interp_offset:literal) => {
        core::arch::naked_asm!(
            "stp x29, x30, [sp, #-{frame_bytes}]!",
            "mov x29, sp",
            "stp x19, x20, [sp, #16]",
            "stp x21, x22, [sp, #32]",
            "stp x23, x24, [sp, #48]",
            "stp x25, x26, [sp, #64]",
            "stp x27, x28, [sp, #80]",
            "mov x19, x0",
            "mov x25, #0",
            "ldrb w9, [x19, #{request_flags}]",
            "tbz w9, #7, 10f",
            // A tier request resumes the published frame with its entry.
            "ldr x25, [x19, #{frame_cell}]",
            "cbz x25, 90f",
            "mov x20, x25",
            "ldr x21, [x25, #{caller}]",
            "ldr x22, [x19, #{request}]",
            "cbz x22, 90f",
            "mov x24, #0",
            "mov w23, #-1",
            "mov x0, #{undefined}",
            "mov x1, #0",
            "b 40f",
            // ---- Classification. Nothing below allocates before the copy.
            "10:",
            "add x9, x19, #{request}",
            "mov x26, #0",
            "mov x27, #0",
            "ldr x28, [x9, #{req_callee}]",
            "ldr x22, [x9]",
            "cbnz x22, 12f",
            "ldrb w15, [x9, #{req_flags}]",
            "mov x10, x28",
            "mov x11, #0",
            "ldr x16, [x19, #{depth_limit}]",
            "60:",
            "and x12, x10, #0xffff",
            "cmp x12, #{fid_tag}",
            "b.ne 61f",
            "tst x10, #{number_tag}",
            "b.ne 61f",
            "ubfx x12, x10, #16, #32",
            "mov w14, #0",
            "b 70f",
            "61:",
            "cbz x10, 80f",
            "tst x10, #{number_tag}",
            "b.ne 80f",
            "tst x10, #{other_tag}",
            "b.ne 80f",
            "ldrb w12, [x10]",
            "cmp w12, #{closure_tag}",
            "b.eq 62f",
            "cmp w12, #{bound_tag}",
            "b.eq 63f",
            "cmp w12, #{class_tag}",
            "b.eq 64f",
            "cmp w12, #{native_tag}",
            "b.eq 81f",
            "cmp w12, #{proxy_tag}",
            "b.eq 82f",
            "b 80f",
            "62:",
            "ldr w12, [x10, #{closure_fid}]",
            "ldr w14, [x10, #{closure_flags}]",
            "b 70f",
            // Bound wrapper: count its prefix, apply its receiver rule, unwrap.
            "63:",
            "add x11, x11, #1",
            "cmp x11, x16",
            "b.hi 91f",
            "ldr w12, [x10, #{bound_args}]",
            "cbz w12, 65f",
            "and x13, x10, #0xffffffff00000000",
            "orr x13, x13, x12",
            "ldr w12, [x13, #{slab_len}]",
            "add x27, x27, x12",
            "65:",
            "tbnz w15, #{construct_bit}, 66f",
            "ldr x12, [x10, #{bound_this}]",
            "str x12, [x9, #{req_receiver}]",
            "b 67f",
            "66:",
            "ldr x12, [x9, #{req_new_target}]",
            "cmp x12, x10",
            "b.ne 67f",
            "ldr x12, [x10, #{bound_target}]",
            "str x12, [x9, #{req_new_target}]",
            "67:",
            "ldr x10, [x10, #{bound_target}]",
            "b 60b",
            // Class wrapper: construct enters its constructor; call throws.
            "64:",
            "tbz w15, #{construct_bit}, 83f",
            "ldr x10, [x10, #{class_ctor}]",
            "b 60b",
            // Bytecode function: w12 id, x10 SELF, w14 closure call flags.
            "70:",
            "ldr x13, [x19, #{thread}]",
            "ldr x17, [x13, #{thread_registry}]",
            "cbz x17, 90f",
            "ldr x16, [x17, #{registry_count}]",
            "cmp x12, x16",
            "b.hs 90f",
            "ldr x16, [x17, #{registry_entries}]",
            "ldr x13, [x16, x12, lsl #3]",
            "cbz x13, 90f",
            "ldr w16, [x13, #{cell_call_flags}]",
            "tbz w15, #{construct_bit}, 140f",
            "tbz w16, #{constructible_bit}, 84f",
            // A compiled current generation builds its own frame: enter it
            // through the JavaScript call ABI with the padded actual span.
            "140:",
            "tbnz w16, #{suspendable_bit}, 71f",
            "ldar x17, [x13]",
            "ldr x0, [x17, #{generation_code_object}]",
            "cbz x0, 71f",
            "ldr x22, [x17]",
            "cbz x22, 90f",
            "mov x24, x17",
            "mov x26, x10",
            "ldr w14, [x9, #{req_argument_count}]",
            "ldr x23, [x9, #{req_arguments}]",
            "cbz w14, 141f",
            "cbz x23, 90f",
            "141:",
            "add x21, x14, x27",
            "ldrh w7, [x13, #{cell_param_count}]",
            "cmp x21, x7",
            "csel x7, x21, x7, hi",
            "lsl x2, x7, #3",
            "add x2, x2, #15",
            "and x2, x2, #-16",
            "mov x3, sp",
            "subs x20, x3, x2",
            "b.lo 91f",
            "ldr x4, [x19, #{stack_limit}]",
            "cmp x20, x4",
            "b.lo 91f",
            "142:",
            "sub x4, x3, #4096",
            "cmp x4, x20",
            "b.ls 143f",
            "str xzr, [x4]",
            "mov x3, x4",
            "b 142b",
            "143:",
            "mov sp, x20",
            // The caller's span follows every bound prefix.
            "add x13, x20, x27, lsl #3",
            "mov x12, #0",
            "144:",
            "cmp x12, x14",
            "b.hs 145f",
            "ldr x11, [x23, x12, lsl #3]",
            "str x11, [x13, x12, lsl #3]",
            "add x12, x12, #1",
            "b 144b",
            "145:",
            "mov x13, x20",
            "mov x1, x27",
            "mov x2, x28",
            "bl 160f",
            // Formals beyond the actuals read `undefined`.
            "mov x11, #{undefined}",
            "mov x12, x21",
            "146:",
            "cmp x12, x7",
            "b.hs 147f",
            "str x11, [x20, x12, lsl #3]",
            "add x12, x12, #1",
            "b 146b",
            "147:",
            "mov x0, x19",
            "mov x1, x26",
            "ldr x2, [x19, #{request_receiver}]",
            "ldr x3, [x19, #{request_new_target}]",
            "mov x4, x21",
            "mov x8, x24",
            "blr x22",
            "b 99f",
            // Interpreter destination: bind the receiver for this frame.
            "71:",
            "tbnz w15, #{construct_bit}, 75f",
            "tbz w14, #{closure_bound_this_bit}, 72f",
            "ldr x17, [x10, #{closure_bound_this}]",
            "str x17, [x9, #{req_receiver}]",
            "tbz w14, #{closure_bound_new_target_bit}, 78f",
            "ldr x17, [x10, #{closure_bound_new_target}]",
            "str x17, [x9, #{req_new_target}]",
            "b 78f",
            "72:",
            "tbnz w16, #{no_conversion_bit}, 78f",
            "ldr x17, [x9, #{req_receiver}]",
            "cmp x17, #{undefined}",
            "b.eq 73f",
            "cmp x17, #{null}",
            "b.eq 73f",
            "and x0, x17, #0xffff",
            "cmp x0, #{fid_tag}",
            "b.ne 74f",
            "tst x17, #{number_tag}",
            "b.eq 78f",
            "74:",
            "tst x17, #{number_tag}",
            "b.ne 76f",
            "tst x17, #{other_tag}",
            "b.ne 76f",
            "ldrb w0, [x17]",
            "cmp w0, #{string_tag}",
            "b.eq 76f",
            "cmp w0, #{symbol_tag}",
            "b.eq 76f",
            "cmp w0, #{bigint_tag}",
            "b.eq 76f",
            "b 78f",
            "76:",
            "mov x26, #1",
            "b 78f",
            "73:",
            "ldr w0, [x13, #{cell_realm}]",
            "ldr x1, [x19, #{thread}]",
            "ldr x1, [x1, #{thread_active_realm}]",
            "ldr w1, [x1]",
            "cmp w0, w1",
            "b.ne 76b",
            "ldr x1, [x19, #{global_this}]",
            "ldr w1, [x1]",
            "ldr x0, [x19, #{thread}]",
            "ldr x0, [x0, #{thread_cage}]",
            "orr x1, x0, x1",
            "str x1, [x9, #{req_receiver}]",
            "b 78f",
            "75:",
            "tbz w16, #{derived_bit}, 77f",
            "mov x17, #{hole}",
            "str x17, [x9, #{req_receiver}]",
            "orr w15, w15, #{derived_flag}",
            "b 78f",
            // A base constructor creates its receiver on the published frame
            // unless the caller allocated it.
            "77:",
            "ldr x17, [x9, #{req_receiver}]",
            "cmp x17, #{undefined}",
            "b.ne 78f",
            "mov x26, #1",
            // The permanent interpreter destination of the function.
            "78:",
            "add x17, x13, #{cell_interpreter}",
            $interp_page,
            $interp_offset,
            "ldp x0, x1, [x17, #{generation_header}]",
            "mov w2, #{request_frame_flags}",
            "and w2, w2, w15",
            "orr x1, x1, x2, lsl #24",
            "stp x0, x1, [x9, #{req_header}]",
            "ldrh w0, [x13, #{cell_param_count}]",
            "str w0, [x9, #{req_parameter_count}]",
            "str x10, [x9, #{req_callee}]",
            "str x22, [x9]",
            "b 12f",
            // Host frame: w12 selects the host body; SELF is the callee.
            "80:",
            "mov w12, #{host_other}",
            "b 85f",
            "81:",
            "mov w12, #{host_native}",
            "b 85f",
            "82:",
            "mov w12, #{host_proxy}",
            "b 85f",
            "83:",
            "mov w12, #{host_class_call}",
            "b 85f",
            "84:",
            "mov w12, #{host_not_constructor}",
            "85:",
            $host_page,
            $host_offset,
            "mov w0, w12",
            "mov w2, #{request_frame_flags}",
            "and w2, w2, w15",
            "mov x1, #{host_registers}",
            "movk x1, #{host_kind}, lsl #16",
            "orr x1, x1, x2, lsl #24",
            "stp x0, x1, [x9, #{req_header}]",
            "str wzr, [x9, #{req_parameter_count}]",
            "str x10, [x9, #{req_callee}]",
            "str x22, [x9]",
            // ---- Reservation of an interpreter or host frame.
            "12:",
            "ldr x21, [x19, #{frame_cell}]",
            "mov w16, #1",
            "cbz x21, 20f",
            "ldr w16, [x21, #{depth}]",
            "adds w16, w16, #1",
            "b.cs 91f",
            "20:",
            "ldr x10, [x19, #{depth_limit}]",
            "cmp x16, x10",
            "b.hi 91f",
            // A host frame keeps its caller's logical JavaScript depth.
            "ldrb w10, [x9, #{req_kind}]",
            "cmp w10, #{host_kind}",
            "b.ne 26f",
            "sub w16, w16, #1",
            "26:",
            "ldrh w14, [x9, #{req_register_count}]",
            "ldr w24, [x9, #{req_argument_count}]",
            "ldr w15, [x9, #{req_parameter_count}]",
            "cmp w15, w14",
            "b.hi 90f",
            "ldr x23, [x9, #{req_arguments}]",
            "cbz w24, 21f",
            "cbz x23, 90f",
            "21:",
            "ldr w12, [x9, #{req_initial_count}]",
            "cmp w12, w14",
            "b.hi 90f",
            "cbz w12, 24f",
            "ldr x10, [x9, #{req_initial}]",
            "cbz x10, 90f",
            "24:",
            "add x24, x24, x27",
            "add x10, x14, x24",
            "lsl x10, x10, #3",
            "add x10, x10, #{frame_size}",
            "add x10, x10, #15",
            "and x10, x10, #-16",
            "mov x11, sp",
            "subs x20, x11, x10",
            "b.lo 91f",
            "ldr x12, [x19, #{stack_limit}]",
            "cmp x20, x12",
            "b.lo 91f",
            // Probe each intervening page before moving SP past a guard page.
            "22:",
            "sub x12, x11, #4096",
            "cmp x12, x20",
            "b.ls 23f",
            "str xzr, [x12]",
            "mov x11, x12",
            "b 22b",
            "23:",
            "mov sp, x20",
            "ldp x10, x11, [x9, #{req_header}]",
            "bic x11, x11, #{tail_header_mask}",
            "stp x10, x11, [x20]",
            // Registers, then the actual window, follow the record.
            "add x10, x20, #{frame_size}",
            "stp x10, x14, [x20, #{registers}]",
            "ldp x11, x12, [x9, #{req_receiver}]",
            "stp x11, x12, [x20, #{this}]",
            "ldr x11, [x9, #{req_callee}]",
            "ldr w12, [x9, #{req_arguments_object}]",
            "orr x12, x24, x12, lsl #32",
            "stp x11, x12, [x20, #{self_value}]",
            "add x13, x10, x14, lsl #3",
            "stp x13, x21, [x20, #{actuals}]",
            "mov x11, #-4294967296",
            "orr x11, x11, x16",
            "stp x11, xzr, [x20, #{depth}]",
            "ldur x11, [x9, #{req_return_destination}]",
            "str x11, [x20, #{continuation}]",
            "mov x11, #{undefined}",
            "mov x12, #0",
            "30:",
            "cmp x12, x14",
            "b.hs 31f",
            "str x11, [x10, x12, lsl #3]",
            "add x12, x12, #1",
            "b 30b",
            // The caller's span follows every bound prefix in the actual window.
            "31:",
            "sub x0, x24, x27",
            "add x1, x13, x27, lsl #3",
            "mov x12, #0",
            "32:",
            "cmp x12, x0",
            "b.hs 33f",
            "ldr x11, [x23, x12, lsl #3]",
            "str x11, [x1, x12, lsl #3]",
            "add x12, x12, #1",
            "b 32b",
            "33:",
            "mov x1, x27",
            "mov x2, x28",
            "bl 160f",
            // Seed formals from the complete actual window.
            "mov x12, #0",
            "125:",
            "cmp x12, x15",
            "b.hs 34f",
            "cmp x12, x24",
            "b.hs 34f",
            "ldr x11, [x13, x12, lsl #3]",
            "str x11, [x10, x12, lsl #3]",
            "add x12, x12, #1",
            "b 125b",
            "34:",
            "ldr x11, [x9, #{req_initial}]",
            "ldr w12, [x9, #{req_initial_count}]",
            "mov x13, #0",
            "35:",
            "cmp x13, x12",
            "b.hs 36f",
            "ldr x14, [x11, x13, lsl #3]",
            "str x14, [x10, x13, lsl #3]",
            "add x13, x13, #1",
            "b 35b",
            "36:",
            "str x20, [x19, #{frame_cell}]",
            // Receiver conversion or creation runs on the published frame.
            "tbz x26, #0, 37f",
            "mov x0, x19",
            "bl {prepare}",
            "cbnz x1, 50f",
            "37:",
            "mov x24, #0",
            "mov w23, #-1",
            "mov x0, #{undefined}",
            "mov x1, #0",
            "40:",
            "stp x0, x1, [x19, #{completion}]",
            "str w23, [x19, #{completion_destination}]",
            "mov x0, x19",
            "blr x22",
            "cbz x24, 41f",
            "mov x22, x24",
            "mov x24, #0",
            "str w26, [x19, #{completion_generation}]",
            "b 40b",
            "41:",
            "cmp x1, #{continue_status}",
            "b.eq 45f",
            "cbz x1, 48f",
            "cmp x1, #{throw_status}",
            "b.eq 50f",
            "cmp x1, #{fatal_status}",
            "b.ne 89f",
            "cmp x0, #{undefined}",
            "b.eq 50f",
            "b 89f",
            // [[Construct]] completion of an interpreter frame.
            "48:",
            "cbnz x25, 50f",
            "ldrb w9, [x20, #{flags}]",
            "tbz w9, #{construct_bit}, 50f",
            "ldrb w10, [x20, #{kind}]",
            "cmp w10, #{host_kind}",
            "b.eq 50f",
            "and x10, x0, #0xffff",
            "cmp x10, #{fid_tag}",
            "b.ne 126f",
            "tst x0, #{number_tag}",
            "b.eq 50f",
            "126:",
            "tst x0, #{number_tag}",
            "b.ne 127f",
            "tst x0, #{other_tag}",
            "b.ne 127f",
            "ldrb w10, [x0]",
            "cmp w10, #{string_tag}",
            "b.eq 127f",
            "cmp w10, #{symbol_tag}",
            "b.eq 127f",
            "cmp w10, #{bigint_tag}",
            "b.ne 50f",
            "127:",
            "tbnz w9, #{derived_bit_frame}, 128f",
            "ldr x0, [x20, #{this}]",
            "b 50f",
            "128:",
            "mov x1, x0",
            "mov x0, x19",
            "bl {derived_result}",
            "b 50f",
            "45:",
            "cbnz x0, 89f",
            "ldrb w9, [x19, #{request_flags}]",
            "tbnz w9, #7, 47f",
            "tbnz w9, #6, 46f",
            "ldr w23, [x19, #{request_return_destination}]",
            "mov x0, x19",
            "bl {trampoline}",
            "b 40b",
            "47:",
            "ldr x9, [x19, #{request}]",
            "cbz x9, 89f",
            "mov x24, x22",
            "ldr w26, [x20, #{code_object_id}]",
            "mov x22, x9",
            "mov w23, #-2",
            "mov x0, #{undefined}",
            "mov x1, #0",
            "b 40b",
            "46:",
            "str x21, [x19, #{frame_cell}]",
            "mov sp, x29",
            "b 10b",
            "89:",
            "mov x0, #{undefined}",
            "mov x1, #{fatal_status}",
            "50:",
            "cmp x25, #0",
            "csel x9, x25, x21, ne",
            "str x9, [x19, #{frame_cell}]",
            "b 99f",
            "90:",
            "mov x0, x19",
            "bl {invalid_request}",
            "b 99f",
            "91:",
            "mov x0, x19",
            "bl {overflow}",
            "99:",
            "mov sp, x29",
            "ldp x19, x20, [sp, #16]",
            "ldp x21, x22, [sp, #32]",
            "ldp x23, x24, [sp, #48]",
            "ldp x25, x26, [sp, #64]",
            "ldp x27, x28, [sp, #80]",
            "ldp x29, x30, [sp], #{frame_bytes}",
            "ret",
            // Leaf: copy the bound prefixes of `x1` actuals in front of each
            // other into the span at `x13`, from the outer wrapper `x2` in.
            // Clobbers x1-x6 and x8.
            "160:",
            "cbz x1, 164f",
            "ldr w3, [x2, #{bound_args}]",
            "cbz w3, 163f",
            "and x4, x2, #0xffffffff00000000",
            "orr x4, x4, x3",
            "ldr w5, [x4, #{slab_len}]",
            "sub x1, x1, x5",
            "add x4, x4, #{slab_values}",
            "mov x6, #0",
            "161:",
            "cmp x6, x5",
            "b.hs 163f",
            "ldr x3, [x4, x6, lsl #3]",
            "add x8, x1, x6",
            "str x3, [x13, x8, lsl #3]",
            "add x6, x6, #1",
            "b 161b",
            "163:",
            "ldr x2, [x2, #{bound_target}]",
            "b 160b",
            "164:",
            "ret",
            request = const std::mem::offset_of!(JitCtx, pending_call),
            request_receiver = const std::mem::offset_of!(JitCtx, pending_call) + std::mem::offset_of!(CallRequest, receiver),
            request_new_target = const std::mem::offset_of!(JitCtx, pending_call) + std::mem::offset_of!(CallRequest, new_target),
            completion = const std::mem::offset_of!(JitCtx, completion),
            completion_generation = const std::mem::offset_of!(JitCtx, completion_generation),
            completion_destination = const std::mem::offset_of!(JitCtx, completion_destination),
            request_return_destination = const std::mem::offset_of!(JitCtx, pending_call) + std::mem::offset_of!(CallRequest, return_destination),
            request_flags = const std::mem::offset_of!(JitCtx, pending_call) + REQUEST_FLAGS_OFFSET,
            frame_cell = const std::mem::offset_of!(JitCtx, native_frame),
            depth_limit = const std::mem::offset_of!(JitCtx, generated_depth_limit),
            stack_limit = const std::mem::offset_of!(JitCtx, native_stack_limit),
            thread = const std::mem::offset_of!(JitCtx, thread),
            global_this = const std::mem::offset_of!(JitCtx, global_this_offset),
            frame_size = const std::mem::size_of::<super::Frame>(),
            flags = const std::mem::offset_of!(super::Frame, header) + std::mem::offset_of!(VmFrameHeader, flags),
            kind = const std::mem::offset_of!(super::Frame, header) + std::mem::offset_of!(VmFrameHeader, kind),
            code_object_id = const std::mem::offset_of!(super::Frame, code_object_id),
            registers = const std::mem::offset_of!(super::Frame, registers),
            this = const std::mem::offset_of!(super::Frame, this_value),
            self_value = const std::mem::offset_of!(super::Frame, self_value),
            actuals = const std::mem::offset_of!(super::Frame, actuals),
            caller = const std::mem::offset_of!(super::Frame, caller),
            depth = const std::mem::offset_of!(super::Frame, depth),
            continuation = const std::mem::offset_of!(super::Frame, return_destination),
            tail_header_mask = const ((super::NativeFrameFlags::TAIL_CALL | super::NativeFrameFlags::TIER_ENTRY) as u64) << 24,
            req_header = const std::mem::offset_of!(CallRequest, header),
            req_flags = const REQUEST_FLAGS_OFFSET,
            req_kind = const REQUEST_KIND_OFFSET,
            req_register_count = const std::mem::offset_of!(CallRequest, header) + std::mem::offset_of!(VmFrameHeader, register_count),
            req_arguments = const std::mem::offset_of!(CallRequest, arguments),
            req_argument_count = const std::mem::offset_of!(CallRequest, argument_count),
            req_parameter_count = const std::mem::offset_of!(CallRequest, parameter_count),
            req_callee = const std::mem::offset_of!(CallRequest, callee),
            req_receiver = const std::mem::offset_of!(CallRequest, receiver),
            req_new_target = const std::mem::offset_of!(CallRequest, new_target),
            req_initial = const std::mem::offset_of!(CallRequest, initial_registers),
            req_initial_count = const std::mem::offset_of!(CallRequest, initial_register_count),
            req_return_destination = const std::mem::offset_of!(CallRequest, return_destination),
            req_arguments_object = const std::mem::offset_of!(CallRequest, arguments_object),
            thread_registry = const std::mem::offset_of!(super::VmThread, code_registry),
            thread_active_realm = const std::mem::offset_of!(super::VmThread, active_realm_cell),
            thread_cage = const std::mem::offset_of!(super::VmThread, cage_base),
            registry_entries = const std::mem::offset_of!(super::CodeRegistryView, function_entries),
            registry_count = const std::mem::offset_of!(super::CodeRegistryView, function_entry_count),
            cell_call_flags = const super::FUNCTION_ENTRY_CALL_FLAGS_OFFSET,
            cell_param_count = const super::FUNCTION_ENTRY_PARAM_COUNT_OFFSET,
            cell_realm = const super::FUNCTION_ENTRY_REALM_OFFSET,
            cell_interpreter = const super::FUNCTION_ENTRY_INTERPRETER_OFFSET,
            generation_header = const std::mem::offset_of!(super::CodeEntryCell, native_frame_header),
            generation_code_object = const std::mem::offset_of!(super::CodeEntryCell, code_object_id),
            frame_bytes = const ARM64_TRAMPOLINE_FRAME_BYTES,
            no_conversion_bit = const super::FUNCTION_CALL_NO_RECEIVER_CONVERSION.trailing_zeros(),
            derived_bit = const super::FUNCTION_CALL_DERIVED_CONSTRUCTOR.trailing_zeros(),
            constructible_bit = const super::FUNCTION_CALL_CONSTRUCTIBLE.trailing_zeros(),
            suspendable_bit = const super::FUNCTION_CALL_SUSPENDABLE.trailing_zeros(),
            construct_bit = const super::NativeFrameFlags::CONSTRUCT.trailing_zeros(),
            derived_bit_frame = const super::NativeFrameFlags::DERIVED_CONSTRUCTOR.trailing_zeros(),
            derived_flag = const super::NativeFrameFlags::DERIVED_CONSTRUCTOR,
            request_frame_flags = const REQUEST_FRAME_FLAGS,
            host_registers = const super::HOST_FRAME_REGISTER_COUNT,
            host_kind = const super::NativeFrameKind::Host as u8,
            host_native = const super::HostCallKind::Native as u32,
            host_proxy = const super::HostCallKind::Proxy as u32,
            host_other = const super::HostCallKind::Other as u32,
            host_class_call = const super::HostCallKind::ClassCall as u32,
            host_not_constructor = const super::HostCallKind::NotConstructor as u32,
            fid_tag = const crate::value::tag::FUNCTION_ID_TAG,
            number_tag = const crate::value::tag::NUMBER_TAG,
            other_tag = const crate::value::tag::OTHER_TAG,
            closure_tag = const crate::closure::JS_CLOSURE_BODY_TYPE_TAG,
            bound_tag = const crate::bound_function::BOUND_FUNCTION_BODY_TYPE_TAG,
            class_tag = const crate::class_constructor::CLASS_CONSTRUCTOR_BODY_TYPE_TAG,
            native_tag = const crate::native_function::NATIVE_FUNCTION_BODY_TYPE_TAG,
            proxy_tag = const crate::proxy::PROXY_BODY_TYPE_TAG,
            string_tag = const crate::string::JS_STRING_BODY_TYPE_TAG,
            symbol_tag = const crate::symbol::SYMBOL_BODY_TYPE_TAG,
            bigint_tag = const crate::bigint::BIG_INT_BODY_TYPE_TAG,
            closure_fid = const BODY + crate::closure::CLOSURE_BODY_FUNCTION_ID_OFFSET,
            closure_flags = const BODY + crate::closure::CLOSURE_BODY_CALL_FLAGS_OFFSET,
            closure_bound_this = const BODY + crate::closure::CLOSURE_BODY_BOUND_THIS_OFFSET,
            closure_bound_new_target = const BODY + crate::closure::CLOSURE_BODY_BOUND_NEW_TARGET_OFFSET,
            closure_bound_this_bit = const crate::closure::CLOSURE_CALL_FLAG_BOUND_THIS.trailing_zeros(),
            closure_bound_new_target_bit = const crate::closure::CLOSURE_CALL_FLAG_BOUND_NEW_TARGET.trailing_zeros(),
            bound_target = const BODY + crate::bound_function::BOUND_FUNCTION_BODY_TARGET_OFFSET,
            bound_this = const BODY + crate::bound_function::BOUND_FUNCTION_BODY_THIS_OFFSET,
            bound_args = const BODY + crate::bound_function::BOUND_FUNCTION_BODY_ARGS_OFFSET,
            class_ctor = const BODY + crate::class_constructor::CLASS_CONSTRUCTOR_BODY_CTOR_OFFSET,
            slab_len = const BODY + crate::value_slab::VALUE_SLAB_LEN_OFFSET,
            slab_values = const BODY + crate::value_slab::VALUE_SLAB_VALUES_OFFSET,
            undefined = const Value::UNDEFINED.to_abi_bits(),
            null = const Value::NULL.to_abi_bits(),
            hole = const crate::value::tag::VALUE_HOLE,
            continue_status = const super::NativeResultStatus::Continue as u64,
            throw_status = const super::NativeResultStatus::Throw as u64,
            fatal_status = const super::NativeResultStatus::Fatal as u64,
            trampoline = sym call_trampoline,
            host_entry = sym crate::interp::host_call::host_call_entry,
            interp_entry = sym crate::interp::call_dispatch::interpreter_entry,
            prepare = sym crate::interp::host_call::prepare_activation,
            derived_result = sym crate::interp::host_call::derived_construct_result,
            overflow = sym call_stack_overflow,
            invalid_request = sym invalid_call_request,
        )
    };
}
/// Invoke the context's pending call on the common JavaScript stack.
///
/// A request with a zero entry is classified first: bound wrappers are
/// unwrapped into the actual span, a class wrapper yields its constructor,
/// and bytecode functions select their current destination through the
/// function directory. A compiled generation is entered through the
/// JavaScript call ABI with the padded span on this stack; its entry builds
/// and owns its frame. An interpreter destination and every other callee get
/// a frame built here. `Continue` from such a frame's body consumes another
/// request, invokes that child and resumes the same parent entry with
/// `ctx.completion`. All other execution statuses leave this extent. A request
/// with `TIER_ENTRY` resumes the already-published frame instead of reserving
/// a child. Its enclosing owner retains that frame through return.
///
/// # Safety
/// `ctx` and its services must remain exclusively owned for this call. The
/// request's entry must obey `JitEntry`, and its source arguments must remain
/// readable until copied. Entries must home their completion before any
/// safepoint and release cold frame state before returning. The context's
/// native frame cell must be registered with the collector for allocating
/// entries. The configured native-stack limit must leave room for error entry.
#[cfg(target_arch = "aarch64")]
#[unsafe(naked)]
pub unsafe extern "C" fn call_trampoline(_ctx: *mut JitCtx) -> NativeResultPair {
    #[cfg(target_vendor = "apple")]
    arm64_call_trampoline!(
        "adrp x22, {host_entry}@PAGE",
        "add x22, x22, {host_entry}@PAGEOFF",
        "adrp x22, {interp_entry}@PAGE",
        "add x22, x22, {interp_entry}@PAGEOFF"
    );
    #[cfg(not(target_vendor = "apple"))]
    arm64_call_trampoline!(
        "adrp x22, {host_entry}",
        "add x22, x22, :lo12:{host_entry}",
        "adrp x22, {interp_entry}",
        "add x22, x22, :lo12:{interp_entry}"
    );
}

/// Bytes of the AArch64 trampoline native frame: the `x29`/`x30` pair and
/// callee-saved `x19`–`x28`.
#[cfg(target_arch = "aarch64")]
pub const ARM64_TRAMPOLINE_FRAME_BYTES: u32 = 96;

/// Invoke the pending call using the x86-64 platform entry ABI.
///
/// # Safety
/// The request, classification, publication and entry requirements are
/// identical to the ARM64 implementation of `call_trampoline`.
#[cfg(target_arch = "x86_64")]
#[unsafe(naked)]
pub unsafe extern "C" fn call_trampoline(_ctx: *mut JitCtx) -> NativeResultPair {
    // Locals below the saved registers: [rbp-64] completion destination,
    // [rbp-72] tier-entry frame, [rbp-80] saved generation, [rbp-88] bound
    // actual count, [rbp-96] callee chain head, [rbp-104] parent entry to
    // resume after a tier transfer, [rbp-112] activation-preparation flag or
    // the compiled callee, [rbp-120] the entered generation.
    core::arch::naked_asm!(
        "push rbp",
        "mov rbp, rsp",
        "push rbx",
        "push r12",
        "push r13",
        "push r14",
        "push r15",
        "push rdi",
        "push rsi",
        "sub rsp, 72",
        ".if {windows}",
        "mov r14, rcx", // C aggregate return destination.
        "mov r12, rdx",
        ".else",
        "mov r12, rdi",
        ".endif",
        "mov qword ptr [rbp - 72], 0",
        "test byte ptr [r12 + {request_flags}], 128",
        "jz 10f",
        // A tier request resumes the published frame with its entry.
        "mov rbx, [r12 + {frame_cell}]",
        "test rbx, rbx",
        "jz 90f",
        "mov [rbp - 72], rbx",
        "mov r13, [rbx + {caller}]",
        "mov r15, [r12 + {request}]",
        "test r15, r15",
        "jz 90f",
        "sub rsp, {call_area}",
        "mov qword ptr [rbp - 104], 0",
        "mov dword ptr [rbp - 64], -1",
        "mov rax, {undefined}",
        "xor edx, edx",
        "jmp 40f",
        // ---- Classification. Nothing below allocates before the copy.
        "10:",
        "lea r8, [r12 + {request}]",
        "mov qword ptr [rbp - 112], 0",
        "mov qword ptr [rbp - 88], 0",
        "mov rax, [r8 + {req_callee}]",
        "mov [rbp - 96], rax",
        "mov r15, [r8]",
        "test r15, r15",
        "jnz 12f",
        "movzx r9d, byte ptr [r8 + {req_flags}]",
        "mov r10, rax",
        "xor r11d, r11d",
        "60:",
        "mov eax, r10d",
        "and eax, 0xffff",
        "cmp eax, {fid_tag}",
        "jne 61f",
        "mov rax, {number_tag}",
        "test r10, rax",
        "jnz 61f",
        "mov rcx, r10",
        "shr rcx, 16",
        "mov ecx, ecx",
        "xor edx, edx",
        "jmp 70f",
        "61:",
        "test r10, r10",
        "jz 80f",
        "mov rax, {number_tag}",
        "test r10, rax",
        "jnz 80f",
        "test r10, {other_tag}",
        "jnz 80f",
        "movzx eax, byte ptr [r10]",
        "cmp eax, {closure_tag}",
        "je 62f",
        "cmp eax, {bound_tag}",
        "je 63f",
        "cmp eax, {class_tag}",
        "je 64f",
        "cmp eax, {native_tag}",
        "je 81f",
        "cmp eax, {proxy_tag}",
        "je 82f",
        "jmp 80f",
        "62:",
        "mov ecx, [r10 + {closure_fid}]",
        "mov edx, [r10 + {closure_flags}]",
        "jmp 70f",
        // Bound wrapper: count its prefix, apply its receiver rule, unwrap.
        "63:",
        "inc r11",
        "cmp r11, [r12 + {depth_limit}]",
        "ja 91f",
        "mov eax, [r10 + {bound_args}]",
        "test eax, eax",
        "jz 65f",
        "mov rcx, r10",
        "shr rcx, 32",
        "shl rcx, 32",
        "or rcx, rax",
        "mov eax, [rcx + {slab_len}]",
        "add [rbp - 88], rax",
        "65:",
        "test r9d, {construct_flag}",
        "jnz 66f",
        "mov rax, [r10 + {bound_this}]",
        "mov [r8 + {req_receiver}], rax",
        "jmp 67f",
        "66:",
        "mov rax, [r8 + {req_new_target}]",
        "cmp rax, r10",
        "jne 67f",
        "mov rax, [r10 + {bound_target}]",
        "mov [r8 + {req_new_target}], rax",
        "67:",
        "mov r10, [r10 + {bound_target}]",
        "jmp 60b",
        // Class wrapper: construct enters its constructor; call throws.
        "64:",
        "test r9d, {construct_flag}",
        "jz 83f",
        "mov r10, [r10 + {class_ctor}]",
        "jmp 60b",
        // Bytecode function: ecx id, r10 SELF, edx closure call flags.
        "70:",
        "mov rax, [r12 + {thread}]",
        "mov rsi, [rax + {thread_registry}]",
        "test rsi, rsi",
        "jz 90f",
        "cmp rcx, [rsi + {registry_count}]",
        "jae 90f",
        "mov rax, [rsi + {registry_entries}]",
        "mov rdi, [rax + rcx * 8]",
        "test rdi, rdi",
        "jz 90f",
        "mov r11d, [rdi + {cell_call_flags}]",
        "test r9d, {construct_flag}",
        "jz 140f",
        "test r11d, {constructible_flag}",
        "jz 84f",
        // A compiled current generation builds its own frame: enter it
        // through the JavaScript call ABI with the padded actual span.
        "140:",
        "test r11d, {suspendable_flag}",
        "jnz 71f",
        "mov rsi, [rdi]",
        "cmp qword ptr [rsi + {generation_code_object}], 0",
        "je 71f",
        "mov r15, [rsi]",
        "test r15, r15",
        "jz 90f",
        "mov [rbp - 120], rsi",
        "mov [rbp - 112], r10",
        "mov ecx, [r8 + {req_argument_count}]",
        "mov rsi, [r8 + {req_arguments}]",
        "test ecx, ecx",
        "jz 141f",
        "test rsi, rsi",
        "jz 90f",
        "141:",
        "mov r13, [rbp - 88]",
        "add r13, rcx",
        "movzx ebx, word ptr [rdi + {cell_param_count}]",
        "cmp rbx, r13",
        "cmovb rbx, r13",
        "lea rax, [rbx * 8 + 15]",
        "and rax, -16",
        "mov rdx, rsp",
        "sub rdx, rax",
        "jc 91f",
        "cmp rdx, [r12 + {stack_limit}]",
        "jb 91f",
        "mov rax, rsp",
        "142:",
        "sub rax, 4096",
        "cmp rax, rdx",
        "jbe 143f",
        "mov qword ptr [rax], 0",
        "jmp 142b",
        "143:",
        "mov rsp, rdx",
        // The caller's span follows every bound prefix.
        "mov rax, [rbp - 88]",
        "lea r8, [rsp + rax * 8]",
        "xor edx, edx",
        "144:",
        "cmp rdx, rcx",
        "jae 145f",
        "mov rax, [rsi + rdx * 8]",
        "mov [r8 + rdx * 8], rax",
        "inc rdx",
        "jmp 144b",
        "145:",
        "mov r8, rsp",
        "call 160f",
        // Formals beyond the actuals read `undefined`.
        "mov rax, {undefined}",
        "mov rdx, r13",
        "146:",
        "cmp rdx, rbx",
        "jae 147f",
        "mov [rsp + rdx * 8], rax",
        "inc rdx",
        "jmp 146b",
        "147:",
        "mov rdi, r12",
        "mov rsi, [rbp - 112]",
        "mov rdx, [r12 + {request_receiver}]",
        "mov rcx, [r12 + {request_new_target}]",
        "mov r8, r13",
        "mov r9, [rbp - 120]",
        "call r15",
        "jmp 99f",
        // Interpreter destination: bind the receiver for this frame.
        "71:",
        "test r9d, {construct_flag}",
        "jnz 75f",
        "test edx, {closure_bound_this_flag}",
        "jz 72f",
        "mov rax, [r10 + {closure_bound_this}]",
        "mov [r8 + {req_receiver}], rax",
        "test edx, {closure_bound_new_target_flag}",
        "jz 78f",
        "mov rax, [r10 + {closure_bound_new_target}]",
        "mov [r8 + {req_new_target}], rax",
        "jmp 78f",
        "72:",
        "test r11d, {no_conversion_flag}",
        "jnz 78f",
        "mov rax, [r8 + {req_receiver}]",
        "cmp rax, {undefined}",
        "je 73f",
        "cmp rax, {null}",
        "je 73f",
        "mov edx, eax",
        "and edx, 0xffff",
        "cmp edx, {fid_tag}",
        "jne 74f",
        "mov rdx, {number_tag}",
        "test rax, rdx",
        "jz 78f",
        "74:",
        "mov rdx, {number_tag}",
        "test rax, rdx",
        "jnz 76f",
        "test rax, {other_tag}",
        "jnz 76f",
        "movzx edx, byte ptr [rax]",
        "cmp edx, {string_tag}",
        "je 76f",
        "cmp edx, {symbol_tag}",
        "je 76f",
        "cmp edx, {bigint_tag}",
        "je 76f",
        "jmp 78f",
        "76:",
        "mov qword ptr [rbp - 112], 1",
        "jmp 78f",
        "73:",
        "mov eax, [rdi + {cell_realm}]",
        "mov rdx, [r12 + {thread}]",
        "mov rdx, [rdx + {thread_active_realm}]",
        "cmp eax, [rdx]",
        "jne 76b",
        "mov rdx, [r12 + {global_this}]",
        "mov eax, [rdx]",
        "mov rdx, [r12 + {thread}]",
        "or rax, [rdx + {thread_cage}]",
        "mov [r8 + {req_receiver}], rax",
        "jmp 78f",
        "75:",
        "test r11d, {derived_flag}",
        "jz 77f",
        "mov rax, {hole}",
        "mov [r8 + {req_receiver}], rax",
        "or r9d, {derived_frame_flag}",
        "jmp 78f",
        // A base constructor creates its receiver on the published frame
        // unless the caller allocated it.
        "77:",
        "mov rax, {undefined}",
        "cmp [r8 + {req_receiver}], rax",
        "jne 78f",
        "mov qword ptr [rbp - 112], 1",
        // The permanent interpreter destination of the function.
        "78:",
        "lea rsi, [rdi + {cell_interpreter}]",
        "lea r15, [rip + {interp_entry}]",
        "mov rax, [rsi + {generation_header}]",
        "mov [r8 + {req_header}], rax",
        "mov rax, [rsi + {generation_header} + 8]",
        "mov edx, r9d",
        "and edx, {request_frame_flags}",
        "shl rdx, 24",
        "or rax, rdx",
        "mov [r8 + {req_header} + 8], rax",
        "movzx eax, word ptr [rdi + {cell_param_count}]",
        "mov [r8 + {req_parameter_count}], eax",
        "mov [r8 + {req_callee}], r10",
        "mov [r8], r15",
        "jmp 12f",
        // Host frame: ecx selects the host body; SELF is the callee.
        "80:",
        "mov ecx, {host_other}",
        "jmp 85f",
        "81:",
        "mov ecx, {host_native}",
        "jmp 85f",
        "82:",
        "mov ecx, {host_proxy}",
        "jmp 85f",
        "83:",
        "mov ecx, {host_class_call}",
        "jmp 85f",
        "84:",
        "mov ecx, {host_not_constructor}",
        "85:",
        "lea r15, [rip + {host_entry}]",
        "mov eax, ecx",
        "mov [r8 + {req_header}], rax",
        "mov edx, r9d",
        "and edx, {request_frame_flags}",
        "shl rdx, 24",
        "or rdx, {host_header_low}",
        "mov [r8 + {req_header} + 8], rdx",
        "mov dword ptr [r8 + {req_parameter_count}], 0",
        "mov [r8 + {req_callee}], r10",
        "mov [r8], r15",
        // ---- Reservation of an interpreter or host frame.
        "12:",
        "mov r13, [r12 + {frame_cell}]",
        "mov r11d, 1",
        "test r13, r13",
        "jz 20f",
        "mov r11d, [r13 + {depth}]",
        "add r11d, 1",
        "jc 91f",
        "20:",
        "cmp r11, [r12 + {depth_limit}]",
        "ja 91f",
        // A host frame keeps its caller's logical JavaScript depth.
        "cmp byte ptr [r8 + {req_kind}], {host_kind}",
        "jne 26f",
        "dec r11d",
        "26:",
        "movzx ecx, word ptr [r8 + {req_register_count}]",
        "mov r9d, [r8 + {req_argument_count}]",
        "mov r10d, [r8 + {req_parameter_count}]",
        "cmp r10d, ecx",
        "ja 90f",
        "mov rsi, [r8 + {req_arguments}]",
        "test r9d, r9d",
        "jz 21f",
        "test rsi, rsi",
        "jz 90f",
        "21:",
        "mov edx, [r8 + {req_initial_count}]",
        "cmp edx, ecx",
        "ja 90f",
        "test edx, edx",
        "jz 24f",
        "cmp qword ptr [r8 + {req_initial}], 0",
        "je 90f",
        "24:",
        "add r9, [rbp - 88]",
        "lea rax, [rcx + r9]",
        "lea rax, [rax * 8 + {frame_size} + {call_area} + 15]",
        "and rax, -16",
        "mov rbx, rsp",
        "sub rbx, rax",
        "jc 91f",
        "cmp rbx, [r12 + {stack_limit}]",
        "jb 91f",
        "mov rax, rsp",
        "22:",
        "sub rax, 4096",
        "cmp rax, rbx",
        "jbe 23f",
        "mov qword ptr [rax], 0",
        "jmp 22b",
        "23:",
        "mov rsp, rbx",
        "add rbx, {call_area}",
        "mov rax, [r8 + {req_header}]",
        "mov [rbx], rax",
        "mov rax, [r8 + {req_header} + 8]",
        "mov [rbx + 8], rax",
        "and byte ptr [rbx + {flags}], {persistent_flags}",
        // Registers, then the actual window, follow the record.
        "lea rdi, [rbx + {frame_size}]",
        "mov [rbx + {registers}], rdi",
        "mov [rbx + {registers} + 8], rcx",
        "mov rax, [r8 + {req_receiver}]",
        "mov [rbx + {this}], rax",
        "mov rax, [r8 + {req_new_target}]",
        "mov [rbx + {this} + 8], rax",
        "mov rax, [r8 + {req_callee}]",
        "mov [rbx + {self_value}], rax",
        "mov [rbx + {self_value} + 8], r9",
        "mov eax, [r8 + {req_arguments_object}]",
        "mov [rbx + {self_value} + 12], eax",
        "lea rax, [rdi + rcx * 8]",
        "mov [rbx + {actuals}], rax",
        "mov [rbx + {caller}], r13",
        "mov [rbx + {depth}], r11d",
        "mov dword ptr [rbx + {depth} + 4], -1",
        "mov qword ptr [rbx + {depth} + 8], 0",
        "mov rax, [r8 + {req_return_destination}]",
        "mov [rbx + {continuation}], rax",
        "mov rax, {undefined}",
        "xor edx, edx",
        "30:",
        "cmp rdx, rcx",
        "jae 31f",
        "mov [rdi + rdx * 8], rax",
        "inc rdx",
        "jmp 30b",
        // The caller's span follows every bound prefix in the actual window.
        "31:",
        "lea r8, [rdi + rcx * 8]",
        "mov r10, r9",
        "sub r10, [rbp - 88]",
        "mov rax, [rbp - 88]",
        "lea r11, [r8 + rax * 8]",
        "xor edx, edx",
        "32:",
        "cmp rdx, r10",
        "jae 33f",
        "mov rax, [rsi + rdx * 8]",
        "mov [r11 + rdx * 8], rax",
        "inc rdx",
        "jmp 32b",
        "33:",
        "call 160f",
        // Seed formals from the complete actual window.
        "lea rsi, [r12 + {request}]",
        "mov r10d, [rsi + {req_parameter_count}]",
        "xor edx, edx",
        "125:",
        "cmp rdx, r10",
        "jae 34f",
        "cmp rdx, r9",
        "jae 34f",
        "mov rax, [r8 + rdx * 8]",
        "mov [rdi + rdx * 8], rax",
        "inc rdx",
        "jmp 125b",
        "34:",
        "mov rax, [rsi + {req_initial}]",
        "mov ecx, [rsi + {req_initial_count}]",
        "xor edx, edx",
        "35:",
        "cmp rdx, rcx",
        "jae 36f",
        "mov r10, [rax + rdx * 8]",
        "mov [rdi + rdx * 8], r10",
        "inc rdx",
        "jmp 35b",
        "36:",
        "mov [r12 + {frame_cell}], rbx",
        // Receiver conversion or creation runs on the published frame.
        "test qword ptr [rbp - 112], 1",
        "jz 37f",
        ".if {windows}",
        "lea rcx, [rsp + 32]",
        "mov rdx, r12",
        "call {prepare}",
        "mov rax, [rsp + 32]",
        "mov rdx, [rsp + 40]",
        ".else",
        "mov rdi, r12",
        "call {prepare}",
        ".endif",
        "test rdx, rdx",
        "jnz 50f",
        "37:",
        "mov qword ptr [rbp - 104], 0",
        "mov dword ptr [rbp - 64], -1",
        "mov rax, {undefined}",
        "xor edx, edx",
        "40:",
        "mov [r12 + {completion}], rax",
        "mov [r12 + {completion} + 8], rdx",
        "mov ecx, [rbp - 64]",
        "mov [r12 + {completion_destination}], ecx",
        ".if {windows}",
        "lea rcx, [rsp + 32]",
        "mov rdx, r12",
        "call r15",
        "mov rax, [rsp + 32]",
        "mov rdx, [rsp + 40]",
        ".else",
        "mov rdi, r12",
        "call r15",
        ".endif",
        "cmp qword ptr [rbp - 104], 0",
        "je 41f",
        "mov r15, [rbp - 104]",
        "mov qword ptr [rbp - 104], 0",
        "mov ecx, [rbp - 80]",
        "mov [r12 + {completion_generation}], ecx",
        "jmp 40b",
        "41:",
        "cmp rdx, {continue_status}",
        "je 45f",
        "test rdx, rdx",
        "jz 48f",
        "cmp rdx, {throw_status}",
        "je 50f",
        "cmp rdx, {fatal_status}",
        "jne 89f",
        "cmp rax, {undefined}",
        "je 50f",
        "jmp 89f",
        // [[Construct]] completion of an interpreter frame.
        "48:",
        "cmp qword ptr [rbp - 72], 0",
        "jne 50f",
        "movzx ecx, byte ptr [rbx + {flags}]",
        "test ecx, {construct_flag}",
        "jz 50f",
        "cmp byte ptr [rbx + {kind}], {host_kind}",
        "je 50f",
        "mov r8d, eax",
        "and r8d, 0xffff",
        "cmp r8d, {fid_tag}",
        "jne 126f",
        "mov r8, {number_tag}",
        "test rax, r8",
        "jz 50f",
        "126:",
        "mov r8, {number_tag}",
        "test rax, r8",
        "jnz 127f",
        "test rax, {other_tag}",
        "jnz 127f",
        "movzx r8d, byte ptr [rax]",
        "cmp r8d, {string_tag}",
        "je 127f",
        "cmp r8d, {symbol_tag}",
        "je 127f",
        "cmp r8d, {bigint_tag}",
        "jne 50f",
        "127:",
        "test ecx, {derived_frame_flag}",
        "jnz 128f",
        "mov rax, [rbx + {this}]",
        "jmp 50f",
        "128:",
        ".if {windows}",
        "mov r8, rax",
        "lea rcx, [rsp + 32]",
        "mov rdx, r12",
        "call {derived_result}",
        "mov rax, [rsp + 32]",
        "mov rdx, [rsp + 40]",
        ".else",
        "mov rsi, rax",
        "mov rdi, r12",
        "call {derived_result}",
        ".endif",
        "jmp 50f",
        "45:",
        "test rax, rax",
        "jnz 89f",
        "test byte ptr [r12 + {request_flags}], 128",
        "jnz 47f",
        "test byte ptr [r12 + {request_flags}], 64",
        "jnz 46f",
        "mov eax, [r12 + {request_return_destination}]",
        "mov [rbp - 64], eax",
        ".if {windows}",
        "lea rcx, [rsp + 32]",
        "mov rdx, r12",
        "call {trampoline}",
        "mov rax, [rsp + 32]",
        "mov rdx, [rsp + 40]",
        ".else",
        "mov rdi, r12",
        "call {trampoline}",
        ".endif",
        "jmp 40b",
        "47:",
        "mov r8, [r12 + {request}]",
        "test r8, r8",
        "jz 89f",
        "mov [rbp - 104], r15",
        "mov eax, [rbx + {code_object_id}]",
        "mov [rbp - 80], eax",
        "mov r15, r8",
        "mov dword ptr [rbp - 64], -2",
        "mov rax, {undefined}",
        "xor edx, edx",
        "jmp 40b",
        "46:",
        "mov [r12 + {frame_cell}], r13",
        "lea rsp, [rbp - 128]",
        "jmp 10b",
        "89:",
        "mov rax, {undefined}",
        "mov edx, {fatal_status}",
        "50:",
        "mov rcx, [rbp - 72]",
        "test rcx, rcx",
        "cmovz rcx, r13",
        "mov [r12 + {frame_cell}], rcx",
        "jmp 99f",
        "90:",
        ".if {windows}",
        "lea rcx, [rsp + 32]",
        "mov rdx, r12",
        "call {invalid_request}",
        "mov rax, [rsp + 32]",
        "mov rdx, [rsp + 40]",
        ".else",
        "mov rdi, r12",
        "call {invalid_request}",
        ".endif",
        "jmp 99f",
        "91:",
        ".if {windows}",
        "lea rsp, [rbp - 128]",
        "lea rcx, [rsp + 32]",
        "mov rdx, r12",
        "call {overflow}",
        "mov rax, [rsp + 32]",
        "mov rdx, [rsp + 40]",
        ".else",
        "mov rdi, r12",
        "call {overflow}",
        ".endif",
        "99:",
        ".if {windows}",
        "mov [r14], rax",
        "mov [r14 + 8], rdx",
        "mov rax, r14",
        ".endif",
        "lea rsp, [rbp - 56]",
        "pop rsi",
        "pop rdi",
        "pop r15",
        "pop r14",
        "pop r13",
        "pop r12",
        "pop rbx",
        "pop rbp",
        "ret",
        // Leaf: copy the bound prefixes of `[rbp - 88]` actuals in front of
        // each other into the span at `r8`, from the outer wrapper
        // `[rbp - 96]` in. Clobbers rax, rcx, rdx, r10 and r11.
        "160:",
        "mov r11, [rbp - 88]",
        "mov r10, [rbp - 96]",
        "161:",
        "test r11, r11",
        "jz 164f",
        "mov eax, [r10 + {bound_args}]",
        "test eax, eax",
        "jz 163f",
        "mov rcx, r10",
        "shr rcx, 32",
        "shl rcx, 32",
        "or rax, rcx",
        "mov ecx, [rax + {slab_len}]",
        "sub r11, rcx",
        "add rax, {slab_values}",
        "lea rdx, [r8 + r11 * 8]",
        "162:",
        "test rcx, rcx",
        "jz 163f",
        "dec rcx",
        "push qword ptr [rax + rcx * 8]",
        "pop qword ptr [rdx + rcx * 8]",
        "jmp 162b",
        "163:",
        "mov r10, [r10 + {bound_target}]",
        "jmp 161b",
        "164:",
        "ret",
        windows = const cfg!(target_os = "windows") as u8,
        call_area = const if cfg!(target_os = "windows") { 48 } else { 0 },
        request = const std::mem::offset_of!(JitCtx, pending_call),
        request_receiver = const std::mem::offset_of!(JitCtx, pending_call) + std::mem::offset_of!(CallRequest, receiver),
        request_new_target = const std::mem::offset_of!(JitCtx, pending_call) + std::mem::offset_of!(CallRequest, new_target),
        completion = const std::mem::offset_of!(JitCtx, completion),
        completion_generation = const std::mem::offset_of!(JitCtx, completion_generation),
        completion_destination = const std::mem::offset_of!(JitCtx, completion_destination),
        request_return_destination = const std::mem::offset_of!(JitCtx, pending_call) + std::mem::offset_of!(CallRequest, return_destination),
        request_flags = const std::mem::offset_of!(JitCtx, pending_call) + REQUEST_FLAGS_OFFSET,
        frame_cell = const std::mem::offset_of!(JitCtx, native_frame),
        depth_limit = const std::mem::offset_of!(JitCtx, generated_depth_limit),
        stack_limit = const std::mem::offset_of!(JitCtx, native_stack_limit),
        thread = const std::mem::offset_of!(JitCtx, thread),
        global_this = const std::mem::offset_of!(JitCtx, global_this_offset),
        frame_size = const std::mem::size_of::<super::Frame>(),
        flags = const std::mem::offset_of!(super::Frame, header) + std::mem::offset_of!(VmFrameHeader, flags),
        kind = const std::mem::offset_of!(super::Frame, header) + std::mem::offset_of!(VmFrameHeader, kind),
        code_object_id = const std::mem::offset_of!(super::Frame, code_object_id),
        registers = const std::mem::offset_of!(super::Frame, registers),
        this = const std::mem::offset_of!(super::Frame, this_value),
        self_value = const std::mem::offset_of!(super::Frame, self_value),
        actuals = const std::mem::offset_of!(super::Frame, actuals),
        caller = const std::mem::offset_of!(super::Frame, caller),
        depth = const std::mem::offset_of!(super::Frame, depth),
        continuation = const std::mem::offset_of!(super::Frame, return_destination),
        persistent_flags = const !(super::NativeFrameFlags::TAIL_CALL | super::NativeFrameFlags::TIER_ENTRY),
        req_header = const std::mem::offset_of!(CallRequest, header),
        req_flags = const REQUEST_FLAGS_OFFSET,
        req_kind = const REQUEST_KIND_OFFSET,
        req_register_count = const std::mem::offset_of!(CallRequest, header) + std::mem::offset_of!(VmFrameHeader, register_count),
        req_arguments = const std::mem::offset_of!(CallRequest, arguments),
        req_argument_count = const std::mem::offset_of!(CallRequest, argument_count),
        req_parameter_count = const std::mem::offset_of!(CallRequest, parameter_count),
        req_callee = const std::mem::offset_of!(CallRequest, callee),
        req_receiver = const std::mem::offset_of!(CallRequest, receiver),
        req_new_target = const std::mem::offset_of!(CallRequest, new_target),
        req_initial = const std::mem::offset_of!(CallRequest, initial_registers),
        req_initial_count = const std::mem::offset_of!(CallRequest, initial_register_count),
        req_return_destination = const std::mem::offset_of!(CallRequest, return_destination),
        req_arguments_object = const std::mem::offset_of!(CallRequest, arguments_object),
        thread_registry = const std::mem::offset_of!(super::VmThread, code_registry),
        thread_active_realm = const std::mem::offset_of!(super::VmThread, active_realm_cell),
        thread_cage = const std::mem::offset_of!(super::VmThread, cage_base),
        registry_entries = const std::mem::offset_of!(super::CodeRegistryView, function_entries),
        registry_count = const std::mem::offset_of!(super::CodeRegistryView, function_entry_count),
        cell_call_flags = const super::FUNCTION_ENTRY_CALL_FLAGS_OFFSET,
        cell_param_count = const super::FUNCTION_ENTRY_PARAM_COUNT_OFFSET,
        cell_realm = const super::FUNCTION_ENTRY_REALM_OFFSET,
        cell_interpreter = const super::FUNCTION_ENTRY_INTERPRETER_OFFSET,
        generation_header = const std::mem::offset_of!(super::CodeEntryCell, native_frame_header),
        generation_code_object = const std::mem::offset_of!(super::CodeEntryCell, code_object_id),
        no_conversion_flag = const super::FUNCTION_CALL_NO_RECEIVER_CONVERSION,
        derived_flag = const super::FUNCTION_CALL_DERIVED_CONSTRUCTOR,
        constructible_flag = const super::FUNCTION_CALL_CONSTRUCTIBLE,
        suspendable_flag = const super::FUNCTION_CALL_SUSPENDABLE,
        construct_flag = const super::NativeFrameFlags::CONSTRUCT,
        derived_frame_flag = const super::NativeFrameFlags::DERIVED_CONSTRUCTOR,
        request_frame_flags = const REQUEST_FRAME_FLAGS,
        host_header_low = const (super::HOST_FRAME_REGISTER_COUNT as u32) | ((super::NativeFrameKind::Host as u32) << 16),
        host_kind = const super::NativeFrameKind::Host as u8,
        host_native = const super::HostCallKind::Native as u32,
        host_proxy = const super::HostCallKind::Proxy as u32,
        host_other = const super::HostCallKind::Other as u32,
        host_class_call = const super::HostCallKind::ClassCall as u32,
        host_not_constructor = const super::HostCallKind::NotConstructor as u32,
        fid_tag = const crate::value::tag::FUNCTION_ID_TAG,
        number_tag = const crate::value::tag::NUMBER_TAG,
        other_tag = const crate::value::tag::OTHER_TAG,
        closure_tag = const crate::closure::JS_CLOSURE_BODY_TYPE_TAG,
        bound_tag = const crate::bound_function::BOUND_FUNCTION_BODY_TYPE_TAG,
        class_tag = const crate::class_constructor::CLASS_CONSTRUCTOR_BODY_TYPE_TAG,
        native_tag = const crate::native_function::NATIVE_FUNCTION_BODY_TYPE_TAG,
        proxy_tag = const crate::proxy::PROXY_BODY_TYPE_TAG,
        string_tag = const crate::string::JS_STRING_BODY_TYPE_TAG,
        symbol_tag = const crate::symbol::SYMBOL_BODY_TYPE_TAG,
        bigint_tag = const crate::bigint::BIG_INT_BODY_TYPE_TAG,
        closure_fid = const BODY + crate::closure::CLOSURE_BODY_FUNCTION_ID_OFFSET,
        closure_flags = const BODY + crate::closure::CLOSURE_BODY_CALL_FLAGS_OFFSET,
        closure_bound_this = const BODY + crate::closure::CLOSURE_BODY_BOUND_THIS_OFFSET,
        closure_bound_new_target = const BODY + crate::closure::CLOSURE_BODY_BOUND_NEW_TARGET_OFFSET,
        closure_bound_this_flag = const crate::closure::CLOSURE_CALL_FLAG_BOUND_THIS,
        closure_bound_new_target_flag = const crate::closure::CLOSURE_CALL_FLAG_BOUND_NEW_TARGET,
        bound_target = const BODY + crate::bound_function::BOUND_FUNCTION_BODY_TARGET_OFFSET,
        bound_this = const BODY + crate::bound_function::BOUND_FUNCTION_BODY_THIS_OFFSET,
        bound_args = const BODY + crate::bound_function::BOUND_FUNCTION_BODY_ARGS_OFFSET,
        class_ctor = const BODY + crate::class_constructor::CLASS_CONSTRUCTOR_BODY_CTOR_OFFSET,
        slab_len = const BODY + crate::value_slab::VALUE_SLAB_LEN_OFFSET,
        slab_values = const BODY + crate::value_slab::VALUE_SLAB_VALUES_OFFSET,
        undefined = const Value::UNDEFINED.to_abi_bits(),
        null = const Value::NULL.to_abi_bits(),
        hole = const crate::value::tag::VALUE_HOLE,
        continue_status = const super::NativeResultStatus::Continue as u64,
        throw_status = const super::NativeResultStatus::Throw as u64,
        fatal_status = const super::NativeResultStatus::Fatal as u64,
        trampoline = sym call_trampoline,
        host_entry = sym crate::interp::host_call::host_call_entry,
        interp_entry = sym crate::interp::call_dispatch::interpreter_entry,
        prepare = sym crate::interp::host_call::prepare_activation,
        derived_result = sym crate::interp::host_call::derived_construct_result,
        overflow = sym call_stack_overflow,
        invalid_request = sym invalid_call_request,
    );
}

/// Park the stack-overflow error for a call that found no room for its frame.
///
/// # Safety
/// `ctx` must be the live context of the running compiled entry.
pub unsafe extern "C" fn call_stack_overflow(ctx: *mut JitCtx) -> NativeResultPair {
    // SAFETY: the trampoline retains the live context and its error slot.
    let ctx = unsafe { &mut *ctx };
    if let Some(error) = unsafe { ctx.error.as_mut() } {
        *error = Some(VmError::StackOverflow {
            limit: ctx.generated_depth_limit.min(u64::from(u32::MAX)) as u32,
        });
    }
    NativeResultPair::fatal_internal()
}

extern "C" fn invalid_call_request(ctx: *mut JitCtx) -> NativeResultPair {
    // SAFETY: the trampoline retains the live context and its error slot.
    let ctx = unsafe { &mut *ctx };
    if let Some(error) = unsafe { ctx.error.as_mut() } {
        *error = Some(VmError::InvalidOperand);
    }
    NativeResultPair::fatal_internal()
}

const _: [(); 88] = [(); std::mem::size_of::<CallRequest>()];
const _: [(); 8] = [(); std::mem::offset_of!(CallRequest, header)];
const _: [(); 20] = [(); std::mem::offset_of!(CallRequest, code_object_id)];
const _: [(); 24] = [(); std::mem::offset_of!(CallRequest, arguments)];
const _: [(); 32] = [(); std::mem::offset_of!(CallRequest, argument_count)];
const _: [(); 36] = [(); std::mem::offset_of!(CallRequest, parameter_count)];
const _: [(); 40] = [(); std::mem::offset_of!(CallRequest, callee)];
const _: [(); 48] = [(); std::mem::offset_of!(CallRequest, receiver)];
const _: [(); 56] = [(); std::mem::offset_of!(CallRequest, new_target)];

#[cfg(test)]
mod tests;
